<div id="<?php echo $this->getContainerId(); ?>">

    <div class="entry-edit" id="magento_block_amazon_synchronization_templates">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Inventory Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_amazon_synchronization_stock_level" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                    <?php $inspectorMode = ($this->inspectorMode == 1)?'<span style="color: green"> (enabled) </span>':''; ?>
                    <?php echo Mage::helper('M2ePro')->__('If Catalog updates in your Magento performed using Import/Export Tools, Custom scripts or direct changes in Database,
                    then, you can use <a target="_blank" href="%url%#magento_block_configuration_settings_advanced">"Track Direct Database Changes"</a> %mode_status% functionality to detect changes in Products\' Price and Quantity.', Mage::helper('M2ePro/View_Configuration')->getSettingsUrl(), $inspectorMode) ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="amazon_templates_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>:</label>
                        </td>
                        <td class="value">
                            <?php $templates_mode = $this->templatesMode ? $this->templatesMode : 0; ?>
                            <select id="amazon_templates_mode" name="amazon_templates_mode" onchange="SynchronizationHandlerObj.changeTemplatesMode('<?php echo Ess_M2ePro_Helper_Component_Amazon::NICK; ?>');">
                                <option value="0"<?php if (0 == $templates_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $templates_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Updates and synchronizes Amazon Listings according to Synchronization Policies' Rules."); ?></span>
                            </p>
                        </td>
                        <td class="value">
                            <div id="amazon_templates_run_now_container" <?php if ($templates_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->getChildHtml('amazon_templates_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('amazon_templates_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('amazon_templates_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>
                    <?php } ?>

                </table>

                <div style="padding: 12px"></div>

                <?php if ($this->isShowReviseAll()) { ?>
                    <div id="block_notice_amazon_synchronization_revise_all" style="<?php if (!$templates_mode) echo 'display: none'; ?>" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

                        <?php echo Mage::helper('M2ePro')->__('If your Amazon Listings for some reason were asynchronized with the Products in Magento, <a href="javascript:" onclick="%script_code%">turn on</a> the Revise All action to catch data up.
        <br/>Revise is performed by the Inventory Synchronization, 100 Items per a cycle.
    <br/><br/>',
        'SynchronizationHandlerObj.showReviseAllConfirmPopup(\''.Ess_M2ePro_Helper_Component_Amazon::NICK.'\');'
                        )?>

                        <span id="amazon_revise_all_start" style="display: none">

                            <span style="color: blue">
                                <?php echo Mage::helper('M2ePro')->__('In Progress, start date - ') ?>
                            </span>

                            <span id="amazon_revise_all_start_date" style="color: blue">
                                <?php echo $this->reviseAllStartDate; ?>
                            </span>

                        </span>

                        <span id="amazon_revise_all_end" style="display: none">

                            <span style="color: green">
                                <?php echo Mage::helper('M2ePro')->__('Finished, end date - ') ?>
                            </span>

                            <span id="amazon_revise_all_end_date" style="color: green">
                                <?php echo $this->reviseAllEndDate; ?>
                            </span>

                        </span>

                    </div>
                <?php } ?>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_amazon_synchronization_orders">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Orders Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="amazon_orders_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>:</label>
                        </td>
                        <td class="value">
                            <?php $orders_mode = $this->ordersMode ? $this->ordersMode : 0; ?>
                            <select id="amazon_orders_mode" name="amazon_orders_mode" onchange="SynchronizationHandlerObj.changeOrdersMode('<?php echo Ess_M2ePro_Helper_Component_Amazon::NICK; ?>');">
                                <option value="0"<?php if (0 == $orders_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $orders_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes Amazon Orders for Accounts, which have enabled Import Amazon Orders in their Accounts Settings.'); ?></span>
                            </p>
                        </td>
                        <td class="value">
                            <div id="amazon_orders_run_now_container" <?php if ($orders_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('amazon_orders_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('amazon_orders_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('amazon_orders_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>
                    <?php } ?>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_amazon_synchronization_listings">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('3rd Party Listings Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="amazon_other_listings_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>:</label>
                        </td>
                        <td class="value">
                            <?php $otherListingsMode = $this->otherListingsMode ? $this->otherListingsMode : 0; ?>
                            <select id="amazon_other_listings_mode" name="amazon_other_listings_mode" onchange="SynchronizationHandlerObj.changeOtherListingsMode('<?php echo Ess_M2ePro_Helper_Component_Amazon::NICK; ?>');">
                                <option value="0"<?php if (0 == $otherListingsMode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $otherListingsMode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes 3rd Party Listings for Amazon Accounts, which have enabled Import 3rd Party Listings in their Accounts Settings.'); ?></span>
                            </p>
                        </td>
                        <td class="value">
                            <div id="amazon_other_listings_run_now_container" <?php if ($otherListingsMode != 1) echo ' style="display: none;"'; ?>>
                                <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('amazon_other_listings_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if ($this->getParentBlock()->canShowRunNowButton('amazon')) { ?>
                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('amazon_other_listings_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('amazon_other_listings_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>
                    <?php } ?>

                </table>

            </div>
        </div>

    </div>

</div>

<div id="amazon_revise_all_confirm_popup" style="display: none;">
    <div style="margin: 17px 0">

        <?php echo Mage::helper('M2ePro')->__(
            'Click \'Confirm\' and Revise will be performed by the Inventory Synchronization, 100 Items per a cycle.'
        ); ?>

    </div>

    <div class="clear"></div>

    <div class="right">
        <a href="javascript:void(0);" onclick="Windows.getFocusedWindow().close()"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $this->getChildHtml('revise_all_confirm_popup_ok_button'); ?>
    </div>

    <div class="clear"></div>

</div>

<?php if ($this->isShowReviseAll()) { ?>
    <script type="text/javascript">

        Event.observe(window, 'load', function() {
            setTimeout(function() {
                SynchronizationHandlerObj.initReviseAllInfo(
                    <?php echo json_encode($this->reviseAllInProcessingState) ?>,
                    '<?php echo $this->reviseAllStartDate ?>',
                    '<?php echo $this->reviseAllEndDate ?>',
                    '<?php echo Ess_M2ePro_Helper_Component_Amazon::NICK ?>'
                );
            }, 400);
        });

    </script>
<?php } ?>