<div id="block_notice_buy_category_template_attributes" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Item Specifics\' Attributes'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Adding specific item details will attract your buyers and help them to find your items.'); ?>
</div>

<script type="text/javascript">

    Event.observe(window, 'load', function() {
        $('buyTemplateNewProductEditTabs_attribute').observe('click', BuyTemplateNewProductHandlerObj.checkAttributeSetSelection);
        $('buyTemplateNewProductEditTabs_attribute').observe('click', BuyTemplateNewProductHandlerObj.checkAttributesReady.bind(BuyTemplateNewProductHandlerObj));
    });

</script>

<div class="entry-edit" id="magento_block_attributes_edit_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Specifics Configuration'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table id="buy_attr_container" class="form-list" cellspacing="0" cellpadding="0" id="attributes" style="width: 100%">
                <td>
                    <?php echo Mage::helper('M2ePro')->__('Select Category first.');?>
                </td>
            </table>

        </div>
    </div>

</div>