<div id="block_notice_buy_template_synchronization_relist" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Relist Rules'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Relist Rules define the conditions and schedule when the Rakuten.com items must be relisted.<br/>
    <ul class="list">
        <li><b>Relist Conditions</b> - the conditions at which the Relist Action will be launched.</li>
        <li><b>Relist Schedule</b> - the schedule of relisting after the end of the initial listing period. It is possible to relist items immediately, after a certain period of time or on certain days of the week that follows.</li>
    </ul>'); ?>
</div>

<?php
$formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();
$defaults = array(
    'relist_mode' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES,
    'relist_filter_user_lock' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES,
    'relist_status_enabled' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES,
    'relist_is_in_stock' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES,
    'relist_qty' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE,
    'relist_qty_value' => '1',
    'relist_qty_value_max' => '10',
    'relist_schedule_type' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_IMMEDIATELY,
    'relist_schedule_through_value' => 0,
    'relist_schedule_through_metric' => Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_DAYS,
    'relist_schedule_week_mo' => 0,
    'relist_schedule_week_tu' => 0,
    'relist_schedule_week_we' => 0,
    'relist_schedule_week_th' => 0,
    'relist_schedule_week_fr' => 0,
    'relist_schedule_week_sa' => 0,
    'relist_schedule_week_su' => 0,
    'relist_schedule_week_start_time' => NULL,
    'relist_schedule_week_end_time' => NULL
);
$formData = array_merge($defaults, $formData);

if (isset($formData['relist_schedule_week']) && $formData['relist_schedule_week']) {
    $temp = explode('_',$formData['relist_schedule_week']);

    $formData['relist_schedule_week_mo'] = (int)$temp[0]{2};
    $formData['relist_schedule_week_tu'] = (int)$temp[1]{2};
    $formData['relist_schedule_week_we'] = (int)$temp[2]{2};
    $formData['relist_schedule_week_th'] = (int)$temp[3]{2};
    $formData['relist_schedule_week_fr'] = (int)$temp[4]{2};
    $formData['relist_schedule_week_sa'] = (int)$temp[5]{2};
    $formData['relist_schedule_week_su'] = (int)$temp[6]{2};
}

$timeStampGmt = Mage::helper('M2ePro')->getCurrentGmtDate(true);
$timeStampCurrentDay = mktime(0, 0, 0, date('m',$timeStampGmt), date('d',$timeStampGmt), date('Y',$timeStampGmt));

if (!is_null($formData['relist_schedule_week_start_time'])) {

    $temp = explode(':',$formData['relist_schedule_week_start_time']);
    $timeStampTemp = $timeStampCurrentDay + (int)$temp[0]*60*60 + (int)$temp[1]*60;
    $formData['relist_schedule_week_start_time'] = Mage::helper('M2ePro')->gmtDateToTimezone($timeStampTemp,false,'H:i');

    $temp = explode(':',$formData['relist_schedule_week_start_time']);
    if (count($temp) >= 2) {
        $formData['relist_schedule_week_start_time'] = $temp[0].':'.$temp[1];
    }
}

if (!is_null($formData['relist_schedule_week_end_time'])) {

    $temp = explode(':',$formData['relist_schedule_week_end_time']);
    $timeStampTemp = $timeStampCurrentDay + (int)$temp[0]*60*60 + (int)$temp[1]*60;
    $formData['relist_schedule_week_end_time'] = Mage::helper('M2ePro')->gmtDateToTimezone($timeStampTemp,false,'H:i');

    $temp = explode(':',$formData['relist_schedule_week_end_time']);
    if (count($temp) >= 2) {
        $formData['relist_schedule_week_end_time'] = $temp[0].':'.$temp[1];
    }
}

if (!is_null($formData['relist_schedule_week_start_time']) &&
    !is_null($formData['relist_schedule_week_end_time'])) {
    $formData['relist_schedule_week_time'] = 1;
} else {
    $formData['relist_schedule_week_start_time'] = '02:00';
    $formData['relist_schedule_week_end_time'] = '03:00';
    $formData['relist_schedule_week_time'] = 0;
}

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.formData.relist_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_mode']); ?>';
    M2ePro.formData.relist_status_enabled = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_status_enabled']); ?>';
    M2ePro.formData.relist_is_in_stock = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_is_in_stock']); ?>';
    M2ePro.formData.relist_qty = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty']); ?>';
    M2ePro.formData.relist_qty_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_value']); ?>';
    M2ePro.formData.relist_qty_value_max = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['relist_qty_value_max']); ?>';

    Event.observe(window, 'load', function() {
        $('relist_mode').observe('change', BuyTemplateSynchronizationHandlerObj.relistMode_change);
        $('relist_qty').observe('change', BuyTemplateSynchronizationHandlerObj.relistQty_change);
        $('relist_schedule_type').observe('change', BuyTemplateSynchronizationHandlerObj.relistScheduleType_change);
        $('relist_schedule_week_time').observe('change', BuyTemplateSynchronizationHandlerObj.relistScheduleWeekTime_change);
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_buy_template_synchronization_relist_filters">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist Action'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_mode" name="relist_mode" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES; ?>" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enables/Disables the Relist action for the Listings, which use current Synchronization Template.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_filter_user_lock_tr_container" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist When Stopped Manually'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_filter_user_lock" name="relist_filter_user_lock" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE; ?>" <?php if ($formData['relist_filter_user_lock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_FILTER_USER_LOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically relists item(s) even it has been stopped manually within M2EPro.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_template_synchronization_relist_rules" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Relist Conditions'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Product Status'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_status_enabled" name="relist_status_enabled" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_NONE; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES; ?>" <?php if ($formData['relist_status_enabled'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_STATUS_ENABLED_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Product Status at which the item(s) have to be relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Stock Availability'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_is_in_stock" name="relist_is_in_stock" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_NONE; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES; ?>" <?php if ($formData['relist_is_in_stock'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_IS_IN_STOCK_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('In Stock'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Stock Availability at which the item(s) have to be relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Item QTY'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_qty" name="relist_qty" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE; ?>" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Any'); ?></option>
                            <!-- <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS; ?>" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_LESS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Less'); ?></option> -->
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE; ?>" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_MORE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('More or Equal'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN; ?>" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Between'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Product(s) quantity at which the item(s) have to be relisted.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_qty_value_container" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_NONE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_value">
                            <span id="relist_qty_item" <?php if ($formData['relist_qty'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Item Quantity'); ?>: <span class="required">*</span></span>
                            <span id="relist_qty_item_min" <?php if ($formData['relist_qty'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>><?php echo Mage::helper('M2ePro')->__('Min Item Quantity'); ?>: <span class="required">*</span></span>
                        </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_value" name="relist_qty_value" value="<?php echo $this->escapeHtml($formData['relist_qty_value']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

                <tr id="relist_qty_value_max_container" <?php if ($formData['relist_qty'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_QTY_BETWEEN) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_qty_value_max"><?php echo Mage::helper('M2ePro')->__('Max Item Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_qty_value_max" name="relist_qty_value_max" value="<?php echo $this->escapeHtml($formData['relist_qty_value_max']); ?>" type="text" class="M2ePro-required-when-visible input-text validate-digits" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_template_synchronization_relist_schedule" <?php if ($formData['relist_mode'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_MODE_NONE): echo ' style="display:none;"'; endif; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Relist Schedule'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Relist Schedule'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_schedule_type" name="relist_schedule_type" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_IMMEDIATELY; ?>" <?php if ($formData['relist_schedule_type'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_IMMEDIATELY): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Immediately'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_THROUGH; ?>" <?php if ($formData['relist_schedule_type'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_THROUGH): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Delay after End'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK; ?>" <?php if ($formData['relist_schedule_type'] == Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Days of Week'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The schedule of item(s) relisting, when the Relist Conditions are met.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_schedule_through_value_container" <?php if ($formData['relist_schedule_type'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_THROUGH) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="relist_schedule_through_value"><?php echo Mage::helper('M2ePro')->__('Delay'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_schedule_through_value" name="relist_schedule_through_value" value="<?php echo $this->escapeHtml($formData['relist_schedule_through_value']); ?>" type="text" style="width: 200px;" class="M2ePro-required-when-visible input-text validate-digits" />
                        <?php $relistThroughMetric = isset($formData['relist_schedule_through_metric']) ? $formData['relist_schedule_through_metric'] : Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_DAYS; ?>
                        <select id="relist_schedule_through_metric" name="relist_schedule_through_metric" style="width: 70px;">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_DAYS; ?>"<?php if (Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_DAYS == $relistThroughMetric) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Days'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_HOURS; ?>"<?php if (Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_HOURS == $relistThroughMetric) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Hours'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_MINUTES; ?>"<?php if (Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_THROUGH_METRIC_MINUTES == $relistThroughMetric) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Minutes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('In how many days, hours or minutes relisting has to start.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_schedule_week_container" <?php if ($formData['relist_schedule_type'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Days of Week'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_schedule_week" name="relist_schedule_week[]" multiple="multiple" class="M2ePro-required-when-visible" style="height: 110px;">
                            <option value="mo" <?php if ($formData['relist_schedule_week_mo'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Monday'); ?></option>
                            <option value="tu" <?php if ($formData['relist_schedule_week_tu'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Tuesday'); ?></option>
                            <option value="we" <?php if ($formData['relist_schedule_week_we'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Wednesday'); ?></option>
                            <option value="th" <?php if ($formData['relist_schedule_week_th'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Thursday'); ?></option>
                            <option value="fr" <?php if ($formData['relist_schedule_week_fr'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Friday'); ?></option>
                            <option value="sa" <?php if ($formData['relist_schedule_week_sa'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Saturday'); ?></option>
                            <option value="su" <?php if ($formData['relist_schedule_week_su'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Sunday'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('On what days of the week that follows the end of initial listing period the items have to be relisted.<br/>(Hold Ctrl button for choosing two or more.)'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_schedule_week_time_container" <?php if ($formData['relist_schedule_type'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Time Interval'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="relist_schedule_week_time" name="relist_schedule_week_time" class="M2ePro-required-when-visible">
                            <option value="0"<?php if ($formData['relist_schedule_week_time'] == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1"<?php if ($formData['relist_schedule_week_time'] == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Sets a time interval, during that the item(s) have to be relisted if the Relist Conditions are met.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_schedule_week_start_time_container" <?php if ($formData['relist_schedule_type'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK || $formData['relist_schedule_week_time'] != 1) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Start Time (hh:mm)'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_schedule_week_start_time" name="relist_schedule_week_start_time" value="<?php echo $this->escapeHtml($formData['relist_schedule_week_start_time']); ?>" type="text" class="M2ePro-required-when-visible M2ePro-input-time input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('hh:mm format (i.e. 20:15).'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="relist_schedule_week_end_time_container" <?php if ($formData['relist_schedule_type'] != Ess_M2ePro_Model_Buy_Template_Synchronization::RELIST_SCHEDULE_TYPE_WEEK || $formData['relist_schedule_week_time'] != 1) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('End Time (hh:mm)'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="relist_schedule_week_end_time" name="relist_schedule_week_end_time" value="<?php echo $this->escapeHtml($formData['relist_schedule_week_end_time']); ?>" type="text" class="M2ePro-required-when-visible M2ePro-input-time input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('hh:mm format (i.e. 21:30).'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>