<div class="entry-edit" id="magento_block_wizard_welcome_requirements" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Requirements'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <?php echo $this->getChildHtml('requirements') ?>

        </div>
    </div>

</div>