<div id="block_notice_common_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set preferences of data synchronization.<br/><br/>

    You have to enable / disable Synchronization tasks, which will be automatically performed for all Accounts, and <i class="underline">Save Settings</i>.<br/>
    To run necessary task manually, click the <i class="underline">Run Now</i> button, to run all tasks at once, click <i class="underline">Run Enabled Now</i>.<br/>'); ?>
</div>