<div id="block_notice_common_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Section allows you to set preferences of data Synchronization.<br/><br/>

    You have to enable / disable Synchronization Tasks, which will be automatically performed for all Accounts, and <i class="underline">Save Settings</i>.<br/>
    To run necessary Task manually, click the <i class="underline">Run Now</i> Button, to run all Tasks at once, click <i class="underline">Run Enabled Now</i>.<br/>'); ?>
</div>