<div id="block_notice_amazon_listings_add_products" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Products'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Displayed products have the same Attribute Set as the Listing you are going to add them to.<br/><br/>
    <b>Note:</b> A product can be added to the listing only once. If a product was added to the Listing earlier, it will not be displayed. '); ?>
</div>