<div id="next_step_warning_popup_content" style="display: none">

    <div style="margin: 10px; height: 155px">
        <?php echo Mage::helper('M2ePro')->__(
'<b>Warning:</b> There are <span id="failed_count"></span> product(s) of <span id="total_count"></span>
which have no Primary eBay category specified.
<br><br>
You can correct it now by Cancelling this message and choosing Edit Category action.
Or if you are not sure which category to choose, Continue working.
You will have a chance to correct category(s) later in the listing settings.'
        ); ?>
    </div>

    <div style="text-align: right">
        <a href="javascript:"
            onclick="EbayListingCategoryProductGridHandlerObj.nextStepWarningPopup.hide();"><?php echo Mage::helper('M2ePro')->__('Cancel') ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>

</div>