<div id="ebay_template_edit_selling_help" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Selling Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('You can adjust how long your items will be active on eBay. You can also choose the price on eBay in relation to your store price. You might want to increase your selling price to take into account the eBay seller fees, or reduce your price to be competitive.'); ?></p>
    <p><?php echo Mage::helper('M2ePro')->__('Remember, you can amend Selling Settings at any time.'); ?></p>
</div>