<div id="ebay_template_edit_selling_help" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Selling Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__(
        'Choose the listing duration, listing type and options you want to use for products listed on eBay using this M2E Pro listing.
        You can also choose whether you want the selling price adjusted for sales on eBay, eg increasing them by a certain amount or
        percentage to allow for seller fees or reducing them to compete against other sellers on eBay.'
    ); ?></p>
<!--    <p>--><?php //echo Mage::helper('M2ePro')->__('Remember, you can amend Selling Settings at any time.'); ?><!--</p>-->
</div>