<?php

$version = Mage::helper('M2ePro/Module')->getVersion();
$skipWizardLink = $this->getUrl("*/adminhtml_wizard_amazon/skip");
$startWizardLink = $this->getUrl("*/adminhtml_wizard_amazon");

?>

<div class="wizard-note">

    <a class="wizard-close" href="javascript:void(0);" onclick="WizardHandlerObj.skip('<?php echo $skipWizardLink; ?>');" title="<?php echo Mage::helper('M2ePro')->__('Skip Wizard') ?>">&times;</a>

    <div>
        <?php

        echo Mage::helper('M2ePro')->__(
            'Click
            <a href="%s">Start Configuration</a> Wizard to quickly set up <strong>Amazon</strong> settings or
            <a href="%s" onclick="%s">Skip</a> it if you intend to set up it later. <br/>
            <strong>Note:</strong> If you close the Wizard now, you will have to set up Amazon settings manually.',
            $startWizardLink,
            'javascript:',
            'confirm(M2ePro.translator.translate(\'Note: If you close the wizard, it never starts again. You will be required to set all settings manually. Press Cancel to continue working with wizard.\')) && setLocation(\''.$skipWizardLink.'\')'
        );

        ?>
    </div>

</div>