<div id="block_notice_ebay_listing_settings_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Set Products Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('Keep the existing M2E Listing settings or customise these settings for the products shown below.'); ?></p>
    <p><?php echo Mage::helper('M2ePro')->__('You can edit Settings for a single product by choosing necessary edit action on appropriate line of the grid<br>
        or edit and set the same settings for several products items: select items and choose necessary action from the Actions drop down menu.'); ?></p>
</div>