<div id="block_notice_ebay_listing_settings_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Set Products Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('Keep the existing M2E Pro Listing settings or customise these settings for the Products shown below.'); ?></p>
    <p><?php echo Mage::helper('M2ePro')->__('You can edit Settings for a single Product by choosing necessary edit action on appropriate line of the grid<br/>
        or edit and set the same settings for several Products Items: select Items and choose necessary action from the Actions drop down menu.'); ?></p>
</div>