<?php
    $selectedCategoriesProductsFrom = '';
    if (count(Mage::helper('M2ePro')->getGlobalValue('temp_listing_categories')) == 0) {
        $selectedCategoriesProductsFrom = 'all';
    } else {
        $selectedCategoriesProductsFrom = 'manual';
    }

    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data') : array();
    $default = array(
        'categories_add_action' => Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE,
        'categories_delete_action' => Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE
    );
    $formData = array_merge($default, $formData);

    $createListingUrl = $this->getUrl(
        '*/adminhtml_amazon_listing/createListing'
    );
    $getProductsUrl = $this->getUrl(
        '*/adminhtml_amazon_listing/getProductsFromCategories'
    );
    $addProductsUrl = $this->getUrl(
        '*/adminhtml_amazon_listing/addProducts'
    );
?>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.create_listing = '<?php echo $createListingUrl ?>';
    M2ePro.url.get_products_from_categories = '<?php echo $getProductsUrl ?>';
    M2ePro.url.add_products = '<?php echo $addProductsUrl ?>';

    WrapperObj = new AreaWrapper('add_products_container');
    ProgressBarObj = new ProgressBar('add_products_progress_bar');
    AmazonAddListingHandlerObj = new AddListingHandler(M2ePro, ProgressBarObj, WrapperObj);
    AmazonListingCategoryHandlerObj = new AmazonListingCategoryHandler(AmazonAddListingHandlerObj);

    Event.observe(window, 'load', function() {
        $('categories_products_from')
            .observe('change', AmazonListingCategoryHandlerObj.categories_products_from_change)
            .simulate('change');
    });

</script>

<div class="entry-edit" id="magento_block_amazon_listings_categories_tree_next_step">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Products Addition'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                <tr>
                    <td class="label">
                        <label for="categories_products_from"><?php echo Mage::helper('M2ePro')->__('Add Products'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="categories_products_from" name="categories_products_from">
                            <option value="all"<?php if ($selectedCategoriesProductsFrom == 'all') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Products'); ?></option>
                            <option value="manual"<?php if ($selectedCategoriesProductsFrom == 'manual') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Select Manually'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Mode of products addition from selected categories.'); ?></span>
                        </p>
                    </td>
                </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_listings_categories_tree_products_actions" <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>style="display:none;"<?php } ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Actions On Categories\' Products'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                    <tr id="categories_add_action_container">
                        <td class="label">
                            <label for="categories_add_action"><?php echo Mage::helper('M2ePro')->__('New Product Added to Category'); ?>: <span class="required" style="float: right;">*</span></label>
                        </td>
                        <td class="value">
                            <select id="categories_add_action" name="categories_add_action" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD_LIST; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD_LIST == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing And List on Amazon'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Actions, which have to be done on products added on categories.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="categories_delete_action_container">
                        <td class="label">
                            <label for="categories_delete_action"><?php echo Mage::helper('M2ePro')->__('Product Deleted from Category'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="categories_delete_action" name="categories_delete_action" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on Amazon'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP_REMOVE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP_REMOVE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on Amazon and Delete from Listing'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Actions, which have to be done on listed products deleted from categories.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>
