<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.getFeedbackTemplates = '<?php echo $this->getUrl('*/*/getFeedbackTemplates'); ?>';

    M2ePro.text.response_text_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Should be between 2 and 80 characters long.')); ?>';
    M2ePro.text.feedback_sent_successfully = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Feedback has been successfully sent.')); ?>';

    Event.observe(window, 'load', function() {
        EbayFeedbackHandlerObj = new EbayFeedbackHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        $('feedback_template').observe('change', EbayFeedbackHandlerObj.feedback_template_change);
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_ebay_feedbacks_response" collapseable="no" style="display: none;">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Response Message'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <input id="feedback_id" name="feedback_id" value="" type="hidden" />

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Transaction ID'); ?>:</label>
                        </td>
                        <td class="label">
                            <span id="transaction_id" class="required-entry" style="width: 275px;"></span>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Item ID'); ?>:</label>
                        </td>
                        <td class="label">
                            <span id="item_id" class="required-entry" style="width: 275px;"></span>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Buyer\'s Feedback'); ?>:</label>
                        </td>
                        <td class="label">
                            <span id="buyer_text" style="width: 275px;"></span>
                        </td>
                    </tr>

                    <tr id="feedback_template_tr" style="display: none;">
                        <td class="label">
                            <label for="feedback_template"><?php echo Mage::helper('M2ePro')->__('Choose Predefined Feedback'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="label">
                            <select id="feedback_template" name="feedback_template" style="width: 275px;"></select>
                        </td>
                    </tr>

                    <tr id="feedback_text_tr">
                        <td class="label">
                            <label for="feedback_text">
                                <span id="new_feedback_label_text" style="display: none;">
                                    <?php echo Mage::helper('M2ePro')->__('Response Message'); ?>: <span class="required">*</span>
                                </span>
                                <span id="template_feedback_label_text" style="display: none;">
                                    <?php echo Mage::helper('M2ePro')->__('Or Write Your Own'); ?>: <span class="required">*</span>
                                </span>
                            </label>
                        </td>
                        <td class="label">
                            <textarea id="feedback_text" name="feedback_text" style="padding: 0px; height: 40px; width: 275px;" class="textarea M2ePro-required-when-visible M2ePro-validate-max-length"></textarea>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('send_feedback');?>
                            <?php echo $this->getChildHtml('cancel_feedback');?>
                        </td>
                    </tr>

                 </table>

            </div>
        </div>

    </div>

</form>