<div id="block_notice_buy_category_template_attributes" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Specifics\' Attributes'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Adding specific item details will attract your buyers and help them to find your items.'); ?>
</div>

<script type="text/javascript">

    M2ePro.translator.add(<?php echo json_encode(array(
        'At least one of the following attributes must be chosen:' => Mage::helper('M2ePro')->__('At least one of the following attributes must be chosen:'),
        'At least one of these attributes is required.' => Mage::helper('M2ePro')->__('At least one of these attributes is required.'),
        'Multiple values ​​must be separated by comma.' => Mage::helper('M2ePro')->__('Multiple values ​​must be separated by comma.'),

        'None' => Mage::helper('M2ePro')->__('None'),
        'Recommended Values' => Mage::helper('M2ePro')->__('Recommended Values'),
        'Allowed Values' => Mage::helper('M2ePro')->__('Allowed Values'),
        'Custom Value' => Mage::helper('M2ePro')->__('Custom Value'),
        'Custom Attribute' => Mage::helper('M2ePro')->__('Custom Attribute'),

        'Any integer value' => Mage::helper('M2ePro')->__('Any integer value'),
        'Any decimal value' => Mage::helper('M2ePro')->__('Any decimal value'),
        'Any string value' => Mage::helper('M2ePro')->__('Any string value'),

        'The category does not have attributes.' => Mage::helper('M2ePro')->__('The category does not have attributes.')
    )); ?>);

    Event.observe(window, 'load', function() {
        $('buyTemplateNewProductEditTabs_attribute').observe('click', BuyTemplateNewProductHandlerObj.checkAttributeSetSelection);
        $('buyTemplateNewProductEditTabs_attribute').observe('click', BuyTemplateNewProductHandlerObj.checkAttributesReady.bind(BuyTemplateNewProductHandlerObj));
    });

</script>

<div class="entry-edit" id="magento_block_attributes_edit_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Specifics Configuration'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table id="buy_attr_container" class="form-list" cellspacing="0" cellpadding="0" id="attributes" style="width: 100%">
                <td>
                    <?php echo Mage::helper('M2ePro')->__('Select Category first.');?>
                </td>
            </table>

        </div>
    </div>

</div>