<div id="block_notice_buy_newProduct_template_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This tab contains the main information on products you want to list: Attribute Set
 (it must be the same as M2E Listing has to be assigned), Products Identifiers and
 Category in which the products have to be listed.<br><br>
The category either can be chosen by <u>Browsing</u> all categories from the list or can be found with <u>Searching
 tool</u> by entering keywords.'); ?>
</div>

<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();
$default = array(
    'category' => array(
        'id' => '',
        'attribute_sets' => array(),
        'path' => '',
        'node_id' => '',
        'node_title' => '',
        'category_id' => '',

        'title' => '',

        'seller_sku_custom_attribute' => '',

        'gtin_mode' => Ess_M2ePro_Model_Buy_Template_NewProduct_Core::GTIN_MODE_CUSTOM_ATTRIBUTE,
        'gtin_custom_attribute' => '',

        'isbn_mode' => '',
        'isbn_custom_attribute' => '',

        'asin_mode' => '',
        'asin_custom_attribute' => '',

        'product_set_id_mode' => '',
        'product_set_id_custom_value' => '',
        'product_set_id_custom_attribute' => '',
    ),
    'attributes' => array()
);

$formData = array_merge($default, $formData);
$isEdit = !!$this->getRequest()->getParam('id');

if (!$isEdit && count((array)$this->listingAttributeSetsIds) > 0) {
    $formData['category']['attribute_sets'] = $this->listingAttributeSetsIds;
}
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Buy_Template_NewProduct_Core'); ?>,'Ess_M2ePro_Model_Buy_Template_NewProduct_Core');
    M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Buy_Template_NewProduct_Attribute'); ?>,'Ess_M2ePro_Model_Buy_Template_NewProduct_Attribute');

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_common_buy_template_newProduct')) ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Invalid input data. Integer value required.' => Mage::helper('M2ePro')->__('Invalid input data. Integer value required.'),
        'Invalid input data. Decimal value required. Example 12.05' => Mage::helper('M2ePro')->__('Invalid input data. Decimal value required. Example 12.05'),
        'Invalid input data. String value required.' => Mage::helper('M2ePro')->__('Invalid input data. String value required.'),

        'The specified title is already used for another New SKU Template.' => Mage::helper('M2ePro')->__('The specified title is already used for another New SKU Template.'),
        'Select Category first.' => Mage::helper('M2ePro')->__('Select Category first.'),
        'Search For Category' => Mage::helper('M2ePro')->__('Search For Category'),

        'All of your product images should meet the following rules:' => Mage::helper('M2ePro')->__('All of your product images should meet the following rules:'),

        'Must be at least 500 pixels in width or height' => Mage::helper('M2ePro')->__('Must be at least 500 pixels in width or height'),
        'No more than 5 megabytes (MB) in size' => Mage::helper('M2ePro')->__('No more than 5 megabytes (MB) in size'),
        'In the JPG/JPEG format' => Mage::helper('M2ePro')->__('In the JPG/JPEG format'),
        'Only contain the product being sold' => Mage::helper('M2ePro')->__('Only contain the product being sold'),
        'Be in focus with realistic color with a pure white background' => Mage::helper('M2ePro')->__('Be in focus with realistic color with a pure white background'),
        'Cannot contain additional text, graphics or inset images' => Mage::helper('M2ePro')->__('Cannot contain additional text, graphics or inset images'),

        'Text to describe the product. Should be one block of text or a single paragraph. Do not use special characters and html tags' => Mage::helper('M2ePro')->__('Text to describe the product. Should be one block of text or a single paragraph. Do not use special characters and html tags'),
        'Internal Error. Please try again later.' => Mage::helper('M2ePro')->__('Internal Error. Please try again later.'),

        'Notes:'        => Mage::helper('M2ePro')->__('Notes:'),
        'Definition:'   => Mage::helper('M2ePro')->__('Definition:'),
        'Tips:'         => Mage::helper('M2ePro')->__('Tips:'),
        'Examples:'     => Mage::helper('M2ePro')->__('Examples:'),
        'Helpful Info:' => Mage::helper('M2ePro')->__('Helpful Info:')

    )); ?>);

    M2ePro.formData  = <?php echo json_encode($formData); ?>;

    Event.observe(window, 'load', function() {

        AttributeSetHandlerObj = new AttributeSetHandler();
        BuyTemplateNewProductHandlerObj = new CommonBuyTemplateNewProductHandler(new CommonBuyTemplateNewProductAttributeHandler,AttributeSetHandlerObj);

        var attribute_sets = $('attribute_sets');
        attribute_sets.observe('change', AttributeSetHandlerObj.changeAttributeSets);
        if (attribute_sets.value) {
            AttributeSetHandlerObj.confirmAttributeSets();
            BuyTemplateNewProductHandlerObj.attribute_sets_confirm();
        }

        $('attribute_sets_confirm_button')
            .observe('click',BuyTemplateNewProductHandlerObj.attribute_sets_confirm.bind(BuyTemplateNewProductHandlerObj))
            .observe('click',BuyTemplateNewProductHandlerObj.confirmAttributeSets);

        $('rakuten_native_id')
            .observe('change', BuyTemplateNewProductHandlerObj.rakuten_category_change)
            .simulate('change');

        $('node_title').observe('change', function(event) {
            BuyTemplateNewProductHandlerObj.node_title_change(this)
        });

        $('gtin_mode')
            .observe('change', BuyTemplateNewProductHandlerObj.gtin_mode_change)
            .simulate('change');
        $('isbn_mode')
            .observe('change', BuyTemplateNewProductHandlerObj.isbn_mode_change)
            .simulate('change');
        $('asin_mode')
            .observe('change', BuyTemplateNewProductHandlerObj.asin_mode_change)
            .simulate('change');
        $('product_set_id_mode')
            .observe('change', BuyTemplateNewProductHandlerObj.product_set_id_mode_change)
            .simulate('change');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
</script>

<style type="text/css">

    .input-text-small {
        width: 120px !important;
    }
    .textarea {
        width: 98% !important;
        height: 500px !important;
    }
    select.select-main {
        width: 356px !important;
    }
    .select-wrapper {
        margin-left: 15px;
    }
    a.action-disabled {
        color: gray !important;
        text-decoration: none !important;
    }
    a.action-disabled:hover {
        color: gray !important;
        text-decoration: none !important;
    }
    td.value {
        width: auto !important;
    }
    .form-list td.value p.note {
        width:auto !important;
    }
</style>

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />
<input name="category[category_id]" value="<?php echo $formData['category']['id']; ?>" type="hidden" />

<div class="entry-edit" id="magento_block_category_edit_general">

    <input name="category[native_id]" class = "rakuten_native_id" id="rakuten_native_id" value="<?php echo $formData['category']['category_id']; ?>" type="hidden" />

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="category[title]" value="<?php echo $this->escapeHtml($formData['category']['title']); ?>" type="text" class="input-text required-entry M2ePro-new-sku-template-title"/>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short meaningful template title for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Set'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                            <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                            <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="category[attribute_sets<?php echo $attributeSetPostfix; ?>][]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['category']['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <?php if ($this->attribute_set_locked): ?>
                        <div id="attribute_sets_breadcrumb" style="width: 280px;">
                            <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                            <?php if (in_array($set['attribute_set_id'], $formData['category']['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                            <?php endforeach; ?>
                            <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                        </div>
                        <input id="attribute_sets" name="category[attribute_sets]" value="<?php echo $this->escapeHtml(implode(',', $formData['category']['attribute_sets'])); ?>" type="hidden" />
                        <?php endif; ?>

                        <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                            <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                            <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                        </div>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Attribute Sets of products which will be listed on Rakuten using this template.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Category'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div <?php if ($isEdit) echo 'style="display: none"'?>>
                            <span style="margin: 0 10px 0 0">
                                <?php echo $this->getChildHtml('browse_category_button'); ?>
                            </span>
                            <strong><?php echo Mage::helper('M2ePro')->__('or'); ?></strong>
                            <span style="margin: 0 0 0 10px">
                                <?php echo $this->getChildHtml('search_category_button'); ?>
                            </span>
                        </div>
                        <div>
                            <p id="category_change_button_container" style="display: none; margin: 1px 0 0 0">
                                <?php echo $this->getChildHtml('category_change_button'); ?>
                            </p>
                        </div>
                    </td>
                </tr>

            </table>

            <div>
                <?php if ($formData['category']['node_title']) { ?>
                    <?php foreach ($this->nodes as $node) {
                        if ($node['title'] == $formData['category']['node_title']) {
                            echo '<input id="node_id" name="node_id" value="'.$node['node_id'].'" type="hidden" />';
                            echo '<input id="id_node_key" name="id_node_key" value="'.$node['category_id'].'" type="hidden" />';
                            break;
                        }
                    } ?>
                    <input type="hidden" name="category[node_title]" value="<?php echo $formData['category']['node_title']; ?>"/>
                <?php } else { ?>
                    <input type="hidden" name="category[node_title]" value=""/>
                <?php } ?>

            </div>

        </div>
    </div>
</div>
<div class="entry-edit" id="magento_block_base_edit_general">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Identifiers'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">

                <!-- Seller Sku-->

                <tr id="seller_sku_custom_attribute_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Seller SKU'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="seller_sku_custom_attribute_td"></div>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Seller defined alpha-numeric string uniquely identifying the product. Needs to be unique across all products and manufacturers.<br />
                                                                         Example: KDK6490CAM'); ?></span>
                        </p>
                    </td>
                </tr>

                <!-- GTIN -->
                <tr <?php if(!$this->isAllowedUpcExemption($formData)) : echo 'style="display: none;"'; endif; ?>>
                    <td class="label">
                        <label for="gtin_mode"><?php echo Mage::helper('M2ePro')->__('GTIN (UPC or EAN)'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="gtin_mode" name="category[gtin_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::GTIN_MODE_NONE; ?>" <?php if ($formData['category']['gtin_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::GTIN_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::GTIN_MODE_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['category']['gtin_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::GTIN_MODE_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('To sell without UPC code you have to get permission from Rakuten.com.'); ?></span>
                        </p>
                    </td>
                </tr>
                <tr id="gtin_custom_attribute_tr">
                    <td class="label">
                        <?php $labelText = $this->isAllowedUpcExemption($formData) ? 'Custom Attribute' : 'GTIN (UPC or EAN)'; ?>
                        <label><?php echo Mage::helper('M2ePro')->__($labelText); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="gtin_custom_attribute_td"></div>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('The GTIN (UPC or EAN) compatible product identifier must be at least 12 digits in length.'); ?></span>
                        </p>
                    </td>
                </tr>

                <!-- ISBN -->
                <tr>
                    <td class="label">
                        <label for="isbn_mode"><?php echo Mage::helper('M2ePro')->__('ISBN'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="isbn_mode" name="category[isbn_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ISBN_MODE_NONE; ?>" <?php if ($formData['category']['isbn_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ISBN_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ISBN_MODE_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['category']['isbn_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ISBN_MODE_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('International book identifier. Use only digits in this field.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="isbn_custom_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="isbn_custom_attribute_td"></div>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;">
                    </td>
                </tr>

                <!-- ASIN -->
                <tr>
                    <td class="label">
                        <label for="asin_mode"><?php echo Mage::helper('M2ePro')->__('ASIN'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="asin_mode" name="category[asin_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ASIN_MODE_NONE; ?>" <?php if ($formData['category']['asin_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ASIN_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ASIN_MODE_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['category']['asin_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::ASIN_MODE_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Rakuten.com product identifier.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="asin_custom_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="asin_custom_attribute_td"></div>
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_product_set_edit_general">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Product Set'); ?></h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">

                <!-- product-set-id -->
                <tr>
                    <td class="label">
                        <label for="product_set_id_mode"><?php echo Mage::helper('M2ePro')->__('Product Set ID'); ?>: </label>
                    </td>
                    <td class="value">
                        <select id="product_set_id_mode" name="category[product_set_id_mode]" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_NONE; ?>" <?php if ($formData['category']['product_set_id_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_CUSTOM_VALUE; ?>" <?php if ($formData['category']['product_set_id_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['category']['product_set_id_mode'] == Ess_M2ePro_Model_Buy_Template_NewProduct_Core::PRODUCT_SET_ID_MODE_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Rakuten.com groups products together in the same family by this parameter.<br/>
                                <b>For ex.</b>, a product "T-shirt" has 4 different colors. As Rakuten.com does not<br/>have parent/child product relationships each of these products is treated as totally separate.
                                <br/>By assigning all 4 T-shirts the same Product Set ID, all of them will be placed on the same<br/>Rakuten.com web page with pull down menu of selecting color.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="product_set_id_custom_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="product_set_id_custom_value_td" name="category[product_set_id_custom_value]" value="<?php echo Mage::helper('M2ePro')->__($formData['category']['product_set_id_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

                <tr id="product_set_id_custom_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="product_set_id_custom_attribute_td"></div>
                    </td>
                </tr>

            </table>
        </div>
    </div>

</div>

<div style="display: none">

    <div class="entry-edit" id="browse_category" style="margin-top: 15px;">

        <div style="height: 450px">
            <div id="block_notice_buy_category_template_browse" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Browse'); ?>">
                <?php echo Mage::helper('M2ePro')->__('Choose the department your product belongs to and then choose the category you need.<br/>Press the Confirm button.'); ?>
            </div>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Category'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellpadding="0" cellspacing="0">

                        <tr>
                            <td class="label">
                                <label for="node_title"><?php echo Mage::helper('M2ePro')->__('Department'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">

                                <select id="node_title" name="category[node_title]" class="required-entry">
                                    <option style="display: none"></option>
                                    <?php foreach ($this->nodes as $node) { ?>
                                    <option value="<?php echo $node['title'] ;?>" id_node_key = "<?php echo $node['category_id']; ?>" node_id="<?php echo $node['node_id']; ?>"> <?php echo $node['title'] ;?></option>
                                    <?php } ?>
                                </select>

                            </td>
                        </tr>

                        <tr id="categories_tr" <?php if (empty($formData['category']['category_path'])) : ?> style="display: none;" <?php endif; ?>>

                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Category'); ?>: <span class="required">*</span></label>
                            </td>

                            <td class="value">
                                <table>
                                    <tr>
                                        <td>
                                            <div id="categories_container"></div>
                                        </td>
                                    </tr>
                                </table>

                                <p id="category_confirm_button_container" style="display: none; margin: 1px 0 0 0; float: left">
                                    <?php echo $this->getChildHtml('category_confirm_button'); ?>
                                </p>
                            </td>

                        </tr>

                    </table>

                </div>
            </div>
        </div>

        <div class="right" style="margin-right: 15px">
            <?php echo $this->getChildHtml('close_browse_popup_button'); ?>
        </div>

    </div>

    <div class="entry-edit" id="search_category" style="margin-top: 15px; height: 500px; overflow: hidden;">

        <div id="error_block" class="error-msg" style="margin-bottom: 10px; display: none">
            <div style="margin: 10px 0px 10px 35px;" >
                <div id="error_message" style="font-weight:bold"></div>
            </div>
        </div>

        <div id="block_notice_buy_category_template_search" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search'); ?>">
            <?php echo Mage::helper('M2ePro')->__('Enter the words, which describe the best your product and click on the Search button.<br/>
Founded categories will be displayed for selection. '); ?>
        </div>

        <div style="padding: 10px; border: 1px solid rgb(205, 221, 221) !important; background-image: none !important; background-attachment: scroll !important; background-color: rgb(231, 239, 239) !important; background-position: 0px 0px !important; background-repeat: repeat repeat !important;">

            <label for="search_keywords" style="margin-right: 10px"><?php echo Mage::helper('M2ePro')->__('Enter Keywords'); ?></label>
            <input id="search_keywords" style="margin-right: 5px;padding: 4px; color: gray;" name="search_keywords" value="Example: mp3 player, baseball glove, DVD, guitar, etc" class="input-text" type="text" size="60"
                   onblur="if (this.value.trim().length == 0) {
                       this.value = 'Example: mp3 player, baseball glove, DVD, guitar, etc';
                       this.style.color = 'gray';
                   }"
                   onclick="if (this.value == 'Example: mp3 player, baseball glove, DVD, guitar, etc') {
                       this.value = '';
                       this.style.color = '';
                   }"
                   onkeypress="if (event.keyCode == 13) {
                       BuyTemplateNewProductHandlerObj.searchClick();
                   }"
                    >

            <?php echo $this->getChildHtml('search_category_popup_button'); ?>
            &nbsp;
            <?php echo $this->getChildHtml('reset_category_popup_button'); ?>

        </div>

        <div id="searchGrid" style="margin: 10px auto; height: 340px !important; overflow-y: auto; overflow-x: hidden;">
        </div>

        <div class="right" style="margin-right: 15px; position: absolute; left: 795px; top: 540px;">
            <?php echo $this->getChildHtml('close_search_popup_button'); ?>
        </div>

        <div style="clear:both;"></div>

    </div>

</div>