<?php
    $categoryType = Mage::helper('M2ePro/Data_Global')->getValue('chooser_category_type');
    $ebayCategoryTypes =  Mage::helper('M2ePro/Component_Ebay_Category')->getEbayCategoryTypes();
?>

<style>
    .category-children-block {
        display: inline-block;
        margin-left: 10px;
    }
</style>

<script type="text/javascript">
    EbayListingCategoryChooserBrowseHandlerObj = new EbayListingCategoryChooserBrowseHandler();

    M2ePro.url.add(<?php echo json_encode(array(
        'adminhtml_general/getChildCategories' => $this->getUrl('M2ePro/adminhtml_general/getChildCategories'),
    )); ?>);

    EbayListingCategoryChooserBrowseHandlerObj.setMarketplaceId(EbayListingCategoryChooserHandlerObj.getMarketplaceId());
    EbayListingCategoryChooserBrowseHandlerObj.renderTopLevelCategories('chooser_browser');
    EbayListingCategoryChooserBrowseHandlerObj.observe('leaf_selected', function(selected) {
        var leafId = selected[selected.length-1];
        EbayListingCategoryChooserHandlerObj.selectCategory(M2ePro.php.constant('Ess_M2ePro_Model_Ebay_Template_Category::CATEGORY_MODE_EBAY'), leafId);
    });
</script>

<?php if (in_array($categoryType, $ebayCategoryTypes)): ?>
    <div id="block_notice_ebay_category_chooser_browser_refresh" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php echo Mage::helper('M2ePro')->__('If you cannot find necessary category, try to <a href="javascript:void(0)" onclick="EbayListingCategoryChooserHandlerObj.refreshEbayCategories()">update eBay sites data</a>.') ?>
    </div>
<?php else: ?>
    <div id="block_notice_ebay_category_chooser_browser_refresh" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
        <?php echo Mage::helper('M2ePro')->__('If you cannot find necessary store category, try to <a href="javascript:void(0)" onclick="EbayListingCategoryChooserHandlerObj.refreshStoreCategories()">refresh eBay store data</a>.') ?>
    </div>
<?php endif; ?>
<div id="chooser_browser"></div>