<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();

$defaults = array(
    'account_id' => 0,
    'sku_mode' => Ess_M2ePro_Model_Play_Listing::SKU_MODE_NOT_SET,
    'sku_custom_attribute' => '',
    'generate_sku_mode' => Ess_M2ePro_Model_Play_Listing::GENERATE_SKU_MODE_NO,

    'general_id_mode' => Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET,
    'general_id_custom_attribute' => '',

    'search_by_magento_title_mode' => Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES,

    'dispatch_to_mode' => Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_NOT_SET,
    'dispatch_to_value' => '',
    'dispatch_to_custom_attribute' => '',

    'dispatch_from_mode' => Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_NOT_SET,
    'dispatch_from_value' => '',

    'shipping_price_gbr_mode' => Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_NONE,
    'shipping_price_gbr_value' => '',
    'shipping_price_gbr_custom_attribute' => '',

    'shipping_price_euro_mode' => Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_NONE,
    'shipping_price_euro_value' => '',
    'shipping_price_euro_custom_attribute' => '',

    'condition_mode' => Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_NOT_SET,
    'condition_value' => '',
    'condition_custom_attribute' => '',
    'condition_note_mode' => Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_NOT_SET,
    'condition_note_value' => '',
    'condition_note_custom_attribute' => '',
);
$formData = array_merge($defaults, $formData);

if (count($this->getData('accounts')) == 1) {
    $formData['account_id'] = $this->getData('accounts');
    $formData['account_id'] = reset($formData['account_id']);
    $formData['account_id'] = (int)$formData['account_id']['id'];
}

$isEdit = (bool)$this->getRequest()->getParam('id');

$docsLink = Mage::helper('M2ePro/View_Common')->getDocumentationUrl();
$docsLinkDispatchTo = $docsLink.'Play.com+Listing+Creation#Play.comListingCreation-DeliveryRegion';
$docsLinkCondition = $docsLink.'Play.com+Listing+Creation#Play.comListingCreation-ConditionIDs';
?>

<?php if (!$isEdit) { ?>
<div id="block_notice_play_listing_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Channel Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('<div>
    This section contains Play.com Channel, Product Search, Shipping and Condition settings.<br>
        <ul class="list">
        <li>In the General section you have to specify Play.com Account, which listed items will be related to, and the Reference Code for its products.</li>
        <li>In the Search Settings you have to specify the identifiers, at which products will be searched on Play.com.</li>
        <li>In the Shipping section you have to specify Shipping information.</li>
        <li>The Condition section allows specifying item(s) condition and making notes to better describe the condition.</li>
        </ul>
        <b>Note:</b> <i>Not Set</i> and <i>Not Set / Not Changeable</i> options are used for the 3rd Party Listings mainly. If these options are chosen, Play.com will be used as a master record.</div>'); ?>
</div>
<?php } ?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }
    //-----------------------------

    M2ePro.text.general_id_label_upc = '<?php echo Mage::helper('M2ePro')->__('UPC/EAN Attribute') ?>';
    M2ePro.text.general_id_label_play_id = '<?php echo Mage::helper('M2ePro')->__('Play ID Attribute') ?>';
    M2ePro.text.general_id_label_isbn = '<?php echo Mage::helper('M2ePro')->__('ISBN Attribute') ?>';

    M2ePro.text.general_id_tips_play_id = '<?php echo Mage::helper('M2ePro')->__('Parameter the product search will be performed by.<br/>For ex.: http://www.play.com/Mobiles/Mobile/4-/20020059/-/Product.html.<br/>Play ID = 20020059'); ?>';
    M2ePro.text.general_id_tips_default = '<?php echo Mage::helper('M2ePro')->__('Parameter the product search will be performed by.') ?>';

</script>

<script type="text/javascript">

    // ie bug fix
    // ---------
    if (Prototype && Prototype.Browser.IE && varienLoaderHandler) {
        var loaderOnCompleteFunction = varienLoaderHandler.handler.onComplete;
        varienLoaderHandler.handler.onComplete = function() {

            loaderOnCompleteFunction();
            $$('select').each(function (el) {
                $(el).style.visibility = 'visible';
            });
        }
    }
    // ---------

    // Data for current tab
    //-----------------------------
    M2ePro.formData.account_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['account_id']); ?>';

    M2ePro.text.condition_note_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be not more than 250 characters long.')); ?>';
    M2ePro.text.shipping_rate_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be a positive number with two decimal places.')); ?>';

    Event.observe(window, 'load', function() {

        PlayListingChannelSettingsHandlerObj = new PlayListingChannelSettingsHandler();
        PlayListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Play_Listing'); ?>');

        $('sku_mode').observe('change', PlayListingChannelSettingsHandlerObj.sku_mode_change);

        $('sku_custom_attribute').observe('change', PlayListingChannelSettingsHandlerObj.sku_custom_attribute_change);
        $F('sku_custom_attribute') && $('sku_custom_attribute').simulate('change');

        $('general_id_mode').observe('change', PlayListingChannelSettingsHandlerObj.general_id_mode_change);
        $('general_id_mode').simulate('change');

        $('general_id_custom_attribute').observe('change', PlayListingChannelSettingsHandlerObj.general_id_custom_attribute_change);
        $F('general_id_custom_attribute') && $('general_id_custom_attribute').simulate('change');

        $('dispatch_to_mode').observe('change', PlayListingChannelSettingsHandlerObj.dispatch_to_mode_change);
        $('dispatch_to_mode').simulate('change');

        $('dispatch_from_mode').observe('change', PlayListingChannelSettingsHandlerObj.dispatch_from_mode_change);
        $('dispatch_from_mode').simulate('change');

        $('dispatch_to_value').observe('change', PlayListingChannelSettingsHandlerObj.dispatch_to_value_change);
        $('dispatch_to_value').simulate('change');

        $('shipping_price_gbr_mode').observe('change', PlayListingChannelSettingsHandlerObj.price_gbr_mode_change);
        $('shipping_price_gbr_mode').simulate('change');

        $('shipping_price_euro_mode').observe('change', PlayListingChannelSettingsHandlerObj.price_euro_mode_change);
        $('shipping_price_euro_mode').simulate('change');

        $('condition_mode').observe('change', PlayListingChannelSettingsHandlerObj.condition_mode_change);
        $('condition_mode').simulate('change');

        $('condition_value').observe('change', PlayListingChannelSettingsHandlerObj.condition_value_change);
        $F('condition_value') && $('condition_value').simulate('change');

        $('condition_custom_attribute').observe('change', PlayListingChannelSettingsHandlerObj.condition_custom_attribute_change);
        $F('condition_custom_attribute') && $('condition_custom_attribute').simulate('change');

        $('condition_note_mode').observe('change', PlayListingChannelSettingsHandlerObj.condition_note_mode_change);

        $('condition_note_custom_attribute').observe('change', PlayListingChannelSettingsHandlerObj.condition_note_custom_attribute_change);
        $F('condition_note_custom_attribute') && $('condition_note_custom_attribute').simulate('change');
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_play_listing_channel_settings_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr <?php if (count($this->getData('accounts')) == 1) { ?>style="display: none;" <?php } ?>>
                    <td class="label">
                        <label for="account_id"><?php echo Mage::helper('M2ePro')->__('Play.com Account'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="account_id" name="account_id" class="required-entry" <?php if ($isEdit): ?>disabled="disabled"<?php endif; ?>>
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('accounts') as $account): ?>
                                <?php if ($isEdit && $formData['account_id'] != $account['id']){ continue; } ?>
                                <option value="<?php echo $account['id']; ?>" <?php if ($formData['account_id'] == $account['id']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($account['title']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Play.com accounts previously added in Configuration > Accounts.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="sku_mode"><?php echo Mage::helper('M2ePro')->__('Reference Code') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="sku_mode" id="sku_mode" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SKU_MODE_NOT_SET ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Play_Listing::SKU_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SKU_MODE_PRODUCT_ID ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Play_Listing::SKU_MODE_PRODUCT_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SKU_MODE_DEFAULT ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Play_Listing::SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SKU_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Play_Listing::SKU_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('A unique ID, which identify a product in your Play.com seller inventory.<br/>
<b>Note:</b> If you list a product and M2E Pro find a product with the same Reference Code in Play.com inventory, they will be mapped.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="sku_custom_attribute_container" <?php if ($formData['sku_mode'] != Ess_M2ePro_Model_Play_Listing::SKU_MODE_CUSTOM_ATTRIBUTE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="sku_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Reference Code Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="sku_custom_attribute" name="sku_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['sku_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['sku_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="generate_sku_mode"><?php echo Mage::helper('M2ePro')->__('Generate Reference Code') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="generate_sku_mode" id="generate_sku_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERATE_SKU_MODE_NO; ?>" <?php if ($formData['generate_sku_mode'] == Ess_M2ePro_Model_Play_Listing::GENERATE_SKU_MODE_NO) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERATE_SKU_MODE_YES ?>" <?php if ($formData['generate_sku_mode'] == Ess_M2ePro_Model_Play_Listing::GENERATE_SKU_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i>, then if the Reference Code of the product you list is found in the 3rd Party or M2E Listings, another one will be automatically created and the product will be listed.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_play_listing_channel_settings_source">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Search Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_play_listing_general_search" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Products On Play.com'); ?>">
                <?php echo Mage::helper('M2ePro')->__('At the moment, it is possible only to list items existing on Play.com.
So before the list action, each product in listing must have existing Play ID.
This section contains parameters for action "Assign Play ID Automatically",
which is used to search and assign Play ID for a single product or in a bulk.
<br><br>The parameters are used according to the following logic:
                <ul class="list">
                <li>the product is searched by Play.com identifier you have specified. (if specified)</li>
                <li>if no result by identifier parameter, then additional search by Magento product name is performed. (if enabled)</li>
                </ul>
<b>Note:</b> These settings are also used in auto list action.
                '); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="general_id_mode_container">
                    <td class="label">
                        <label for="general_id_mode"><?php echo Mage::helper('M2ePro')->__('Identifiers'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="general_id_mode" name="general_id_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_WORLDWIDE ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_WORLDWIDE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('UPC/EAN') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_GENERAL_ID ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_GENERAL_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Play ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_ISBN ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_ISBN) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('ISBN') ?></option>
                        </select>
                        <p class="note" id="general_id_tips"></p>
                    </td>
                </tr>

                <tr id="general_id_custom_attribute_container" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="general_id_custom_attribute" id="general_id_attribute_label"></label>
                    </td>
                    <td class="value">
                        <select id="general_id_custom_attribute" name="general_id_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['general_id_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['general_id_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Specify the attribute, which contains necessary information.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="search_by_magento_title_mode"><?php echo Mage::helper('M2ePro')->__('Additional Search by Product Name'); ?>:
                    </td>
                    <td class="value">
                        <select id="search_by_magento_title_mode" name="search_by_magento_title_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE ?>" <?php if ($formData['search_by_magento_title_mode'] == Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Disable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES ?>" <?php if ($formData['search_by_magento_title_mode'] == Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Enable') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If no results are found by the search criteria above, the additional search will be performed by Magento Product Name.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_play_listing_channel_settings_shipping">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Shipping Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_play_listing_general_shipping" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Shipping'); ?>">
                <?php echo Mage::helper('M2ePro')->__('
                This section determines information about how your products will be shipped.
                <br><br>
                <b>Note:</b> <i>Not Set / Not Changeable</i> is used for the 3rd Party Listings mainly. If this option is chosen, Play.com will be used as a master record.
                '); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="dispatch_to_mode"><?php echo Mage::helper('M2ePro')->__('Delivery Region') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="dispatch_to_mode" id="dispatch_to_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_NOT_SET ?>" <?php if ($formData['dispatch_to_mode'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_DEFAULT ?>" <?php if ($formData['dispatch_to_mode'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Recommended Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['dispatch_to_mode'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Region to which you are willing to deliver.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="dispatch_to_value_tr" <?php if ($formData['dispatch_to_mode'] != Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_DEFAULT): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="dispatch_to_value"><?php echo Mage::helper('M2ePro')->__('Delivery Region Value') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="dispatch_to_value" id="dispatch_to_value" class="M2ePro-required-when-visible">
                            <?php if ($formData['dispatch_to_value'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_UK ?>" <?php if ($formData['dispatch_to_value'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_UK) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('UK Only') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_EUROPA ?>" <?php if ($formData['dispatch_to_value'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_EUROPA) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Europe Only') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_BOTH ?>" <?php if ($formData['dispatch_to_value'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_BOTH) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('UK & Europe') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="dispatch_to_custom_attribute_tr" <?php if ($formData['dispatch_to_mode'] != Ess_M2ePro_Model_Play_Listing::DISPATCH_TO_MODE_CUSTOM_ATTRIBUTE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="dispatch_to_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Delivery Region Attribute') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="dispatch_to_custom_attribute" name="dispatch_to_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['dispatch_to_custom_attribute'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['dispatch_to_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span>
                                <?php echo Mage::helper('M2ePro')->__('Choose the attribute that contains <a href="%url%" target="_blank">identifier</a>.', $docsLinkDispatchTo); ?>
                            </span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="dispatch_from_mode"><?php echo Mage::helper('M2ePro')->__('Dispatch Country') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="dispatch_from_mode" id="dispatch_from_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_NOT_SET ?>" <?php if ($formData['dispatch_from_mode'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_DEFAULT ?>" <?php if ($formData['dispatch_from_mode'] == Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Recommended Value') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Country you will be dispatching your item from.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="dispatch_from_value_tr" <?php if ($formData['dispatch_from_mode'] != Ess_M2ePro_Model_Play_Listing::DISPATCH_FROM_MODE_DEFAULT): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="dispatch_from_value"><?php echo Mage::helper('M2ePro')->__('Dispatch Country Value') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="dispatch_from_value" id="dispatch_from_value" class="M2ePro-required-when-visible">
                            <?php if ($formData['dispatch_from_value'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <option value="UK" <?php if ($formData['dispatch_from_value'] == 'UK') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('UK') ?></option>
                            <option value="Andorra" <?php if ($formData['dispatch_from_value'] == 'Andorra') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Andorra') ?></option>
                            <option value="Austria" <?php if ($formData['dispatch_from_value'] == 'Austria') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Austria') ?></option>
                            <option value="Belgium" <?php if ($formData['dispatch_from_value'] == 'Belgium') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Belgium') ?></option>
                            <option value="Cyprus" <?php if ($formData['dispatch_from_value'] == 'Cyprus') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Cyprus') ?></option>
                            <option value="Denmark" <?php if ($formData['dispatch_from_value'] == 'Denmark') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Denmark') ?></option>
                            <option value="Finland" <?php if ($formData['dispatch_from_value'] == 'Finland') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Finland') ?></option>
                            <option value="France" <?php if ($formData['dispatch_from_value'] == 'France') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('France') ?></option>
                            <option value="Germany" <?php if ($formData['dispatch_from_value'] == 'Germany') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Germany') ?></option>
                            <option value="Gibraltar" <?php if ($formData['dispatch_from_value'] == 'Gibraltar') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Gibraltar') ?></option>
                            <option value="Greece" <?php if ($formData['dispatch_from_value'] == 'Greece') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Greece') ?></option>
                            <option value="Greenland" <?php if ($formData['dispatch_from_value'] == 'Greenland') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Greenland') ?></option>
                            <option value="Iceland" <?php if ($formData['dispatch_from_value'] == 'Iceland') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Iceland') ?></option>
                            <option value="Ireland" <?php if ($formData['dispatch_from_value'] == 'Ireland') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Ireland') ?></option>
                            <option value="Italy" <?php if ($formData['dispatch_from_value'] == 'Italy') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Italy') ?></option>
                            <option value="Liechtenstein" <?php if ($formData['dispatch_from_value'] == 'Liechtenstein') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Liechtenstein') ?></option>
                            <option value="Luxembourg" <?php if ($formData['dispatch_from_value'] == 'Luxembourg') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Luxembourg') ?></option>
                            <option value="Malta" <?php if ($formData['dispatch_from_value'] == 'Malta') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Malta') ?></option>
                            <option value="Monaco" <?php if ($formData['dispatch_from_value'] == 'Monaco') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Monaco') ?></option>
                            <option value="Netherlands" <?php if ($formData['dispatch_from_value'] == 'Netherlands') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Netherlands') ?></option>
                            <option value="Norway" <?php if ($formData['dispatch_from_value'] == 'Norway') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Norway') ?></option>
                            <option value="San Marino" <?php if ($formData['dispatch_from_value'] == 'San Marino') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('San Marino') ?></option>
                            <option value="Spain" <?php if ($formData['dispatch_from_value'] == 'Spain') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Spain') ?></option>
                            <option value="Sweden" <?php if ($formData['dispatch_from_value'] == 'Sweden') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Sweden') ?></option>
                            <option value="Switzerland" <?php if ($formData['dispatch_from_value'] == 'Switzerland') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Switzerland') ?></option>
                            <option value="Vatican" <?php if ($formData['dispatch_from_value'] == 'Vatican') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Vatican') ?></option>
                            <option value="USA" <?php if ($formData['dispatch_from_value'] == 'USA') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('USA') ?></option>
                            <option value="Canada" <?php if ($formData['dispatch_from_value'] == 'Canada') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Canada') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="shipping_price_hr" ">
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <tr id="shipping_price_gbr_mode_tr">
                    <td class="label">
                        <label for="shipping_price_gbr_mode"><?php echo Mage::helper('M2ePro')->__('Shipping Cost per Item, GBP') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="shipping_price_gbr_mode" id="shipping_price_gbr_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_NONE ?>" <?php if ($formData['shipping_price_gbr_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Free') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_CUSTOM_VALUE ?>" <?php if ($formData['shipping_price_gbr_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_CUSTOM_VALUE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['shipping_price_gbr_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_GBR_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="shipping_price_gbr_value_tr">
                    <td class="label">
                        <label for="shipping_price_gbr_value"><?php echo Mage::helper('M2ePro')->__('Cost Value, GBP') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" name="shipping_price_gbr_value" id="shipping_price_gbr_value" class="input-text M2ePro-validation-float M2ePro-validate-shipping-value-positive" value="<?php echo $formData['shipping_price_gbr_value']; ?>">
                    </td>
                </tr>

                <tr id="shipping_price_gbr_custom_attribute_tr">
                    <td class="label">
                        <label for="shipping_price_gbr_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Cost Attribute, GBP') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="shipping_price_gbr_custom_attribute" name="shipping_price_gbr_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['shipping_price_gbr_custom_attribute'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['shipping_price_gbr_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

                <tr id="shipping_price_euro_mode_tr">
                    <td class="label">
                        <label for="shipping_price_euro_mode"><?php echo Mage::helper('M2ePro')->__('Shipping Cost per Item, EUR') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="shipping_price_euro_mode" id="shipping_price_euro_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_NONE ?>" <?php if ($formData['shipping_price_euro_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Free') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_CUSTOM_VALUE ?>" <?php if ($formData['shipping_price_euro_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_CUSTOM_VALUE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['shipping_price_euro_mode'] == Ess_M2ePro_Model_Play_Listing::SHIPPING_PRICE_EURO_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="shipping_price_euro_value_tr">
                    <td class="label">
                        <label for="shipping_price_euro_value"><?php echo Mage::helper('M2ePro')->__('Cost Value, EUR') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" name="shipping_price_euro_value" id="shipping_price_euro_value" class="input-text M2ePro-validation-float M2ePro-validate-shipping-value-positive" value="<?php echo $formData['shipping_price_euro_value']; ?>">
                    </td>
                </tr>

                <tr id="shipping_price_euro_custom_attribute_tr">
                    <td class="label">
                        <label for="shipping_price_euro_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Cost Attribute, EUR') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="shipping_price_euro_custom_attribute" name="shipping_price_euro_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['shipping_price_euro_custom_attribute'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['shipping_price_euro_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_play_listing_channel_settings_condition">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Condition Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="condition_mode"><?php echo Mage::helper('M2ePro')->__('Condition') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="condition_mode" id="condition_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_NOT_SET ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_DEFAULT ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Recommended Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <?php if (!$isEdit) { ?>
                                <span><?php echo Mage::helper('M2ePro')->__('Condition of the product(s) you want to list on Play.com.'); ?></span>
                            <?php } else { ?>
                                <span><?php echo Mage::helper('M2ePro')->__('Condition of the product(s) you want to list on Play.com.<br/>
                                <b>Note:</b> Condition of Active Items cannot be changed.'); ?></span>
                            <?php } ?>
                        </p>
                    </td>
                </tr>

                <tr id="condition_value_tr" <?php if ($formData['condition_mode'] != Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_DEFAULT): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_value"><?php echo Mage::helper('M2ePro')->__('Condition Value') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="condition_value" id="condition_value" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_value'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_NEW ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('New') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_USED_LIKE_NEW ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_USED_LIKE_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Like New') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_USED_VERY_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_USED_VERY_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Very Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_USED_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_USED_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_USED_AVERAGE ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_USED_AVERAGE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Average') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_LIKE_NEW ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_LIKE_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Collectable - Like New') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_VERY_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_VERY_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Collectable - Very Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Collectable - Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_AVERAGE ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_COLLECTABLE_AVERAGE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Collectable - Average') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_REFURBISHED ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Play_Listing::CONDITION_REFURBISHED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Refurbished') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="condition_custom_attribute_tr" <?php if ($formData['condition_mode'] != Ess_M2ePro_Model_Play_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Condition Attribute') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="condition_custom_attribute" name="condition_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['condition_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span>
                            <?php echo Mage::helper('M2ePro')->__('Choose the attribute that contains Condition <a href="%url%" target="_blank">identifier</a>.', $docsLinkCondition); ?>
                            </span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_mode_tr">
                    <td class="label">
                        <label for="condition_note_mode"><?php echo Mage::helper('M2ePro')->__('Comment') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="condition_note_mode" id="condition_note_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_NOT_SET ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_NONE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short description of item(s) condition.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_value_tr" <?php if ($formData['condition_note_mode'] != Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_note_value"><?php echo Mage::helper('M2ePro')->__('Comment Text') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <textarea name="condition_note_value" id="condition_note_value" class="M2ePro-required-when-visible M2ePro-validate-condition-note-length"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['condition_note_value']) ?></textarea>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Description of the condition of the item(s).'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_custom_attribute_tr" <?php if ($formData['condition_note_mode'] != Ess_M2ePro_Model_Play_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_note_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Comment Attribute') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="condition_note_custom_attribute" id="condition_note_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_note_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['condition_note_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>
