<div id="block_notice_wizard_installation_step_synchronization" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
    <div>
        <div class="step_container_description">
            <?php echo Mage::helper('M2ePro')->__('In this Section you can set the general Synchronization Settings, which will indicate what data will be synchronized between Magento and Play.com. <br/>
             <b>Please Note:</b> you can always change these Settings in %synchronization_path%.', Mage::helper('M2ePro/View_Common')->getMenuPath('configuration/synchronization')); ?>
        </div>
        <div class="step_container_completed">
            <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
        </div>
        <div class="step_container_incomplete">
            <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Incomplete'); ?></span>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="step_container_buttons">
        <span class="step_skip" style="display:none;"><?php echo $this->getChildHtml('skip_synchronization_button'); ?></span>
        <span class="step_process" style="display:none;"><?php echo $this->getChildHtml('process_synchronization_button'); ?></span>
    </div>
</div>

<script type="text/javascript">

    WizardHandlerObj.addStep('synchronization', 'block_notice_wizard_installation_step_synchronization');

</script>