<div id="block_notice_translation_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Translation'); ?>">
    <?php echo Mage::helper('M2ePro')->__('To add translated text you have to perform the next steps:

<ul class="list">
    <li>go to the necessary Language tab;</li>
    <li>click the Add Translation on the appropreate line;</li>
    <li>in the opened text area enter the translated text;</li>
    <li>click Add.</li>
</ul>

To see other suggested translations, click on the <i>Show More Translations</i> link.
If you like one of the suggested translations you can <i>Confirm</i> it.
<br/>When translated text is confirmed 10 times by different users, it will be displayed on the interface.
<br/><br/>
<b>Note:</b> You can see different html symbols, like &lt;b&gt;, &lt;br&gt;, %ver%, %s, %d, %1$s and others. Please, keep these symbols on their places in the translated texts.
It will format texts to be displayed correctly on the interface.'); ?>
</div>