<style type="text/css">
    div.listing-view-header {
        background: none repeat scroll 0 0 #FAFAFA !important;
        border: 1px solid #D6D6D6 !important;
        margin-bottom: 15px !important;
        padding: 10px 15px !important;
    }

    div.listing-view-header ul {
        list-style: none;
    }

    div.listing-view-header ul li {
        display: inline-block;
        width: 23%;
    }

    div.listing-view-header span.label {
        font-weight: bold;
    }

    div.listing-view-header span.value {
        color: #8e9393;
    }
</style>
<div class="listing-view-header">
    <ul>
        <li>
            <label>
                <span class="label">
                    <?php echo Mage::helper('M2ePro')->escapeHtml(Mage::helper('M2ePro')->__('Listing')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->getProfileTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php echo Mage::helper('M2ePro')->escapeHtml(Mage::helper('M2ePro')->__('eBay User ID')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->getAccountTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php echo Mage::helper('M2ePro')->escapeHtml(Mage::helper('M2ePro')->__('eBay Site')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->getMarketplaceTitle()); ?>
                </span>
            </label>
        </li>
        <li style="width: 30%;">
            <label>
                <span class="label">
                    <?php echo Mage::helper('M2ePro')->escapeHtml(Mage::helper('M2ePro')->__('Magento Store View')); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->getStoreViewBreadcrumb()); ?>
                </span>
            </label>
        </li>
    </ul>
</div>