<div id="block_notice_wizard_welcome_content" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php
    echo Mage::helper('M2ePro')->__(
        'This part of extension allows quick and simple creation as well as management of product listings on eBay.
        You will significantly reduce time required for listing maintenance using it.
        <br/><br/><u>The main features are of M2E Pro eBay:</u><br/>
        <ul class="list">
        <li>automated synchronization of stock levels, pricing, and product details;</li>
        <li>import of eBay Orders;</li>
        <li>creation of Magento Orders based on imported eBay Orders;</li>
        <li>automated feedback posting for buyers</li>
        and many others.
        </ul>'
    ); ?>
</div>