<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    if (isset($formData['other_listings_move_settings'])) {
        $formData['other_listings_move_settings'] = (array)json_decode($formData['other_listings_move_settings'],true);
        if (isset($formData['other_listings_move_settings']['synch'])) {
            $formData['other_listings_move_synch'] = $formData['other_listings_move_settings']['synch'];
        }
    }

    $defaults = array(
        'related_store_id' => 0,

        'other_listings_synchronization' => Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES,
        'other_listings_mapping_mode' => Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_MODE_YES,
        'other_listings_mapping_settings' => array(),
        'other_listings_move_mode' => Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_DISABLED,
        'other_listings_move_synch' => Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_NONE
    );

    $formData = array_merge($defaults, $formData);
    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.translator.add(<?php echo json_encode(array(
        'If Yes is chosen, you must select at least one attribute for product mapping.' => Mage::helper('M2ePro')->__('If Yes is chosen, you must select at least one attribute for product mapping.')
    )); ?>);
    //-----------------------------

    Event.observe(window, 'load', function() {
        setTimeout(function() {

            $('other_listings_synchronization')
                .observe('change', AmazonAccountHandlerObj.other_listings_synchronization_change)
                .simulate('change');
            $('other_listings_mapping_mode')
                .observe('change', AmazonAccountHandlerObj.other_listings_mapping_mode_change)
                .simulate('change');

            $('mapping_general_id_mode')
                .observe('change', AmazonAccountHandlerObj.mapping_general_id_mode_change)
                .simulate('change');
            $('mapping_sku_mode')
                .observe('change', AmazonAccountHandlerObj.mapping_sku_mode_change)
                .simulate('change');
            $('mapping_title_mode')
                .observe('change', AmazonAccountHandlerObj.mapping_title_mode_change)
                .simulate('change');
            $('other_listings_move_mode')
                .observe('change', AmazonAccountHandlerObj.move_mode_change)
                .simulate('change');

            $('amazonAccountEditTabs_listingOther').removeClassName('changed');
        }, 350);
    });

</script>

<div id="block_notice_amazon_accounts_other_listings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php
        $menuLabel = Mage::helper('M2ePro/View_Common')->getMenuRootNodeLabel();
        echo Mage::helper('M2ePro')->__('
The 3rd Party Listings are the items, which were listed on Amazon without using M2E Pro extension. <br/><br/>
To allow importing of these listings for the current Amazon Account, set Import 3rd Party Listings to <i>Yes</i>.<br/>
Imported Listings can be found in %menu_label% > Manage Listings > 3rd Party Listings.<br/><br/>
<b>Note:</b> The 3rd Party Listings Synchronization must be enabled in %menu_label% > Configuration > Synchronization.<br/><br/>
To map the products of the 3rd Party Listings with existing products in Magento by ASIN, ISBN, SKU or Title, set Product Mapping to <i>Yes</i> and choose appropriate attribute(s).
A Magento product will be mapped if at least one of the chosen attributes meets the same value in Amazon Listing as it has in Magento.
<br/><br/>
After mapping the Amazon Listing can be automatically moved from the 3rd Party Listings to M2E Pro Listings for further management.<br/><br/>

<b>Note:</b> Auto mapping and moving actions are performed only once during the first 3rd Party Listings Synchronization.
Afterwards, it can be performed manually on the 3rd Party Listings page (%menu_label% > Manage Listings > 3rd Party Listings).
', $menuLabel);
    ?>
</div>

<div class="entry-edit" id="magento_block_amazon_accounts_other_listings_synchronization">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="other_listings_synchronization"><?php echo Mage::helper('M2ePro')->__('Import 3rd Party Listings'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_synchronization" name="other_listings_synchronization">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Allows importing 3rd Party Listings.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tbody id="other_listings_store_view_tr">
                    <tr id="marketplaces_related_store_id_container" <?php if (!$isEdit) echo ' style="display:none;"'; ?>>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Related Store View'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <?php
                            $tempStoreBlock = $this->getLayout()->createBlock(
                                'M2ePro/adminhtml_storeSwitcher',
                                '',
                                array(
                                    'id'=>'related_store_id',
                                    'name' => 'related_store_id',
                                    'selected' => $formData['related_store_id']
                                )
                            );
                            echo $tempStoreBlock->toHtml();

                            ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Store View, which will be associated with chosen<br/>Marketplace of the current account.'); ?></span>
                            </p>
                        </td>
                    </tr>
                </tbody>

                <tr id="other_listings_mapping_mode_tr">
                    <td class="label">
                        <label for="other_listings_mapping_mode"><?php echo Mage::helper('M2ePro')->__('Product Mapping'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_mapping_mode" name="other_listings_mapping_mode" class="M2ePro-require-select-attribute">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_MODE_YES ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_MODE_NO ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Maps Amazon product with Magento product.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_other_listings_product_mapping" <?php if ($formData['other_listings_mapping_mode'] == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Attributes Of Mapping Amazon Items To Magento Products'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php $mappingSettings = $formData['other_listings_mapping_settings']; ?>

                <tr class="amazon-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_sku_mode"><?php echo Mage::helper('M2ePro')->__('SKU') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="mapping_sku_mode" name="mapping_sku_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                    <td id="mapping_sku_priority_td" class="value" <?php if (!isset($mappingSettings['sku']['mode']) || $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_sku_priority" type="text" value="<?php echo isset($mappingSettings['sku']['priority']) ? (int)$mappingSettings['sku']['priority'] : Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_SKU_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr id="mapping_sku_attribute_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">
                        <?php $tempAttributeValue = isset($mappingSettings['sku']['attribute']) ? $mappingSettings['sku']['attribute'] : ''; ?>
                        <select name="mapping_sku_attribute">
                            <?php foreach ($this->attributes as $attribute) { ?>
                                <option value="<?php echo $attribute['code'] ?>" <?php if ($tempAttributeValue == $attribute['code']) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>

                <tr class="amazon-listings-mapping-settings">
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <tr class="amazon-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_title_mode"><?php echo Mage::helper('M2ePro')->__('Listing Title') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="mapping_title_mode" name="mapping_title_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product Name') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                    <td id="mapping_title_priority_td" class="value" <?php if (!isset($mappingSettings['title']['mode']) || $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_title_priority" type="text" value="<?php echo isset($mappingSettings['title']['priority']) ? (int)$mappingSettings['title']['priority'] : Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_TITLE_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr id="mapping_title_attribute_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">
                        <?php $tempAttributeValue = isset($mappingSettings['title']['attribute']) ? $mappingSettings['title']['attribute'] : ''; ?>
                        <select name="mapping_title_attribute">
                            <?php foreach ($this->attributes as $attribute) { ?>
                                <option value="<?php echo $attribute['code'] ?>" <?php if ($tempAttributeValue == $attribute['code']) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>

                <tr class="amazon-listings-mapping-settings">
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <tr class="amazon-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_general_id_mode"><?php echo Mage::helper('M2ePro')->__('ASIN / ISBN') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="mapping_general_id_mode" name="mapping_general_id_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_MODE_NONE ?>" <?php if (isset($mappingSettings['general_id']['mode']) && $mappingSettings['general_id']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_MODE_CUSTOM_ATTRIBUTE ?>" <?php if (isset($mappingSettings['general_id']['mode']) && $mappingSettings['general_id']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                    <td id="mapping_general_id_priority_td" class="value" <?php if (!isset($mappingSettings['general_id']['mode']) || $mappingSettings['general_id']['mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_general_id_priority" type="text" value="<?php echo isset($mappingSettings['general_id']['priority']) ? (int)$mappingSettings['general_id']['priority'] : Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MAPPING_GENERAL_ID_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr id="mapping_general_id_attribute_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">
                        <?php $tempAttributeValue = isset($mappingSettings['general_id']['attribute']) ? $mappingSettings['general_id']['attribute'] : ''; ?>
                        <select name="mapping_general_id_attribute">
                            <?php foreach ($this->attributes as $attribute) { ?>
                                <option value="<?php echo $attribute['code'] ?>" <?php if ($tempAttributeValue == $attribute['code']) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_accounts_other_listings_move_mode" <?php if ($formData['other_listings_move_mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_DISABLED) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Auto Moving Mapped Amazon Items To M2E Listings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_amazon_accounts_other_listings_move_synch" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Moving 3rd Party Listings'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This section allows you automatically move mapped Amazon Items in default created M2E Listing and synchronize their Prices and Quantities with Magento values at once they have been moved.'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="other_listings_move_mode"><?php echo Mage::helper('M2ePro')->__('Move Mapped Amazon Items') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="other_listings_move_mode" name="other_listings_move_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_ENABLED ?>" <?php if ($formData['other_listings_move_mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_ENABLED) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_DISABLED ?>" <?php if ($formData['other_listings_move_mode'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_DISABLED) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Automatically moves Amazon Listings from 3rd Party Listings to default created M2E Listing.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="other_listings_move_synch_tr" style="display: none;">
                    <td class="label">
                        <label for="other_listings_move_synch"><?php echo Mage::helper('M2ePro')->__('Immediate Synchronization') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="other_listings_move_synch" name="other_listings_move_synch">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_NONE ?>" <?php if ($formData['other_listings_move_synch'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_ALL ?>" <?php if ($formData['other_listings_move_synch'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_ALL) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Price and QTY') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_PRICE ?>" <?php if ($formData['other_listings_move_synch'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_PRICE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Price Only') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_QTY ?>" <?php if ($formData['other_listings_move_synch'] == Ess_M2ePro_Model_Amazon_Account::OTHER_LISTINGS_MOVE_TO_LISTINGS_SYNCH_MODE_QTY) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('QTY Only') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Updates Price and / or Quantity of Amazon Listing with Magento values.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>