<div id="ebay_template_edit_general_help" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Payment and Shipping Settings'); ?>">
    <p><?php echo Mage::helper('M2ePro')->__('Select the payment, shipping and cross border options you would like eBay to use.'); ?></p>
    <p><?php echo Mage::helper('M2ePro')->__('Remember, you can amend Payment and Shipping Settings at any time.'); ?></p>
</div>