<div id="block_notice_ebay_listings_categories_tree" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Product Selection'); ?>">
    <?php echo Mage::helper('M2ePro')->__('The number shown next to each category is the quantity of products filtered by
    Attribute Set and Products Filter settings of the Listing.<br/><br/>
    There are two modes of products addition:
    <ul class="list">
        <li><b>All Products</b> - all products, which are included in selected categories, will be added to the Listing.</li>
        <li><b>Select Manually</b> - the list of products of chosen categories will be shown on the next page after the Next button is pressed at the top right corner.</li>
    </ul>
    <b>Note:</b> If a product belongs to different categories, it will be added to the Listing or shown for manual selection only once.'); ?>
</div>