<div id="block_notice_ebay_configuration_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Categories In Use'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
    Be careful when you edit categories data, as all changes you have made will be automatically applied to all M2E listings where these categories are used.
    <br>
    <br>
    <b>Note:</b> If M2E has defined, that a category was removed from eBay, it highlights it.
    '); ?>
</div>