<div id="block_notice_ebay_configuration_category" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Categories In Use'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows the eBay categories you\'re currently using in your M2E Pro listings.
        Categories are highlighted if the eBay category no longer exists due to category changes made by eBay.<br/><br/>
        Click the line with the order in the table below to <b>Edit</b> the eBay category and Item Specifics for that category.<br/><br/> Any changes you make will affect all M2E Pro listings that use that category.'
    ); ?>
</div>