<style type="text/css">

    /* Header Styles */
    /* ================================================ */

    .header {
        font: 11px Arial,Helvetica,sans-serif;
        background-color: #586A88;
        padding: 10px 10px 10px 20px;
        border:  1px solid #273B60;
    }

    .header a {
        color: white;
    }

    .header .title {
        float: left;
        font-size: 20px;
        color: white;
    }

    .header .links {
        float: left;
        font-size: 11px;
        color: white;
        margin-left: 140px;
        margin-top: 4px;
    }

    .header .links a {
        color: silver;
    }

    .header .datetime {
        float: right;
        font-size: 13px;
        color: white;
        padding-top: 4px;
        padding-right: 15px;
    }

    /* ================================================ */

</style>

<div class="header">
    <div class="title">
        &larr; <a href="<?php echo $this->backUrl;?>">Back To Control Panel</a>
    </div>
    <div class="links">
        <a href="<?php echo $this->aboutPageUrl; ?>">About Page</a>
    </div>
    <div class="links">
        <a href="http://m2epro.com/" target="_blank">m2epro.com</a>
        &nbsp;|&nbsp;
        <a href="http://support.m2epro.com/" target="_blank">Support</a>
        &nbsp;|&nbsp;
        <a href="http://www.magentocommerce.com/magento-connect/customer-experience/alternative-sales-models/ebay-magento-integration-order-importing-and-stock-level-synchronization-9193.html" target="_blank">Magento Connect</a>
    </div>
    <div class="datetime">
        <?php echo date('Y-m-d H:i:s',(int)gmdate('U')); ?>
    </div>
    <div style="clear:both;"></div>
</div>

<div style="clear:both;">&nbsp;</div>