<html>
    <head>

        <title>M2ePro Extension Control Panel</title>

        <style type="text/css">

            /* General Styles */
            /* ================================================ */

            body {
                text-align: center;
                background-color: white;
                font: 11px Arial,Helvetica,sans-serif;
            }

            a {
                color: brown;
            }

            /* ================================================ */

            /* Header Styles */
            /* ================================================ */

            .header {
                background-color: #586A88;
                padding: 10px 10px 10px 20px;
                border:  1px solid #273B60;
                margin-bottom: 15px;
            }

            .header .title {
                float: left;
                font-size: 20px;
                color: white;
            }

            .header .links {
                float: left;
                font-size: 11px;
                color: white;
                margin-left: 140px;
                margin-top: 4px;
            }

            .header .links a {
                color: silver;
            }

            .header .datetime {
                float: right;
                font-size: 13px;
                color: white;
                padding-top: 4px;
                padding-right: 15px;
            }

            /* ================================================ */

            /* Widgets Messages Styles */
            /* ================================================ */

            .messages {

            }

            .messages .container {
                margin-bottom: 15px;
                padding: 10px 15px;
                font-size: 14px;
                text-align: left;
            }

            .messages .success {
                background-color: #ebfcdd;
                border: 1px solid #5aed16;
            }

            .messages .warning {
                background-color: #FCFCCF;
                border: 1px solid #EDC149;
            }

            .messages .error {
                background-color: #FAEBE7;
                border: 1px solid #F16048;
            }

            /* ================================================ */

            /* Groups Styles */
            /* ================================================ */

            .group {
                float: left;
                min-width: 250px;
                height: 450px;
                padding: 0;
                margin-right: 15px;
                background-color: #F8F8F8;
                border: 2px solid #586A88;
            }

            .group_title {
                padding: 5px 0;
                background-color: #586A88;
                border-bottom: 1px solid gray;
                color: white;
                font-size: 13px;
                font-weight: bold;
                text-align: center;
            }

            .group table {
                min-width: 220px;
                margin: 10px 15px;
                font-size: 14px;
                line-height: 20px;
            }

            /* ================================================ */

        </style>

    </head>
    <body>

        <div class="header">
            <div class="title">
                M2ePro Extension Control Panel
            </div>
            <div class="links">
                <a href="<?php echo $this->aboutPageUrl; ?>">About Page</a>
            </div>
            <div class="links">
                <a href="http://m2epro.com/" target="_blank">m2epro.com</a>
                &nbsp;|&nbsp;
                <a href="http://support.m2epro.com/" target="_blank">Support</a>
                &nbsp;|&nbsp;
                <a href="http://www.magentocommerce.com/magento-connect/customer-experience/alternative-sales-models/ebay-magento-integration-order-importing-and-stock-level-synchronization-9193.html" target="_blank">Magento Connect</a>
            </div>
            <div class="datetime">
                <?php echo date('Y-m-d H:i:s',(int)gmdate('U')); ?>
            </div>
            <div style="clear:both;"></div>
        </div>

        <div class="messages">

            <?php if ($this->success_message != '') { ?>
                <div class="container success">
                    <?php echo $this->success_message; ?>
                </div>
            <?php } ?>

            <?php if ($this->error_message != '') { ?>
                <div class="container error">
                    <?php echo $this->error_message; ?>
                </div>
            <?php } ?>

            <?php if ($this->warning_message != '') { ?>
                <div class="container warning">
                    <?php echo $this->warning_message; ?>
                </div>
            <?php } ?>

        </div>

        <?php foreach($this->groups as $groupName => $groupData) { ?>

            <?php
                $number = 0;
            ?>

            <div class="group">

                <div class="group_title">
                    <?php echo ucfirst($groupName); ?>
                </div>

                <table>

                    <?php foreach($groupData as $command) { ?>

                        <?php
                            $number++;
                        ?>

                        <tr>
                            <td style="width: 10px;">
                                <b><?php echo $number; ?>.</b>
                            </td>
                            <td style="width: 10px;">
                                &nbsp;&nbsp;|&nbsp;&nbsp;
                            </td>
                            <td>
                                <a href="<?php echo $command['url']; ?>" <?php if ($command['confirm'] != ''): ?>onclick="return confirm('<?php echo $command['confirm']; ?>');"<?php endif; ?> title="<?php echo $command['description']; ?>" alt="<?php echo $command['description']; ?>"><?php echo $command['title']; ?></a>

                                <?php
                                    $components = array();
                                    if ($command['components']) {
                                        $components = $command['components'] === true ? $this->enabledComponents : $command['components'];
                                    }
                                ?>

                                <?php if (count($components) > 1): ?>
                                    <?php foreach ($this->enabledComponents as $key => $component): ?>
                                        <?php echo $key == 0 ? '(' : ''; ?><a href="<?php echo rtrim($command['url'], '/') . '/component/' . $component . '/'; ?>" <?php if ($command['confirm'] != ''): ?>onclick="return confirm('<?php echo $command['confirm']; ?>');"<?php endif; ?>><?php echo $component; ?></a><?php echo isset($this->enabledComponents[$key + 1]) ? ', ' : ')'; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </td>
                        </tr>

                        <?php if ($command['new_line']): ?>
                            <tr>
                                <td colspan="3">
                                    <hr />
                                </td>
                            </tr>
                        <?php endif; ?>

                    <?php } ?>

                 </table>
            </div>

        <?php } ?>

    </body>
</html>