<style type="text/css">

    /* Footer Styles */
    /* ================================================ */

    .footer {
        height: 15px;
        padding: 10px 20px;
        margin-top: 15px;
        border-top:  3px solid gray;
        text-align: center;
        background-color: white;
        font: 11px Arial,Helvetica,sans-serif;
    }

    /* ================================================ */

</style>

<div style="clear:both;"></div>
<div class="footer">
    &nbsp;&copy; 2007 - <?php echo date('Y',(int)gmdate('U')); ?> ESS-UA company. All Rights Reserved.
    <div style="clear:both;"></div>
</div>