<style type="text/css">
        /* Blocks */
    .step_container_description {
        float: left;
    }
    .step_container_completed {
        float: right;
    }
    .step_container_incomplete {
        float: right;
    }
    .step_container_buttons {
        clear:both;
        padding-top: 10px;
    }
        /* Text */
    .step_completed {
        font-size: 14px;
        font-weight: bold;
        color: green;
    }
    .step_incomplete {
        font-size: 14px;
        font-weight: bold;
        color: red;
    }
    .step_skip {}
    .step_process {}
</style>

<script type="text/javascript">
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.setStep = '<?php echo $this->getUrl(
        '*/adminhtml_'.$this->getEdition().'_'.$this->getNick().'/setStep'
    ); ?>';
    M2ePro.url.setStatus = '<?php echo $this->getUrl(
        '*/adminhtml_'.$this->getEdition().'_'.$this->getNick().'/setStatus'
    ); ?>';

    M2ePro.text.step_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Step')); ?>';
    M2ePro.text.skip_confirm = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Note: If you close the wizard, it never starts again. You will be required to set all settings manually. Press Cancel to continue working with wizard.')); ?>';

    WizardHandlerObj = new WizardHandler('<?php echo $this->getStatus(); ?>','<?php echo $this->getStep(); ?>');
    WizardHandlerObj.steps.all = <?php echo $this->getSteps(); ?>;
    WizardHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Helper_Wizard'); ?>');
</script>