<?php
$selectedCategoriesProductsFrom = '';
if (count(Mage::helper('M2ePro/Data_Global')->getValue('temp_listing_categories')) == 0) {
    $selectedCategoriesProductsFrom = 'all';
} else {
    $selectedCategoriesProductsFrom = 'manual';
}

$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();
$default = array(
    'save_categories' => 1
);
$formData = array_merge($default, $formData);

$createListingUrl = $this->getUrl(
    '*/adminhtml_common_play_listing/createListing'
);
$getProductsUrl = $this->getUrl(
    '*/adminhtml_common_play_listing/getProductsFromCategories'
);
$addProductsUrl = $this->getUrl(
    '*/adminhtml_common_play_listing/addProducts'
);
?>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.create_listing = '<?php echo $createListingUrl ?>';
    M2ePro.url.get_products_from_categories = '<?php echo $getProductsUrl ?>';
    M2ePro.url.add_products = '<?php echo $addProductsUrl ?>';

    WrapperObj = new AreaWrapper('add_products_container');
    ProgressBarObj = new ProgressBar('add_products_progress_bar');
    PlayAddListingHandlerObj = new AddListingHandler(M2ePro, ProgressBarObj, WrapperObj);
    PlayListingCategoryHandlerObj = new ListingCategoryHandler(PlayAddListingHandlerObj);

    Event.observe(window, 'load', function() {
        $('categories_products_from')
            .observe('change', PlayListingCategoryHandlerObj.categories_products_from_change)
            .simulate('change');
    });

</script>

<div <?php if (!$formData['is_source_categories']) { ?>style="display:none;"<?php } ?>>
<br>
<div>
    <input id="save_categories" name="save_categories" type="checkbox"<?php if ($formData['save_categories']) echo 'checked="checked"'; ?>>
    <?php echo Mage::helper('M2ePro')->__('Apply Actions On Categories Products to the selected categories.'); ?>
</div>
<br>
</div>

<div class="entry-edit" id="magento_block_play_listings_categories_tree_next_step">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Products Addition'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                <tr>
                    <td class="label">
                        <label for="categories_products_from"><?php echo Mage::helper('M2ePro')->__('Add Products'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="categories_products_from" name="categories_products_from">
                            <option value="all"<?php if ($selectedCategoriesProductsFrom == 'all') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Products'); ?></option>
                            <option value="manual"<?php if ($selectedCategoriesProductsFrom == 'manual') echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Select Manually'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Mode of products addition from selected categories.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr style="display: none">
                    <td class="label">
                        <label for="hide_products_others_listings"><?php echo Mage::helper('M2ePro')->__('Add Products Presented in Other Listings'); ?>: </label>
                    </td>
                    <td class="value">
                        <select id="hide_products_others_listings" name="hide_products_others_listings">
                            <option value="0"><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="1"><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                    </td>
                </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>