<script type="text/javascript">
    function viewModeChange()
    {
        if (this.value == '<?php echo Ess_M2ePro_Helper_View_Ebay::MODE_SIMPLE; ?>') {
            $('magento_block_ebay_configuration_general_notification').hide();
        } else {
            $('magento_block_ebay_configuration_general_notification').show();
        }
    }

    Event.observe(window, 'load', function() {
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

        $('view_ebay_mode')
            .observe('change', viewModeChange)
            .simulate('change');
    });
</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_ebay_configuration_general_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                        <tr id="view_ebay_mode_tr">
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Mode'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="view_ebay_mode" name="view_ebay_mode">
                                    <option value="<?php echo Ess_M2ePro_Helper_View_Ebay::MODE_SIMPLE; ?>" <?php if ($this->view_ebay_mode == Ess_M2ePro_Helper_View_Ebay::MODE_SIMPLE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Simple'); ?></option>
                                    <option value="<?php echo Ess_M2ePro_Helper_View_Ebay::MODE_ADVANCED; ?>" <?php if ($this->view_ebay_mode == Ess_M2ePro_Helper_View_Ebay::MODE_ADVANCED): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Advanced'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('There are two modes. Simple is suitable for new users and for those with a limited inventory. Advanced is suitable for the more experienced user.'); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_configuration_general_notification">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Notifications'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                    <tr id="negative_feedbacks_row">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Negative Feedback'); ?>: </label>
                        </td>
                        <td class="value">
                            <select name="view_ebay_feedbacks_notification_mode">
                                <option value="0" <?php if (!$this->view_ebay_feedbacks_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1" <?php if ($this->view_ebay_feedbacks_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Notifies when a new negative feedback was received.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Cron'); ?>: </label>
                        </td>
                        <td class="value">
                            <select name="cron_notification_mode">
                                <option value="0" <?php if (!$this->cron_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1" <?php if ($this->cron_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Notifies if cron is not run more than 12 hours.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

</form>