<script type="text/javascript" src="<?php echo $this->getJsUrl('M2ePro/VideoTutorialHandler.js'); ?>"></script>

<script type="text/javascript">

    VideoTutorialHandlerListingObj = new VideoTutorialHandler(
        'video_tutorial_pop_up_listing',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('eBay/Magento Integration: Listing')); ?>',
        function() {}
    );

    VideoTutorialHandlerProductsObj = new VideoTutorialHandler(
        'video_tutorial_pop_up_products',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('eBay/Magento Integration: Products Management')); ?>',
        function() {}
    );

</script>

<style type="text/css">

    .migration_installation_intro_block {
        margin-top: 30px;
    }

    .migration_installation_note {
        color: #808080;
        padding-left: 10px;
    }

    .migration_installation_intro_block ul li {
        margin-bottom: 8px;
    }

</style>

<div id="block_notice_wizard_migration_v6_intro" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <table>

        <tr>

            <td>
                <p><?php echo Mage::helper('M2ePro')->__('<b>Congratulations!</b><br>
                You have successfully installed a totally new M2E Pro version.<br>
                In this version the \'Sell on eBay\' part was completely updated and separated from the other channels.
                The main changes you can see below.<br>
                All data was successfully migrated but some of the settings need to be checked. They are shown on the next steps.
                '); ?></p>
            </td>

        </tr>

    </table>
</div>

<div id = "block_wizard_migration_v6_intro_content" style="padding-left: 20px">

    <div class="migration_installation_intro_block">

        <h2>
            <?php echo Mage::helper('M2ePro')->__('1) Templates &rarr; Policies'); ?>
        </h2>

        <div style="color: #808080; padding-left: 40px;">

            <p><?php echo Mage::helper('M2ePro')->__(
                'All types of templates were replaced to Policies. And now they are used to set up all necessary settings for listing Magento products on eBay.
                <br/><br/>
                There are 6 types of policies:
                <br/><br/>
            <ul style="list-style: decimal; padding-left: 35px;">

                <li><b>Payment</b> - includes information about how you wish your buyers pay.</li>
                <li><b>Shipping</b> - includes information about shipping charges.</li>
                <li><b>Return</b> - includes information about return policy.</li>
                <li><b>Price, Quantity and Format</b> - includes detailed information about eBay items and how long they will be on sale.</li>
                <li><b>Description</b> – includes settings of how to design items on eBay.</li>
                <li><b>Synchronization</b> – includes settings for autosynchronization data between Magento and eBay.</li>
            </ul>
                <br/>
                Where can I find my settings?
                <br/><br/>
                <ul style="list-style: disc; padding-left: 25px;">
                <li>settings of the <b><i>Selling Format</i></b> template migrated in <b><i>Price, Quantity and Format</i></b> policy;</li>
                <li>settings of the <b><i>Description</i></b> template migrated in <b><i>Description</i></b> policy;</li>
                <li>the <b><i>General</i></b> template was replaced to three <b><i>Payment</i></b>, <b><i>Shipping</i></b> and <b><i>Return</i></b> policies;</li>
                <li>settings of the <b><i>Synchronization</i></b> template migrate in <b><i>Synchronization</i></b> policy;</li>
                <li>Listing Upgrades, Product Details and Condition settings were moved from <b><i>General</i></b> templates to <b><i>Description</i></b> policies;</li>
                </ul>
                '); ?></p>

        </div>

    </div>

    <div class="migration_installation_intro_block" style="padding-left: 20px">

        <h2>
            <?php echo Mage::helper('M2ePro')->__('2) New Listings Conception'); ?>
        </h2>

        <div>
        <span class="migration_installation_note" style="padding-left: 40px;">
            <p><?php echo Mage::helper('M2ePro')->__('M2E Listing creation became more easy and simple.
        <br/><br/>
        There are only several steps you should perform to create a listing. Settings for M2E listing can be set up individually (using Custom settings mode)
        or from previously saved policies.
        <br/>
        Also they <b>can be customized for each product individually</b>, or for a bulk of products and taken from:
        <br/>
            <ul style="list-style: disc; padding-left: 35px;">
                <li><b>Listing settings;</b></li>
                <li><b>Policies;</b></li>
                <li><b>Custom Settings mode (individually set).</b></li>
            </ul>
        <br/>
        After listing is created, you can view its items in three different modes:
        <br/><br/>
        <ul style="list-style: disc; padding-left: 35px;">
            <li><b>eBay</b> – displays product information related to eBay. In this mode, you can easily find products by eBay information, perform actions in bulk (i.e. List, Revise, Relist, Stop, etc);</li>
            <li><b>Magento</b> - displays products information related to Magento Catalog. In this mode, you can easily find products using magento products information (i.e. Magento QTY, Stock Status, etc);</li>
            <li><b>Settings</b> – displays information about settings set for products (i.e. Selling settings, eBay categories, etc). In this mode, you can easily find products by settings they use, change the settings in bulk.</li>
        </ul>
        <br/>
        <b>Note:</b> Attributes Sets were removed from the Listings Settings.
        '); ?>
        </div>

        <h2 style="margin-top: 25px;">Please check video tutorials to have quick overview of new UI.</h2>

        <div style="float: left; width: 450px;">
            <div>
                <a href="javascript:" onclick="VideoTutorialHandlerListingObj.openPopUp()">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/ebay-video-thumbnail.png'); ?>" alt="">
                </a>
            </div>
            <div style="float:left; width: 400px;">
                <h4 style="text-align: center">eBay/Magento Integration: Listing</h4>
            </div>
        </div>

        <div id="video_tutorial_pop_up_listing" style="display: none;">
            <div class="player_container" style="margin: 20px 5px; ">
                <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/IvXP-tA64KE?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/IvXP-tA64KE?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
            </div>
        </div>

        <div style="float: left; width: 450px;">
            <div>
                <a href="javascript:" onclick="VideoTutorialHandlerProductsObj.openPopUp()">
                    <img src="<?php echo $this->getSkinUrl('M2ePro/images/ebay-video-thumbnail.png'); ?>" alt="">
                </a>
            </div>
            <div style="float:left; width: 400px;">
                <h4 style="text-align: center">eBay/Magento Integration: Products Management</h4>
            </div>
        </div>

        <div id="video_tutorial_pop_up_products" style="display: none;">
            <div class="player_container" style="margin: 20px 5px; ">
                <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/iBEiQ8Ilya8?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/iBEiQ8Ilya8?version=3&amp;hl=ru_RU&amp;rel=0&amp;vq=hd720" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
            </div>
        </div>

        <div style="clear: both;"></div>

    </div>

    <div class="migration_installation_intro_block">

        <h2>
            <?php echo Mage::helper('M2ePro')->__('3) Major Changes and Improvements of M2E v.6.x.x'); ?>
        </h2>
        <div>
            <span class="migration_installation_note">
                        <?php echo Mage::helper('M2ePro')->__('
                        <ul style="list-style: decimal; padding-left: 35px;">
                            <li>
                                <b>eBay Fee estimation was added on the listing view</b>
                                <br/>It allows you to see the fee, that will be charged after item is listed on eBay.
                            </li>
                            <li>
                                <b>Actions On Categories\' Products were renamed to Automatic Actions and moved from the listing settings to the Add Products page.</b>
                                <br/>Automatic Actions determines rules by which products will be automatically added or deleted from the M2E listing.
                            </li>
                            <li>
                                <b>Automatic Currency Rate Conversion was added</b>
                                <br/>If Magento has currency conversion rate it will be performed automatically to all your prices depending on eBay / Amazon / Rakuten.com / Play.com Marketplace you chose in M2E listing settings.
                            </li>
                            <li>
                                <b>List / Relist Schedule</b>
                                <br/>Schedule was removed from Amazon, Rakuten.com and Play.com Synchronization templates and updated for eBay Synchronization template (policy). Now it also covers the List rules, not only Relist.
                            </li>
                            <li>
                                <b>Renames (rephrasing)</b>
                                <br/>Some concepts were renamed (only for eBay part):
                                <br/>
                                <ul style="list-style: disc; padding-left: 35px;">
                                    <li>Account Title -> eBay User ID</li>
                                    <li>Marketplace -> eBay Site</li>
                                    <li>Template -> Policy</li>
                                    <li>Actions On Categories\' Products -> Automatic Actions</li>
                                </ul>
                            </li>
                            <li>
                                <b>Simple / Advanced Mode for eBay</b>
                                <br/>Now two modes are available:
                                <ul style="list-style: disc; padding-left: 35px;">
                                    <li><b>Simple</b> - suitable for new users and for those with a limited inventory;</li>
                                    <li><b>Advanced</b> - suitable for the more experienced user.</li>
                                </ul>
                                You can change the mode any time you want in Sell on eBay > Configuration > General tab.
                            </li>
                            <li>
                                <b>The Global settings for M2E were moved and divided into 2 parts: common (for all channels) and eBay settings</b>
                                <br/>The common settings you can find in Magento -> System -> Configuration, in the Configuration panel on the left, select M2E Pro.
                                <br/>eBay settings are in Sell On eBay -> Configuration -> General tab.
                            </li>
                        </ul>
                        '); ?>
                    </span>
                </div>

    </div>

</div>

<div id="video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
        <object width="853" height="480">
            <param id="video_tutorial_pop_up_param" name="movie" value="" />
            <param name="allowFullScreen" value="true" />
            <param name="allowscriptaccess" value="always" />
            <embed id="video_tutorial_pop_up_embed" src="" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed>
        </object>
    </div>
</div>