<?php if (!$this->getRequest()->getParam('id')) { ?>

    <div id="block_notice_ebay_listing_add" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Listing'); ?>">
        <?php echo Mage::helper('M2ePro')->__('This section allows you to create a Listing. Listing is a group of items, which have the same
        Attribute Set and were combined to be listed on eBay.<br/><br/>
        Creating a Listing requires four types of templates (Selling Format, General, Description, Synchronization) to be created in advance,
        that allows reaching a high level of flexibility in listing and synchronization processes. <br/>
            It is also possible to create templates by clicking the <span style="text-decoration: underline;">Add New</span> button next to the appropriate template option. Do not forget to press
            the <span style="text-decoration: underline;">Refresh</span> button after the new template creation in order to see the newly added template in the dropdown list.<br/>
        <br/>In the Listing Configuration block you are required to choose appropriate Selling Format, General and Description Templates,
        which determine how the items of this Listing will be presented on eBay.<br/>
        <br/>In the Synchronization Settings block you are required to choose a Synchronization Template and its settings.
        This determines the actions, which have to be done on the eBay Listings depending on any changes of their products happened in Magento,
        and of their templates that are used in the Listing Configuration settings.<br/>
        <br/>The Products Filter block allows you to filter the products, which you would like to add to the Listing.
        The filtered products will be shown on the next page after the <span style="text-decoration: underline;">Next</span> button is pressed at the top right corner.'); ?>
    </div>

<?php } ?>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data') : array();
    $default = array(
        'title' => '',
        'store_id' => 0,
        'attribute_sets' => -1,

        'template_selling_format_id'    => 0,
        'template_selling_format_title' => '',

        'template_general_id'    => 0,
        'template_general_title' => '',

        'template_description_id'    => 0,
        'template_description_title' => '',

        'template_synchronization_id'    => -1,
        'template_synchronization_title' => '',

        'synchronization_start_type' => Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_IMMEDIATELY,
        'synchronization_start_through_metric' => Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS,
        'synchronization_start_through_value' => 1,
        'synchronization_start_date' => Mage::helper('M2ePro')->getCurrentGmtDate(),

        'synchronization_stop_type' => Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_NEVER,
        'synchronization_stop_through_metric' => Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS,
        'synchronization_stop_through_value' => 1,
        'synchronization_stop_date' => Mage::helper('M2ePro')->getCurrentGmtDate(),

        'source_products' => Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CUSTOM,
        'categories_add_action' => Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE,
        'categories_delete_action' => Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE,
        'hide_products_others_listings' => Ess_M2ePro_Model_Listing::HIDE_PRODUCTS_OTHERS_LISTINGS_NO
    );
    $formData = array_merge($default, $formData);

    if (!isset($formData['id'])) {
        $blockStoreSwitcher = $this->getLayout()->createBlock('M2ePro/adminhtml_storeSwitcher', '', array('id'=>'store_id','selected' => $formData['store_id']));
        $this->setChild('store_id', $blockStoreSwitcher);
    } else {
        $storeModel = Mage::getModel('core/store')->load($formData['store_id']);
        $formData['store_name'] = $storeModel->getWebsite()->getName();
        if (strtolower($formData['store_name']) != 'admin') {
            $formData['store_name'] .= ' -> '.$storeModel->getGroup()->getName();
            $formData['store_name'] .= ' -> '.$storeModel->getName();
        } else {
            $formData['store_name'] = Mage::helper('M2ePro')->__('Admin (Default Values)');
        }
    }

    $formData['synchronization_start_date'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['synchronization_start_date']);
    $formData['synchronization_stop_date'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['synchronization_stop_date']);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.autoCompleteData = {
        url : {}
    };

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.getSellingFormatTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'Template_SellingFormat','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.url.getGeneralTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'Template_General','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.url.getDescriptionTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'Template_Description','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC','component_mode'=>Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.url.getSynchronizationTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'Template_Synchronization','id_field'=>'id','data_field'=>'title','component_mode'=>Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    M2ePro.formData.store_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_id']); ?>';

    M2ePro.formData.template_selling_format_id    = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_selling_format_id']); ?>';
    M2ePro.formData.template_selling_format_title = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_selling_format_title']); ?>';

    M2ePro.formData.template_general_id    = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_general_id']); ?>';
    M2ePro.formData.template_general_title = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_general_title']); ?>';

    M2ePro.formData.template_description_id    = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_description_id']); ?>';
    M2ePro.formData.template_description_title = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_description_title']); ?>';

    M2ePro.formData.template_synchronization_id    = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_synchronization_id']); ?>';
    M2ePro.formData.template_synchronization_title = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['template_synchronization_title']); ?>';

    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other listing. Listing title must be unique.')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Set first')); ?>';
    M2ePro.text.wrong_date_time_format_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Invalid date time format string.')); ?>';

    M2ePro.text.typeTemplateNameHere = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Template Name Here...')); ?>';

    M2ePro.autoCompleteData.flags = {
        sellingFormatTemplatesDropDown    : <?php echo $this->sellingFormatTemplatesDropDown    ? 'true' : 'false'; ?>,
        descriptionsTemplatesDropDown     : <?php echo $this->descriptionsTemplatesDropDown     ? 'true' : 'false'; ?>,
        generalTemplatesDropDown          : <?php echo $this->generalTemplatesDropDown          ? 'true' : 'false'; ?>,
        synchronizationsTemplatesDropDown : <?php echo $this->synchronizationsTemplatesDropDown ? 'true' : 'false'; ?>
    };
    M2ePro.autoCompleteData.url.getSellingFormatTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/searchAutocompleteByAttributeSetId', array('model' => 'Template_SellingFormat', 'component' => Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.autoCompleteData.url.getGeneralTemplatesBySet       = '<?php echo $this->getUrl('*/adminhtml_general/searchAutocompleteByAttributeSetId', array('model' => 'Template_General', 'component' => Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.autoCompleteData.url.getDescriptionTemplatesBySet   = '<?php echo $this->getUrl('*/adminhtml_general/searchAutocompleteByAttributeSetId', array('model' => 'Template_Description', 'component' => Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';
    M2ePro.autoCompleteData.url.getSynchronizationTemplates    = '<?php echo $this->getUrl('*/adminhtml_general/searchAutocomplete', array('model' => 'Template_Synchronization', 'component' => Ess_M2ePro_Helper_Component_Ebay::NICK)); ?>';

    Event.observe(window, 'load', function() {

        EbayListingEditHandlerObj = new EbayListingEditHandler();
        EbayListingEditHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Listing'); ?>');
        AutoCompleteHandler    = new AutoComplete();

        if (M2ePro.autoCompleteData.flags.synchronizationsTemplatesDropDown) {
            $('template_synchronization_id').observe('change', EbayListingEditHandlerObj.synchronization_template_id_change)
            if ($('template_synchronization_id').value) {
                $('template_synchronization_id').simulate('change');
            }
        } else {
            AutoCompleteHandler.bind('template_synchronization_autocomplete',
                M2ePro.autoCompleteData.url.getSynchronizationTemplates,
                M2ePro.formData.template_synchronization_id > 0 ? M2ePro.formData.template_synchronization_id : '',
                M2ePro.formData.template_synchronization_title,
                function (id) {$('template_synchronization_id').value = id}
            );
            $('template_synchronization_id').value = $('template_synchronization_autocomplete').readAttribute('selected_id');
            M2ePro.formData.template_synchronization_id > 0 && $('template_synchronization_autocomplete').setStyle({color: 'initial'});
        }

        $('attribute_sets').observe('change', EbayListingEditHandlerObj.attribute_set_change);
        $('attribute_sets').value && EbayListingEditHandlerObj.attribute_set_change();

        $('synchronization_start_type')
            .observe('change', EbayListingEditHandlerObj.synchronization_start_type_change)
            .simulate('change');

        $('synchronization_stop_type')
            .observe('change', EbayListingEditHandlerObj.synchronization_stop_type_change)
            .simulate('change');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_ebay_listing_edit_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Listing Configuration'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="title" name="title" value="<?php echo Mage::helper('M2ePro')->__($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-listing-title" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Short meaningful Listing title for your internal use.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Set'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if (!$isEdit) : ?>
                                <select id="attribute_sets" name="attribute_sets" class="select-main required-entry">
                                    <?php if ($formData['attribute_sets'] == -1): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->attributesSets as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if ($formData['attribute_sets'] == $set['attribute_set_id']) echo ' selected="selected"'; ?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            <?php else: ?>
                                <select id="attribute_sets_fake" name="attribute_sets_fake" class="select-main" disabled="disabled">
                                    <?php foreach ($this->attributesSets as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if ($formData['attribute_sets'] == $set['attribute_set_id']) echo ' selected="selected"'; ?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <input id="attribute_sets" name="attribute_sets" value="<?php echo $this->escapeHtml($formData['attribute_sets']); ?>" type="hidden" />
                            <?php endif ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Attribute Set of products, which will be listed on eBay from this Listing.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_selling_format_id"><?php echo Mage::helper('M2ePro')->__('Selling Format Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" id="template_selling_format_cell">
                            <?php if ($this->sellingFormatTemplatesDropDown): ?>
                                <select id="template_selling_format_id" name="template_selling_format_id" class="required-entry"></select>
                            <?php else: ?>
                                <input type="text" id="template_selling_format_autocomplete" class="input-text" selected_id="" style="width: 275px;" />
                                <input type="hidden" name="template_selling_format_id" id="template_selling_format_id" class="required-entry" value="" />
                            <?php endif; ?>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_selling_format_template_button'); ?>
                            <?php if ($this->sellingFormatTemplatesDropDown) echo $this->getChildHtml('reload_selling_format_templates_button'); ?>
                            <p class="note">
                                <?php if ($this->sellingFormatTemplatesDropDown) { ?>
                                    <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                                <?php } else {?>
                                    <span><?php echo Mage::helper('M2ePro')->__('Search for template which have previously chosen Attribute Set.'); ?></span>
                                <?php } ?>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_general_id"><?php echo Mage::helper('M2ePro')->__('General Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" id="template_general_cell">
                            <?php if ($this->generalTemplatesDropDown): ?>
                                <select id="template_general_id" name="template_general_id" class="required-entry"></select>
                            <?php else: ?>
                                <input type="text" id="template_general_autocomplete" class="input-text" selected_id="" style="width: 275px;" />
                                <input type="hidden" id="template_general_id" name="template_general_id" class="required-entry" value="" />
                            <?php endif; ?>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_general_template_button'); ?>
                            <?php if ($this->generalTemplatesDropDown) echo $this->getChildHtml('reload_general_templates_button'); ?>
                            <p class="note">
                                <?php if ($this->generalTemplatesDropDown) { ?>
                                    <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                                <?php } else {?>
                                    <span><?php echo Mage::helper('M2ePro')->__('Search for template which have previously chosen Attribute Set.'); ?></span>
                                <?php } ?>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="template_description_id"><?php echo Mage::helper('M2ePro')->__('Description Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" id="template_description_cell">
                            <?php if ($this->descriptionsTemplatesDropDown): ?>
                                <select id="template_description_id" name="template_description_id" class="required-entry"></select>
                            <?php else: ?>
                                <input type="text" id="template_description_autocomplete" class="input-text" selected_id="" style="width: 275px;" />
                                <input type="hidden" name="template_description_id" id="template_description_id" class="required-entry" value="" />
                            <?php endif; ?>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_description_template_button'); ?>
                            <?php if ($this->descriptionsTemplatesDropDown) echo $this->getChildHtml('reload_description_templates_button'); ?>
                            <p class="note">
                                <?php if ($this->descriptionsTemplatesDropDown) { ?>
                                    <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                                <?php } else {?>
                                    <span><?php echo Mage::helper('M2ePro')->__('Search for template which have previously chosen Attribute Set.'); ?></span>
                                <?php } ?>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_listing_edit_synchronization">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="template_synchronization_id"><?php echo Mage::helper('M2ePro')->__('Synchronization Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if ($this->synchronizationsTemplatesDropDown): ?>
                                <select id="template_synchronization_id" name="template_synchronization_id" class="required-entry">
                                    <?php if ($formData['template_synchronization_id'] == -1): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->synchronizationsTemplates as $item){ ?>
                                        <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $formData['template_synchronization_id']) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                    <?php } ?>
                                </select>
                            <?php else:?>
                                <input type="text" id="template_synchronization_autocomplete" class="input-text" selected_id="" style="width: 275px; color: gray;"
                                       value="<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Template Name Here...')); ?>"
                                       onblur="if (this.value.trim().length == 0) {
                                           this.value = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Template Name Here...')); ?>';
                                           this.style.color = 'gray';
                                       }"
                                       onfocus="if (this.value == '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Template Name Here...')); ?>') {
                                           this.value = '';
                                           this.style.color = '';
                                       }"
                                >
                                <input type="hidden" name="template_synchronization_id" id="template_synchronization_id" class="required-entry" value="" />
                            <?php endif; ?>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_synchronization_template_button'); ?>
                            <?php if ($this->synchronizationsTemplatesDropDown) echo $this->getChildHtml('reload_synchronization_templates_button'); ?>
                            <p class="note">
                                <?php if ($this->synchronizationsTemplatesDropDown) { ?>
                                    <span><?php echo Mage::helper('M2ePro')->__('All Synchronization Templates you have created.'); ?></span>
                                <?php } else {?>
                                    <span><?php echo Mage::helper('M2ePro')->__('Search for Synchronization Template you have created.'); ?></span>
                                <?php } ?>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="synchronization_start_type"><?php echo Mage::helper('M2ePro')->__('Activation'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="synchronization_start_type" name="synchronization_start_type" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_IMMEDIATELY; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_IMMEDIATELY == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Immediately'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_THROUGH; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_THROUGH == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Delay After Listing Creation'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_DATE; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_DATE == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Since Date'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_NEVER; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_NEVER == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Never'); ?></option></select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time, when settings of chosen Synchronization Template take effect.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="synchronization_start_through_value_container" <?php if ($formData['synchronization_start_type'] != Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_THROUGH) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_start_through_value"><?php echo Mage::helper('M2ePro')->__('Delay'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input id="synchronization_start_through_value" name="synchronization_start_through_value" value="<?php echo $formData['synchronization_start_through_value']; ?>" type="text" style="width: 180px;" class="input-text validate-digits M2ePro-required-when-visible" />
                            <select id="synchronization_start_through_metric" name="synchronization_start_through_metric" style="width: 90px;" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Day(s)'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_HOURS; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_HOURS == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Hour(s)'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_MINUTES; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_THROUGH_METRIC_MINUTES == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Minute(s)'); ?></option> -->
                            </select>
                             <p class="note">
                                 <span><?php echo Mage::helper('M2ePro')->__('In how many days, hours or minutes Synchronization Template settings have to be activated.'); ?></span>
                            </p>
                       </td>
                    </tr>

                    <tr id="synchronization_start_date_container" <?php if ($formData['synchronization_start_type'] != Ess_M2ePro_Model_Listing::SYNCHRONIZATION_START_TYPE_DATE) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_start_date"><?php echo Mage::helper('M2ePro')->__('Date'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="synchronization_start_date" name="synchronization_start_date" value="<?php echo $formData['synchronization_start_date']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "synchronization_start_date",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "synchronization_start_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Date and time when Synchronization Template has to be activated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="deactivation_row">
                        <td class="label">
                            <label for="synchronization_stop_type"><?php echo Mage::helper('M2ePro')->__('Deactivation'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="synchronization_stop_type" name="synchronization_stop_type" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_NEVER; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_NEVER == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Never'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_THROUGH; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_THROUGH == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Through Period After Activation'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_DATE; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_DATE == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('On Date'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time, when settings of chosen Synchronization Template have to be deactivated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="synchronization_stop_through_value_container" <?php if ($formData['synchronization_stop_type'] != Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_THROUGH) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_stop_through_value"><?php echo Mage::helper('M2ePro')->__('Period Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="synchronization_stop_through_value" name="synchronization_stop_through_value" value="<?php echo $formData['synchronization_stop_through_value']; ?>" type="text" style="width: 180px;" class="input-text validate-digits M2ePro-required-when-visible" />
                            <select id="synchronization_stop_through_metric" name="synchronization_stop_through_metric" style="width: 90px;" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Day(s)'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_HOURS; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_HOURS == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Hour(s)'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_MINUTES; ?>"<?php if (Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_THROUGH_METRIC_MINUTES == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Minute(s)'); ?></option> -->
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('In how many days, hours or minutes after activation Synchronization Template settings have to be deactivated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="synchronization_stop_date_container" <?php if ($formData['synchronization_stop_type'] != Ess_M2ePro_Model_Listing::SYNCHRONIZATION_STOP_TYPE_DATE) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_stop_date"><?php echo Mage::helper('M2ePro')->__('Date'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="synchronization_stop_date" name="synchronization_stop_date" value="<?php echo $formData['synchronization_stop_date']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "synchronization_stop_date",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "synchronization_stop_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Date and time when Synchronization Template has to be deactivated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_listing_edit_source_products">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Products Filter'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="store_id"><?php echo Mage::helper('M2ePro')->__('Store View'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if (!$isEdit) { ?>
                                <?php echo $this->getChildHtml('store_id'); ?>
                            <?php } else { ?>
                                <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                    <span style="display: block; padding: 4px 0 0;">
                                <?php } ?>

                                <strong><?php echo $formData['store_name']; ?></strong>

                                <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                    </span>
                                <?php } ?>
                            <?php } ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Store View the items' information has to be taken from."); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="source_products"><?php echo Mage::helper('M2ePro')->__('Select from'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="source_products" name="source_products" <?php if ($isEdit): ?> disabled="disabled"<?php endif ?> class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CUSTOM; ?>"<?php if (Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CUSTOM == $formData['source_products']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Products List'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CATEGORIES; ?>"<?php if (Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CATEGORIES == $formData['source_products']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Categories'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Modes of the products selection.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="hide_products_others_listings"><?php echo Mage::helper('M2ePro')->__('Products Presented in Other Listings'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="hide_products_others_listings" name="hide_products_others_listings" class="required-entry" <?php if ($isEdit): ?> disabled="disabled"<?php endif ?>>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::HIDE_PRODUCTS_OTHERS_LISTINGS_NO; ?>"<?php if (Ess_M2ePro_Model_Listing::HIDE_PRODUCTS_OTHERS_LISTINGS_NO == $formData['hide_products_others_listings']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listing::HIDE_PRODUCTS_OTHERS_LISTINGS_YES; ?>"<?php if (Ess_M2ePro_Model_Listing::HIDE_PRODUCTS_OTHERS_LISTINGS_YES == $formData['hide_products_others_listings']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                            </select>
                            <p class="note"></p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <?php if ($isEdit) : ?>
        <div class="entry-edit" id="magento_block_ebay_listings_edit_categories_product_actions" <?php if ($formData['source_products'] == Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CUSTOM) echo ' style="display: none;"'; ?>>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Actions On Categories\' Products'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <tbody>

                            <?php if ($isEdit && $formData['source_products'] == Ess_M2ePro_Model_Listing::SOURCE_PRODUCTS_CATEGORIES): ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Selected Categories'); ?>: <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->getChildHtml('categoriesTree'); ?>
                                    </td>
                                </tr>

                            <?php endif; ?>

                            <tr id="categories_add_action_container" <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) echo ' style="display: none;"'; ?>>
                                <td class="label">
                                    <label for="categories_add_action"><?php echo Mage::helper('M2ePro')->__('New Product Added to Category'); ?>: <span class="required" style="float: right;">*</span></label>
                                </td>
                                <td class="value">
                                    <select id="categories_add_action" name="categories_add_action" class="M2ePro-required-when-visible">
                                        <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_NONE == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing'); ?></option>
                                        <?php // Magento GO ugly hack
                                            if (!Mage::helper('M2ePro/Magento')->isGoEdition()) { ?>
                                            <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD_LIST; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_ADD_ACTION_ADD_LIST == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing And List on eBay'); ?></option>
                                        <?php } ?>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Actions, which have to be done to products added to categories.'); ?></span>
                                    </p>
                               </td>
                            </tr>

                            <tr id="categories_delete_action_container" <?php if (Mage::helper('M2ePro/Magento')->isGoEdition()) echo ' style="display: none;"'; ?>>
                                <td class="label">
                                    <label for="categories_delete_action"><?php echo Mage::helper('M2ePro')->__('Product Deleted from Category'); ?>: <span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <select id="categories_delete_action" name="categories_delete_action" class="M2ePro-required-when-visible">
                                        <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_NONE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP_REMOVE; ?>"<?php if (Ess_M2ePro_Model_Listing::CATEGORIES_DELETE_ACTION_STOP_REMOVE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay and Delete from Listing'); ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Actions, which have to be done to listed products deleted from categories.'); ?></span>
                                    </p>
                                </td>
                            </tr>

                        </tbody>

                    </table>

                </div>
            </div>

        </div>

        <input type="hidden" value="" name="selected_categories" id="selected_categories" />
    <?php endif; ?>

</form>