<script type="text/javascript">

    setTimeout(function() {
        ModuleNoticeObj.observeModulePrepareStart($('block_notice_ebay_listing_tutorial'));
    }, 50);

</script>

<div id="<?php echo $this->getContainerId() ?>">
    <div class="content-header">
    </div>
    <div>
        <div id="block_notice_ebay_listing_tutorial" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

            <?php
                $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
                $descriptionTemplatesUrl = $this->getUrl('*/adminhtml_template_description/index');
                $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
                $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

                $listingsUrl = $this->getUrl('*/adminhtml_ebay_listing/add/step/1/clear/yes');

                $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

                echo Mage::helper('M2ePro')->__(
                    'Listing is a group of items, which have the same Attribute Set and were combined to be listed on eBay.
                    <br/><br/>
                    Creating a Listing requires four types of templates to be created in advance.<br/>
                    You can use the same template for similar products you want to list on eBay and don’t have to enter the same information over and over again for each product you want to list.
                    <br/><br/>
                    Templates you’ll need in order to list on eBay:
                    <br/><br/>
                    <ul style="margin-left: 15px; list-style: disc">
                        <li><a href="%s">Selling Format Template</a> contains information about listing types, quantities, auction duration and specifies price-related data (including that of Best Offer).</li>
                        <li><a href="%s">Description Template</a> sets products "look and feel".</li>
                        <li><a href="%s">General Template</a> contains basic settings which are required for successful eBay listing.</li>
                        <li><a href="%s">Synchronization Template</a> controls how the information between eBay and Magento is synchronized and in which cases eBay listings are revised, relisted or stopped.  This template is not bound to a product group with a specific attribute set, so it’s likely that you’ll only need one template to begin with.</li>
                    </ul>
                    <br/>',
                    $sellingFormatTemplatesUrl,$descriptionTemplatesUrl,$listingTemplatesUrl,$synchronizationTemplatesUrl
                );

                echo $this->getChildHtml('confirm_tutorial');
            ?>

        </div>
    </div>
</div>