<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('M2E Pro Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows the M2E Pro listings you\'ve set up.<br/><br/>
        Click a line in the table below to manage the products current listed using that M2E Pro listing.
        Otherwise use the dropdown menu in the <b>Actions</b> column for more options.<br/><br/>
        To clear the logs or delete more than one M2E Pro listing at a time, use the <b>Actions</b> dropdown at the very top of the table.'
    ); ?>
</div>