<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Type'); ?>: </label>
        </td>
        <td class="value">
           <?php echo $this->cronCurrentType; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Last Run'); ?>: </label>
        </td>
        <?php
            $style = '';
            if ($this->cronIsNotWorking) {
                $style = ' style="color: red"';
            }
        ?>
        <td class="value">
            <span<?php echo $style; ?>><?php echo $this->cronLastRunTime ?></span>
            <?php
                if ($this->cronIsNotWorking) {
                    echo ' (' . Mage::helper('M2ePro')->__('not working') . ')';
                }
            ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Cron Schedule Table'); ?>: </label>
        </td>
        <td class="value">
            <a href="<?php echo $this->getUrl('*/adminhtml_development_inspection/cronScheduleTable'); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Show') ?></a>
        </td>
    </tr>

</table>