<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Type'); ?>: </label>
        </td>
        <td class="value">
           <?php echo $this->cronCurrentType; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Last Run'); ?>: </label>
        </td>
        <?php
            $style = '';
            if ($this->cronIsNotWorking) {
                $style = ' style="color: red"';
            }
        ?>
        <td class="value">
            <span<?php echo $style; ?>><?php echo $this->cronLastRunTime ?></span>
            <?php
                if ($this->cronIsNotWorking) {
                    echo ' (' . Mage::helper('M2ePro')->__('not working') . ')';
                }
            ?>
        </td>
    </tr>

    <?php if ($this->isShownRecommendationsMessage()) : ?>
        <tr>
            <td class="label" colspan="2" style="width: 600px">
                <strong><?php echo Mage::helper('M2ePro')->__('We recommend to set up your cron job to be run every 1 minute (e.g. * * * * *).'); ?></strong>
            </td>
        </tr>

        <tr>
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('PHP command'); ?>: </label>
            </td>
            <td class="value">
                <?php echo $this->cronPhp; ?>
            </td>
        </tr>

        <tr>
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('GET command'); ?>: </label>
            </td>
            <td class="value">
                <?php echo $this->cronGet; ?>
            </td>
        </tr>
    <?php endif; ?>

    <?php if ($this->isShownServiceDescriptionMessage()) : ?>
        <tr>
            <td class="label" colspan="2" style="width: 600px">
                <strong><?php echo Mage::helper('M2ePro')->__('What is the cron type Service?'); ?></strong>
            </td>
        </tr>
        <tr>
            <td class="label" colspan="2" style="width: 600px">
                <?php echo Mage::helper('M2ePro')->__(
                    'It is M2E Pro cron system where you were registered automatically during the extension installation.
                    No additional settings are required. Our service does HTTP calls to your Magento from IP address: <b>%server_ip%</b>.',
                    $this->cronServiceIp
                ); ?>
            </td>
        </tr>
    <?php endif; ?>

    <?php if (!$this->getData('is_support_mode')) : ?>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Cron Schedule Table'); ?>: </label>
            </td>
            <td class="value">
                <a href="<?php echo $this->getUrl('*/adminhtml_development_inspection/cronScheduleTable'); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Show') ?></a>
            </td>
        </tr>
    <?php endif; ?>

</table>