<?php
    $lastUpgradeDate = isset($this->installationVersionHistory[0]['value']) ? $this->installationVersionHistory[0]['value'] : 'no data';
    $lastUpgradeVersion = isset($this->installationVersionHistory[0]['key']) ? $this->installationVersionHistory[0]['key'] : 'no data';
?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Last Version'); ?>: </label>
        </td>
        <td class="value">
            <?php echo $this->lastVersion; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?php echo Mage::helper('M2ePro')->__('Last Upgrade'); ?>: </label>
        </td>
        <td class="value">
            <?php echo "{$lastUpgradeDate} (to {$lastUpgradeVersion})"; ?>
            <a style="margin-left: 10px;" href="<?php echo $this->getUrl('*/adminhtml_development_tools_m2ePro_install/showInstallationVersionHistory'); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Show All'); ?></a>
        </td>
    </tr>

</table>