<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_common_marketplace/save'),
        'logViewUrl' => $this->getUrl('M2ePro/adminhtml_common_log/synchronization',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_common_synchronization/index'))),

        'runSynchNow' => $this->getUrl('M2ePro/adminhtml_common_marketplace/runSynchNow'),
        'synchCheckProcessingNow' => $this->getUrl('M2ePro/adminhtml_common_synchronization/synchCheckProcessingNow')
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Marketplaces settings have been saved.' => $this->__('Marketplaces settings have been saved.'),
        'You must select at least one marketplace you will work with.' => $this->__('You must select at least one marketplace you will work with.'),

        'Another Synchronization Is Already Running.' => $this->__('Another Synchronization Is Already Running.'),
        'Getting information. Please wait ...' => $this->__('Getting information. Please wait ...'),
        'Preparing to start. Please wait ...' => $this->__('Preparing to start. Please wait ...'),

        'Synchronization has successfully ended.' => $this->__('Synchronization has successfully ended.'),
        'Synchronization ended with warnings. <a target="_blank" href="%url%">View log</a> for details.' => $this->__('Synchronization ended with warnings. <a target="_blank" href="%url%">View log</a> for details.'),
        'Synchronization ended with errors. <a target="_blank" href="%url%">View log</a> for details.' => $this->__('Synchronization ended with errors. <a target="_blank" href="%url%">View log</a> for details.')
    )); ?>);

    Event.observe(window, 'load', function() {
        editForm = new varienForm('<?php echo $this->getForm()->getId(); ?>', '<?php echo $this->getValidationUrl(); ?>');

        MarketplaceProgressBarObj = new ProgressBar('marketplaces_progress_bar');
        MarketplaceWrapperObj = new AreaWrapper('marketplaces_content_container');

        MarketplaceProgressHandlerObj = new SynchProgressHandler(MarketplaceProgressBarObj, MarketplaceWrapperObj );
        MarketplaceHandlerObj = new MarketplaceHandler(MarketplaceProgressHandlerObj);
        MarketplaceProgressHandlerObj.initPageCheckState();

        <?php if (!is_null($this->getChildBlockId())) { ?>
            <?php
                $childBlockId = Mage::helper('M2ePro')->escapeJs($this->getChildBlockId());
                $destinationBlockId = Mage::helper('M2ePro')->escapeJs($this->getForm()->getId());
            ?>
            MarketplaceHandlerObj.moveChildBlockContent('<?php echo $childBlockId; ?>', '<?php echo $destinationBlockId; ?>');
        <?php } ?>

        varienGlobalEvents && varienGlobalEvents.fireEvent('initReady');
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

</form>