<div id="block_notice_marketplaces_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Marketplaces'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set up the Marketplaces you will work with.<br/><br/>

    Enable certain Marketplaces and press the <i class="underline">Save</i> button in the top right corner, all necessary marketplace data will be downloaded and synchronized with M2E Pro settings.<br/>
    It is recommended to update Marketplaces when any marketplace changes are announced by clicking <i class="underline">Update All Now</i> button. <br/><br/>
    <b>Note:</b> Installation and update processes might be time-consuming, depending on the number of enabled Marketplaces and your server environment. <br/>
    '); ?>
</div>