<script type="text/javascript">

    if (typeof M2eProPlayListingTutorial == 'undefined') {
        M2eProPlayListingTutorial = {};
        M2eProPlayListingTutorial.url = {};
        M2eProPlayListingTutorial.formData = {};
        M2eProPlayListingTutorial.text = {};
    }

    M2eProPlayListingTutorial.text.confim_offer_show_video = '';
    M2eProPlayListingTutorial.text.confim_close_video = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Are you sure?')); ?>';

    PlayListingVideoTutorialHandlerObj = new VideoTutorialHandler(M2eProPlayListingTutorial,'play_listing_video_tutorial_pop_up',
                                                                         '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('M2E Pro - Play.com/Magento Integration : Listings')); ?>',
                                                                         function(){});

    setTimeout(function() {
        ModuleNoticeObj.observeModulePrepareStart($('block_notice_play_listing_tutorial'));
    }, 50);

</script>

<div id="<?php echo $this->getContainerId() ?>">
    <div class="content-header">
    </div>
    <div>
        <div id="block_notice_play_listing_tutorial" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

            <table>
                <tr>
<!--                    todo-->
<!--                    <td>-->
<!--                        <a href="javascript:" onclick="PlayListingVideoTutorialHandlerObj.openPopUp()">-->
<!--                            <img src="--><?php //echo $this->getSkinUrl('M2ePro/images/play-video-thumbnail.png'); ?><!--" alt="">-->
<!--                        </a>-->
<!--                        <h4 style="text-align: center">Play.com Listings (12 min. video)</h4>-->
<!--                    </td>-->

<!--                    <td style="padding: 10px  0 0 30px">-->
                    <td style="padding: 0">
                        <?php
                            $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
                            $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
                            $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

                            $listingsUrl = $this->getUrl('*/adminhtml_play_listing/add/step/1/clear/yes');

                            $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

                            echo Mage::helper('M2ePro')->__(
                            'Listing is a group of items, which have the same Attribute Set and were combined to be listed on Play.com.
                            <br/><br/>
                            Creating a Listing requires two types of templates to be created in advance.<br/>
                            You can use the same template for similar products you want to list on Play.com and don\'t have to enter the same information over and over again for each product you want to list.
                            <br/><br/>
                            Templates you’ll need in order to list on Play.com:
                            <br/><br/>
                            <ul style="margin-left: 15px; list-style: disc">
                                <li><a href="%s">Selling Format Template</a> contains information about quantity and price-related data.</li>
                                <li><a href="%s">Synchronization Template</a> controls how the information between Play.com and Magento is synchronized and in which cases Play.com listings are revised, relisted or stopped.  This template is not bound to a product group with a specific attribute set, so it\'s likely that you\'ll only need one template to begin with.</li>
                            </ul>
                            <br/>
                            <b>Note:</b> Only simple products are supported in current version.
                            <br/><br/>',
                            $sellingFormatTemplatesUrl, $synchronizationTemplatesUrl);

                            echo $this->getChildHtml('confirm_tutorial');
                        ?>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>

<div id="play_listing_video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
       <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/jUOcdYO9ZPM?version=3&amp;hl=ru_RU&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/jUOcdYO9ZPM?version=3&amp;hl=ru_RU&amp;rel=0" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>