<div id="block_notice_ebay_listing_other_synchronization_source" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Source'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Specifies Magento product data to be synchronized with eBay.
    <br><br>
    <b>Note:</b> If you set \'Not Set\' in an option, the synchronization will not be performed for it.'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();

    $attributes = $formData['attributes'];
    $formData = $formData['source'];

    $formDataDefaults = array(
        'qty'           => Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_PRODUCT,
        'price'         => Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_PRODUCT,
        'title'         => Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_PRODUCT,
        'sub_title'     => Ess_M2ePro_Model_Ebay_Listing_Other_Source::SUB_TITLE_SOURCE_NONE,
        'description'   => Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_PRODUCT_MAIN,
    );
    $formData = array_merge($formDataDefaults, $formData);

    $attributesDefaults = array(
        'qty'           => '',
        'price'         => '',
        'title'         => '',
        'sub_title'     => '',
        'description'   => '',
    );
    $attributes = array_merge($attributesDefaults, $attributes);
?>

<script type="text/javascript">

    Event.observe(window, 'load', function() {

        M2ePro.translator.add(<?php echo json_encode(array(
            'The price will be calculated according to Catalog Price Rules (Magento > Promotions > Catalog Price Rules).' =>
                Mage::helper('M2ePro')->__('The price will be calculated according to Catalog Price Rules (Magento > Promotions > Catalog Price Rules).'),
            'Updates price on eBay listing(s) when the source of price changes.' =>
                Mage::helper('M2ePro')->__('Updates price on eBay listing(s) when the source of price changes.'),
        )); ?>);

        M2ePro.url.add(<?php echo json_encode(array(
            'formSubmit' => $this->getUrl('M2ePro/adminhtml_ebay_listing_other_synchronization/save'),
            'adminhtml_ebay_listing_other_synchronization/save' => $this->getUrl('M2ePro/adminhtml_ebay_listing_other_synchronization/save')
        )); ?>);

        M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Listing_Other_Source') ?>, 'Ess_M2ePro_Model_Ebay_Listing_Other_Source');
        M2ePro.php.setConstants(<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Listing_Other_Synchronization') ?>, 'Ess_M2ePro_Model_Ebay_Listing_Other_Synchronization');

        $$('.source').each(function(elem) {
           elem.observe('change', EbayListingOtherSynchronizationHandlerObj.source_change)
               .simulate('change');
        });
    });

</script>

<div class="entry-edit" id="magento_block_ebay_listing_other_source_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization Source'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <input type="hidden" id="qty" name="qty" value="<?php echo $formData['qty']; ?>">
                <input type="hidden" id="qty_attribute" name="qty_attribute" value="<?php echo $attributes['qty']; ?>">

                <tr>
                    <td class="label">
                        <label for="qty"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_source" class="source">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_NONE ?>" <?php if ($formData['qty'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Not Set (not changeable on eBay)'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_PRODUCT ?>" <?php if ($formData['qty'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product QTY'); ?></option>
                            <optgroup label="<?php echo Mage::helper('M2ePro')->__('Magento Attributes'); ?>" qty_source="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_ATTRIBUTE; ?>">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_PRODUCT_FIXED; ?>" <?php if (Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_PRODUCT_FIXED == $formData['qty']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('QTY'); ?></option>
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value="<?php echo $attribute['code'] ?>" <?php if ($attributes['qty'] == $attribute['code'] && $formData['qty'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::QTY_SOURCE_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('<b>Product QTY</b> - eBay listing quantity will be synchronized with Magento product quantity.
    <br><b>Magento Attribute</b> - eBay listing quantity will be synchronized with attribute value.
'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <input type="hidden" id="price" name="price" value="<?php echo $formData['price']; ?>">
                <input type="hidden" id="price_attribute" name="price_attribute" value="<?php echo $attributes['price']; ?>">

                <tr>
                    <td class="label">
                        <label for="price"><?php echo Mage::helper('M2ePro')->__('Price'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="price_source" class="source">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_NONE ?>" <?php if ($formData['price'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Not Set (not changeable on eBay)'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_PRODUCT ?>" <?php if ($formData['price'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_SPECIAL ?>" <?php if ($formData['price'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_SPECIAL): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                            <optgroup label="<?php echo Mage::helper('M2ePro')->__('Magento Attributes'); ?>" price_source="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_ATTRIBUTE; ?>">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value="<?php echo $attribute['code'] ?>" <?php if ($attributes['price'] == $attribute['code'] && $formData['price'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::PRICE_SOURCE_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('
    <b>Product Price</b> - eBay Listing price will be synchronized with the original Magento product price.<br>
    <b>Special Price</b> - eBay Listing price will be synchronized with the special price of Magento product.<br>
    <b>Magento Attribute</b> - eBay listing price will be synchronized with attribute value.
'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <input type="hidden" id="title" name="title" value="<?php echo $formData['title']; ?>">
                <input type="hidden" id="title_attribute" name="title_attribute" value="<?php echo $attributes['title']; ?>">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="title_source" class="source">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_NONE ?>" <?php if ($formData['title'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Not Set (not changeable on eBay)'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_PRODUCT ?>" <?php if ($formData['title'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_PRODUCT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Name'); ?></option>
                            <optgroup label="<?php echo Mage::helper('M2ePro')->__('Magento Attributes'); ?>" title_source="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_ATTRIBUTE; ?>">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value="<?php echo $attribute['code'] ?>" <?php if ($attributes['title'] == $attribute['code'] && $formData['title'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::TITLE_SOURCE_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('
    <b>Product Name</b> - eBay listing title will be synchronized with the original Magento product name.<br>
    <b>Magento Attribute</b> - eBay listing title will be synchronized with attribute value.
    '); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <input type="hidden" id="sub_title" name="sub_title" value="<?php echo $formData['sub_title']; ?>">
                <input type="hidden" id="sub_title_attribute" name="sub_title_attribute" value="<?php echo $attributes['sub_title']; ?>">

                <tr>
                    <td class="label">
                        <label for="sub_title"><?php echo Mage::helper('M2ePro')->__('Subtitle'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="sub_title_source" class="source">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::SUB_TITLE_SOURCE_NONE ?>" <?php if ($formData['sub_title'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::SUB_TITLE_SOURCE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Not Set (not changeable on eBay)'); ?></option>
                            <optgroup label="<?php echo Mage::helper('M2ePro')->__('Magento Attributes'); ?>" sub_title_source="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::SUB_TITLE_SOURCE_ATTRIBUTE; ?>">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value="<?php echo $attribute['code'] ?>" <?php if ($attributes['sub_title'] == $attribute['code'] && $formData['sub_title'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::SUB_TITLE_SOURCE_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose Magento attribute that will be synchronized with subtitle on eBay.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <input type="hidden" id="description" name="description" value="<?php echo $formData['description']; ?>">
                <input type="hidden" id="description_attribute" name="description_attribute" value="<?php echo $attributes['description']; ?>">

                <tr>
                    <td class="label">
                        <label for="description"><?php echo Mage::helper('M2ePro')->__('Description'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="description_source" class="source">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_NONE ?>" <?php if ($formData['description'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Not Set (not changeable on eBay)'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_PRODUCT_MAIN ?>" <?php if ($formData['description'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_PRODUCT_MAIN): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Description'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_PRODUCT_SHORT ?>" <?php if ($formData['description'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_PRODUCT_SHORT): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Short Description'); ?></option>
                            <optgroup label="<?php echo Mage::helper('M2ePro')->__('Magento Attributes'); ?>" description_source="<?php echo Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_ATTRIBUTE; ?>">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value="<?php echo $attribute['code'] ?>" <?php if ($attributes['description'] == $attribute['code'] && $formData['description'] == Ess_M2ePro_Model_Ebay_Listing_Other_Source::DESCRIPTION_SOURCE_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('
    <b>Product Description</b> - eBay listing description will be synchronized with the original description of Magento product.<br>
    <b>Product Short Description</b> - eBay listing description will be synchronized with the original short Magento product description.<br>
    <b>Magento Attribute</b> - eBay listing description will be synchronized with attribute value.
    '); ?></span>
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>

</div>
