<div id="block_notice_wizard_congratulation" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php

    $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
    $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
    $descriptionTemplatesUrl = $this->getUrl('*/adminhtml_template_description/index');
    $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

    $listingsUrl = $this->getUrl('*/adminhtml_listing/index');
    $docsLink = Mage::helper('M2ePro/Module')->getConfig()->getGroupValue('/documentation/', 'baseurl');

    $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

    $components = Mage::helper('M2ePro/Component')->getAllowedComponentsTitles();
    $components = implode(' / ',$components);

    $tempString = Mage::helper('M2ePro')->__(
        'You have set the main M2E Pro settings and now you have to set up the main settings of the chosen Channel(s).'
    );

    echo $tempString;

    ?>
</div>