<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.view_ebay_order = '<?php echo $this->getUrl('*/adminhtml_ebay_order/view',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_order/index'))); ?>';
    M2ePro.url.view_amazon_order = '<?php echo $this->getUrl('*/adminhtml_amazon_order/view',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_order/index'))); ?>';
    M2ePro.url.view_buy_order = '<?php echo $this->getUrl('*/adminhtml_buy_order/view',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_order/index'))); ?>';

    M2ePro.text.view_all_order_logs_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('View All Order Logs.')); ?>';

    M2ePro.text.success_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Success')); ?>';
    M2ePro.text.warning_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Warning')); ?>';
    M2ePro.text.error_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Error')); ?>';
    M2ePro.text.close_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Close')); ?>';

    Event.observe(window, 'load', function() {
        OrderHandlerObj = new OrderHandler('<?php echo json_encode($this->getGridIds()); ?>');
        OrderHandlerObj.initializeGrids();
        OrderHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Order_Log'); ?>');
    });

</script>