<style type="text/css">
    .column_condition {
        color: gray;
    }
    .column_value_fail {
        color: red;
    }
    .column_value_success {
        color: green;
    }
</style>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label" style="width:200px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Properties'); ?></strong>
        </td>
        <td class="value" style="width:200px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Recommended Value'); ?></strong>
        </td>
        <td class="value" style="width:200px;">
            <strong><?php echo Mage::helper('M2ePro')->__('Current Value'); ?></strong>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('Magento Version'); ?>
        </td>
        <td class="value column_condition">
            <?php echo '>= '.$this->magento_version['recommended'] ?>
        </td>
        <td class="value <?php echo $this->magento_version['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo $this->magento_version['value']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('PHP Version'); ?>
        </td>
        <td class="value column_condition">
            <?php echo '>= '.$this->php_version['recommended'] ?>
        </td>
        <td class="value <?php echo $this->php_version['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo $this->php_version['value']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('Memory Limit'); ?>
        </td>
        <td class="value column_condition">
            <?php echo '>= '.$this->memory_limit['recommended'].' '.Mage::helper('M2ePro')->__('Mb'); ?>
        </td>
        <td class="value <?php echo $this->memory_limit['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo $this->memory_limit['value'].' '.Mage::helper('M2ePro')->__('Mb'); ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('Max Execution Time'); ?>
        </td>
        <td class="value column_condition">
            <?php echo '>= '.$this->max_execution_time['recommended'].' '.Mage::helper('M2ePro')->__('sec'); ?>
        </td>
        <td class="value <?php echo $this->max_execution_time['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo is_int($this->max_execution_time['value']) ? $this->max_execution_time['value'].' '.Mage::helper('M2ePro')->__('sec') : $this->max_execution_time['value']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('JSON support'); ?>
        </td>
        <td class="value column_condition">
            <?php echo $this->json['recommended']; ?>
        </td>
        <td class="value <?php echo $this->json['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo $this->json['value']; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <?php echo Mage::helper('M2ePro')->__('CURL support'); ?>
        </td>
        <td class="value column_condition">
            <?php echo $this->curl['recommended']; ?>
        </td>
        <td class="value <?php echo $this->curl['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
            <?php echo $this->curl['value']; ?>
        </td>
    </tr>

    <?php /*
        <tr>
            <td class="label">
                <?php echo Mage::helper('M2ePro')->__('GMP support'); ?>
            </td>
            <td class="value column_condition">
                <?php echo $this->gmp['recommended']; ?>
            </td>
            <td class="value <?php echo $this->gmp['validation'] ? 'column_value_success' : 'column_value_fail'; ?>">
                <?php echo $this->gmp['value']; ?>
            </td>
        </tr>
    */ ?>

</table>