<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/save'),
        'logViewUrl' => $this->getUrl('M2ePro/adminhtml_ebay_log/synchronization',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_ebay_synchronization/index'))),

        'runAllEnabledNow'    => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/runAllEnabledNow'),
        'runNowTemplates'     => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/runNowTemplates'),
        'runNowOrders'        => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/runNowOrders'),
        'runNowOtherListings' => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/runNowOtherListings'),
        'runNowFeedbacks'     => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/runNowFeedbacks'),

        'synchCheckProcessingNow' => $this->getUrl('M2ePro/adminhtml_ebay_synchronization/synchCheckProcessingNow')
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Synchronization settings have been saved.' => $this->__('Synchronization settings have been saved.'),
        'Running All Enabled Tasks' => $this->__('Running All Enabled Tasks'),
        'Stock Level Synchronization' => $this->__('Stock Level Synchronization'),
        'Orders Synchronization' => $this->__('Orders Synchronization'),
        '3rd Party Listings Synchronization' => $this->__('3rd Party Listings Synchronization'),
        'Feedback Synchronization' => $this->__('Feedback Synchronization'),

        'Another Synchronization Is Already Running.' => $this->__('Another Synchronization Is Already Running.'),
        'Getting information. Please wait ...' => $this->__('Getting information. Please wait ...'),
        'Preparing to start. Please wait ...' => $this->__('Preparing to start. Please wait ...'),

        'Synchronization has successfully ended.' => $this->__('Synchronization has successfully ended.'),
        'Synchronization ended with warnings. <a target="_blank" href="%url%">View log</a> for details.' => $this->__('Synchronization ended with warnings. <a target="_blank" href="%url%">View log</a> for details.'),
        'Synchronization ended with errors. <a target="_blank" href="%url%">View log</a> for details.' => $this->__('Synchronization ended with errors. <a target="_blank" href="%url%">View log</a> for details.')
    )); ?>);

    Event.observe(window, 'load', function() {
        setTimeout(function() {
            SynchronizationProgressHandlerObj = new SynchProgressHandler(SynchProgressBarObj, SynchWrapperObj );
            SynchronizationHandlerObj = new SynchronizationHandler(SynchronizationProgressHandlerObj);
            SynchronizationProgressHandlerObj.initPageCheckState();

            editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

            <?php if (!is_null($this->getChildBlockId())) { ?>
            <?php
                $childBlockId = Mage::helper('M2ePro')->escapeJs($this->getChildBlockId());
                $destinationBlockId = Mage::helper('M2ePro')->escapeJs($this->getId());
            ?>
            SynchronizationHandlerObj.moveChildBlockContent('<?php echo $childBlockId; ?>', '<?php echo $destinationBlockId; ?>');
            <?php } ?>

        }, 350);
    });

</script>

<form id="<?php echo $this->getId(); ?>" action="<?php echo $this->getData('action'); ?>" method="post" enctype="multipart/form-data">

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

<div id="<?php echo $this->getContainerId(); ?>">

    <div class="entry-edit" id="magento_block_ebay_synchronization_templates">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Stock Level Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_ebay_synchronization_stock_level" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
                    <?php echo Mage::helper('M2ePro')->__('If catalog updates in your magento performed using import/export tools, custom scripts or direct changes in database,
                    then, you can use <a target="_blank" href="%s#magento_block_configuration_settings_advanced">"Track Direct Database Changes"</a> functionality to detect changes in products\' price and quantity.', Mage::helper('M2ePro/View_Configuration')->getSettingsUrl()) ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="ebay_templates_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $templates_mode = $this->templates['mode'] ? $this->templates['mode'] : 0; ?>
                            <select id="ebay_templates_mode" name="ebay_templates_mode" onchange="SynchronizationHandlerObj.changeTemplatesMode('<?php echo Ess_M2ePro_Helper_Component_Ebay::NICK; ?>');">
                                <option value="0"<?php if ($templates_mode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if ($templates_mode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Updates and synchronizes eBay Listings according to<br/>Synchronization Templates' rules."); ?></span>
                            </p>
                        </td>

                        <td class="value">
                            <div id="ebay_templates_run_now_container" <?php if ($templates_mode != 1) echo ' style="display: none;"'; ?>>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('ebay_templates_run_now'); ?>
                            </div>
                        </td>

                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('ebay_templates_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('ebay_templates_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_synchronization_orders">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Orders Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="ebay_orders_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $orders_mode = $this->orders ? $this->orders : 0; ?>
                            <select id="ebay_orders_mode" name="ebay_orders_mode" onchange="SynchronizationHandlerObj.changeOrdersMode('<?php echo Ess_M2ePro_Helper_Component_Ebay::NICK; ?>');">
                                <option value="0"<?php if ($orders_mode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if ($orders_mode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes eBay Orders for accounts,<br/>which have enabled Import eBay Orders in their<br/>Accounts settings.'); ?></span>
                            </p>
                        </td>
                        <td class="value">
                            <div id="ebay_orders_run_now_container" <?php if ($orders_mode != 1) echo ' style="display: none;"'; ?>>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('ebay_orders_run_now'); ?>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('ebay_orders_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('ebay_orders_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_synchronization_feedbacks" <?php if (Mage::helper('M2ePro/View_Ebay')->isSimpleMode()) : echo ' style="display: none"'; endif; ?>>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Feedback Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="ebay_feedbacks_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $feedbacks_mode = $this->feedbacks ? $this->feedbacks : 0; ?>
                            <select id="ebay_feedbacks_mode" name="ebay_feedbacks_mode" onchange="SynchronizationHandlerObj.changeFeedbacksMode('<?php echo Ess_M2ePro_Helper_Component_Ebay::NICK; ?>');">
                                <option value="0"<?php if ($feedbacks_mode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if ($feedbacks_mode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Imports buyers' feedback and automatically sends<br/>Auto Responses according to eBay Accounts settings."); ?></span>
                            </p>
                        </td>
                        <td class="value">
                            <div id="ebay_feedbacks_run_now_container" <?php if ($feedbacks_mode != 1) echo ' style="display: none;"'; ?>>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('ebay_feedbacks_run_now'); ?>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('ebay_feedbacks_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('ebay_feedbacks_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_synchronization_other_listings" <?php if (Mage::helper('M2ePro/View_Ebay')->isSimpleMode()) : echo ' style="display: none"'; endif; ?>>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('3rd Party Listings Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="ebay_other_listings_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <?php $otherListingsMode = $this->otherListings ? $this->otherListings : 0; ?>
                            <select id="ebay_other_listings_mode" name="ebay_other_listings_mode" onchange="SynchronizationHandlerObj.changeOtherListingsMode('<?php echo Ess_M2ePro_Helper_Component_Ebay::NICK; ?>');">
                                <option value="0"<?php if ($otherListingsMode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if ($otherListingsMode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes 3rd Party Listings for eBay accounts, which have enabled Import 3rd Party Listings in their Accounts settings.<br /><br /><strong>Note: </strong>click "Synchronization Settings" for configure settings.'); ?></span>
                            </p>
                        </td>
                        <td class="value" id="ebay_other_listings_synchronization_settings_button_container" <?php if ($otherListingsMode != 1) echo ' style="display: none;"'; ?>>
                            <?php echo $this->getChildHtml('ebay_other_listings_synchronization_settings'); ?>
                        </td>
                        <td class="value">
                            <div id="ebay_other_listings_run_now_container" <?php if ($otherListingsMode != 1) echo ' style="display: none;"'; ?>>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <?php echo $this->getChildHtml('ebay_other_listings_run_now'); ?>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('ebay_other_listings_view_log'); ?>
                            &nbsp;&nbsp;
                            <?php echo $this->getChildHtml('ebay_other_listings_clear_log'); ?>
                        </td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

</form>