<div id="block_notice_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows whether Synchronization between Magento and eBay is enabled for specific functions.<br/><br/>
        You can choose to enable or disable Synchronization or trigger Synchronization manually by clicking <b>Run Now</b>.<br/><br/>
        You can also view the Synchronization Logs or clear the Logs.'
    ); ?>
</div>