<div id="block_notice_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows whether synchronization between Magento and eBay is enabled for specific functions.<br/><br/>
        You can choose to enable or disable synchronization or trigger synchronization manually by clicking <b>Run Now</b>.<br/><br/>
        You can also view the synchronization logs or clear the logs.'
    ); ?>
</div>