<div id="block_notice_amazon_template_newProduct_specifics" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Item Specifics'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Adding specific item details will attract your buyers and help them to find your items.'); ?>
</div>

<script type="text/javascript">

    Event.observe(window, 'load', function() {
        $('amazonTemplateNewProductEditTabs_specifics').observe('click', AmazonTemplateNewProductHandlerObj.checkAttributeSetSelection);
        $('amazonTemplateNewProductEditTabs_specifics').observe('click', AmazonTemplateNewProductHandlerObj.checkSpecificsReady.bind(AmazonTemplateNewProductHandlerObj));

        $('attribute_sets_confirm_button').observe('click',AmazonTemplateNewProductSpecificHandlerObj.attribute_sets_confirm.bind(AmazonTemplateNewProductHandlerObj));
        $('attribute_sets').value && AmazonTemplateNewProductSpecificHandlerObj.attribute_sets_confirm();
    });

</script>

<div class="entry-edit" id="magento_block_specific_edit_general" style="display: none;">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Specifics Configuration'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0" id="specifics_container" style="width: 100%">

            </table>

        </div>
    </div>

</div>