<div id="ebay_listing_product_sourceCategories_summary_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Magento Categories'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In the table below there is a list of Magento categories assigned to selected products. The figure in brackets shows the number of products in each category.
<br>
You can Remove a category and its products. But be aware, if you remove a product, it will be removed from all categories it is assigned to.
<br>
<b>Note:</b> If your product is assigned to more than one category, it will be added to M2E listing only once.'); ?>
</div>