<div id="ebay_listing_product_sourceCategories_summary_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Magento Categories'); ?>">
    <?php echo Mage::helper('M2ePro')->__('The quantity of chosen products in each category is shown in brackets.
<br>
If the product belongs to several categories, it is shown in each category. And if you remove the category with such product it will be subtracted from
 each category.'); ?>
</div>