<div id="block_notice_ebay_feedbacks_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Feedback'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page contains feedback received from eBay buyers and your responses to them.<br/><br/>
        You can respond to feedback that hasn\'t already been responded to by clicking the <b>Response</b> button for the order and completing the form.<br/><br/>
        <b>Note:</b> Auto-responses to feedback are sent according to the eBay Accounts > Feedback settings.'
    ); ?>
</div>