<script type="text/javascript">

</script>

<?php

$version = Mage::helper('M2ePro/Module')->getVersion();
$skipWizardLink = $this->getUrl("*/adminhtml_wizard_ebay/skip");
$startWizardLink = $this->getUrl("*/adminhtml_wizard_ebay");

?>

<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Channel'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <div>
       <?php echo Mage::helper('M2ePro')->__('Setting up settings to be able to sell on <strong>eBay</strong>.'); ?>
    </div>

    <div class="step_container_buttons">
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>
</div>