<div id="productSearchMenu_pop_up_content" style="display: none;">
    <div class="hor-scroll" style="padding-top: 15px; ">

        <div id="productSearchMenu_error_block" class="error-msg" style="display:none">
            <div style="margin: 6px 0px 6px 35px">
                <strong><?php echo Mage::helper('M2ePro')->__('There was an error during previous automatic Play ID search:'); ?></strong><br />
                <div id="productSearchMenu_error_message"></div>
            </div>
        </div>

        <div style="text-align:center; margin: 20px auto;">
            <div>
                <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchManualPrompt();"><?php echo Mage::helper('M2ePro')->__('Assign Play ID Manually'); ?></a>
                <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo Mage::helper('M2ePro')->__('Allows searching Play ID by data that will be specified on the next step.'); ?></div>
            </div>
            <div>
                <a style="font-size:140%" href="javascript:void(0);" onclick="ListingGridHandlerObj.productSearchHandler.showSearchGeneralIdAutoPrompt();"><?php echo Mage::helper('M2ePro')->__('Assign Play ID Automatically'); ?></a>
                <div style="color:#666; height:50px; margin:5px auto 10px auto;"> <?php echo Mage::helper('M2ePro')->__('Allows searching Play ID by data, that have already been specified in Listing Search settings.'); ?></div>
            </div>
        </div>

        <div id="productSearchMenu_buttons" style="text-align: right; margin: 10px 0px;">
            <?php echo $this->getChildHtml('productSearchMenu_cancel_button') ?>
        </div>

    </div>
</div>