<div id="block_notice_wizard_installation_step_otherListing" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Synchronization Set Up'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="display:none;">
    <div>
        <div class="step_container_description">
            <?php
            $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();
            echo Mage::helper('M2ePro')->__(
                'Set up Synchronization rules according to which auto and manual 3rd Party Listings Synchronization will be performed.
                <br/>
                <b>Note:</b> The 3rd Party Listings Synchronization has to be enabled in %s -> Configuration -> Synchronization to allow 3rd party listings to be imported from eBay.',
                $menuLabel
            ); ?>
        </div>
        <div class="step_container_completed">
            <span class="step_completed" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
        </div>
        <div class="step_container_incomplete">
            <span class="step_incomplete" style="display:none;"><?php echo Mage::helper('M2ePro')->__('Incomplete'); ?></span>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="step_container_buttons">
        <span class="step_process" style="display:none;"><?php echo $this->getChildHtml('process_otherListing_button'); ?></span>
    </div>
</div>

<script type="text/javascript">

    WizardHandlerObj.addStep('otherListing', 'block_notice_wizard_installation_step_otherListing');

</script>