<div id="block_notice_common_accounts" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Accounts'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Section allows you to Create, Edit and Delete the Accounts for Amazon and Rakuten.com.<br/><br/>
    <b>Note:</b> That it is required to have separate Account for each Amazon Marketplace. <br/>
     For example, if you sell Items on Amazon.co.uk, you cannot use the same M2E Pro %amazon% Account to sell Items on different European Marketplaces.<br/>
     So in order to sell Items on Amazon.es, Amazon.it etc., you need to create another M2E Pro %amazon% Accounts for Spain and Italy Marketplaces, although you can still use the same Seller ID.  <br/>
    ', Mage::helper('M2ePro/Component_Amazon')->getTitle()); ?>
</div>