<?php
    $formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data')
        ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray()
        : array();

    $key = 'other_listings_mapping_settings';
    if (isset($formData[$key])) {
        $formData[$key] = (array)json_decode($formData[$key],true);
    }

    $helper = Mage::helper('M2ePro');

    $defaults = array(
        'other_listings_synchronization' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES,
        'other_listings_mapping_mode' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO,
        'other_listings_mapping_settings' => array(),
        'other_listings_synchronization_mapped_items_mode' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES
    );
    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    Event.observe(window, 'load', function() {
        setTimeout(function() {

            $('other_listings_synchronization')
                .observe('change', EbayAccountHandlerObj.other_listings_synchronization_change)
                .simulate('change');
            $('other_listings_mapping_mode')
                .observe('change', EbayAccountHandlerObj.other_listings_mapping_mode_change)
                .simulate('change');
            $('other_listings_synchronization_mapped_items_mode')
                .observe('change', EbayAccountHandlerObj.synchronization_mapped_change)
                .simulate('change');
            $('mapping_sku_mode')
                .observe('change', EbayAccountHandlerObj.mapping_sku_mode_change)
                .simulate('change');
            $('mapping_title_mode')
                .observe('change', EbayAccountHandlerObj.mapping_title_mode_change)
                .simulate('change');

            $('ebayAccountEditTabs_listingOther').removeClassName('changed');
        }, 350);
    });

</script>

<div id="block_notice_ebay_accounts_other_listings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Edit the import, mapping and synchronization settings for <b>3rd Party Listings</b> here.<br/>
        3rd Party Listings are items that have been listed on eBay either directly or with a tool other than M2E Pro.<br/><br/>
        <b>Note:</b> Settings made here only take effect if <b>3rd Party Listings Synchronization</b> is enabled in %root_node_label% > Configuration > Synchronization.',
    Mage::helper('M2ePro/View_Ebay')->getMenuRootNodeLabel()); ?>
</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_synchronization">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="other_listings_synchronization"><?php echo Mage::helper('M2ePro')->__('Import 3rd Party Listings'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_synchronization" name="other_listings_synchronization">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Choose whether to import eBay listings that have been listed on eBay either directly or using a tool other than M2E Pro.
                                 Only active eBay listings created within the last 2 years will be imported.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="other_listings_mapping_mode_tr">
                    <td class="label">
                        <label for="other_listings_mapping_mode"><?php echo Mage::helper('M2ePro')->__('Product Mapping'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_mapping_mode" name="other_listings_mapping_mode" class="M2ePro-require-select-attribute">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_YES ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Choose whether imported eBay listings should automatically map to a product in your Magento inventory.'
                            ); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_product_mapping" <?php if ($formData['other_listings_mapping_mode'] == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Mapping Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php $mappingSettings = $formData['other_listings_mapping_settings']; ?>

                <tr class="ebay-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_sku_mode"><?php echo Mage::helper('M2ePro')->__('Custom Label (SKU)') ?>:</label>
                    </td>
                    <td class="value">

                        <?php $tempAttributeValue = isset($mappingSettings['sku']['attribute']) ? $mappingSettings['sku']['attribute'] : ''; ?>
                        <input type="hidden" name="mapping_sku_attribute" id="mapping_sku_attribute" value="<?php echo $tempAttributeValue; ?>"/>

                        <select id="mapping_sku_mode" name="mapping_sku_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product ID') ?></option>

                            <optgroup label="Magento Attributes">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value_hack="<?php echo $attribute['code']; ?>"
                                            value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE; ?>"
                                        <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE && $tempAttributeValue == $attribute['code']) : echo 'selected="selected"'; endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->__($attribute['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>

                        </select>
                      </td>
                    <td id="mapping_sku_priority_td" class="value" <?php if (!isset($mappingSettings['sku']['mode']) || $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_sku_priority" type="text" value="<?php echo isset($mappingSettings['sku']['priority']) ? (int)$mappingSettings['sku']['priority'] : Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr class="ebay-listings-mapping-settings">
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <tr class="ebay-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_title_mode"><?php echo Mage::helper('M2ePro')->__('Listing Title') ?>:</label>
                    </td>
                    <td class="value">

                        <?php $tempAttributeValue = isset($mappingSettings['title']['attribute']) ? $mappingSettings['title']['attribute'] : ''; ?>
                        <input type="hidden" name="mapping_title_attribute" id="mapping_title_attribute" value="<?php echo $tempAttributeValue; ?>"/>

                        <select id="mapping_title_mode" name="mapping_title_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product Name') ?></option>

                            <optgroup label="Magento Attributes">
                                <?php foreach ($this->attributes as $attribute): ?>
                                    <option value_hack="<?php echo $attribute['code']; ?>"
                                            value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE; ?>"
                                        <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE && $tempAttributeValue == $attribute['code']) : echo 'selected="selected"'; endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->__($attribute['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>

                        </select>
                    </td>
                    <td id="mapping_title_priority_td" class="value" <?php if (!isset($mappingSettings['title']['mode']) || $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_title_priority" type="text" value="<?php echo isset($mappingSettings['title']['priority']) ? (int)$mappingSettings['title']['priority'] : Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_product_synchronization_mapped" <?php if ($formData['other_listings_mapping_mode'] == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="other_listings_synchronization_mapped_items_mode_container">
                    <td class="label">
                        <label for="other_listings_synchronization_mapped_items_mode"><?php echo Mage::helper('M2ePro')->__('Mapped Items Synchronization'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_synchronization_mapped_items_mode" name="other_listings_synchronization_mapped_items_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES; ?>" <?php if ($formData['other_listings_synchronization_mapped_items_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_NO; ?>" <?php if ($formData['other_listings_synchronization_mapped_items_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__(
                                'Choose whether the details for 3rd Party Listings mapped to a product in your Magento inventory should change on eBay when the details have been changed in Magento.
                                Click <b>Synchronization Settings</b> to specify which details should change.<br/><br/>
                                <b>Note:</b> The first product auto-mapping runs when 3rd Party Listings Synchronization happens for the first time.
                                To run auto-mapping manually after that, go to Sell on eBay > Listings > 3rd Party.'
                            ); ?></span>
                        </p>
                    </td>
                    <td class="value" id="settings_button" style="width: auto;">
                        <?php echo $this->getChildHtml('ebay_other_listings_synchronization_settings'); ?>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php if (!empty($this->marketplaces)) { ?>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_related_store_views" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO || count($this->marketplaces) == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Related Store Views'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_ebay_accounts_related_store_view" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Related Store View'); ?>">
                <?php echo Mage::helper('M2ePro')->__(
                    'Establish connection between eBay sites and Magento Store Views for correct data synchronization.'
                ); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php $storeSwitcher = $this->getLayout()->createBlock('M2ePro/adminhtml_storeSwitcher'); ?>

                <?php foreach ($this->marketplaces as $marketplace): ?>

                    <tr>
                        <td class="label">
                            <p style="padding-top: 10px;">
                                <label><?php echo Mage::helper('M2ePro')->__($marketplace['title']); ?>: </label>
                            </p>
                        </td>
                        <td class="value">
                            <?php
                                $storeSwitcher->addData(array(
                                    'id'=> 'related_store_id_'.$marketplace['id'],
                                    'selected' => $marketplace['related_store_id']
                                ));
                                echo $storeSwitcher->toHtml();
                            ?>
                        </td>
                    </tr>

                <?php endforeach; ?>

            </table>

        </div>
    </div>

</div>

<?php } ?>