<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $helper = Mage::helper('M2ePro');

    $defaults = array(
        'other_listings_synchronization' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES,
        'other_listings_mapping_mode' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO,
        'other_listings_mapping_settings' => array(),
        'other_listings_synchronization_mapped_items_mode' => Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES
    );
    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.text.need_select_attributes_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('If Yes is chosen, you must select at least one attribute for product mapping.')); ?>';
    //-----------------------------

    Event.observe(window, 'load', function() {
        setTimeout(function() {

            $('other_listings_synchronization')
                .observe('change', EbayAccountHandlerObj.other_listings_synchronization_change)
                .simulate('change');
            $('other_listings_mapping_mode')
                .observe('change', EbayAccountHandlerObj.other_listings_mapping_mode_change)
                .simulate('change');
            $('other_listings_synchronization_mapped_items_mode')
                .observe('change', EbayAccountHandlerObj.synchronization_mapped_change)
                .simulate('change');
            $('mapping_sku_mode')
                .observe('change', EbayAccountHandlerObj.mapping_sku_mode_change)
                .simulate('change');
            $('mapping_title_mode')
                .observe('change', EbayAccountHandlerObj.mapping_title_mode_change)
                .simulate('change');

            $('ebayAccountEditTabs_listingOther').removeClassName('changed');
        }, 350);
    });

</script>

<div id="block_notice_ebay_accounts_other_listings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php
        $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

        echo Mage::helper('M2ePro')->__('The 3rd Party Listings are the items, which were listed on eBay without using M2E Pro
                extension. <br/>
                To allow importing of these listings for the current eBay Account, set Import eBay listings to <i>Yes</i>.
                Imported Listings can be found in %1$s > Manage Listings > 3rd Party Listings.
                <br/><br/>

                <b>Note:</b> The 3rd Party Listings Synchronization must be enabled in %1$s > Configuration > Synchronization.
                <br/><br/>
                To map the products of the 3rd Party Listings with existing products in Magento by Custom Label (SKU)
                or Title, set Product Mapping to <i>Yes</i> and choose appropriate attribute(s).
                A Magento product will be mapped if at least one of the chosen attributes meets the same
                value in eBay Listing as it has in Magento.
                <br/><br/>
                Mapped 3rd Party Listings can be synchronized according to the rules you can set by clicking on the Synchronization Settings button.
                <br/><br/>
                <b>Note:</b> Auto mapping action is performed only once during the first
                3rd Party Listings Synchronization. Afterwards, it can be performed manually on
                the 3rd Party Listings page (%1$s > Manage Listings > 3rd Party Listings).

                ', $menuLabel); ?></div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_synchronization">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="other_listings_synchronization"><?php echo Mage::helper('M2ePro')->__('Import 3rd Party Listings'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_synchronization" name="other_listings_synchronization">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO; ?>" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Allows importing 3rd Party Listings.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="other_listings_mapping_mode_tr">
                    <td class="label">
                        <label for="other_listings_mapping_mode"><?php echo Mage::helper('M2ePro')->__('Product Mapping'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="other_listings_mapping_mode" name="other_listings_mapping_mode" class="M2ePro-require-select-attribute">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_YES ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_YES) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO ?>" <?php if ($formData['other_listings_mapping_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_MODE_NO) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Maps eBay product with Magento product.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_product_mapping" <?php if ($formData['other_listings_mapping_mode'] == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Attributes Of Mapping eBay Items To Magento Products'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php $mappingSettings = $formData['other_listings_mapping_settings']; ?>

                <tr class="ebay-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_sku_mode"><?php echo Mage::helper('M2ePro')->__('Custom Label (SKU)') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="mapping_sku_mode" name="mapping_sku_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_PRODUCT_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE ?>" <?php if (isset($mappingSettings['sku']['mode']) && $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                      </td>
                    <td id="mapping_sku_priority_td" class="value" <?php if (!isset($mappingSettings['sku']['mode']) || $mappingSettings['sku']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_sku_priority" type="text" value="<?php echo isset($mappingSettings['sku']['priority']) ? (int)$mappingSettings['sku']['priority'] : Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_SKU_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr id="mapping_sku_attribute_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">
                        <?php $tempAttributeValue = isset($mappingSettings['sku']['attribute']) ? $mappingSettings['sku']['attribute'] : ''; ?>
                        <select name="mapping_sku_attribute">
                            <?php foreach ($this->attributes as $attribute) { ?>
                            <option value="<?php echo $attribute['code'] ?>" <?php if ($tempAttributeValue == $attribute['code']) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>

                <tr class="ebay-listings-mapping-settings">
                    <td class="value" colspan="2" style="width: auto;">
                        <hr style="border: 1px solid silver; border-bottom: none;"/>
                    </td>
                </tr>

                <tr class="ebay-listings-mapping-settings">
                    <td class="label">
                        <label for="mapping_title_mode"><?php echo Mage::helper('M2ePro')->__('Listing Title') ?>:</label>
                    </td>
                    <td class="value">
                        <select id="mapping_title_mode" name="mapping_title_mode" class="attribute-mode-select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product Name') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE ?>" <?php if (isset($mappingSettings['title']['mode']) && $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                    <td id="mapping_title_priority_td" class="value" <?php if (!isset($mappingSettings['title']['mode']) || $mappingSettings['title']['mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_MODE_NONE) echo 'style="display: none;"' ?>>
                        <?php echo Mage::helper('M2ePro')->__('Priority') ?>: <input name="mapping_title_priority" type="text" value="<?php echo isset($mappingSettings['title']['priority']) ? (int)$mappingSettings['title']['priority'] : Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPING_TITLE_DEFAULT_PRIORITY; ?>" class="input-text" style="width: 30px;" />
                    </td>
                </tr>

                <tr id="mapping_title_attribute_tr" style="display: none;">
                    <td class="label"></td>
                    <td class="value">
                        <?php $tempAttributeValue = isset($mappingSettings['title']['attribute']) ? $mappingSettings['title']['attribute'] : ''; ?>
                        <select name="mapping_title_attribute">
                            <?php foreach ($this->attributes as $attribute) { ?>
                            <option value="<?php echo $attribute['code'] ?>" <?php if ($tempAttributeValue == $attribute['code']) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']) ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_product_synchronization_mapped" <?php if ($formData['other_listings_mapping_mode'] == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="other_listings_synchronization_mapped_items_mode_container">
                    <td class="label">
                        <label for="other_listings_synchronization_mapped_items_mode"><?php echo Mage::helper('M2ePro')->__('Synchronization of Mapped Items'); ?>:</label>
                    </td>
                    <td class="value" style="width: 305px;">
                        <select id="other_listings_synchronization_mapped_items_mode" name="other_listings_synchronization_mapped_items_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES; ?>" <?php if ($formData['other_listings_synchronization_mapped_items_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_NO; ?>" <?php if ($formData['other_listings_synchronization_mapped_items_mode'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_MAPPED_SYNCHRONIZATION_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Enables / Disables synchronization of Mapped 3rd Party<br/>Listings for the current account.'); ?></span>
                        </p>
                    </td>
                    <td class="value" id="settings_button">
                        <?php echo $this->getChildHtml('ebay_other_listings_synchronization_settings'); ?>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Settings for 3rd Party Listings Synchronization.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_accounts_other_listings_related_store_views" <?php if ($formData['other_listings_synchronization'] == Ess_M2ePro_Model_Ebay_Account::OTHER_LISTINGS_SYNCHRONIZATION_NO || count($this->marketplaces) == 0) echo 'style="display:none"'; ?>>

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Related Store Views'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_ebay_accounts_related_store_view" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Related Store View'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This section displays all <i>Enabled</i> Marketplaces in eBay > Configuration > Marketplaces.
And allows you to choose Store Views the items\' information for Synchronization processes has to be taken from depending on the 3rd Party Listing Marketplaces.
<br/><br/>
<b>Note:</b> If the product doesn\'t have information in specified Store View, then all necessary data will be taken from default values of this product.
'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php $storeSwitcher = $this->getLayout()->createBlock('M2ePro/adminhtml_storeSwitcher'); ?>

                <?php foreach ($this->marketplaces as $marketplace): ?>

                    <tr>
                        <td class="label">
                            <p style="padding-top: 10px;">
                                <label><?php echo Mage::helper('M2ePro')->__($marketplace['title']); ?>: </label>
                            </p>
                        </td>
                        <td class="value">
                            <?php
                                $storeSwitcher->addData(array(
                                    'id'=> 'related_store_id_'.$marketplace['id'],
                                    'selected' => $marketplace['related_store_id']
                                ));
                                echo $storeSwitcher->toHtml();
                            ?>
                        </td>
                    </tr>

                <?php endforeach; ?>

            </table>

        </div>
    </div>

</div>