<div id="block_notice_listings_items_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains information on all Listings\' Items.<br/>
    You can search for necessary Items and manage them from their Listings: click on the icon in the Manage column on appropriate
    line to navigate to the Listing, that contains chosen product.'); ?>
</div>