<div id="block_notice_ebay_listing_other" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows eBay Accounts and Sites that have 3rd Party Listings associated with them. (3rd Party Listings are eBay Listings that haven\'t been added by M2E Pro.)<br/><br/>
        Filter by eBay user ID and eBay Site and click a line to see the Listings.<br/><br/>
        To import 3rd Party Listings, <b>Import 3rd Party Listings</b> must be enabled for an eBay Account
        in (%menu_root_node% > Accounts Settings > 3rd Party Listings) and <b>3rd Party Listings Synchronization</b>
        must be enabled in (%menu_root_node% > Synchronization).',
        Mage::helper('M2ePro/View_Ebay')->getMenuPath('configuration')
    ); ?>
</div>