<style type="text/css">
    .global_node {
        padding-bottom: 10px;
    }
</style>

<div id="block_notice_ebay_configuration_global" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Global Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'Settings are split into four categories. Descriptions for each category are below.'
    ); ?>
</div>

<div class="entry-edit" id="magento_block_ebay_configuration_global">

    <div class="fieldset">
        <div class="hor-scroll">

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getComponentsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Channels');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('eBay, Amazon, Rakuten.com, Play.com channels activation.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getSettingsUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('General');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Interface and synchronization preferences.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLogsCleaningUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Logs Clearing');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('Preferences for logs history clearing.');?></p>
            </div>

            <div class="global_node">
                <a href="<?php echo Mage::helper('M2ePro/View_Configuration')->getLicenseUrl(); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('License');?></a>
                <p><?php echo Mage::helper('M2ePro')->__('M2E Pro activation.');?></p>
            </div>

        </div>
    </div>

</div>