<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_configuration_settings')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_configuration_settings/save')
    )); ?>);

    Event.observe(window, 'load', function() {
        SettingsHandlerObj = new ConfigurationSettingsHandler();

        ControlPanelHandlerObj = new ControlPanelHandler();

        //------------------------------

        $('force_qty_mode').simulate('change');

        //------------------------------

        configEditForm = new varienForm('config_edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style>
    .columns .form-list td.value {
        width: 280px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <!-- General   -->
    <div class="entry-edit" id="magento_block_configuration_interface_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Interface'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_configuration_interface" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Interface'); ?>">
                    <?php echo Mage::helper('M2ePro')->__('Set M2E interface preferences, then click <b>Save Config</b>.'); ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Products Thumbnails'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="products_show_thumbnails" name="products_show_thumbnails" class="required-entry">
                                <option value="0" <?php if (!$this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                                <option value="1" <?php if ($this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose whether you want to see thumbnail images for products on the Add Products and View Listing pages.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Help Blocks'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="block_notices_show" name="block_notices_show" class="required-entry">
                                <option value="0" <?php if (!$this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                                <option value="1" <?php if ($this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose whether you want the help at the top of each M2E Pro page to be available.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('restore_block_notices'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Restores manually closed help blocks.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>
    <!-- End General   -->

    <!-- Qty Settings  -->
    <div class="entry-edit" id="magento_block_configuration_settings_qty">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_configuration_qty" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Quantity'); ?>">
                    <?php echo Mage::helper('M2ePro')->__(
                        'Choose whether M2E Pro should list products on external channels even if there is no stock or stock is negative.
                        <b>Disallow</b> is the recommended setting if you are selling on eBay.'
                    ); ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                    <tr>
                        <td class="label">
                            <label for="force_qty_mode"><?php echo Mage::helper('M2ePro')->__('Manage Stock "No", Backorders'); ?>: </label>
                        </td>
                        <td class="value" colspan="2">
                            <select id="force_qty_mode" name="force_qty_mode" onchange="SettingsHandlerObj.changeForceQtyMode();">
                                <option value="0"<?php if ($this->forceQtyMode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disallow'); ?></option>
                                <option value="1"<?php if ($this->forceQtyMode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Allow'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__(
                                    'Choose whether M2E Pro should list products on external channels when Manage Stock = \'No\' or Backorders is enabled.
                                    <b>Disallow</b> is the recommended setting if you are selling on eBay.'
                                ); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="force_qty_value_tr">
                        <td class="label">
                            <label for="force_qty_value"><?php echo Mage::helper('M2ePro')->__('QTY To Be Listed'); ?>: </label>
                        </td>
                        <td class="value" colspan="2">
                            <input id="force_qty_value" name="force_qty_value" value="<?php echo $this->forceQtyValue; ?>" type="text" class="M2ePro-required-when-visible input-text validate-greater-than-zero" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Set a number to list, e.g. if you have Manage Stock "No" in Magento Product and set this value to 10, 10 will be sent as available quantity to the channel.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>
    <!-- End Qty Settings   -->

    <!-- Advanced Settings  -->
    <div class="entry-edit" id="magento_block_configuration_settings_advanced">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Global Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_configuration_advanced_settings" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Global Synchronization'); ?>">
                    <?php echo Mage::helper('M2ePro')->__(
                        'If you change product price or quantity via direct database access (eg using import/export tools or custom scripts), enable this option.<br/><br/>
                        <b>Warning:</b> Tracking direct database changes is resource-intensive and may affect the performance of your Magento site and synchronization with channels.
                        Only choose \'Yes\' if you are certain you need this functionality.'
                    ); ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                        <tr>
                            <td class="label">
                                <label for="inspector_mode"><?php echo Mage::helper('M2ePro')->__('Track Direct Database Changes'); ?>: </label>
                            </td>
                            <td class="value" colspan="2">
                                <select id="inspector_mode" name="inspector_mode">
                                    <option value="0"<?php if ($this->inspectorMode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if ($this->inspectorMode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__("<b>Note:</b> Enable this option if you really need it, as it is very resource and time consuming and may affect synchronization performance."); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>
    <!-- End Advanced Settings   -->

</form>