<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_configuration_settings')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_configuration_settings/save')
    )); ?>);

    Event.observe(window, 'load', function() {
        configEditForm = new varienForm('config_edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style>
    .columns .form-list td.value {
        width: 280px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <!-- General   -->
    <div class="entry-edit" id="magento_block_configuration_interface_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Interface'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_configuration_interface" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Interface'); ?>">
                    <?php echo Mage::helper('M2ePro')->__('Set visual interface preferences and Save configuration.'); ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Products Thumbnails'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="products_show_thumbnails" name="products_show_thumbnails" class="required-entry">
                                <option value="0" <?php if (!$this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                                <option value="1" <?php if ($this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Shows / does not show products thumbnails on Add Products and View Listing pages.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Help Blocks'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="block_notices_show" name="block_notices_show" class="required-entry">
                                <option value="0" <?php if (!$this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                                <option value="1" <?php if ($this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Shows / does not show Help blocks.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <?php echo $this->getChildHtml('restore_block_notices'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Restores manually closed Help blocks.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>
    <!-- End General   -->

    <!-- Advanced Settings  -->
    <div class="entry-edit" id="magento_block_configuration_settings_advanced">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Global Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_configuration_advanced_settings" class="block_notices_module no-icon" title="<?php echo Mage::helper('M2ePro')->__('Global'); ?>">
                    <?php echo Mage::helper('M2ePro')->__('Has to be enabled if product price and quantity changes are made directly to database.  Data update depends on the number of products and can be fully completed after several synchronization cycles finish.
                    <br><br>
                    <b>Note:</b> Enable this option if you really need it, as it is very resource and time consuming and may affect synchronization performance.'); ?>
                </div>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                        <tr>
                            <td class="label">
                                <label for="inspector_mode"><?php echo Mage::helper('M2ePro')->__('Track Direct Database Changes'); ?>: </label>
                            </td>
                            <td class="value" colspan="2">
                                <select id="inspector_mode" name="inspector_mode">
                                    <option value="0"<?php if ($this->inspectorMode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if ($this->inspectorMode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__("<b>Note:</b> Enable this option if you really need it, as it is very resource and time consuming and may affect synchronization performance."); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>
    <!-- End Advanced Settings   -->

</form>