<?php  if (count($this->sellingFormatTemplates) > 1 || count($this->synchronizationsTemplates) > 1 || !$this->sellingFormatTemplatesDropDown || !$this->synchronizationsTemplatesDropDown): ?>

    <p class="<?php echo Mage::helper('M2ePro/Magento')->isGoEdition() ? '' : 'switcher'; ?>">

        <?php if (count($this->sellingFormatTemplates) > 1 || !$this->sellingFormatTemplatesDropDown): ?>
            <label for="amazon_selling_format_template_switcher"><?php echo Mage::helper('M2ePro')->__('Selling Format Policy'); ?>:</label>
            <?php if ($this->sellingFormatTemplatesDropDown): ?>
                <select id="amazon_selling_format_template_switcher" name="amazon_selling_format_template_switcher" style="min-width: 100px; width: 130px;" onchange="return switchTemplate(this,'<?php echo $this->sellingFormatTemplateUrl; ?>','filter_amazon_selling_format_template');">
                    <option value="0" <?php if ($this->selectedSellingFormatTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Policies') ?></option>
                    <?php foreach ($this->sellingFormatTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedSellingFormatTemplate == $id) echo 'selected="selected"'; ?>><?php echo $title; ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input id="amazon_selling_format_template_autocomplete"
                       type="text"
                       class="input-text"
                       name="amazon_selling_format_template_autocomplete"
                       selected_id=""
                       style="width: 130px; font-size: 10px"
                       onblur="if (this.value.trim().length == 0) {
                           this.value = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Policy Name Here...')); ?>';
                           this.style.color = 'gray';
                       }"
                       onfocus="if (this.value == '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Policy Name Here...')); ?>') {
                           this.value = '';
                           this.style.color = '';
                       }" />
            <?php endif; ?>
        <?php endif; ?>

        <?php if (count($this->synchronizationsTemplates) > 1 || !$this->synchronizationsTemplatesDropDown): ?>
            <label for="amazon_synchronization_template_switcher" style="margin-left: 30px;"><?php echo Mage::helper('M2ePro')->__('Synchronization Policy') ?>:</label>
            <?php if ($this->synchronizationsTemplatesDropDown): ?>
                <select id="amazon_synchronization_template_switcher" name="amazon_synchronization_template_switcher" style="min-width: 100px; width: 130px;" onchange="return switchTemplate(this,'<?php echo $this->synchronizationTemplateUrl; ?>','filter_amazon_synchronization_template');">
                    <option value="0" <?php if ($this->selectedSynchronizationTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Policies') ?></option>
                    <?php foreach ($this->synchronizationsTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedSynchronizationTemplate == $id) echo 'selected="selected"'; ?>><?php echo $title; ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input id="amazon_synchronization_template_autocomplete"
                       type="text"
                       class="input-text"
                       name="amazon_synchronization_template_autocomplete"
                       selected_id=""
                       style="width: 130px; font-size: 10px"
                       onblur="if (this.value.trim().length == 0) {
                           this.value = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Policy Name Here...')); ?>';
                           this.style.color = 'gray';
                       }"
                       onfocus="if (this.value == '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Type Policy Name Here...')); ?>') {
                           this.value = '';
                           this.style.color = '';
                       }" />
            <?php endif; ?>
        <?php endif; ?>

    </p>

    <script type="text/javascript">

        switchTemplate = function(obj,url,urlParamName)
        {
            if (obj.value == 0) {
                setLocation(url);
            } else {
                setLocation(url+urlParamName+'/'+obj.value+'/');
            }
        }

        autoCompleteHandler = new AutoComplete();

        <?php if (!$this->sellingFormatTemplatesDropDown): ?>
            autoCompleteHandler.bind(
                'amazon_selling_format_template_autocomplete',
                "<?php echo $this->getUrl('*/adminhtml_common_general/searchAutocomplete', array(
                    'component' => Ess_M2ePro_Helper_Component_Amazon::NICK,
                    'model'     => 'Template_SellingFormat'
                )) ?>",
                "<?php echo $this->selectedSellingFormatTemplate; ?>",
                "<?php echo $this->selectedSellingFormatTemplateValue; ?>",
                function (id) {
                    switchTemplate({value: id}, '<?php echo $this->sellingFormatTemplateUrl; ?>', 'filter_amazon_selling_format_template');
                }
            );
            $('amazon_selling_format_template_autocomplete').simulate('blur');
        <?php endif; ?>

        <?php if (!$this->synchronizationsTemplatesDropDown): ?>
            autoCompleteHandler.bind(
                'amazon_synchronization_template_autocomplete',
                "<?php echo $this->getUrl('*/adminhtml_common_general/searchAutocomplete', array(
                    'component' => Ess_M2ePro_Helper_Component_Amazon::NICK,
                    'model'     => 'Template_Synchronization'
                )) ?>",
                "<?php echo $this->selectedSynchronizationTemplate; ?>",
                "<?php echo $this->selectedSynchronizationTemplateValue; ?>",
                function (id) {
                    switchTemplate({value: id}, '<?php echo $this->synchronizationTemplateUrl; ?>', 'filter_amazon_synchronization_template');
                }
            );
            $('amazon_synchronization_template_autocomplete').simulate('blur');
        <?php endif; ?>

    </script>

<?php endif; ?>