<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('New SKU Template (Beta)'); ?>">
    <?php
    echo Mage::helper('M2ePro')->__('These type of templates is used for creation of new products on Rakuten.com.
        <ul class="list">
        <li>to create a new template, click on <i>Add New SKU Template</i>;</li>
        <li>to assign one of the existing templates to products click on <i>Assing To This Template</i> link.</li>
        </ul>
        <b>Note:</b> Attribute Sets of New ASIN Template must include all Attribute Sets of current M2E Listing to be assigned.');
    ?>
</div>