<div id="block_notice_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Page contains all created Listings. <br/><br/>

    On this page you can quickly navigate to the required Listing, perform different actions on separate Listing via using actions dropdown menu in
    <strong>Actions</strong> grid column <br/> or perform Actions on Listings in bulk via using mass <strong>Action</strong> dropdown menu located in the right corner above the grid. <br/><br/>

    You can use Policies filters to sort Listings by Policies that they use in their settings, in case you use more than one Policy.
    '); ?>
</div>