<div id="block_notice_play_template_selling_format" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selling Format Policy'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Selling Format Policy contains Price-Related data and Quantity for the Items, which will be Listed on Play.com.<br/><br/>
    Next to each Price Options Dropdown there is a box for Price Change. Price Change is a value you want the Magento Price to be modified while Listing on Play.com.<br/><br/>
    <b>Examples:</b><br/>

    <ul class="list">
        <li>If you want the Price on Play.com to be greater by 15% than the Price in Magento, you should set +15% in the Price Change field.<br/>
        <i>Play.com Price = Magento Price + Magento Price * 0.15</i></li>
        <li>If you want the Price on Play.com to be less by 10 Currency units than the Price in Magento, you should set -10 in the Price Change field.<br/>
        <i>Play.com Price = Magento Price - 10</i></li>
        <li>If you want the Price on Play.com to be multiplied by coefficient 1.2, you should set 1.2 in the Price Change field.<br/>
        <i>Play.com Price = Magento Price * 1.2.</i></li>
    </ul>

    <b>Note:</b> If the Special Price is chosen in the <i class="underline">Price</i> Option, but it is not set in Magento Product Settings or it is set but it has already expired, the Product Price is used instead.
    <br/><br/>
    <b>Note:</b> Attributes must contain only Numeric Values.'); ?>
</div>

<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data')->toArray() : array();

$default = array(
    'title' => '',

    'qty_mode' => Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_PRODUCT,
    'qty_custom_value' => 1,
    'qty_custom_attribute' => '',
    'qty_percentage' => 100,
    'qty_modification_mode' => Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MODIFICATION_MODE_ON,
    'qty_min_posted_value' => Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MIN_POSTED_DEFAULT_VALUE,
    'qty_max_posted_value' => Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MAX_POSTED_DEFAULT_VALUE,

    'price_gbr_mode' => Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT,
    'price_gbr_coefficient' => '',
    'price_gbr_custom_attribute' => '',

    'price_euro_mode' => Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT,
    'price_euro_coefficient' => '',
    'price_euro_custom_attribute' => '',

    'price_variation_mode' => Ess_M2ePro_Model_Play_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT,
);

$formData = array_merge($default, $formData);

/** @var Ess_M2ePro_Helper_Magento_Attribute $magentoAttributeHelper */
$magentoAttributeHelper = Mage::helper('M2ePro/Magento_Attribute');

$attributesByInputTypes = array(
    'text' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text')),
    'text_select' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text', 'select')),
    'text_price' => $magentoAttributeHelper->filterByInputTypes($this->attributes, array('text', 'price')),
);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Template_SellingFormat'); ?>,
        'Ess_M2ePro_Model_Template_SellingFormat'
    );

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Play_Template_SellingFormat'); ?>,
        'Ess_M2ePro_Model_Play_Template_SellingFormat'
    );

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Play'); ?>,
        'Ess_M2ePro_Helper_Component_Play'
    );

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Block_Adminhtml_Common_Play_Template_SellingFormat_Edit_Form'); ?>,
        'Ess_M2ePro_Block_Adminhtml_Common_Play_Template_SellingFormat_Edit_Form'
    );

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit'    => $this->getUrl('M2ePro/adminhtml_common_play_template_sellingFormat/save', array('id' => $this->getRequest()->getParam('id'))),
        'formSubmitNew' => $this->getUrl('M2ePro/adminhtml_common_play_template_sellingFormat/save'),
        'deleteAction'  => $this->getUrl('M2ePro/adminhtml_common_template_sellingFormat/delete', array('id' => $this->getRequest()->getParam('id')))
    )); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'QTY' => Mage::helper('M2ePro')->__('QTY'),

        'Product Price for selling in UK.' => Mage::helper('M2ePro')->__('Product Price for selling in UK.'),
        'Product Price for selling in Europe.' => Mage::helper('M2ePro')->__('Product Price for selling in Europe.'),
        'The Price of Products in Play.com Listing(s).<br/><b>Note:</b> The Final Price is only used for Simple Products.' => Mage::helper('M2ePro')->__('The Price of Products in Play.com Listing(s).<br/><b>Note:</b> The Final Price is only used for Simple Products.'),

        'Add Selling Format Policy.' => Mage::helper('M2ePro')->__('Add Selling Format Policy.'),
        'The specified Title is already used for other Policy. Policy Title must be unique.' => Mage::helper('M2ePro')->__('The specified Title is already used for other Policy. Policy Title must be unique.'),
        'You should select Attribute Sets first and press Confirm Button.' => Mage::helper('M2ePro')->__('You should select Attribute Sets first and press Confirm Button.'),
        'Coefficient is not valid.' => Mage::helper('M2ePro')->__('Coefficient is not valid.'),

        'Wrong value. Only integer numbers.' => Mage::helper('M2ePro')->__('Wrong value. Only integer numbers.')
    )); ?>);

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    M2ePro.formData.qty_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_mode']); ?>';
    M2ePro.formData.qty_modification_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_modification_mode']); ?>';
    M2ePro.formData.qty_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_custom_attribute']); ?>';

    // virtual attribute for QTY_FIXED replacement
    <?php if ($formData['qty_mode'] == Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_PRODUCT_FIXED) { ?>

        <?php $formData['qty_mode'] = Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_ATTRIBUTE; ?>
        M2ePro.formData.qty_mode = '<?php echo Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_ATTRIBUTE; ?>';

        <?php $formData['qty_custom_attribute'] = Ess_M2ePro_Block_Adminhtml_Common_Play_Template_SellingFormat_Edit_Form::QTY_MODE_PRODUCT_FIXED_VIRTUAL_ATTRIBUTE_VALUE; ?>
        M2ePro.formData.qty_custom_attribute = '<?php echo Ess_M2ePro_Block_Adminhtml_Common_Play_Template_SellingFormat_Edit_Form::QTY_MODE_PRODUCT_FIXED_VIRTUAL_ATTRIBUTE_VALUE; ?>';

    <?php } ?>

    M2ePro.formData.price_gbr_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['price_gbr_custom_attribute']); ?>';
    M2ePro.formData.price_euro_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['price_euro_custom_attribute']); ?>';

    Event.observe(window, 'load', function() {

        PlayTemplateSellingFormatHandlerObj = new CommonPlayTemplateSellingFormatHandler();
        PlayTemplateSellingFormatHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Play_Template_SellingFormat'); ?>');

        $('qty_mode')
            .observe('change', PlayTemplateSellingFormatHandlerObj.qty_mode_change)
            .simulate('change');

        $('qty_modification_mode')
            .observe('change', PlayTemplateSellingFormatHandlerObj.qtyPostedMode_change)
            .simulate('change');

        $('price_gbr_mode')
            .observe('change', PlayTemplateSellingFormatHandlerObj.price_gbr_mode_change)
            .simulate('change');

        $('price_euro_mode')
            .observe('change', PlayTemplateSellingFormatHandlerObj.price_euro_mode_change)
            .simulate('change');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style type="text/css">
    .coef {
        padding-left: 5px !important;
        padding-top: 5px !important;
    }
    .coef input {
        text-align: right;
        width: 36px;
    }
    .form-list td.label {
        width: 275px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

<div class="entry-edit" id="magento_block_play_template_selling_format_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-price-tpl-title"/>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short meaningful Policy Title for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_play_template_selling_format_qty">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr class="requirie-attribute-set">
                    <td class="label">
                        <label for="qty_mode"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input type="hidden" id="qty_custom_attribute" name="qty_custom_attribute" value="<?php echo $formData['qty_custom_attribute']; ?>"/>

                        <select id="qty_mode" name="qty_mode">
                            <option id="qty_mode_product" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_PRODUCT == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Product Quantity'); ?></option>
                            <option id="qty_mode_single" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_SINGLE; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_SINGLE == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Single Item'); ?></option>
                            <option id="qty_mode_cv" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_NUMBER; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_NUMBER == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>

                            <optgroup label="Magento Attribute">
                                <?php foreach($attributesByInputTypes['text'] as $attribute) : ?>
                                    <option attribute_code="<?php echo $attribute['code']; ?>" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_ATTRIBUTE; ?>" <?php if ($formData['qty_mode'] == Ess_M2ePro_Model_Template_SellingFormat::QTY_MODE_ATTRIBUTE && $attribute['code'] == $formData['qty_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Product Quantity for Play.com Listing(s).'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="qty_custom_value_tr" style="display: none;">
                    <td class="label">
                        <label for="qty_custom_value"><?php echo Mage::helper('M2ePro')->__('Quantity Value'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="qty_custom_value" name="qty_custom_value" value="<?php echo $this->escapeHtml($formData['qty_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible validate-digits" />
                    </td>
                </tr>

                <tr id="qty_percentage_tr" style="display: none;">
                    <td class="label">
                        <label for="qty_percentage"><?php echo Mage::helper('M2ePro')->__('Quantity Percentage'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_percentage" name="qty_percentage" class="required-entry">
                            <?php for ($i = 100; $i >= 5; $i -= 5) : ?>
                                <option value="<?php echo $i; ?>" <?php if ($formData['qty_percentage'] == $i) : echo ' selected="selected"'; endif; ?>><?php echo $i; ?> %</option>
                            <?php endfor; ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Sets the percentage for calculation of Items number to be Listed on Play.com basing on Product Quantity or Magento Attribute.
E.g., if QTY percentage is set to 10% and Product Quantity is 100, the Quantity to be Listed on Play.com will be calculated as <br/> 100 *10%  = 10.
'); ?></span>
                        </p>
                    </td>
                </tr>

                <!-- Max Posted QTY-->
                <tr id="qty_modification_mode_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Conditional Quantity'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="qty_modification_mode" name="qty_modification_mode" class="required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MODIFICATION_MODE_OFF; ?>" <?php if ($formData['qty_modification_mode'] == Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MODIFICATION_MODE_OFF): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MODIFICATION_MODE_ON; ?>" <?php if ($formData['qty_modification_mode'] == Ess_M2ePro_Model_Play_Template_SellingFormat::QTY_MODIFICATION_MODE_ON): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('<i>Enables</i> to set the Quantity that will be sent on Play.com.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="qty_min_posted_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Minimum Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="qty_min_posted_value_td" class="value" style="width: auto;">
                        <input id="qty_min_posted_value" name="qty_min_posted_value" value="<?php echo $this->escapeHtml($formData['qty_min_posted_value']); ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If you have 2 pieces in Stock but set a min QTY to be Listed of 5, Item will not be Listed on Play.com.
Otherwise, the Item will be Listed with Quantity according to the Settings in the Selling Format Policy.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="qty_max_posted_value_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Maximum Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="qty_max_posted_value_td" class="value" style="width: auto;">
                        <input id="qty_max_posted_value" name="qty_max_posted_value" value="<?php echo $this->escapeHtml($formData['qty_max_posted_value']); ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If you have 5 pieces in Stock but set a max QTY of 2 to be Listed, a QTY of 2 will be Listed on Play.com.<br/>
                                                                         If you have 1 piece in Stock but max QTY is set to 3, only 1 will be Listed on Play.com.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_play_template_selling_format_price">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Price'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_play_template_selling_format_shipping" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Price'); ?>">
                <?php echo Mage::helper('M2ePro')->__('You are required to set both prices for the UK and Europe delivery regions.
                <br/>Depending on Delivery Region, chosen in Listing Settings necessary Price will be used for the Items you list.'); ?>
            </div>

            <table id="price_table" cellspacing="0" class="form-list">

                <tr>
                    <td class="label">
                        <label for="price_gbr_mode"><?php echo Mage::helper('M2ePro')->__('Price, GBP'); ?>:</label>
                    </td>
                    <td class="value">
                        <input type="hidden" id="price_gbr_custom_attribute" name="price_gbr_custom_attribute" value="<?php echo $formData['price_gbr_custom_attribute']; ?>"/>

                        <select id="price_gbr_mode" name="price_gbr_mode" class="select-main required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT == $formData['price_gbr_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::PRICE_SPECIAL == $formData['price_gbr_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>

                            <optgroup label="Magento Attribute">
                                <?php foreach($attributesByInputTypes['text_price'] as $attribute) : ?>
                                    <option attribute_code="<?php echo $attribute['code']; ?>" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if ($formData['price_gbr_mode'] == Ess_M2ePro_Model_Template_SellingFormat::PRICE_ATTRIBUTE && $attribute['code'] == $formData['price_gbr_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span id="price_gbr_note"></span>
                        </p>
                    </td>
                    <td id="price_gbr_coefficient_td" class="coef">
                        <div style="font-size: 11px; float: right; padding-left: 10px;">
                            <img src="<?php echo $this->getSkinUrl('M2ePro/images/note_cell_bg.gif'); ?>" />
                            <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or Currency rate (1.44)'); ?>.</span>
                        </div>
                        <input id="price_gbr_coefficient" name="price_gbr_coefficient" value="<?php echo $this->escapeHtml($formData['price_gbr_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="price_euro_mode"><?php echo Mage::helper('M2ePro')->__('Price, EUR'); ?>:</label>
                    </td>
                    <td class="value">
                        <input type="hidden" id="price_euro_custom_attribute" name="price_euro_custom_attribute" value="<?php echo $formData['price_euro_custom_attribute']; ?>"/>

                        <select id="price_euro_mode" name="price_euro_mode" class="select-main required-entry">
                            <option value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::PRICE_PRODUCT == $formData['price_euro_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Template_SellingFormat::PRICE_SPECIAL == $formData['price_euro_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>

                            <optgroup label="Magento Attribute">
                                <?php foreach($attributesByInputTypes['text_price'] as $attribute) : ?>
                                    <option attribute_code="<?php echo $attribute['code']; ?>" value="<?php echo Ess_M2ePro_Model_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if ($formData['price_euro_mode'] == Ess_M2ePro_Model_Template_SellingFormat::PRICE_ATTRIBUTE && $attribute['code'] == $formData['price_euro_custom_attribute']): ?>selected="selected"<?php endif; ?>>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        </select>
                        <p class="note">
                            <span id="price_euro_note"></span>
                        </p>
                    </td>
                    <td id="price_euro_coefficient_td" class="coef">
                        <div style="font-size: 11px; float: right; padding-left: 10px;">
                            <img src="<?php echo $this->getSkinUrl('M2ePro/images/note_cell_bg.gif'); ?>" />
                            <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or Currency rate (1.44)'); ?>.</span>
                        </div>
                        <input id="price_euro_coefficient" name="price_euro_coefficient" value="<?php echo $this->escapeHtml($formData['price_euro_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="price_variation_mode"><?php echo Mage::helper('M2ePro')->__('Variation Price Source'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="price_variation_mode" name="price_variation_mode" class="select-main">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT; ?>" <?php if (Ess_M2ePro_Model_Play_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Main Product'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN; ?>" <?php if (Ess_M2ePro_Model_Play_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Associated Products'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Determines where the Price for Configurable and Bundle Products Options should be taken from.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

</form>
