<div id="block_notice_ebay_listing_search_help" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This Page shows all Products Listed using M2E Pro Listings or added as a 3rd Party Listing.<br/><br/>
        Use the filters to find the Product you want to manage. If an eBay Item ID is available, clicking it will take you to the Listing on eBay.
        Clicking the arrows icon in the Manage Column will take you to the M2E Pro Listing\'s Products Page.'
    ); ?>
</div>