<style>
    .list {
        margin: 10px 0px !important;
        padding-left: 30px !important;
        list-style: disc outside;
    }
</style>
<div id="switch_to_parent_popup" style="display: none;">

    <div style="margin-top: 10px;">
        <?php echo Mage::helper('M2ePro')->__(
            'M2E Pro is able to work with Magento Variational Products in two different Modes:
            <ul class="list">
                <li>Selling Magento Variational Product as an Amazon Product with Parent/Child relation;</li>
                <li>Selling certain Variation of Magento Product as Individual Amazon Product.</li>
            </ul>

            You can read more about those two Modes in M2E Pro <a href="http://docs.m2epro.com/LINK_ANCHOR">documentation</a>. <br/>
            This Product is now being treated as Individual Amazon Product, do you want to switch to Parent/Child Mode? <br/><br/>'
        ); ?>
    </div>

    <div style="margin-left: 10px; float: left;">
        <input id="switch_to_parent_remember_checkbox" type="checkbox">
        &nbsp;&nbsp;
        <label for="switch_to_parent_remember_checkbox"><?php echo Mage::helper('M2ePro')->__('Remember my choice') ?></label>
    </div>

    <div style="float: right;">
        <?php echo $this->getChildHtml('yes_btn'); ?>
        &nbsp;&nbsp;
        <?php echo $this->getChildHtml('no_btn'); ?>
    </div>

</div>