<div id="block_notice_settings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains global settings of M2E Pro and allows you to manage them in your opinion.'); ?>
</div>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';

    M2ePro.text.component_not_selected = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should enable at least one component.')); ?>';
    M2ePro.text.default_component_disabled = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Default component should be enabled.')); ?>';

    Event.observe(window, 'load', function() {
        SettingsHandlerObj = new SettingsHandler();
        SettingsHandlerObj.setConstants('<?php echo $this->getComponentConstants(); ?>');

        $('component_ebay_mode')
            .observe('change', SettingsHandlerObj.component_mode_change);
        $('component_amazon_mode')
            .observe('change', SettingsHandlerObj.component_mode_change);
        $('component_buy_mode')
            .observe('change', SettingsHandlerObj.component_mode_change);
        $('component_play_mode')
            .observe('change', SettingsHandlerObj.component_mode_change);

        SettingsHandlerObj.component_mode_change();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_settings_components" <?php if ($this->components_allowed_count < 2) echo 'style="display: none;"'; ?>>

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Channel Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <?php if ($this->component_ebay_allowed) { ?>
                            <tr>
                                <td class="label">
                                    <label><?php echo Ess_M2ePro_Helper_Component_Ebay::TITLE; ?>: </label>
                                </td>
                                <td class="value">
                                    <select id="component_ebay_mode" name="component_ebay_mode" class="M2ePro-component-mode">
                                        <option value="0" <?php if (!$this->component_ebay_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                        <option value="1" <?php if ($this->component_ebay_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('eBay channel status.') ?></span>
                                    </p>
                                </td>
                            </tr>
                        <?php } ?>

                        <?php if ($this->component_amazon_allowed) { ?>
                            <tr>
                                <td class="label">
                                    <label><?php echo Ess_M2ePro_Helper_Component_Amazon::TITLE; ?>: </label>
                                </td>
                                <td class="value">
                                    <select id="component_amazon_mode" name="component_amazon_mode" class="M2ePro-component-mode">
                                        <option value="0" <?php if (!$this->component_amazon_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                        <option value="1" <?php if ($this->component_amazon_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Amazon channel status.') ?></span>
                                    </p>
                                </td>
                            </tr>
                        <?php } ?>

                        <?php if ($this->component_group_rakuten_allowed) { ?>

                        <tr>
                            <td class="value">
                                <h4><label><?php echo Mage::helper('M2ePro')->__('Rakuten'); ?>: </label></h4>
                            </td>
                        </tr>

                        <?php } ?>

                    </tbody>

                </table>

                <?php if ($this->component_group_rakuten_allowed) { ?>

                <div class="custom-options" style="width: 600px; margin-top: -20px;">
                <div class="option-box" style="padding-left: 50px;">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <?php if ($this->component_buy_allowed) { ?>
                            <tr>
                                <td class="label">
                                    <label><?php echo Ess_M2ePro_Helper_Component_Buy::TITLE; ?>: </label>
                                </td>
                                <td class="value">
                                    <select id="component_buy_mode" name="component_buy_mode" class="M2ePro-component-mode">
                                        <option value="0" <?php if (!$this->component_buy_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                        <option value="1" <?php if ($this->component_buy_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Rakuten.com channel status.') ?></span>
                                    </p>
                                </td>
                            </tr>
                        <?php } ?>

                        <?php if ($this->component_play_allowed) { ?>
                            <tr>
                                <td class="label">
                                    <label><?php echo Ess_M2ePro_Helper_Component_Play::TITLE; ?>: </label>
                                </td>
                                <td class="value">
                                    <select id="component_play_mode" name="component_play_mode" class="M2ePro-component-mode">
                                        <option value="0" <?php if (!$this->component_play_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled') ?></option>
                                        <option value="1" <?php if ($this->component_play_mode) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled') ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Play.com channel status.') ?></span>
                                    </p>
                                </td>
                            </tr>
                        <?php } ?>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Rakuten.de'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="component_rde_mode" name="component_rde_mode" disabled="disabled" class="M2ePro-component-mode">
                                    <option value="0"><?php echo Mage::helper('M2ePro')->__('Disabled - Coming Soon...') ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Rakuten.de channel status.') ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

                </div>
                </div>

                <?php } ?>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                    <tr id="component_default_tr" style="display: none;">
                        <td class="label">
                            <label for="component_default"><?php echo Mage::helper('M2ePro')->__('Default Channel'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="component_default" name="component_default">
                                <option value="<?php echo Ess_M2ePro_Helper_Component_Ebay::NICK; ?>" <?php if ($this->component_default == Ess_M2ePro_Helper_Component_Ebay::NICK) echo 'selected="selected"'; ?>><?php echo Ess_M2ePro_Helper_Component_Ebay::TITLE; ?></option>
                                <option value="<?php echo Ess_M2ePro_Helper_Component_Amazon::NICK; ?>" <?php if ($this->component_default == Ess_M2ePro_Helper_Component_Amazon::NICK) echo 'selected="selected"'; ?>><?php echo Ess_M2ePro_Helper_Component_Amazon::TITLE; ?></option>
                                <option value="<?php echo Ess_M2ePro_Helper_Component_Buy::NICK; ?>" <?php if ($this->component_default == Ess_M2ePro_Helper_Component_Buy::NICK) echo 'selected="selected"'; ?>><?php echo Ess_M2ePro_Helper_Component_Buy::TITLE; ?></option>
                                <option value="<?php echo Ess_M2ePro_Helper_Component_Play::NICK; ?>" <?php if ($this->component_default == Ess_M2ePro_Helper_Component_Play::NICK) echo 'selected="selected"'; ?>><?php echo Ess_M2ePro_Helper_Component_Play::TITLE; ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The tab of which channel must be opened by default.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    </tbody>

                </table>

                <input type="hidden" name="validate_selected_components" value="" class="M2aPro-require-select-component" />
                <input type="hidden" name="validate_default_component" value="" class="M2aPro-check-default-component" />

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_settings_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Interface Settings'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Products Thumbnails'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="products_show_thumbnails" name="products_show_thumbnails" class="required-entry">
                                    <option value="0" <?php if (!$this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Hide'); ?></option>
                                    <option value="1" <?php if ($this->products_show_thumbnails): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Shows / Hides products thumbnails on Add Products and View Listing pages.'); ?></span>
                                </p>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Help Blocks'); ?>: </label>
                            </td>
                            <td class="value">
                                <select id="block_notices_show" name="block_notices_show" class="required-entry">
                                    <option value="0" <?php if (!$this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Hide'); ?></option>
                                    <option value="1" <?php if ($this->block_notices_show): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Shows / Hides all Help blocks.'); ?></span>
                                </p>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <?php echo $this->getChildHtml('restore_block_notices'); ?>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Restores all manually closed Help blocks.'); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_settings_notifications">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Notifications'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tbody>

                        <tr id="negative_feedbacks_row">
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Negative Feedbacks'); ?>: </label>
                            </td>
                            <td class="value">
                                <select name="feedbacks_notification_mode" class="required-entry">
                                    <option value="0" <?php if (!$this->feedbacks_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1" <?php if ($this->feedbacks_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Notifies when a new negative feedback was received.'); ?></span>
                                </p>
                            </td>
                        </tr>

                        <?php if ((bool)(int)Mage::helper('M2ePro/Module')->getConfig()->getGroupValue('/messages/', 'mode')): ?>

                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('M2ePro')->__('My Messages'); ?>: </label>
                                </td>
                                <td class="value">
                                    <select name="messages_notification_mode" class="required-entry">
                                        <option value="0" <?php if (!$this->messages_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                        <option value="1" <?php if ($this->messages_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Notifies when new messages were received during synchronization.'); ?></span>
                                    </p>
                                </td>
                            </tr>

                        <?php endif; ?>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Cron'); ?>: </label>
                            </td>
                            <td class="value">
                                <select name="cron_notification_mode" class="required-entry">
                                    <option value="0" <?php if (!$this->cron_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1" <?php if ($this->cron_notification_mode): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Notifies if cron is not run more than 12 hours.'); ?></span>
                                </p>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

</form>