<?php if ($websites = $this->getWebsites()): ?>

    <p class="<?php echo Mage::helper('M2ePro/Magento')->isGoEdition() ? '' : 'switcher'; ?>">

        <select id="<?php echo $this->getStoreSelectId(); ?>" name="<?php echo $this->getStoreSelectName(); ?>" style="width: 250px;" class="left-col-block">

            <?php if ($this->hasDefaultOption()): ?>
                <option value=""><?php echo $this->getDefaultStoreName(); ?></option>
            <?php endif; ?>

            <?php foreach ($websites as $website): ?>
                <?php $showWebsite=false; ?>
                <?php foreach ($website->getGroups() as $group): ?>
                    <?php $showGroup=false; ?>
                    <?php foreach ($this->getStores($group) as $store): ?>
                        <?php if ($showWebsite == false): ?>
                            <?php $showWebsite = true; ?>
                            <optgroup label="<?php echo $website->getName(); ?>"></optgroup>
                        <?php endif; ?>
                        <?php if ($showGroup == false): ?>
                            <?php $showGroup = true; ?>
                            <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName(); ?>">
                        <?php endif; ?>
                        <option value="<?php echo $store->getId(); ?>"<?php if($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $store->getName(); ?></option>
                    <?php endforeach; ?>
                    <?php if ($showGroup): ?>
                        </optgroup>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>

        </select>

    </p>

    <script type="text/javascript">

        function switchStore(obj)
        {
            var storeParam = obj.value ? 'store/'+obj.value + '/' : '';

            if(obj.switchParams){
                storeParam+= obj.switchParams;
            }

            <?php if($this->getUseConfirm()): ?>
              $('edit_form').action = "<?php echo $this->getSwitchUrl(); ?>"+storeParam;
              $('edit_form').submit();
            <?php else: ?>
                setLocation('<?php echo $this->getSwitchUrl(); ?>'+storeParam);
            <?php endif; ?>
        }

    </script>

<?php endif; ?>