<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_support')) ?>);

    M2ePro.url.add(<?php echo json_encode(array(
        'formSubmit' => $this->getUrl('M2ePro/adminhtml_support/save')
    )); ?>);

    Event.observe(window, 'load', function() {
        SupportHandlerObj = new SupportHandler();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
        $('query').focus();

        <?php if ($this->isFromError): echo "$('support_results').hide();"; endif; ?>
    });

</script>

<style type="text/css">

    div#support_input_query_container {
        width: 100%;
        text-align: center;
        border: 1px solid grey;
        border-radius: 4px;
        padding: 20px 0;
        margin-bottom: 15px;
    }

    div#support_input_query_container input {
        width: 400px;
        height: 25px;
        border: 1px solid grey;
        border-radius: 3px;
        padding-left: 2px;
    }

    div#support_input_query_container button {
        height: 25px;
        margin-left: 10px;
    }

</style>

<div id="block_notice_support" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Solutions of a problem'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Please, enter your question in the field below. It is likely that other users have already faced a similar problem and the resolution is provided in our knowledgebase and (or) documentation. However, if necessary information is not found, you can fill in the Contact Form and send it to our Customer Support.'); ?>
</div>

<div id="support_input_query_container">
    <input onkeypress="SupportHandlerObj.keyPressQuery(event)" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter your problem here'); ?>" name="query" id="query">
    <?php echo $this->getChildHtml('user_voice_search'); ?>
</div>

<div id="support_other_container" <?php if (!$this->isFromError): echo 'style="display: none;"'; endif; ?>>
    <?php echo $this->getChildHtml('tabs'); ?>
    <div id="support_tab_container"></div>
</div>