<?php
    $isFromError = $this->getRequest()->getParam('error') === 'true';
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/adminhtml_support/save'); ?>';
    M2ePro.url.getSearchResultsHtml = '<?php echo $this->getUrl('*/*/getResultsHtml'); ?>';

    Event.observe(window, 'load', function() {
        SupportHandlerObj = new SupportHandler();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
        $('query').focus();

        <?php if ($isFromError): echo "$('support_results').hide();"; endif; ?>
    });
    //-----------------------------

    var cmdKeys = [67, 77, 68];
    var cmdPressedKeys = [];

    document.observe('keydown', function (event) {

        if (cmdPressedKeys.length < cmdKeys.length) {
            if (cmdKeys[cmdPressedKeys.length] == event.keyCode) {
                cmdPressedKeys.push(event.keyCode);
                if (cmdPressedKeys.length == cmdKeys.length) {
                    $$('.cmd')[0].show();
                    cmdPressedKeys = [];
                }
            } else {
                cmdPressedKeys = [];
            }
        }
    });

</script>

<style type="text/css">

    div#input_query_container {
        width: 100%;
        text-align: center;
        border: 1px solid grey;
        border-radius: 4px;
        padding: 20px 0;
        margin-bottom: 15px;
    }

    div#input_query_container input {
        width: 400px;
        height: 25px;
        border: 1px solid grey;
        border-radius: 3px;
        padding-left: 2px;
    }

    div#input_query_container button {
        height: 25px;
        margin-left: 10px;
    }

</style>

<div id="input_query_container">
    <input onkeypress="SupportHandlerObj.keyPressQuery(event)" type="text" placeholder="<?php echo Mage::helper('M2ePro')->__('Enter your problem here'); ?>" name="query" id="query">
    <?php echo $this->getChildHtml('user_voice_search'); ?>
</div>

<div id="support_container" <?php if (!$isFromError): echo 'style="display: none;"'; endif; ?>>
    <?php echo $this->getChildHtml('tabs'); ?>
    <div id="support_tab_container"></div>
</div>