<?php
    $listingData = Mage::helper('M2ePro')->getGlobalValue('temp_data');

    $suffix = isset($listingData['listing_id']) ? $listingData['listing_id'] : '';
    $gridJsObjectName = $listingData['component_mode'] . 'ListingProductGrid' . $suffix . 'JsObject';
?>

<div class="entry-edit" id="listing_product_rules" style="display: none;" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Advanced Filter'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <form id="<?php echo $this->getForm()->getId(); ?>" method="post" onsubmit="<?php echo $gridJsObjectName ?>.doFilter(event)">
                <?php echo $this->getChildHtml('rule_block') ?>
            </form>

        </div>
    </div>

</div>