<div id="block_notice_ebay_template_general_shipping" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Shipping'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This tab allows you to determine information about how, when and where your products will be shipped from.'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();
    $defaults = array(
        'country' => 'US',
        'postal_code' => '',
        'address' => '',

        'use_ebay_local_shipping_rate_table' => 0,
        'use_ebay_international_shipping_rate_table' => 0,
        'use_ebay_tax_table' => 0,
        'vat_percent' => 0,

        'get_it_fast' => Ess_M2ePro_Model_Ebay_Template_General::GET_IT_FAST_DISABLED,
        'dispatch_time' => 1,

        'local_shipping_mode' =>  Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FLAT,
        'local_shipping_discount_mode' => 0,
        'local_shipping_combined_discount_profile_id' => '',

        'local_shipping_cash_on_delivery_cost_mode' => Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_NONE,
        'local_shipping_cash_on_delivery_cost_value' => '',
        'local_shipping_cash_on_delivery_cost_attribute' => '',

        'international_shipping_mode' => Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_NO_INTERNATIONAL,
        'international_shipping_discount_mode' => 0,
        'international_shipping_combined_discount_profile_id' => '',

        // CALCULATED SHIPPING
        //----------------------------------
        'measurement_system' => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::MEASUREMENT_SYSTEM_ENGLISH,
        'originating_postal_code' => '',

        'package_size_mode' => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::PACKAGE_SIZE_EBAY,
        'package_size_ebay' => 'None',
        'package_size_attribute' => '',

        'dimension_mode'   => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_NONE,
        'dimension_width'  => '',
        'dimension_height' => '',
        'dimension_depth'  => '',
        'dimension_width_attribute'  => '',
        'dimension_height_attribute' => '',
        'dimension_depth_attribute'  => '',

        'weight_mode' => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_NONE,
        'weight_minor' => '',
        'weight_major' => '',
        'weight_attribute' => '',

        'local_handling_cost_mode' => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_NONE,
        'local_handling_cost_value' => '',
        'local_handling_cost_attribute' => '',

        'international_handling_cost_mode' => Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_NONE,
        'international_handling_cost_value' => '',
        'international_handling_cost_attribute' => '',

        'international_trade_na' => Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO,
        'international_trade_uk' => Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO,
        'international_trade_au' => Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO
        //----------------------------------
    );

    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.url.updateShippingDiscountProfilesByAccount = '<?php echo $this->getUrl('*/*/updateShippingDiscountProfilesByAccount') ?>';

    M2ePro.formData.local_handling_cost_attribute         = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['local_handling_cost_attribute']); ?>';
    M2ePro.formData.international_handling_cost_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['international_handling_cost_attribute']); ?>';

    M2ePro.formData.package_size_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['package_size_attribute']); ?>';
    M2ePro.formData.package_size_ebay = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['package_size_ebay']); ?>';
    M2ePro.formData.dimension_width_attribute  = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['dimension_width_attribute']); ?>';
    M2ePro.formData.dimension_height_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['dimension_height_attribute']); ?>';
    M2ePro.formData.dimension_depth_attribute  = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['dimension_depth_attribute']); ?>';
    M2ePro.formData.weight_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['weight_attribute']); ?>';
    M2ePro.formData.local_shipping_combined_discount_profile_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['local_shipping_combined_discount_profile_id']) ?>';
    M2ePro.formData.international_shipping_combined_discount_profile_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['international_shipping_combined_discount_profile_id']) ?>';

    M2ePro.formData.shippings = <?php echo json_encode($formData['shippings']); ?>;
    M2ePro.customData.shippingsWasRendered = false;
    M2ePro.customData.marketplaceWasChanged = false;

    M2ePro.text.none_word = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('None')); ?>';
    M2ePro.text.no_location_or_postal_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Location or Zip/Postal Code should be specified.')); ?>';
    M2ePro.text.no_shipping_method_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should specify at least one shipping method.')); ?>';
    M2ePro.text.no_international_ship_to_location_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Select one or more international ship-to locations.')); ?>';

    M2ePro.customData.attributesReceiving.push(
        {
            id : 'weight_attribute',
            container : 'weight_attribute_td'
        },  {
            id : 'package_size_attribute',
            container : 'package_size_attribute_td'
        }, {
            id : 'dimension_width_attribute',
            container : 'dimension_width_attribute_span'
        }, {
            id : 'dimension_height_attribute',
            container : 'dimension_height_attribute_span'
        }, {
            id : 'dimension_depth_attribute',
            container : 'dimension_depth_attribute_span'
        }, {
            id : 'local_handling_cost_attribute',
            container : 'local_handling_cost_attribute_td'
        }, {
            id : 'international_handling_cost_attribute',
            container : 'international_handling_cost_attribute_td'
        }
    );

    Event.observe(window, 'load', function() {

        EbayTemplateGeneralShippingHandlerObj = new EbayTemplateGeneralShippingHandler('<?php echo Mage::helper('M2ePro')->escapeJs($this->getData('accounts_shipping_discount_profiles')) ?>'.evalJSON(true));
        EbayTemplateGeneralShippingHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_General'); ?>');
        EbayTemplateGeneralShippingHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General'); ?>');
        EbayTemplateGeneralShippingHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General_Shipping'); ?>');
        EbayTemplateGeneralShippingHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General_CalculatedShipping'); ?>');

        $('ebayTemplateGeneralEditTabs_shipping').observe('click', EbayTemplateGeneralTabHandlerObj.checkAttributeSetSelection);
        $('ebayTemplateGeneralEditTabs_shipping').observe('click', EbayTemplateGeneralTabHandlerObj.checkMarketplaceSelection);

        $('postal_code').observe('change', EbayTemplateGeneralShippingHandlerObj.postal_code_change);

        EbayTemplateGeneralShippingHandlerObj.prepareShippingObservers();

        $('local_shipping_mode')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.local_shipping_mode_change)
                .simulate('change');

        $('local_handling_cost_mode')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.local_handling_cost_mode_change)
                .simulate('change');

        $('local_shipping_cash_on_delivery_cost_mode')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.local_shipping_cash_on_delivery_cost_mode_change);

        $('use_ebay_local_shipping_rate_table')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.use_ebay_local_shipping_rate_table_change);

        $('international_shipping_mode')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.international_shipping_mode_change)
                .simulate('change');

        $('international_handling_cost_mode')
                .observe('change', EbayTemplateGeneralShippingHandlerObj.international_handling_cost_mode_change)
                .simulate('change');
    });
    //-----------------------------

</script>

<style type="text/css">
    .shipping-cost-ca select, .shipping-cost-additional-ca select {
        width: 89%;
    }
    .shipping-service {
        width: 250px;
    }
    .cost-mode {
        width: 95px;
    }
    .shipping-priority {
        width: 25px;
        text-align: right;
        padding-right: 2px;
    }
    .shipping-cost-additional {
        width: 50px;
        text-align: right;
        padding-right: 2px;
    }

    #weight_cv input {
        width: 130px !important;
    }
    #dimensions_ca_tr select {
        width: 86px !important;
    }
    #dimensions_cv_tr input {
        width: 80px !important;
    }
    td.note span {
        padding-left: 12px !important;
        font-size: 11px;
    }
</style>

<div class="entry-edit" id="magento_block_ebay_template_general_shipping_location">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Location'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="country"><?php echo Mage::helper('M2ePro')->__('Country'); ?>:</label>
                     </td>
                    <td class="value" style="width: auto;">
                        <select id="country" name="country" class="required-entry">
                            <?php foreach ($this->getData('countries') as $country): ?>
                                <option value="<?php echo $country['country_id']; ?>" <?php if ($formData['country'] == $country['country_id']): echo ' selected="selected"'; endif; ?>><?php echo $country['name'] ?></option>
                            <?php endforeach; ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Country your product will be shipped from.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="postal_code"><?php echo Mage::helper('M2ePro')->__('Zip/Postal Code'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="postal_code" name="postal_code" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['postal_code']); ?>" type="text" class="M2ePro-location-or-postal-required input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Zip/Postal Code of the item location that is used for searches by location.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="address"><?php echo Mage::helper('M2ePro')->__('City, State'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="address" name="address" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['address']); ?>" type="text" class="M2ePro-location-or-postal-required input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('City, State for the location from which the package will be shipped.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_shipping_tax">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Taxation'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="taxation_tax_table_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Use eBay Tax Table'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="use_ebay_tax_table" name="use_ebay_tax_table">
                            <option value="0" <?php if (!$formData['use_ebay_tax_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['use_ebay_tax_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Charges sales tax according to the tax table of your eBay account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="taxation_vat_tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('VAT Rate, %'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input name="vat_percent" value="<?php echo $formData['vat_percent']; ?>" type="text" class="M2ePro-validate-vat input-text" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__("To specify it, a seller must have business eBay account and must be listing the item on a VAT-enabled site."); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_shipping_domestic">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Domestic Shipping'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="local_shipping_mode"><?php echo Mage::helper('M2ePro')->__('Type'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="local_shipping_mode" name="local_shipping_mode" class="M2ePro-validate-shipping-methods">
                            <option id="local_shipping_mode_flat" value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FLAT; ?>"
                                <?php if ($formData['local_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FLAT): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Flat: same cost to all buyers'); ?></option>
                            <option id="local_shipping_mode_calculated" value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_CALCULATED; ?>"
                                <?php if ($formData['local_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_CALCULATED): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Calculated: cost varies by buyer location'); ?></option>
                            <option id="local_shipping_mode_freight" value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FREIGHT; ?>"
                                <?php if ($formData['local_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FREIGHT): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Freight: large items'); ?></option>
                            <option id="local_shipping_mode_local" value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_LOCAL; ?>"
                                <?php if ($formData['local_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_LOCAL): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('No Shipping: local pickup only'); ?></option>
                        </select>
                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="use_ebay_local_shipping_rate_table_tr" class="local-shipping-tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Use eBay Shipping Rate Table'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="use_ebay_local_shipping_rate_table" name="use_ebay_local_shipping_rate_table">
                            <option value="0" <?php if (!$formData['use_ebay_local_shipping_rate_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['use_ebay_local_shipping_rate_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Charges shipping cost according to the shipping rate per an item table of your eBay account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="local-shipping-tr" style="display: none;">
                    <td id="local_shipping_flat_options_td" colspan="2"></td>
                </tr>

                <tr class="local-shipping-tr" style="display: none;">
                    <td id="local_shipping_calculated_options_td" colspan="2"></td>
                </tr>

                <tr id="local_shipping_methods_tr" class="local-shipping-tr" style="display: none; margin-top: 10px;">
                    <td class="grid" colspan="2">

                        <table class="border" cellpadding="0" cellspacing="0" style="width: 900px;">
                            <thead>
                                <tr class="headings">
                                    <th style="width: 250px;"><?php echo Mage::helper('M2ePro')->__('Service'); ?><span class="required">*</span></th>
                                    <th style="width: 95px;"><?php echo Mage::helper('M2ePro')->__('Mode'); ?><span class="required">*</span></th>
                                    <th style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('Cost'); ?><span class="required">*</span></th>
                                    <th style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('Additional Item Cost'); ?><span class="required">*</span></th>
                                    <th style="width: 25px;"><?php echo Mage::helper('M2ePro')->__('Priority'); ?></th>
                                    <th class="type-butt last">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="shipping_local_tbody">
                                <!-- #shipping_table_row_template inserts here -->
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="20" class="a-right"><?php echo $this->getChildHtml('add_local_shipping_method_button'); ?></td>
                                </tr>
                            </tfoot>
                        </table>

                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <div id="block_notice_ebay_template_general_shipping_local" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Local pickup'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="width: 900px; display: none;">
                            <?php echo Mage::helper('M2ePro')->__('Item is available for local pickup only.'); ?>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <div id="block_notice_ebay_template_general_shipping_freight" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Freight'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes" style="width: 900px; display: none;">
                            <?php echo Mage::helper('M2ePro')->__('Specify your own freight shipping options in your item description.'); ?>
                        </div>
                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="local_shipping_git_tr" class="local-shipping-tr">
                    <td class="label">
                        <label for="get_it_fast"><?php echo Mage::helper('M2ePro')->__('Get It Fast'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="get_it_fast" name="get_it_fast">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GET_IT_FAST_DISABLED; ?>"
                                <?php if ($formData['get_it_fast'] == Ess_M2ePro_Model_Ebay_Template_General::GET_IT_FAST_DISABLED): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GET_IT_FAST_ENABLED; ?>"
                                <?php if ($formData['get_it_fast'] == Ess_M2ePro_Model_Ebay_Template_General::GET_IT_FAST_ENABLED): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('At least one qualifying expedited shipping service and 1 day handling time must be offered to enable this option.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="local-shipping-tr">
                    <td class="label">
                        <label for="dispatch_time"><?php echo Mage::helper('M2ePro')->__('Handling Time'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="dispatch_time" name="dispatch_time" class="M2ePro-required-when-visible">
                            <option class="empty"></option>
                            <?php foreach(array(0, 1, 2, 3, 4, 5, 7, 10, 15, 20, 30) as $i): ?>
                                <option id="dispatch_<?php echo $i; ?>" value="<?php echo $i; ?>" <?php if ($formData['dispatch_time'] == $i): ?>selected="selected"<?php endif; ?>><?php if ($i == 0) { echo Mage::helper('M2ePro')->__('Same Day'); } else { $daysWord = ($i == 1) ? 'Day' : 'Day(s)'; echo $i.' '.Mage::helper('M2ePro')->__($daysWord); } ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Time that is needed to prepare an item to be shipped.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="local_handling_cost_tr" class="local-shipping-tr">
                    <td class="label">
                        <label for="local_handling_cost_mode"><?php echo Mage::helper('M2ePro')->__('Handling Cost'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="local_handling_cost_mode" name="local_handling_cost_mode" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::OPTION_NONE; ?>" <?php if ($formData['local_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::OPTION_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::OPTION_CUSTOM_VALUE; ?>" <?php if ($formData['local_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::OPTION_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::OPTION_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['local_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::OPTION_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Addition of handling cost to the shipping costs.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="local_handling_cost_ca_tr" class="local-shipping-tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Handling Cost Attribute'); ?>:</label>
                    </td>
                    <td id="local_handling_cost_attribute_td" class="value" style="width: auto;"></td>
                </tr>

                <tr id="local_handling_cost_cv_tr" class="local-shipping-tr" style="display: none;">
                    <td class="label">
                        <label for="local_handling_cost_value"><?php echo Mage::helper('M2ePro')->__('Handling Cost Value'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="local_handling_cost_value" name="local_handling_cost_value" value="<?php echo $this->escapeHtml($formData['local_handling_cost_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

                <tr class="local-shipping-tr">
                    <td class="label">
                        <label for="local_shipping_combined_discount_profile_id"><?php echo Mage::helper('M2ePro')->__('Combined Shipping Profile') ?>:</label>

                    </td>
                    <td class="value">
                        <select name="local_shipping_combined_discount_profile_id" id="local_shipping_combined_discount_profile_id"></select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Allows using Flat Shipping Rule and Calculated Shipping Rule profiles, which were created on eBay.'); ?></span>
                        </p>
                    </td>
                    <td class="value">
                        <?php echo $this->getChildHtml('update_shipping_discount_profiles'); ?>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Uploads new or refreshes eBay Shipping profiles.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="local-shipping-tr">
                    <td class="label">
                        <label for="local_shipping_discount_mode"><?php echo Mage::helper('M2ePro')->__('Promotional Shipping Rule'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="local_shipping_discount_mode" name="local_shipping_discount_mode" class="M2ePro-required-when-visible">
                            <option value="0" <?php if ($formData['local_shipping_discount_mode'] == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['local_shipping_discount_mode'] == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Adding Shipping Discounts according to the rules that are set in your eBay Account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="local_shipping_cash_on_delivery_cost_mode_tr" class="cash-on-delivery-tr" style="display: none;">
                    <td class="label">
                        <label for="local_shipping_cash_on_delivery_cost_mode"><?php echo Mage::helper('M2ePro')->__('"Cash On Delivery" Cost') ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="local_shipping_cash_on_delivery_cost_mode" name="local_shipping_cash_on_delivery_cost_mode" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_NONE ?>" <?php if ($formData['local_shipping_cash_on_delivery_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_NONE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_CUSTOM_VALUE ?>" <?php if ($formData['local_shipping_cash_on_delivery_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_CUSTOM_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['local_shipping_cash_on_delivery_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General::CASH_ON_DELIVERY_COST_MODE_CUSTOM_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Required when using COD Payment Method.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="local_shipping_cash_on_delivery_cost_ca_tr" class="cash-on-delivery-tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>:</label>
                    </td>
                    <td id="local_shipping_cash_on_delivery_cost_attribute_td" class="value" style="width: auto;"></td>
                </tr>

                <tr id="local_shipping_cash_on_delivery_cost_cv_tr" class="cash-on-delivery-tr" style="display: none;">
                    <td class="label">
                        <label for="local_shipping_cash_on_delivery_cost_value"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="local_shipping_cash_on_delivery_cost_value" name="local_shipping_cash_on_delivery_cost_value" value="<?php echo $this->escapeHtml($formData['local_shipping_cash_on_delivery_cost_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_general_international_trade" style="display: none;">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Cross Border Trade'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_ebay_template_general_general_international_trade" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Cross Border Trade'); ?>">
                <?php echo Mage::helper('M2ePro')->__('The international site visibility feature allows qualifying listings to be posted on international sites.
<br/>Buyers on these sites will see the listings exactly as you originally post them.
<br/><br/><b>Note:</b> eBay charges some additional fee for using this option.'); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="international_trade_au_container">
                    <td class="label">
                        <label for="international_trade_au"><?php echo Mage::helper('M2ePro')->__('Australia Marketplace Visibility'); ?>:</label>
                    </td>

                    <td class="value">
                        <select id="international_trade_au" name="international_trade_au" onchange="EbayTemplateGeneralShippingHandlerObj.international_trade_change(this);">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO ?>" <?php if ($formData['international_trade_au'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES ?>" <?php if ($formData['international_trade_au'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="international_trade_na_container">
                    <td class="label">
                        <label for="international_trade_na"><?php echo Mage::helper('M2ePro')->__('USA / Canada Marketplace Visibility'); ?>:</label>
                    </td>

                    <td class="value">
                        <select id="international_trade_na" name="international_trade_na" onchange="EbayTemplateGeneralShippingHandlerObj.international_trade_change(this);">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO ?>" <?php if ($formData['international_trade_na'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES ?>" <?php if ($formData['international_trade_na'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('eBay North America (ebay.com and ebay.ca)'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="international_trade_uk_container">
                    <td class="label">
                        <label for="international_trade_uk"><?php echo Mage::helper('M2ePro')->__('UK Marketplace Visibility'); ?>:</label>
                    </td>

                    <td class="value">
                        <select id="international_trade_uk" name="international_trade_uk" onchange="EbayTemplateGeneralShippingHandlerObj.international_trade_change(this);">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO ?>" <?php if ($formData['international_trade_uk'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES ?>" <?php if ($formData['international_trade_uk'] == Ess_M2ePro_Model_Ebay_Template_General::INTERNATIONAL_TRADE_MODE_YES): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('eBay UK (ebay.co.uk)'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_shipping_international">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('International Shipping'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="international_shipping_mode"><?php echo Mage::helper('M2ePro')->__('Type'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="international_shipping_mode" name="international_shipping_mode" class="M2ePro-validate-shipping-methods">
                            <option id="international_shipping_none" value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_NO_INTERNATIONAL; ?>"
                                <?php if ($formData['international_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_NO_INTERNATIONAL): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('No International Shipping'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FLAT; ?>"
                                <?php if ($formData['international_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_FLAT): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Flat: same cost to all buyers'); ?>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_CALCULATED; ?>"
                                <?php if ($formData['international_shipping_mode'] == Ess_M2ePro_Model_Ebay_Template_General::SHIPPING_TYPE_CALCULATED): echo ' selected="selected"'; endif; ?>>
                                <?php echo Mage::helper('M2ePro')->__('Calculated: cost varies by buyer location'); ?></option>
                        </select>
                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr class="international-shipping-tr" style="display: none;">
                    <td id="international_shipping_calculated_options_td" colspan="2"></td>
                </tr>

                <tr class="international-shipping-tr">
                    <td class="grid" colspan="2">

                        <table class="border" cellpadding="0" cellspacing="0" style="width: 900px;">
                            <thead>
                                <tr class="headings">
                                    <th style="width: 250px;"><?php echo Mage::helper('M2ePro')->__('Service'); ?><span class="required">*</span></th>
                                    <th style="width: 95px;"><?php echo Mage::helper('M2ePro')->__('Mode'); ?><span class="required">*</span></th>
                                    <th style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('Cost'); ?><span class="required">*</span></th>
                                    <th style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('Additional Item Cost'); ?><span class="required">*</span></th>
                                    <th style="width: 25px;"><?php echo Mage::helper('M2ePro')->__('Priority'); ?></th>
                                    <th class="type-butt last">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="shipping_international_tbody">
                                <!-- #shipping_table_row_template inserts here -->
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="20" class="a-right"><?php echo $this->getChildHtml('add_international_shipping_method_button'); ?></td>
                                </tr>
                            </tfoot>
                        </table>

                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="use_ebay_international_shipping_rate_table_tr" class="international-shipping-tr">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Use eBay Shipping Rate Table'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="use_ebay_international_shipping_rate_table" name="use_ebay_international_shipping_rate_table">
                            <option value="0" <?php if (!$formData['use_ebay_international_shipping_rate_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['use_ebay_international_shipping_rate_table']): echo ' selected="selected"'; endif; ?> ><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Charges shipping cost according to the shipping rate per an item table of your eBay account.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="international_handling_cost_tr" class="international-shipping-tr">
                    <td class="label">
                        <label for="international_handling_cost_mode"><?php echo Mage::helper('M2ePro')->__('Handling Cost'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="international_handling_cost_mode" name="international_handling_cost_mode" class="select">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_NONE; ?>" <?php if ($formData['international_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_CUSTOM_VALUE; ?>" <?php if ($formData['international_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['international_handling_cost_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::HANDLING_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Addition of handling cost to the shipping costs.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="international_handling_cost_ca_tr" class="international-shipping-tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Handling Cost Attribute'); ?>:</label>
                    </td>
                    <td id="international_handling_cost_attribute_td" class="value" style="width: auto;"></td>
                </tr>

                <tr id="international_handling_cost_cv_tr" class="international-shipping-tr" style="display: none;">
                    <td class="label">
                        <label for="international_handling_cost_value"><?php echo Mage::helper('M2ePro')->__('Handling Cost Value'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="international_handling_cost_value" name="international_handling_cost_value" value="<?php echo $this->escapeHtml($formData['international_handling_cost_value']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
                    </td>
                </tr>

                <tr class="international-shipping-tr">
                    <td class="label">
                        <label for="international_shipping_combined_discount_profile_id"><?php echo Mage::helper('M2ePro')->__('Combined Shipping Profile') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="international_shipping_combined_discount_profile_id" id="international_shipping_combined_discount_profile_id"></select>
                    </td>
                    <td class="value">
                        <?php echo $this->getChildHtml('update_shipping_discount_profiles'); ?>
                    </td>
                </tr>

                <tr class="international-shipping-tr">
                    <td class="label">
                        <label for="international_shipping_discount_mode"><?php echo Mage::helper('M2ePro')->__('Promotional Shipping Rule:'); ?></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="international_shipping_discount_mode" name="international_shipping_discount_mode" class="M2ePro-required-when-visible">
                            <option value="0" <?php if ($formData['international_shipping_discount_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['international_shipping_discount_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Adding Shipping Discounts according to the rules that are set in your eBay Account.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<table id="block_listing_template_shipping_calculated_options" cellpadding="0" cellspacing="0" style="display: none;">

    <tbody>

        <tr class="visible-for-flat-by-default visible-for-calculated-by-default">
            <td class="label">
                <label for="measurement_system"><?php echo Mage::helper('M2ePro')->__('Measurement System'); ?>:</label>
            </td>
            <td class="value">
                <select id="measurement_system" name="measurement_system" class="select">
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::MEASUREMENT_SYSTEM_ENGLISH; ?>" <?php if ($formData['measurement_system'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::MEASUREMENT_SYSTEM_ENGLISH): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('English (lbs, oz, in)'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::MEASUREMENT_SYSTEM_METRIC; ?>" <?php if ($formData['measurement_system'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::MEASUREMENT_SYSTEM_METRIC): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Metric (kg, g, cm)'); ?></option>
                </select>
            </td>
        </tr>

        <tr class="visible-for-calculated-by-default">
            <td class="label">
                <label for="package_size_mode"><?php echo Mage::helper('M2ePro')->__('Package Size Source'); ?>:</label>
            </td>
            <td class="value">
                <select id="package_size_mode" name="package_size_mode" class="select">
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::PACKAGE_SIZE_EBAY; ?>" <?php if ($formData['package_size_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::PACKAGE_SIZE_EBAY): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('eBay Values'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::PACKAGE_SIZE_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['package_size_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::PACKAGE_SIZE_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                </select>
            </td>
        </tr>

        <tr id="package_size_ebay_predefined_tr" class="visible-for-calculated-by-default">
            <td class="label">
                <label for="package_size_ebay"><?php echo Mage::helper('M2ePro')->__('Package Size'); ?>:</label>
            </td>
            <td class="value" style="width: auto;">
                <select id="package_size_ebay" name="package_size_ebay"></select>
                <p class="note">
                    <span><?php echo Mage::helper('M2ePro')->__('If you don\'t know your package type, select the "Large package" option.'); ?></span>
                </p>
            </td>
        </tr>

        <tr id="package_size_attribute_tr" style="display: none;">
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Package Size Attribute'); ?>:</label>
            </td>
            <td id="package_size_attribute_td" class="value" style="width: auto;"></td>
            <td id="package_size_attribute_td_note" style="display: none;">
                <p class="note">
                    <span><?php echo Mage::helper('M2ePro')->__('The Package Size Attribute must have package ID as value.'); ?></span>
                </p>
            </td>
        </tr>

        <tr id="dimensions_tr" class="visible-for-calculated-by-default">
            <td class="label">
                <label for="dimension_mode"><?php echo Mage::helper('M2ePro')->__('Dimension Source'); ?>:</label>
            </td>
            <td class="value">
                <select id="dimension_mode" name="dimension_mode" class="select">
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_NONE; ?>" <?php if ($formData['dimension_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_CUSTOM_VALUE; ?>" <?php if ($formData['dimension_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['dimension_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::DIMENSIONS_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                </select>
            </td>
        </tr>

        <tr id="dimensions_ca_tr" style="display: none;">
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Dimensions (Width/Height/Depth)'); ?>:</label>
            </td>
            <td class="value">
                <span id="dimension_width_attribute_span"></span> x <span id="dimension_height_attribute_span"></span> x <span id="dimension_depth_attribute_span"></span>
            </td>
            <td class="note">
                <span class="measurement-system-english"><?php echo Mage::helper('M2ePro')->__('inches'); ?></span>
                <span class="measurement-system-metric"><?php echo Mage::helper('M2ePro')->__('cm'); ?></span>
            </td>
        </tr>

        <tr id="dimensions_cv_tr" style="display: none;">
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Dimensions (Width/Height/Depth)'); ?>:</label>
            </td>
            <td class="value">
                <input name="dimension_width" value="<?php echo $this->escapeHtml($formData['dimension_width']); ?>" type="text" class="input-text M2ePro-required-when-visible" /> x
                <input name="dimension_height" value="<?php echo $this->escapeHtml($formData['dimension_height']); ?>" type="text" class="input-text M2ePro-required-when-visible" /> x
                <input name="dimension_depth" value="<?php echo $this->escapeHtml($formData['dimension_depth']); ?>" type="text" class="input-text M2ePro-required-when-visible" />
            </td>
            <td class="note">
                <span class="measurement-system-english"><?php echo Mage::helper('M2ePro')->__('inches'); ?></span>
                <span class="measurement-system-metric"><?php echo Mage::helper('M2ePro')->__('cm'); ?></span>
            </td>
        </tr>

        <tr class="visible-for-flat-by-default visible-for-calculated-by-default">
            <td class="label">
                <label for="weight_mode"><?php echo Mage::helper('M2ePro')->__('Weight Source'); ?>:</label>
            </td>
            <td class="value">
                <select id="weight_mode" name="weight_mode" class="select">
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_NONE; ?>" <?php if ($formData['weight_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_NONE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_CUSTOM_VALUE; ?>" <?php if ($formData['weight_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_CUSTOM_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['weight_mode'] == Ess_M2ePro_Model_Ebay_Template_General_CalculatedShipping::WEIGHT_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                </select>
            </td>
        </tr>

        <tr id="weight_ca" class="visible-for-flat-by-default visible-for-calculated-by-default">
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Weight Attribute'); ?>:</label>
            </td>
            <td id="weight_attribute_td" class="value" style="width: auto;"></td>
            <td id="weight_attribute_td_note" style="display: none;">
                <p class="note">
                    <span><?php echo Mage::helper('M2ePro')->__('The Weight Attribute must have the weight of the item.'); ?></span>
                </p>
            </td>
            <td class="note">
                <span class="measurement-system-english"><?php echo Mage::helper('M2ePro')->__('lbs. oz.'); ?></span>
                <span class="measurement-system-metric"><?php echo Mage::helper('M2ePro')->__('kg. g.'); ?></span>
            </td>
        </tr>

        <tr id="weight_cv" class="visible-for-flat-by-default visible-for-calculated-by-default">
            <td class="label">
                <label><?php echo Mage::helper('M2ePro')->__('Weight'); ?>: <span class="required">*</span></label>
            </td>
            <td class="value">
                <input name="weight_major" value="<?php echo $this->escapeHtml($formData['weight_major']); ?>" type="text" class="M2ePro-required-when-visible input-text" />&nbsp;<input name="weight_minor" value="<?php echo $this->escapeHtml($formData['weight_minor']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
            </td>
            <td class="note">
                <span class="measurement-system-english"><?php echo Mage::helper('M2ePro')->__('lbs. oz.'); ?></span>
                <span class="measurement-system-metric"><?php echo Mage::helper('M2ePro')->__('kg. g.'); ?></span>
            </td>
        </tr>

        <tr class="visible-for-calculated-by-default">
            <td class="label">
                <label for="originating_postal_code"><?php echo Mage::helper('M2ePro')->__('Zip/Postal Code'); ?>: <span class="required">*</span></label>
            </td>
            <td class="value">
                <input id="originating_postal_code" name="originating_postal_code" value="<?php echo $this->escapeHtml($formData['originating_postal_code']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
                <p class="note">
                    <span><?php echo Mage::helper('M2ePro')->__('Postal code for the location from which the package will be shipped.'); ?></span>
                </p>
            </td>
        </tr>

    </tbody>

</table>

<table id="block_listing_template_shipping_table_row_template_table" style="display: none;">

    <tbody>

        <tr id="shipping_variant_%type%_%i%_tr" class="shipping-variant">
            <td>
                <select name="shipping_service[%i%]" class="shipping-service" onchange="EbayTemplateGeneralShippingHandlerObj.shipping_service_change(this)"></select>
            </td>
            <td>
                <input name="shipping_type[%i%]" value="%type%" type="hidden" />
                <select name="cost_mode[%i%]" class="cost-mode" onchange="EbayTemplateGeneralShippingHandlerObj.cost_mode_change(this)">
                    <option value="0" class="shipping-mode-option-free"><?php echo Mage::helper('M2ePro')->__('Free'); ?></option>
                    <option value="1" class="shipping-mode-option-notcalc"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                    <option value="2" class="shipping-mode-option-notcalc"><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                    <option value="3" class="shipping-mode-option-calc"><?php echo Mage::helper('M2ePro')->__('Calculated'); ?></option>
                </select>
            </td>
            <td style="text-align: right; width: 200px;">
                <input name="shipping_cost_value[%i%]" type="text" style="display: none; text-align: right;" class="shipping-cost-cv input-text M2ePro-required-when-visible" />
                <span class="shipping-cost-ca" style="width: 86%;">
                    <!-- shipping_cost_attribute[%i%] -->
                </span>
            </td>
            <td style="text-align: right; width: 200px;">
                <span class="shipping-cost-additional-ca" style="width: 86%;">
                    <!-- shipping_cost_additional_attribute[%i%] -->
                </span>
                <input name="cost_additional_items[%i%]" type="text" class="shipping-cost-additional input-text" />
            </td>
            <td style="text-align: right; width: 25px;">
                <input name="shipping_priority[%i%]" type="text" class="shipping-priority input-text" />
            </td>
            <td style="text-align: center; vertical-align: middle;">
                <?php echo $this->getChildHtml('remove_shipping_method_button'); ?>
            </td>
        </tr>

    </tbody>

</table>

<table id="block_listing_template_shipping_table_locations_row_template_table" style="display: none;">

    <tbody>

        <tr id="shipping_variant_locations_%i%_tr" class="shipping-variant">
            <td colspan="5">
                <!-- locations will be rendered here -->
            </td>
        </tr>

    </tbody>

</table>
