<script type="text/javascript" src="<?php echo $this->getJsUrl('M2ePro/VideoTutorialHandler.js'); ?>"></script>

<script type="text/javascript">

    // todo next
    // var isTutorialFinished = false;
    var isTutorialFinished = true;

    M2eProPlayWelcomeTutorialHandlerObj = new VideoTutorialHandler(
        'play_welcome_video_tutorial_pop_up',
        '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('M2E Pro - Play.com/Magento Integration : Configuration Wizard')); ?>',
        function() {}
    );

</script>

<div id="block_notice_wizard_welcome_content" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <table>

        <tr>

            <!-- todo next uncomment -->
            <!--            <td>-->
            <!--                <a id="tutorial_image_container" href="javascript:" onclick="isTutorialFinished = true; M2eProPlayWelcomeTutorialHandlerObj.openPopUp()">-->
            <!--                    <img src="--><?php //echo $this->getSkinUrl('M2ePro/images/play-video-thumbnail.png'); ?><!--" alt="">-->
            <!--                </a>-->
            <!--                <h4 style="text-align: center">--><?php //echo Mage::helper('M2ePro')->__('Play.com Configuration (6 min. video)'); ?><!--</h4>-->
            <!--            </td>-->

            <td style="padding: 0">

                <h3>
                    <?php echo Mage::helper('M2ePro')->__('With M2E Pro, listing your Magento Inventory on Play.com couldn\'t be easier.'); ?>
                </h3>
                <br/>
                <p>
                    <?php
                    echo Mage::helper('M2ePro')->__(
                        'This part of Extension facilitates quick and simple Listings creation as well as management of Product Listings.<br/>
                        Also, it is possible to Import and Map existing Items (created directly on Play.com or with the help of 3rd party tools) to Magento Products. <br/>
                        The M2E Pro fully supports multiple Play.com Accounts and multiple Magento Stores. <br/><br/>
                        <u>Among the features:</u> <br/>
                        <ul class="list">
                        <li>Ability to import Play.com Products into Magento Catalogue for Play.com Order, if such Product is not found in exiting Catalogue;</li>
                        <li>Ability to import of Play.com Orders and many other Tasks which would significantly reduce a time required for Listings maintenance;</li>
                        <li>Ability to set Tax Settings for Magento Order based on Play.com Order (Play.com Order Tax Settings);</li>
                        <li>Automated and manual Mapping of 3rd party (existing) Products to Magento Products Catalogue;</li>
                        <li>Ability to move 3rd party (existing, mapped to Magento) Products to existing M2E Pro Listings;</li>
                        <li>Automated Synchronization (Inventory, Pricing);</li>
                        <li>Automatic and Manual "Play ID Lookup" features.</li>
                        </ul>'
                    ); ?>
                </p>
                <br/>
                <div><?php echo $this->getChildHtml('start_wizard_button'); ?></div>
            </td>

        </tr>

    </table>
</div>

<div id="play_welcome_video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
        <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/Kjtl7wPXxfA?version=3&amp;hl=ru_RU&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/Kjtl7wPXxfA?version=3&amp;hl=ru_RU&amp;rel=0" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>