<div id="block_notice_amazon_template_selling_format" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selling Format Template'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Selling Format Template contains price-related data and quantity for the items, which will be listed on Amazon.<br/><br/>
Next to each price options dropdown there is a box for Price Change. Price Change is a value you want the Magento Price to be modified while listing on Amazon.<br/><br/>
<b>Examples:</b><br/>
If you want the price on Amazon to be greater by 15% than the price in Magento, you should set +15% in the Price Change field.<br/>
<i>Amazon Price = Magento Price + Magento Price * 0.15</i>
<br/>
If you want the price on Amazon to be less by 10 currency units than the price in Magento, you should set -10 in the Price Change field.<br/>
<i>Amazon Price = Magento Price - 10</i>
<br/>
If you want the price on Amazon to be multiplied by coefficient 1.2, you should set 1.2 in the Price Change field.
<br/>
<i>Amazon Price = Magento Price * 1.2.</i>
<br/><br/>
<b>Note:</b> If the Special Price is chosen in the <span style="text-decoration: underline;">Item Price</span> option, but it is not set in Magento Product settings or it is set but it has already expired, the Product Price is used instead.
<br/>If the Special Price is chosen in the <span style="text-decoration: underline;">Sale Price</span> option, its Magento <i>From</i>, <i>To</i> dates are ignored. Only the value is used. When the Sale Price has expired, the Item Price is used.
<br/><br/>
<b>Note:</b> Attributes must contain only numeric values.
'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();

    $paramsAttributeSetId = $this->getRequest()->getParam('attribute_sets');
    !is_null($paramsAttributeSetId) && $formData['attribute_sets'] = explode(',', $paramsAttributeSetId);

    $default = array(
        'title' => '',
        'attribute_sets' => array(),

        'qty_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_PRODUCT,
        'qty_custom_value' => 1,
        'qty_custom_attribute' => '',
        'qty_max_posted_value' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MAX_POSTED_DEFAULT_VALUE,

        'currency' => Mage::helper('M2ePro/Magento')->getBaseCurrency(),

        'price_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_PRODUCT,
        'price_coefficient' => '',
        'price_custom_attribute' => '',

        'sale_price_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NONE,
        'sale_price_coefficient' => '',
        'sale_price_custom_attribute' => '',

        'price_variation_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT,

        'sale_price_start_date_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE,
        'sale_price_end_date_mode' => Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE,

        'sale_price_start_date_custom_attribute' => '',
        'sale_price_end_date_custom_attribute' => '',

        'sale_price_start_date_value' => Mage::helper('M2ePro')->getCurrentGmtDate(),
        'sale_price_end_date_value' => Mage::helper('M2ePro')->getCurrentGmtDate(),

        'customer_group_id' => ''
    );

    $formData = array_merge($default, $formData);

    if ($formData['sale_price_start_date_value'] != '') {
        $formData['sale_price_start_date_value'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['sale_price_start_date_value']);
    }
    if ($formData['sale_price_end_date_value'] != '') {
        $formData['sale_price_end_date_value'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['sale_price_end_date_value']);
    }

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.formSubmitNew = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_template_sellingFormat/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.magentoGetAttributesByAttributeSets = '<?php echo $this->getUrl('*/adminhtml_general/magentoGetAttributesByAttributeSets'); ?>';

    M2ePro.text.price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The price of products in Amazon listing(s).')); ?>';
    M2ePro.text.final_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The price of products in Amazon listing(s).<br/><b>Note:</b> The Final Price is only used for Simple Products.')); ?>';

    M2ePro.text.sale_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The price, at which you want to sell your product(s)<br/>at specific time.')); ?>';
    M2ePro.text.final_sale_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The price, at which you want to sell your product(s).<br/>at specific time.<br/><b>Note:</b> The Final Price is only used for Simple Products.')); ?>';

    M2ePro.formData.id = '<?php echo (int)$this->getRequest()->getParam('id'); ?>';
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';

    M2ePro.formData.qty_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_mode']); ?>';
    M2ePro.formData.qty_max_posted_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_max_posted_value']); ?>';

    M2ePro.formData.qty_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_custom_attribute']); ?>';
    M2ePro.formData.price_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['price_custom_attribute']); ?>';
    M2ePro.formData.sale_price_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['sale_price_custom_attribute']); ?>';
    M2ePro.formData.sale_price_start_date_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['sale_price_start_date_custom_attribute']); ?>';
    M2ePro.formData.sale_price_end_date_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['sale_price_end_date_custom_attribute']); ?>';

    M2ePro.text.chapter_when_duplicate = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Add Selling Format Template.')); ?>';
    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other template. Template title must be unique.')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Sets first and press Confirm button.')); ?>';
    M2ePro.text.price_coef_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Coefficient is not valid.')); ?>';

    Event.observe(window, 'load', function() {

        AttributeSetHandlerObj = new AttributeSetHandler();

        AmazonTemplateSellingFormatHandlerObj = new AmazonTemplateSellingFormatHandler();
        AmazonTemplateSellingFormatHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Amazon_Template_SellingFormat'); ?>');

        $('attribute_sets').observe('change', AttributeSetHandlerObj.changeAttributeSets);
        $('attribute_sets').value && AmazonTemplateSellingFormatHandlerObj.attribute_sets_confirm();

        $('qty_mode')
                .observe('change', AmazonTemplateSellingFormatHandlerObj.qty_mode_change)
                .simulate('change');

        $('qty_max_posted_value_mode')
                .observe('change', AmazonTemplateSellingFormatHandlerObj.qtyMaxPostedMode_change)
                .simulate('change');

        $('price_mode')
                .observe('change', AmazonTemplateSellingFormatHandlerObj.price_mode_change)
                .simulate('change');

        $('sale_price_start_date_mode')
            .observe('change', AmazonTemplateSellingFormatHandlerObj.sale_price_start_date_mode_change)
            .simulate('change');

        $('sale_price_end_date_mode')
            .observe('change', AmazonTemplateSellingFormatHandlerObj.sale_price_end_date_mode_change)
            .simulate('change');

        $('sale_price_mode')
                .observe('change', AmazonTemplateSellingFormatHandlerObj.sale_price_mode_change)
                .simulate('change');

        $('customer_group_id')
                .observe('change', function() { CommonHandlerObj.hideEmptyOption(this); });

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style type="text/css">
    .coef {
        padding-left: 5px !important;
        padding-top: 5px !important;
    }
    .coef input {
        text-align: right;
        width: 36px;
    }
    .form-list td.label {
        width: 275px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_amazon_template_selling_format_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-price-tpl-title"/>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Short meaningful template title for your internal use.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Sets'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                                <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                                <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="attribute_sets<?php echo $attributeSetPostfix; ?>[]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                    <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <?php if ($this->attribute_set_locked): ?>
                                <div id="attribute_sets_breadcrumb" style="width: 280px;">
                                    <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                                        <?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                                    <?php endforeach; ?>
                                    <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                                </div>
                                <input id="attribute_sets" name="attribute_sets" value="<?php echo $this->escapeHtml(implode(',', $formData['attribute_sets'])); ?>" type="hidden" />
                            <?php endif; ?>

                            <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                                <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                                <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                            </div>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Attribute Sets of products which will be listed on Amazon<br />using this template.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

        <div class="entry-edit" id="magento_block_amazon_template_selling_format_qty">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr class="requirie-attribute-set">
                        <td class="label">
                            <label for="qty_mode"><?php echo Mage::helper('M2ePro')->__('Item Quantity'); ?>: </label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="qty_mode" name="qty_mode">
                                <option id="qty_mode_product" value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_PRODUCT == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Product QTY'); ?></option>
                                <option id="qty_mode_single" value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_SINGLE; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_SINGLE == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Single Item'); ?></option>
                                <option id="qty_mode_cv" value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_NUMBER; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_NUMBER == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom QTY Number'); ?></option>
                                <option id="qty_mode_ca" value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MODE_ATTRIBUTE == $formData['qty_mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom QTY Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Products quantity in Amazon listing(s).'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="qty_custom_value_tr" style="display: none;">
                        <td class="label">
                            <label for="qty_custom_value"><?php echo Mage::helper('M2ePro')->__('Custom QTY Number'); ?>: </label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input id="qty_custom_value" name="qty_custom_value" value="<?php echo $this->escapeHtml($formData['qty_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible validate-digits" />
                        </td>
                    </tr>

                    <tr id="qty_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom QTY Attribute'); ?>: </label>
                        </td>
                        <td id="qty_custom_attribute_td" class="value" style="width: auto;"></td>
                    </tr>

                    <tr>

                    </tr>

                    <!-- Max Posted QTY-->
                    <tr id="qty_max_posted_value_mode_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Conditional Quantity'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="qty_max_posted_value_mode" name="qty_max_posted_value_mode" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MAX_POSTED_MODE_OFF; ?>" <?php if ($formData['qty_max_posted_value'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::QTY_MAX_POSTED_MODE_ON; ?>" <?php if ($formData['qty_max_posted_value'] > 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                            </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('<i>Enables</i> to set the quantity that will be sent on Amazon.'); ?></span>
                                </p>
                        </td>
                    </tr>

                    <tr id="qty_max_posted_value_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Max Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="qty_max_posted_value_td" class="value" style="width: auto;">
                            <input id="qty_max_posted_value" name="qty_max_posted_value" value="<?php echo $this->escapeHtml($formData['qty_max_posted_value']); ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('If you have 5 pieces in stock but set a max qty of 2 to be listed, a qty of 2 will be listed on Amazon.
                                                                            <br/>If you have 1 piece in stock but max qty is set to 3, only 1 will be listed on Amazon.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_amazon_template_selling_format_prices">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Price'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table id="currency_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="currency"><?php echo Mage::helper('M2ePro')->__('Currency'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="currency" name="currency" class="select-main">
                                <?php foreach ($this->getData('currencies') as $code => $title): ?>
                                    <option value="<?php echo $code; ?>"<?php if ($formData['currency'] == $code): echo ' selected="selected"'; endif;?>><?php echo $title ?></option>
                                <?php endforeach; ?>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The currency for items price(s). Must correspond to Amazon Marketpace.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

                <table id="price_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="price_mode"><?php echo Mage::helper('M2ePro')->__('Price'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="price_mode" name="price_mode" class="select-main required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_PRODUCT == $formData['price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_SPECIAL == $formData['price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_FINAL; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_FINAL == $formData['price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Final Price'); ?></option> -->
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_ATTRIBUTE == $formData['price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span id="price_note"></span>
                            </p>
                        </td>
                        <td id="price_coefficient_td" class="coef">
                            <div style="font-size: 11px; float: right; padding-left: 10px;">
                                <img src="<?php echo $this->getSkinUrl('images/note_cell_bg.gif'); ?>" />
                                <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or currency rate (1.44)'); ?>.</span>
                            </div>
                            <input id="price_coefficient" name="price_coefficient" value="<?php echo $this->escapeHtml($formData['price_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                        </td>
                    </tr>

                    <tr id="price_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Price Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="price_custom_attribute_td" class="value" colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="price_variation_mode"><?php echo Mage::helper('M2ePro')->__('Variation Price Source'); ?>:</label>
                        </td>
                        <td class="value" colspan="2">
                            <select id="price_variation_mode" name="price_variation_mode" class="select-main">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Main Product'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN; ?>" <?php if (Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Associated Products'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Determines where the price for Configurable and Bundle products options should be taken from.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_amazon_template_selling_format_sale_price">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Sale Price'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="sale_price_mode"><?php echo Mage::helper('M2ePro')->__('Sale Price'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="sale_price_mode" name="sale_price_mode" class="select-main required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NOT_SET; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NOT_SET) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Set'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NONE; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NONE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_PRODUCT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_SPECIAL) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_FINAL; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_FINAL) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Final Price'); ?></option> -->
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span id="sale_price_note"></span>
                            </p>
                        </td>
                        <td id="sale_price_coefficient_td" class="coef" <?php if ($formData['sale_price_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::PRICE_NONE) echo 'style="display: none;"'; ?>>
                            <div style="font-size: 11px; float: right; padding-left: 10px;">
                                <img src="<?php echo $this->getSkinUrl('images/note_cell_bg.gif'); ?>" />
                                <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or currency rate (1.44)'); ?>.</span>
                            </div>
                            <input id="sale_price_coefficient" name="sale_price_coefficient" value="<?php echo $this->escapeHtml($formData['sale_price_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                        </td>
                    </tr>

                </table>

                <table cellspacing="0" class="form-list">

                    <tr id="sale_price_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Sale Price Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="sale_price_custom_attribute_td" class="value"></td>
                    </tr>

                    <tr id="sale_price_start_date_mode_tr" style="display: none;">
                        <td class="label">
                            <label for="sale_price_start_date_mode"><?php echo Mage::helper('M2ePro')->__('Start Date'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="sale_price_start_date_mode" name="sale_price_start_date_mode">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE; ?>" <?php if ($formData['sale_price_start_date_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_ATTRIBUTE; ?>" <?php if ($formData['sale_price_start_date_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time and date when the <i>Sale Price</i> will be displayed on Amazon.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="sale_price_start_date_value_tr" style="display: none;">
                        <td class="label">
                            <label for="sale_price_start_date_value"><?php echo Mage::helper('M2ePro')->__('Start Date Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="sale_price_start_date_value" name="sale_price_start_date_value" value="<?php echo $formData['sale_price_start_date_value']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "sale_price_start_date_value",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "sale_price_start_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                        </td>
                    </tr>

                    <tr id="sale_price_start_date_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Start Date Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" id="sale_price_start_date_custom_attribute_td"></td>
                    </tr>

                    <tr id="sale_price_end_date_mode_tr" style="display: none;">
                        <td class="label">
                            <label for="sale_price_end_date_mode"><?php echo Mage::helper('M2ePro')->__('End Date'); ?>: </label>
                        </td>
                        <td class="value">
                            <select id="sale_price_end_date_mode" name="sale_price_end_date_mode">
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE; ?>" <?php if ($formData['sale_price_end_date_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_ATTRIBUTE; ?>" <?php if ($formData['sale_price_end_date_mode'] == Ess_M2ePro_Model_Amazon_Template_SellingFormat::DATE_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time and date when the <i>Sale Price</i> will be hidden on Amazon.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="sale_price_end_date_value_tr" style="display: none;">
                        <td class="label">
                            <label for="sale_price_end_date_value"><?php echo Mage::helper('M2ePro')->__('End Date Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="sale_price_end_date_value" name="sale_price_end_date_value" value="<?php echo $formData['sale_price_end_date_value']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "sale_price_end_date_value",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "sale_price_end_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                        </td>
                    </tr>

                    <tr id="sale_price_end_date_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Start Date Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" id="sale_price_end_date_custom_attribute_td">
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_amazon_template_selling_format_customer_group_id">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Customer Group For Final Price'); ?></h4>
        </div>

        <div class="fieldset">
           <div class="hor-scroll">

                <div id="block_notice_amazon_template_selling_format_customer_group_id" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Fixed Price'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This block appears when the <b>Final Price</b> is chosen in the Price option(s).
                <br/>
                The Final Price means that the price, that will be sent to Amazon, is calculated according to Catalog Price Rules. So Amazon buyers can buy your products at Magento Store Price.
                <br/><br/>
                <b>Note:</b> If there is a Special Price on a product and conditions are met for Catalog Price Rule to be applied, the <u>smaller</u> price from the Special and price calculated according to Catalog Price Rules will be set.
                <br/>
                If the Final Price is set, but any of Catalog Price Rules is not applied, the Special Price will be chosen, if there is no Special Price on the product, the Products Price will be set.
                <br/><br/>
                For correct definition Price Rule, which must be applied, you have to specify the <b>Customer Group</b> your Amazon buyers will be associated to.
                '); ?>
                </div>

                <table cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="customer_group_id"><?php echo Mage::helper('M2ePro')->__('Customer Group'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="customer_group_id" name="customer_group_id" class="select-main">
                                <?php if ($formData['customer_group_id'] === ''): ?>
                                    <option class="empty"></option>
                                <?php endif; ?>
                                <?php foreach ($this->customerGroups as $group): ?>
                                    <option value="<?php echo (int)$group['value'] ?>" <?php if ($formData['customer_group_id'] !== '' && $formData['customer_group_id'] == (int)$group['value']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($group['label']); ?></option>
                                <?php endforeach; ?>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Which customer group Amazon buyers have to be associated to.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</form>