<div id="block_notice_common_sellingFormat_templates" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selling Format Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In this Section you can Create, Edit, and Delete Selling Format Policies. <br/><br/>
    Selling Format Policies are used to work with values related to the offer part of the Listings, such as Price, Quantity and similar parameters.
    '); ?>
</div>