<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label" style="width: 300px;">
            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Table');?></label>
        </td>
        <td class="value" style="width: 150px;">
            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Status');?></label>
        </td>
        <td class="value">
            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Records');?></label>
        </td>
    </tr>

    <?php foreach ($this->mysql['tables'] as $table => $row): ?>
        <tr>
            <td class="label" style="width: 300px; font-style: italic;">
                <label style="width: 300px;"><?php echo $table; ?> </label>
            </td>
            <?php if ($row['is_exist']) : ?>
                <td class="value" style="color: green;">
                    <?php echo Mage::helper('M2ePro')->__('Yes'); ?>&nbsp;
                    <?php if ($row['has_model']) { ?>
                        <span class="manage_db_table_item" <?php if (!$this->show_cmd) { ?>style="display:none;"<?php } ?>>(<a href="<?php echo $row['manage_link']; ?>">manage</a>)</span>
                    <?php } ?>
                </td>
            <?php else : ?>
                <td class="value" style="color: red;"><?php echo Mage::helper('M2ePro')->__('No'); ?></td>
            <?php endif; ?>
            <td class="value"><?php echo $row['count_items']; ?></td>
        </tr>
    <?php endforeach; ?>

</table>