<?php
    $internalData = !is_null($this->getInternalData()) ? $this->getInternalData() : array();
    $selectCallback = $this->getSelectCallback();
    $unselectCallback = $this->getUnselectCallback();
    $taxCategories = $this->_getTaxCategories();
    $attributes = Mage::helper('M2ePro/Magento_Attribute')->getAttributesLabels($this->getAttributes());
    $isInterfaceModeFull = $this->isInterfaceModeFull();
    $isShowEditLinks = $this->isShowEditLinks();
?>

<?php if (!$this->_isAjax): ?>
    <div id="<?php echo $this->getDivId(); ?>">
<?php endif; ?>

<script type="text/javascript">
    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_ebay_category')) ?>);
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Template_Category'); ?>,
        'Ess_M2ePro_Model_Ebay_Template_Category'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Ebay_Category'); ?>,
        'Ess_M2ePro_Helper_Component_Ebay_Category'
    );
    M2ePro.translator.add(<?php echo json_encode(array(
        'Select' => Mage::helper('M2ePro')->escapeJs($this->__('Select')),
        'Reset' => Mage::helper('M2ePro')->escapeJs($this->__('Reset')),
        'No recently used categories' => Mage::helper('M2ePro')->escapeJs($this->__('No recently used categories')),
        'Change' => Mage::helper('M2ePro')->escapeJs($this->__('Change')),
        'Category' => Mage::helper('M2ePro')->escapeJs($this->__('Category')),
        'Not Selected' => Mage::helper('M2ePro')->escapeJs($this->__('Not Selected')),
        'No results' => Mage::helper('M2ePro')->escapeJs($this->__('No results')),
    )); ?>);

    EbayListingCategoryChooserHandlerObj = new EbayListingCategoryChooserHandler('<?php echo $this->getDivId(); ?>', '<?php echo $this->getMarketplaceId(); ?>', '<?php echo $this->getAccountId(); ?>');
    EbayListingCategoryChooserHandlerObj.setCategoryTitles(<?php echo json_encode(Ess_M2ePro_Block_Adminhtml_Ebay_Listing_Category_Chooser_Edit::getCategoryTitles()); ?>);
    EbayListingCategoryChooserHandlerObj.setSelectedCategories(<?php echo json_encode($this->getInternalData()); ?>);
    EbayListingCategoryChooserHandlerObj.setAttributes(<?php echo json_encode($this->getAttributes()); ?>);
    EbayListingCategoryChooserHandlerObj.setInterfaceMode(<?php echo json_encode($this->getInterfaceMode()); ?>);
    EbayListingCategoryChooserHandlerObj.setShowEditLinks(<?php echo json_encode($this->isShowEditLinks()); ?>);

    <?php if (!empty($selectCallback)): ?>
        EbayListingCategoryChooserHandlerObj.setSelectCallback(<?php echo $selectCallback; ?>);
    <?php endif; ?>

    <?php if (!empty($unselectCallback)): ?>
        EbayListingCategoryChooserHandlerObj.setUnselectCallback(<?php echo $unselectCallback; ?>);
    <?php endif; ?>

</script>

<div id="ebay_category_chooser" class="ebay_category_chooser">

    <?php if ($isInterfaceModeFull): ?>
        <div class="entry-edit" id="magento_block_ebay_listing_category_chooser_ebay">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Category'); ?></h4>
            </div>
    <?php endif; ?>

    <div class="fieldset">
        <div class="hor-scroll">

            <?php if (!$isInterfaceModeFull): ?>
                <h5><?php echo Mage::helper('M2ePro')->__('eBay Category'); ?></h5>
            <?php endif; ?>

            <table class="form-list" cellspacing="0" cellpadding="0" <?php if (!$isInterfaceModeFull): ?>style="padding-left: 25px" <?php endif; ?>>

                <tr>
                    <td class="label" style="width: 110px;">
                        <?php echo Mage::helper('M2ePro')->__('Primary'); ?>: <span class="required">*</span>
                    </td>
                    <td class="value" style="min-width: 300px;">
                        <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN]['mode'])
                                  && $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN]['mode'] != Ess_M2ePro_Model_Ebay_Template_Category::CATEGORY_MODE_NONE): ?>
                            <?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN]['path']; ?>
                        <?php else: ?>
                            <span style="font-style: italic; color: grey"><?php echo Mage::helper('M2ePro')->__('Not Selected'); ?></span>
                            <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN]['message'])): ?>
                                <div class="validation-advice default-value-message"><?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN]['message']; ?></div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="validation-advice main-empty-advice" style="display: none;"><?php echo Mage::helper('M2ePro')->__('eBay Primary Category must be selected.') ?></div>
                    </td>
                    <?php if ($isShowEditLinks): ?>
                        <td class="value">
                            <a href="#" onclick="EbayListingCategoryChooserHandlerObj.showEditPopUp(<?php echo Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_MAIN; ?>)"><?php echo Mage::helper('M2ePro')->__('Edit'); ?></a>
                        </td>
                    <?php endif; ?>
                </tr>

                <tr>
                    <td class="label" style="width: 110px;">
                        <?php echo Mage::helper('M2ePro')->__('Secondary'); ?>:
                    </td>
                    <td class="value" style="min-width: 300px;">
                        <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY]['mode'])
                            && $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY]['mode'] != Ess_M2ePro_Model_Ebay_Template_Category::CATEGORY_MODE_NONE): ?>
                            <?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY]['path']; ?>
                        <?php else: ?>
                            <span style="font-style: italic; color: grey"><?php echo Mage::helper('M2ePro')->__('Not Selected'); ?></span>
                            <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY]['message'])): ?>
                                <div class="validation-advice default-value-message"><?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY]['message']; ?></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if ($isShowEditLinks): ?>
                        <td class="value">
                            <a href="#" onclick="EbayListingCategoryChooserHandlerObj.showEditPopUp(<?php echo Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_EBAY_SECONDARY; ?>)"><?php echo Mage::helper('M2ePro')->__('Edit'); ?></a>
                        </td>
                    <?php endif; ?>
                </tr>

            </table>

        </div>
    </div>
    <?php if ($isInterfaceModeFull): ?>
        </div>
    <?php endif; ?>

    <?php if ($this->isShowStoreCatalog()): ?>

    <?php if ($isInterfaceModeFull): ?>
        <div class="entry-edit" id="magento_block_ebay_listing_category_chooser_store">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Store Category'); ?></h4>
            </div>
    <?php endif; ?>

    <div class="fieldset">
        <div class="hor-scroll">

            <?php if (!$isInterfaceModeFull): ?>
                <h5><?php echo Mage::helper('M2ePro')->__('eBay Store Category'); ?></h5>
            <?php endif; ?>

            <table class="form-list" cellspacing="0" cellpadding="0" <?php if (!$isInterfaceModeFull): ?>style="padding-left: 25px" <?php endif; ?>>

                <tr>
                    <td class="label" style="width: 110px;">
                        <?php echo Mage::helper('M2ePro')->__('Primary'); ?>:
                    </td>
                    <td class="value" style="min-width: 300px;">
                        <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN]['mode'])
                                  && $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN]['mode'] != Ess_M2ePro_Model_Ebay_Template_Category::STORE_CATEGORY_MODE_NONE): ?>
                            <?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN]['path']; ?>
                        <?php else: ?>
                            <span style="font-style: italic; color: grey"><?php echo Mage::helper('M2ePro')->__('Not Selected'); ?></span>
                            <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN]['message'])): ?>
                                <div class="validation-advice default-value-message"><?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN]['message']; ?></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if ($isShowEditLinks): ?>
                        <td class="value">
                            <a href="#" onclick="EbayListingCategoryChooserHandlerObj.showEditPopUp(<?php echo Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_MAIN; ?>)"><?php echo Mage::helper('M2ePro')->__('Edit'); ?></a>
                        </td>
                    <?php endif; ?>
                </tr>

                <tr>
                    <td class="label" style="width: 110px;">
                        <?php echo Mage::helper('M2ePro')->__('Secondary'); ?>:
                    </td>
                    <td class="value" style="min-width: 300px;">
                        <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY]['mode'])
                            && $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY]['mode'] != Ess_M2ePro_Model_Ebay_Template_Category::STORE_CATEGORY_MODE_NONE): ?>
                            <?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY]['path']; ?>
                        <?php else: ?>
                            <span style="font-style: italic; color: grey"><?php echo Mage::helper('M2ePro')->__('Not Selected'); ?></span>
                            <?php if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY]['message'])): ?>
                                <div class="validation-advice default-value-message"><?php echo $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY]['message']; ?></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if ($isShowEditLinks): ?>
                        <td class="value">
                            <a href="#" onclick="EbayListingCategoryChooserHandlerObj.showEditPopUp(<?php echo Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_STORE_SECONDARY; ?>)"><?php echo Mage::helper('M2ePro')->__('Edit'); ?></a>
                        </td>
                    <?php endif; ?>
                </tr>

            </table>

        </div>
    </div>

    <?php if ($isInterfaceModeFull): ?>
        </div>
    <?php endif; ?>

    <?php endif; ?>

    <?php if (Ess_M2ePro_Model_Ebay_Template_Category::isTaxCategoryShow()): ?>

        <?php if ($isInterfaceModeFull): ?>
            <div class="entry-edit" id="magento_block_ebay_listing_category_chooser_tax_category">

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Tax Category'); ?></h4>
                </div>
        <?php endif; ?>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label" style="width: 135px;">
                            <?php echo Mage::helper('M2ePro')->__('Tax Category'); ?>:
                        </td>
                        <td class="value" style="min-width: 300px;">
                            <?php $selectedTaxCategory = ''; ?>
                            <select id="tax_category" onchange="EbayListingCategoryChooserHandlerObj.taxCategoryChange(this)">
                                <option value=""><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <?php if (!empty($taxCategories)): ?>
                                    <optgroup label="Ebay Recommended" tax_category_mode="<?php echo Ess_M2ePro_Model_Ebay_Template_Category::TAX_CATEGORY_MODE_VALUE ?>">
                                        <?php
                                            if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]) &&
                                                $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]['mode'] == Ess_M2ePro_Model_Ebay_Template_Category::TAX_CATEGORY_MODE_VALUE
                                            ) {
                                                $selectedTaxCategory = $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]['value'];
                                            }
                                        ?>
                                        <?php foreach ($taxCategories as $taxCategory): ?>
                                            <option value="<?php echo $taxCategory['ebay_id']; ?>" <?php if ($selectedTaxCategory == $taxCategory['ebay_id']): ?>selected="selected"<?php endif; ?>><?php echo $taxCategory['title']; ?></option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endif; ?>
                                <?php if (!empty($attributes)): ?>
                                    <optgroup label="Magento Attributes" tax_category_mode="<?php echo Ess_M2ePro_Model_Ebay_Template_Category::TAX_CATEGORY_MODE_ATTRIBUTE ?>">
                                        <?php
                                            $selectedTaxCategory = '';
                                            if (isset($internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]) &&
                                                $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]['mode'] == Ess_M2ePro_Model_Ebay_Template_Category::TAX_CATEGORY_MODE_ATTRIBUTE
                                                ) {

                                                $selectedTaxCategory = $internalData[Ess_M2ePro_Helper_Component_Ebay_Category::CATEGORY_TYPE_TAX]['attribute'];
                                            }
                                        ?>
                                        <?php foreach ($attributes as $attribute): ?>
                                            <option value="<?php echo $attribute['code']; ?>" <?php if ($selectedTaxCategory == $attribute['code']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->__($attribute['label']); ?></option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endif; ?>
                            </select>
                            <?php  ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

        <?php if ($isInterfaceModeFull): ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

</div>

<?php if (!$this->_isAjax): ?>
    </div>
<?php endif; ?>