<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>

<?php echo $this->getChildHtml('view_header'); ?>

<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('You have to set eBay Categories before you can List Items on eBay.'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">

    <div style="padding: 2px"></div>

    <span>
        <?php echo Mage::helper('M2ePro')->__('Choose one of the options below.');?>
    </span>

    <form id="categories_mode_form" method="post" action="<?php echo $this->getUrl('*/*/*',array('step' => 1, '_current' => true)); ?>">

        <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

        <div style="margin:15px 0 0 10px">

            <input id="same" name="mode" type="radio" value="same">&nbsp;&nbsp;
            <label style="font-weight: bold" for="same"><?php echo Mage::helper('M2ePro')->__('The same category'); ?></label>

            <div style="margin: 10px 22px">
                <?php echo Mage::helper('M2ePro')->__('The Products will all have the same category.'); ?>
            </div>

            <?php if (Mage::helper('M2ePro/View_Ebay')->isAdvancedMode()) { ?>

                <input id="category" name="mode" type="radio" value="category">&nbsp;&nbsp;
                <label style="font-weight: bold" for="category"><?php echo Mage::helper('M2ePro')->__('Based on Magento categories'); ?></label>

                <div style="margin: 10px 22px">
                    <?php echo Mage::helper('M2ePro')->__('The products will all have the eBay categories that are based on Magento categories.'); ?>
                </div>

            <?php } ?>

            <input id="product" name="mode" type="radio" value="product">&nbsp;&nbsp;
            <label style="font-weight: bold" for="product"><?php echo Mage::helper('M2ePro')->__('Get suggested categories'); ?></label>

            <div style="margin: 10px 22px">
                <?php echo Mage::helper('M2ePro')->__('eBay suggests the best categories for your products based on title and attribute set of product.'); ?>
            </div>

            <?php if (Mage::helper('M2ePro/View_Ebay')->isAdvancedMode()) { ?>

                <input id="manually" name="mode" type="radio" value="manually">&nbsp;&nbsp;
                <label style="font-weight: bold" for="manually"><?php echo Mage::helper('M2ePro')->__('Set manually for each product'); ?></label>

                <div style="margin: 10px 22px">
                    <?php echo Mage::helper('M2ePro')->__('You have complete freedom to choose (individually, or by grouping a set of products together) the most suitable eBay category for your products.'); ?>
                </div>

            <?php } ?>

        </div>
    </form>

</div>

<script type="text/javascript">

    var init = function() {
        var mode = '<?php echo $this->getData('mode'); ?>';
        $$('input[value='+mode+']').shift().checked = true;
    };

    Event.observe(window,'load',init);
</script>
