<?php
$internalData = $this->getInternalData();
$categoryData = $this->getCategoryData();

$customSpecifics = $this->getCustomSpecifics();
if (isset($categoryData['item_specifics']['specifics'])) {
    $categoryData['item_specifics']['specifics'] = array_merge($categoryData['item_specifics']['specifics'], $customSpecifics['specifics']);
} else {
    $categoryData['item_specifics']['specifics'] = $customSpecifics['specifics'];
}

$defaults = array(
    'motors_specifics_attribute' => '',
);
$internalData = array_merge($defaults, $internalData);
?>

<?php if (!$this->_isAjax): ?>
    <?php echo '<div id="' . $this->getDivId() . '">'; ?>
<?php endif; ?>

<script type="text/javascript">

    M2ePro.translator.add(<?php echo json_encode(array(

        'The category <b>%cat%</b> doesn\'t have Item Specific.' => Mage::helper('M2ePro')->escapeJs($this->__('The category <b>%cat%</b> doesn\'t have Item Specific.')),
        'Only Text Area type attributes are allowed.'            => Mage::helper('M2ePro')->escapeJs($this->__('Only Text Area type attributes are allowed.')),

    )); ?>);

    M2ePro.url.add(<?php echo json_encode(Mage::helper('M2ePro')->getControllerActions('adminhtml_ebay_category')) ?>);

    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Ebay'); ?>,
        'Ess_M2ePro_Helper_Component_Ebay'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Template_Category'); ?>,
        'Ess_M2ePro_Model_Ebay_Template_Category'
    );
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Ebay_Template_Category_Specific'); ?>,
        'Ess_M2ePro_Model_Ebay_Template_Category_Specific'
    );

    // Data for current tab
    //-----------------------------
    M2ePro.formData.motors_specifics_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($internalData['motors_specifics_attribute']); ?>';

    var init = function() {

        EbayListingCategorySpecificHandlerObj = new EbayListingCategorySpecificHandler('<?php echo $this->getCategoryMode(); ?>',
                                                                         '<?php echo $this->getCategoryValue(); ?>',
                                                                         '<?php echo $this->getMarketplaceId(); ?>');

        EbayListingCategorySpecificHandlerObj.setDivId('<?php echo $this->getDivId(); ?>');
        EbayListingCategorySpecificHandlerObj.setAttributes(<?php echo json_encode($this->getAttributes()); ?>);
        EbayListingCategorySpecificHandlerObj.setSelectedSpecifics(<?php echo json_encode($this->getSelectedSpecifics()); ?>);
        EbayListingCategorySpecificHandlerObj.initCategory();

        <?php if ($this->getCategoryMode() == Ess_M2ePro_Model_Ebay_Template_Category::CATEGORY_MODE_EBAY): ?>
            EbayListingCategorySpecificHandlerObj.setCategoryData(<?php echo json_encode($categoryData); ?>);
        <?php else: ?>
            EbayListingCategorySpecificHandlerObj.setCategoryData({"item_specifics": <?php echo json_encode($this->getCustomSpecifics()); ?>});
        <?php endif; ?>

        specificForm = new varienForm('category_specific_form', '<?php echo $this->getValidationUrl(); ?>');
    };

    <?php if ($this->_isAjax) { ?>
        init();

    <?php } else { ?>
        Event.observe(window, 'load', init);
    <?php } ?>

    //-----------------------------

</script>

<form id="category_specific_form">

<div id="listing_category_specific_item_specifics_container">

    <div id="block_notice_ebay_category_specific_item_specifics" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Specifics'); ?>">
        <?php echo Mage::helper('M2ePro')->__(
            'Adding specific item details will attract your buyers and help them to find your item in a search. We recommend using as many item specifics as you can.
            <br/>There are mandatory specifics and the chance to create your own.
            <br/>
            <br/>There are four options available to you.
            <br/>
            <ul class="list">
                <li>
                    <b>eBay Recommended</b>
                    <br/>eBay recommends certain characteristics your item may possess. Simply choose the most appropriate one from the drop down menu.
                    <br>So if you are selling headphones, eBay will recommend an ABC list of the most common brands from Apple and Bose to Creative.
                    <br/>This is a sensible option for beginners to eBay.
                    <br/>
                    <b>Note:</b> These options correspond to the Primary eBay Category, not any Secondary Category you may have chosen.
                </li>
                <li>
                    <b>Custom Attribute</b>
                    <br/>You can create more customisable detail by choosing the Custom Attribute that contains the item specific.
                </li>
                <li>
                    <b>Custom Value</b>
                    <br/>This allows you to manually type specific information about your product rather than choosing from a dropdown list.
                    <br/>This is particularly useful if the eBay recommended option does not include information about the specific item you have for sale.
                </li>
                <li>
                    <b>None</b>
                    <br/>You choose not to offer potential buyers any item specific information. Be aware that this may hamper your items appearing in eBay search results.
                </li>
            </ul>'
        ); ?>
    </div>

    <div class="entry-edit" id="magento_block_ebay_category_specific_item_specifics">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Specifics'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table id="item_specifics_table" class="form-list" cellspacing="0" cellpadding="0" style="width: 100%">

                    <tr>

                        <td colspan="2">

                            <table class="form-list" cellspacing="0" cellpadding="0" style="width: 100%;">

                                <tr class="item-specifics-tr">
                                    <td class="grid" colspan="2">

                                        <table class="border" cellpadding="0" cellspacing="0">
                                            <thead>
                                            <tr class="headings">
                                                <th style="width: 30%;"><?php echo Mage::helper('M2ePro')->__('Name'); ?></th>
                                                <th style="width: 30%;"><?php echo Mage::helper('M2ePro')->__('Mode'); ?></th>
                                                <th style="width: 37%;"><?php echo Mage::helper('M2ePro')->__('Value'); ?></th>
                                                <th style="width: 3%;">&nbsp;</th>
                                            </tr>
                                            </thead>
                                            <tbody id="item_specifics_tbody">
                                            <!-- #specific_table_row_template inserts here -->
                                            </tbody>
                                            <tfoot id="add_custom_container">
                                            <tr>
                                                <td colspan="4" class="a-right"><?php echo $this->getChildHtml('add_custom_specific_button'); ?></td>
                                            </tr>
                                            </tfoot>
                                        </table>

                                    </td>
                                </tr>

                            </table>

                            <p class="note note-no-tool-tip">
                                <?php echo Mage::helper('M2ePro')->__('Add more information to help buyers find your item in search results.') ?>
                            </p>

                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

<div id="listing_category_specific_motors_specifics_container" style="display: none;">

    <div id="block_notice_ebay_category_specific_motors_specifics" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Compatibility'); ?>">
        <?php echo Mage::helper('M2ePro')->__('Parts compatibility is a better way for sellers to list parts that fit a variety of vehicles. This format adds standard information to your listing. You can create one listing describing a single part and add a complete list of compatible vehicles.
    <br/><br/><u>To use this feature you have to:</u>
     <ul class="list">
        <li>In the section below choose the attribute, which will be used for saving ePIDs (Product Reference IDs) of compatible vehicles.</li>
        <li>In created M2E listing on the \'View Listing\' page use the <b>Add Compatible Vehicles tool</b> to find necessary compatible items.</li>
    </ul>
'); ?>
    </div>

    <div class="entry-edit" id="magento_block_ebay_category_specific_motors_specifics">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Compatibility'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="motors_specifics_attribute"><?php echo Mage::helper('M2ePro')->__('Compatibility Attribute'); ?>:</label>
                        </td>
                        <td id="motors_specifics_attribute_td" class="value"></td>
                        <td id="motors_specifics_attribute_td_note">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose only Text Area type attribute.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

<script type="text/m2e-template-html" id="specific_template">

    <input id="item_specifics_mode_%i%" name="item_specifics_mode_%i%" value="%relation_mode%" type="hidden" />
    <input id="item_specifics_mode_relation_id_%i%" name="item_specifics_mode_relation_id_%i%" value="%relation_id%" type="hidden" />

    <input id="item_specifics_attribute_id_%i%" name="item_specifics_attribute_id_%i%" value="%attribute_id%" type="hidden" />
    <input id="item_specifics_attribute_title_%i%" name="item_specifics_attribute_title_%i%" value="%attribute_title%" type="hidden" />

    <tr id="specific_%i%_row" class="specific-row not-custom" style="height: 30px;">
        <td style="vertical-align:top;">
            <span id="attribute_title_%i%">%attribute_title%%required%</span>
            <input id="custom_item_specifics_label_custom_value_%i%" name="custom_item_specifics_label_custom_value_%i%" type="text" style="display: none; width: 98%;" class="input-text M2ePro-required-when-visible custom-item-specific" />
            <input id="custom_item_specifics_label_custom_label_attribute_%i%" name="custom_item_specifics_label_custom_label_attribute_%i%" type="text" style="display: none; width: 98%;" class="input-text M2ePro-required-when-visible custom-item-specific" />
            <span id="custom_item_specifics_label_custom_attribute_%i%" style="display:none;"><strong>From attribute label</strong></span>
        </td>
        <td style="vertical-align:top;">
            <select id="item_specifics_value_mode_%i%" name="item_specifics_value_mode_%i%" style="width: 100%; margin-bottom: 2px;" onchange="EbayListingCategorySpecificHandlerObj.specificModeChange(this);">
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_NONE ?>" class="specific-mode-none"><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_EBAY_RECOMMENDED ?>" class="specific-mode-recommended"><?php echo Mage::helper('M2ePro')->__('eBay Recommended'); ?></option>
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_CUSTOM_VALUE ?>" class="specific-mode-custom-value"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_CUSTOM_ATTRIBUTE ?>" class="custom-specific-mode-custom-attribute"><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
            </select>
            <select id="custom_item_specifics_value_mode_%i%" name="custom_item_specifics_value_mode_%i%" style="display: none; width: 100%;margin-bottom: 2px;" onchange="EbayListingCategorySpecificHandlerObj.specificCustomModeChange(this);">
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_CUSTOM_ATTRIBUTE ?>" class="custom-specific-mode-custom-attribute"><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_CUSTOM_VALUE ?>" class="custom-specific-mode-custom-value"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_Category_Specific::VALUE_MODE_CUSTOM_LABEL_ATTRIBUTE ?>" class="custom-specific-mode-custom-label-attribute"><?php echo Mage::helper('M2ePro')->__('Custom Label / Attribute'); ?></option>
            </select>
        </td>
        <td id="specific_value_%i%_cell" style="width: 100%; vertical-align:top; text-align: left; padding-top: 2px !important;" class="value">
            <input id="item_specifics_value_custom_value_%i%" name="item_specifics_value_custom_value_%i%" type="text" style="display: none; width: 100%; padding-left: 2px; padding-right: 0px;" class="input-text M2ePro-required-when-visible item-specific" />
            <select id="item_specifics_value_ebay_recommended_%i%" name="item_specifics_value_ebay_recommended_%i%" style="display: none; width: 100%;" class="M2ePro-required-when-visible item-specific"></select>
            <select id="item_specifics_value_custom_attribute_%i%" name="item_specifics_value_custom_attribute_%i%" style="display: none; width: 100%;"></select>
        </td>
        <td id="custom_item_specific_remove_%i%" style="display: none; text-align: center; vertical-align: middle;">
            <?php echo $this->getChildHtml('remove_custom_specific_button'); ?>
        </td>
    </tr>

</script>

</form>

<?php if (!$this->_isAjax): ?>
    <?php echo '</div>'; ?>
<?php endif; ?>