<?php

$version = Mage::helper('M2ePro/Module')->getVersion();
$skipWizardLink = $this->getUrl("*/adminhtml_wizard_buy/skip");
$startWizardLink = $this->getUrl("*/adminhtml_wizard_buy");

?>

<div class="wizard-note">

    <a class="wizard-close" href="javascript:void(0);" onclick="WizardHandlerObj.skip('<?php echo $skipWizardLink; ?>');" title="<?php echo Mage::helper('M2ePro')->__('Skip Wizard') ?>">&times;</a>

    <div>
        <?php

        echo Mage::helper('M2ePro')->__(
            'Click
            <a href="%s" onclick="%s">Start Configuration</a> Wizard to quickly set up <strong>Rakuten.com</strong> settings or
            <a href="%s" onclick="%s">Skip</a> it if you intend to set up it later. <br/>
            <strong>Note:</strong> If you close the Wizard now, you will have to set up Rakuten.com settings manually.',
            'javascript:',
            'setLocation(\''.$startWizardLink.'\')',
            'javascript:',
            'confirm(M2ePro.text.skip_confirm) && setLocation(\''.$skipWizardLink.'\')'
        );

        ?>
    </div>

</div>