<div id="block_notice_buy_synchronization_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set preferences of data synchronization.<br/>
    You have to enable / disable synchronization tasks, which will be automatically performed for all Rakuten.com accounts, and <span style="text-decoration: underline;">Save Settings</span>.<br/>
    To run necessary task manually, click the <span style="text-decoration: underline;">Run Now</span> button, to run all tasks at once, click <span style="text-decoration: underline;">Run Enabled Now</span>.<br/>'); ?>
</div>