<div id="block_notice_ebay_configuration_category_edit_primary" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Primary Category'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Every time you set a category you specify Item Specifics adapted to M2E listing or product it is set for.
<br>All variety of Item Specifics sets you can find on the Specifics tab.
The number of sets is equal to the number of category usage in M2E.
<br>
<br>
<b>Note:</b> When you change a Primary category, you will need to specify Item Specifics for every created dates.
'); ?>
</div>