<div id="block_notice_play_listing_general_search" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In this Section you can specify the source from which the values for Item Identifiers (ISNBN, UPC/EAN, Play ID) will be taken in case you have those for your Items. <br/><br/>
    These Settings will be used during the list process. <br/>
    For example if you have ISBN Attribute with valid value in your Item, M2E Pro will perform Search on Play.com according to the data provided in this Attribute and, if the match is found, link the Magento Product to Play.com Item.<br/>
    These Setting will also be used during automatic ISBN Search. <br/>
    In this case the parameters are used according to the following logic:

    <ul class="list">
        <li>the Product is searched by specified Item Identifier. (if specified)</li>
        <li>if no result by Identifier parameter, then additional Search by Magento Product name is performed. (if enabled)</li>
    </ul>'); ?>
</div>

<?php

    /** @var Ess_M2ePro_Helper_Magento_Attribute $magentoAttributeHelper */
    $magentoAttributeHelper = Mage::helper('M2ePro/Magento_Attribute');

    $attributesByInputTypes = array(
        'text' => $magentoAttributeHelper->filterByInputTypes($this->getData('general_attributes'), array('text')),
    );

?>

<script type="text/javascript">
    // Data for current tab
    // ----------------------------
    M2ePro.php.setConstants(
        <?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Helper_Component_Play'); ?>,
        'Ess_M2ePro_Helper_Component_Play'
    );

    M2ePro.text.general_id_label_upc = '<?php echo Mage::helper('M2ePro')->__('UPC/EAN Attribute') ?>';
    M2ePro.text.general_id_label_play_id = '<?php echo Mage::helper('M2ePro')->__('Play ID Attribute') ?>';
    M2ePro.text.general_id_label_isbn = '<?php echo Mage::helper('M2ePro')->__('ISBN Attribute') ?>';

    M2ePro.text.general_id_tips_play_id = '<?php echo Mage::helper('M2ePro')->__('Parameter the Product Search will be performed by.<br/>For ex.: http://www.play.com/Mobiles/Mobile/4-/20020059/-/Product.html.<br/>Play ID = 20020059'); ?>';
    M2ePro.text.general_id_tips_default = '<?php echo Mage::helper('M2ePro')->__('Parameter the Product Search will be performed by.') ?>';

    //-----------------------------
    Event.observe(window, 'load', function() {

        PlayListingChannelSettingsHandlerObj = new PlayListingChannelSettingsHandler();
        PlayListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Play_Listing'); ?>');

        $('general_id_mode').observe('change', PlayListingChannelSettingsHandlerObj.general_id_mode_change);
        $F('general_id_mode') && $('general_id_mode').simulate('change');

        $('general_id_custom_attribute').observe('change', PlayListingChannelSettingsHandlerObj.general_id_custom_attribute_change);
        $F('general_id_custom_attribute') && $('general_id_custom_attribute').simulate('change');

    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_play_listing_channel_settings_source">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Search Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="general_id_mode_container">
                    <td class="label">
                        <label for="general_id_mode"><?php echo Mage::helper('M2ePro')->__('Identifiers'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="general_id_mode" name="general_id_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET ?>" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_WORLDWIDE ?>" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_WORLDWIDE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('UPC/EAN') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_GENERAL_ID ?>" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_GENERAL_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Play ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_ISBN ?>" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_ISBN) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('ISBN') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Identifiers Search Settings.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="general_id_custom_attribute_container" <?php if ($this->getData('general_id_mode') == Ess_M2ePro_Model_Play_Listing::GENERAL_ID_MODE_NOT_SET): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="general_id_custom_attribute" id="general_id_attribute_label"></label>
                    </td>
                    <td class="value">
                        <select id="general_id_custom_attribute" name="general_id_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($this->getData('general_id_custom_attribute') == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($attributesByInputTypes['text'] as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($this->getData('general_id_custom_attribute') == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Specify the Attribute, which contains necessary information.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_play_listing_add_search_advanced">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Additional Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="search_by_magento_title_mode"><?php echo Mage::helper('M2ePro')->__('Search by Product Name'); ?>:
                    </td>
                    <td class="value">
                        <select id="search_by_magento_title_mode" name="search_by_magento_title_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE ?>" <?php if ($this->getData('search_by_magento_title_mode') == Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Disable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES ?>" <?php if ($this->getData('search_by_magento_title_mode') == Ess_M2ePro_Model_Play_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Enable') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If no results are found by the Search criteria above, the additional Search will be performed by Magento Product Name.'); ?></span>
                        </p>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>
