<div id="block_notice_wizard_welcome_description" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php $tempString = Mage::helper('M2ePro')->__('<strong>You have successfully installed M2E Pro v. %s.</strong><br/><br/>
    The next step is setting up of the main settings, such as Cron job, Licensing (extension does not work without license)
    and others to enable a proper work of the extension.<br/>
    In the table below there are recommended server settings, which guaranty a stable work of the extension. <br/><br/>
    Press the <span style="text-decoration: underline;">Start Configuration</span> button to start setting M2E Pro configuration.',
    Mage::helper('M2ePro/Module')->getVersion());
    echo $tempString; ?>
</div>