<div id="block_notice_common_synchronization_templates" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In this section you can Create, Edit, and Delete Synchronization Policies. <br/><br/>
    In the Synchronization Policy you can set the rules by which the dynamic data synchronization between Amazon and Magento will be performed. <br/>
    '); ?>
</div>