<!-- ########################################################################################### -->

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.getDebugInformation = '<?php echo $this->getUrl('*/adminhtml_order/getDebugInformation', array('id' => $this->getRequest()->getParam('id'))); ?>';

    var debugKeys = [68, 69, 66, 85, 71];
    var debugPressedKeys = [];

    document.observe('keydown', function (event) {

        if (debugPressedKeys.length < debugKeys.length) {
            if (debugKeys[debugPressedKeys.length] == event.keyCode) {
                debugPressedKeys.push(event.keyCode);
                if (debugPressedKeys.length == debugKeys.length) {

                    if (!$('magento_block_debug_information')) {
                        new Ajax.Request( M2ePro.url.getDebugInformation ,
                            {
                                method: 'get',
                                asynchronous: true,
                                onSuccess: function(transport)
                                {
                                    $$('.content-header')[0].insert({
                                        after: transport.responseText
                                    });
                                }
                            });
                    }

                    debugPressedKeys = [];
                }
            } else {
                debugPressedKeys = [];
            }
        }
    });

</script>

<!-- ########################################################################################### -->

<?php echo $this->getChildHtml('item_edit'); ?>

<div class="box-left">
    <div class="entry-edit" id="magento_block_ebay_orders_general" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('M2ePro')->__('eBay Order');?> # <?php echo $this->order->getData('ebay_order_id'); ?>
                <?php if ((int)$this->order->getData('selling_manager_record_number') > 0) { ?>
                    [ <?php echo Mage::helper('M2ePro')->__('Selling Manager') . ': # ' . $this->order->getData('selling_manager_record_number') ?> ]
                <?php } ?>
            </h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Magento Order #');?></td>
                            <td class="value">
                                <strong>
                                    <?php if (!is_null($this->realMagentoOrderId)) { ?>

                                        <?php if (!is_null($this->realMagentoOrderId)) { ?>
                                            <a href="<?php echo $this->getUrl('adminhtml/sales_order/view/', array('order_id' => $this->order->getData('magento_order_id'))); ?>" target="_blank"><?php echo $this->realMagentoOrderId; ?></a>
                                        <?php } else { ?>
                                            <?php echo $this->order->getData('magento_order_id'); ?>
                                        <?php } ?>

                                    <?php } else { ?>

                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>

                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Sale Time');?></td>
                            <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('purchase_create_date'), 'medium', true); ?></strong></td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Update Time');?></td>
                            <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('purchase_update_date'), 'medium', true); ?></strong></td>
                        </tr>

                        <?php if (!is_null($this->order->getData('reservation_start_date'))): ?>
                        <tr>
                                <td class="label"><?php echo Mage::helper('M2ePro')->__('Reservation Time') ?></td>
                                <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('reservation_start_date'), 'medium', true); ?></strong></td>
                            </tr>
                        <?php endif; ?>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Order Status'); ?></td>
                            <td class="value">
                                <strong>

                                    <b><?php echo Mage::helper('M2ePro')->__('Checkout'); ?>: </b>

                                    <?php if ($this->order->getChildObject()->isCheckoutCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
                                    <?php } else {
                                        echo Mage::helper('M2ePro')->__('Incomplete');
                                    } ?>

                                    <br />

                                    <b><?php echo Mage::helper('M2ePro')->__('Payment'); ?>: </b>

                                    <?php if ($this->order->getChildObject()->isPaymentCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Paid'); ?></span>

                                    <?php } else if ($this->order->getChildObject()->isPaymentStatusUnknown()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Unknown Error'); ?>

                                    <?php } else { ?>
                                        <!-- TODO: receive and show error from eBay -->
                                        <?php echo Mage::helper('M2ePro')->__('Waiting'); ?>
                                    <?php } ?>

                                    <br />

                                    <b><?php echo Mage::helper('M2ePro')->__('Shipping'); ?>: </b>

                                    <?php if ($this->order->getChildObject()->isShippingCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Shipped'); ?></span>

                                    <?php } else if ($this->order->getChildObject()->isShippingInProcess()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Not Shipped'); ?>

                                    <?php } else if ($this->order->getChildObject()->isShippingMethodNotSelected()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Waiting'); ?>

                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Unknown Error'); ?>
                                    <?php } ?>

                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Account');?></td>
                            <td class="value">
                                <strong>

                                    <?php if (!$this->order->getAccount()->getId()) { ?>
                                        <span style="color: red;"><?php echo Mage::helper('M2ePro')->__('Deleted'); ?></span>

                                    <?php } else { ?>

                                        <a href="<?php echo $this->getUrl('*/adminhtml_ebay_account/edit', array('id' => $this->order->getAccount()->getId())); ?>" target="_blank"><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getAccount()->getTitle()); ?></a>

                                        <?php echo '(' . ($this->order->getAccount()->getChildObject()->isModeProduction() ? Mage::helper('M2ePro')->__('Production') : Mage::helper('M2ePro')->__('Sandbox')) . ')'; ?>

                                    <?php }?>

                                </strong>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

<div class="box-right">
    <div class="entry-edit" id="magento_block_ebay_orders_buyer" collapseable="no" magento_block="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Buyer Information');?></h4>
            <div style="float: right;">
                <a href="<?php echo $this->getUrl('*/*/editShippingAddress', array('id' => $this->order->getId())) ?>"><?php echo Mage::helper('M2ePro')->__('Edit') ?></a>
            </div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Customer Name');?></td>
                            <td class="value">
                                <strong>

                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_name')) ?><br/>

                                    <?php if ($this->order->getData('buyer_email') != '') { ?>
                                        <?php if (stripos($this->order->getData('buyer_email'), 'Invalid Request') !== false) { ?>
                                            &lt;<?php echo Mage::helper('M2ePro')->__('Private Restriction'); ?>&gt;<br />
                                        <?php } else { ?>
                                            &lt;<?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_email')); ?>&gt;<br />
                                        <?php } ?>
                                    <?php } ?>

                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_userid')) ?>

                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Address'); ?></td>
                            <td class="value">
                                <strong>

                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_name')) ?>

                                    <?php if (!empty($this->shippingAddress)): ?>

                                        <?php if (!empty($this->shippingAddress['street'][0])): ?>
                                            <br /><?php echo Mage::helper('M2ePro')->escapeHtml($this->shippingAddress['street'][0]); ?>
                                        <?php endif; ?>

                                        <?php if (!empty($this->shippingAddress['street'][1])): ?>
                                            <br /><?php echo Mage::helper('M2ePro')->escapeHtml($this->shippingAddress['street'][1]); ?>
                                        <?php endif; ?>

                                        <?php if (!empty($this->shippingAddress['city'])): ?>
                                            <br /><?php echo Mage::helper('M2ePro')->escapeHtml(implode(', ', array($this->shippingAddress['city'], $this->shippingAddress['state'], $this->shippingAddress['postal_code']))) ?>
                                        <?php endif; ?>

                                        <?php if (!empty($this->shippingAddress['country_name'])): ?>
                                            <br />
                                            <?php
                                                if (!empty($this->shippingAddress['country_name'])) {
                                                    echo Mage::helper('M2ePro')->escapeHtml($this->shippingAddress['country_name']);
                                                } else {
                                                    echo Mage::helper('M2ePro')->escapeHtml($this->shippingAddress['country_code']);
                                                }
                                            ?>
                                        <?php endif; ?>

                                        <?php if (!empty($this->shippingAddress['phone']) && stripos($this->shippingAddress['phone'], 'Invalid Request') === false): ?>
                                            <br /><?php echo 'T: ' . Mage::helper('M2ePro')->escapeHtml($this->shippingAddress['phone']); ?>
                                        <?php endif; ?>

                                    <?php endif; ?>

                                </strong>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

<br style="clear: both;"/>

<div class="box-left">
    <div class="entry-edit" id="magento_block_ebay_orders_payment" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Payment Information');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Order Currency');?></td>
                            <td class="value">
                                <strong>
                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('currency')); ?>
                                </strong>

                                <?php
                                    if (!$this->isCurrencyAllowed()) {
                                        echo '<br /><b>' . Mage::helper('M2ePro')->__('Attention!') . '</b> ' . Mage::helper('M2ePro')->__('Order currency is not enabled in Magento.<br />Please, enable it in System -> Configuration -> Currency Setup.');
                                    } elseif (!$this->hasCurrencyConversionRate()) {
                                        echo '<br /><b>' . Mage::helper('M2ePro')->__('Attention!') . '</b> ' . Mage::helper('M2ePro')->__('There\'s no rate for Order currency in Magento.<br />Please, add currency convert rate in System -> Manage Currency -> Rates.');
                                    }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Payment Date');?></td>
                            <td class="value"><strong><?php echo $this->order->getData('payment_date') ? Mage::helper('core')->formatDate($this->order->getData('payment_date'), 'medium', true) : Mage::helper('M2ePro')->__('N/A'); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Payment Method');?></td>
                            <td class="value"><strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('payment_method')); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('eBay Account'); ?></td>
                            <td class="value"><strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_user_id')); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('eBay Final Fee');?></td>
                            <td class="value">
                                <strong>
                                    <?php if ($this->order->getData('final_fee') <= 0) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getCurrency(), round($this->order->getData('final_fee'), 2)); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                    </tbody>
                </table>

                <?php if ($this->order->getChildObject()->hasExternalTransactions()) { ?>
                    <br />
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td colspan="2" class="label" style="width: 100%">
                                    <h4><?php echo Mage::helper('M2ePro')->__('External Transactions'); ?></h4>
                                    <?php echo $this->getChildHtml('external_transaction'); ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                <?php } ?>

            </div>
        </div>

    </div>
</div>

<div class="box-right">
    <div class="entry-edit" id="magento_block_ebay_orders_shipping" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Shipping & Handling Information');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Selected Service');?></td>
                            <td class="value">
                                <strong>
                                    <?php if (is_null($this->order->getData('shipping_method'))) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('shipping_method')); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Cost');?></td>
                            <td class="value">
                                <strong>
                                    <?php if ($this->order->getShippingPrice() <= 0) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getCurrency(), $this->order->getShippingPrice()); ?>
                                        <?php echo $this->getShippingTaxSuffix(); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <?php if (!is_null($this->order->getData('shipping_date'))) { ?>
                            <tr>
                                <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Time');?></td>
                                <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('shipping_date'), 'medium', true); ?></strong></td>
                            </tr>
                        <?php } ?>

                        <?php if (count($this->order->getChildObject()->getShippingTrackingDetails())) { ?>

                            <tr>
                                <td class="grid" colspan="2">
                                    <br/>
                                    <h4><?php echo Mage::helper('M2ePro')->__('Tracking Details'); ?></h4>
                                    <table class="data" cellpadding="0" cellspacing="0">
                                        <thead>
                                            <tr class="headings">
                                                <th><?php echo Mage::helper('M2ePro')->__('Carrier'); ?></th>
                                                <th><?php echo Mage::helper('M2ePro')->__('Number'); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <?php foreach ($this->order->getChildObject()->getShippingTrackingDetails() as $key => $trackingDetail) { ?>
                                                <tr class="<?php echo $key%2 ? 'odd' : 'even'?>">
                                                    <td><?php echo $trackingDetail['title']; ?></td>
                                                    <td><?php echo $trackingDetail['number']; ?></td>
                                                </tr>
                                            <?php } ?>

                                        </tbody>
                                    </table>
                                </td>
                            </tr>

                        <?php } ?>

                    </tbody>
                </table>

            </div>
        </div>

    </div>

</div>

<br style="clear: both;"/>

<div class="entry-edit" id="magento_block_ebay_orders_transaction" collapseable="no">
    <div class="entry-edit-head">
        <h4 class="icon-head head-products"><?php echo Mage::helper('M2ePro')->__('Transaction Item(s)'); ?></h4>
    </div>
</div>

<div class="grid np">
    <div class="hor-scroll">
         <?php echo $this->getChildHtml('item'); ?>
    </div>
</div>

<br style="clear: both;"/>

<div class="box-left">

    <div class="entry-edit" id="magento_block_ebay_orders_message" collapseable="no">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Checkout Message From Buyer');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <?php if ($checkoutMessage = $this->order->getData('checkout_buyer_message')) { ?>
                <?php echo Mage::helper('M2ePro')->escapeHtml($checkoutMessage); ?>
            <?php } else { ?>
                <?php echo Mage::helper('M2ePro')->__('None') ?>
            <?php } ?>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_orders_history" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Log History');?></h4>
            <div class="form-buttons"></div>
        </div>

        <a name="order_log"></a>

        <div class="fieldset">
            <?php echo $this->getChildHtml('log'); ?>
        </div>

    </div>

</div>

<div class="box-right entry-edit" collapseable="no">

    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('M2ePro')->__('Order Totals');?></h4>
    </div>

    <div class="order-totals">
        <table cellspacing="0" width="100%">
            <tbody>

                <tr>
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Subtotal').$this->getTaxSuffix(); ?></td>
                    <td><span class="price"><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getChildObject()->getSubtotalPrice());?></span></td>
                </tr>

                <tr>
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping & Handling').$this->getTaxSuffix(); ?></td>
                    <td><span class="price"><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getChildObject()->getShippingPrice());?></span></td>
                </tr>

                <tr>
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Tax') ?></td>
                    <td><span class="price"><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getChildObject()->getRealTaxAmount());?></span></td>
                </tr>

            </tbody>

            <tfoot>

                <tr>
                    <td class="label">
                        <strong><big><?php echo Mage::helper('M2ePro')->__('Grand Total');?></big></strong>
                    </td>
                    <td class="emph"><big><strong><span class="price"><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getChildObject()->getGrandTotalPrice());?></span></strong></big></td>
                </tr>

                <tr>
                    <td class="label"><small><?php echo Mage::helper('M2ePro')->__('Amount Paid'); ?></small></td>
                    <td><span class="price"><small><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getData('paid_amount'));?></small></span></td>
                </tr>

                <tr>
                    <td class="label"><small><?php echo Mage::helper('M2ePro')->__('Amount Saved'); ?></small></td>
                    <td><span class="price"><small><?php echo Mage::getSingleton('M2ePro/Currency')->formatPrice($this->order->getData('currency'), $this->order->getData('saved_amount'));?></small></span></td>
                </tr>

            </tfoot>
        </table>

    </div>
</div>
