<div id="block_notice_amazon_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains information about product items of chosen listing and their statuses on Amazon.<br/>
    <u>To list a product the ASIN/ISBN must be assigned first.</u> To assign ASIN/ISBN you can use the Search ASIN/ISBN tool: press the icon in ASIN / ISBN column or choose appropriate command in the Action dropdown.
<br/>You can manage items by choosing appropriate actions from the Actions dropdown of the grid and manage Listing and its settings by using buttons in the top right corner.'); ?>
</div>