<div id="block_notice_common_sellingFormat_templates" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__('In this Section you can Create, Edit, and Delete Selling Format or Synchronization Policies.<br/><br/>
Selling Format Policies are used to work with values related to the offer part of the Listings, such as Price, Quantity and similar parameters.<br/>
In the Synchronization Policy you can set the Rules by which the dynamic data Synchronization between Channel and Magento will be performed.'); ?>
</div>