<div class="entry-edit" id="magento_block_ebay_template_description_preview" style="padding: 5px;">

    <h2 style="color: maroon; margin-bottom: 5px;"><?php echo Mage::helper('M2ePro')->escapeHtml($this->getData('title')); ?></h2>
    <h4 style="color: gray;"><?php echo Mage::helper('M2ePro')->escapeHtml($this->getData('subtitle')) ?></h4>

    <hr />

    <?php echo $this->getData('description') ?>

</div>