<style type="text/css">
    body {
        background: none;
    }
</style>

<div class="entry-edit" id="magento_block_ebay_template_description_form" style="padding: 5px;">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Select Product'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

                <input type="hidden" name="show" value="1" />
                <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />

                <?php if ($errorTxt = $this->getData('error_txt')): ?>
                    <span style="color: red; font-weight: bold;"><?php echo Mage::helper('M2ePro')->escapeHtml($errorTxt); ?></span>
                    <br /><br />
                <?php endif; ?>

                <?php echo Mage::helper('M2ePro')->__('Enter Product Id'); ?>: <input id="product_id" type="text" name="id" value="" class="input-text" />

                <?php echo $this->getChildHtml('display_product_description') ?>
                <?php echo Mage::helper('M2ePro')->__('or') ?>
                <?php echo $this->getChildHtml('display_random_product_description') ?>

            </form>

        </div>
    </div>

</div>