<div id="block_notice_ebay_template_general_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('General Template contains basic settings which are required for listing items on eBay.<br/><br/>
    <b>Note:</b> Before General Template creating Marketplaces should be uploaded (Configuration > Marketplaces).
    Otherwise, categories and marketplaces will not be displayed.'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();

    $paramsAttributeSetId = $this->getRequest()->getParam('attribute_set_id');
    !is_null($paramsAttributeSetId) && $formData['attribute_sets'] = array($paramsAttributeSetId);

    $defaults = array(
        'title' => '',
        'attribute_sets' => array(),
        'marketplace_id' => -1,

        'categories_mode' => -1,
        'categories_main_id' => 0,
        'categories_main_attribute' => 0,
        'categories_secondary_id' => 0,
        'categories_secondary_attribute' => 0,

        'account_id' => 0,

        'store_categories_main_mode' => 0,
        'store_categories_main_id' => 0,
        'store_categories_main_attribute' => '',

        'store_categories_secondary_mode' => 0,
        'store_categories_secondary_id' => 0,
        'store_categories_secondary_attribute' => '',

        'tax_category' => '',
        'tax_category_attribute' => '',

        'sku_mode' => 1,

        'variation_enabled' => 0,
        'variation_ignore'=> 0
    );
    $formData = array_merge($defaults, $formData);

    if (count($this->getData('accounts')) == 1) {
        $formData['account_id'] = $this->getData('accounts');
        $formData['account_id'] = reset($formData['account_id']);
        $formData['account_id'] = (int)$formData['account_id']['id'];
    }

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmitNew = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_template_general/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.magentoGetAttributesByAttributeSets = '<?php echo $this->getUrl('*/adminhtml_general/magentoGetAttributesByAttributeSets'); ?>';

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    <?php
        if (count(Mage::helper('M2ePro/Component')->getActiveComponents()) > 1) {
            $componentName = ' eBay';
        } else {
            $componentName = '';
        }
    ?>

    M2ePro.text.chapter_when_duplicate = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__("Add%s General Template", $componentName)); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Sets first and press Confirm button.')); ?>';
    M2ePro.text.marketplace_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select a Marketplace first.')); ?>';
    M2ePro.text.main_category_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Please, choose a Primary eBay Category to have an access to this section.')); ?>';

    // ie bug fix
    // ---------
    if (Prototype && Prototype.Browser.IE && varienLoaderHandler) {
        var loaderOnCompleteFunction = varienLoaderHandler.handler.onComplete;
        varienLoaderHandler.handler.onComplete = function() {

            loaderOnCompleteFunction();
            $$('select').each(function (el) {
                $(el).style.visibility = 'visible';
            });
        }
    }
    // ---------

    Event.observe(window, 'load', function() {

        AttributeSetHandlerObj = new AttributeSetHandler();

        EbayTemplateGeneralTabHandlerObj = new EbayTemplateGeneralTabHandler();
        EbayTemplateGeneralTabHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_General'); ?>');
        EbayTemplateGeneralTabHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General'); ?>');

        var multivariationMarketplaces = <?php echo '['.implode(',',Mage::getModel('M2ePro/Ebay_Marketplace')->getMultivariationIds()).']'; ?>;

        EbayTemplateGeneralHandlerObj = new EbayTemplateGeneralHandler(multivariationMarketplaces);
        EbayTemplateGeneralHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_General'); ?>');
        EbayTemplateGeneralHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General'); ?>');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.url.getMarketplaceInfo = '<?php echo $this->getUrl('*/*/getMarketplaceInfo'); ?>';

    M2ePro.url.getChildCategories = '<?php echo $this->getUrl('*/*/getChildCategories'); ?>';
    M2ePro.url.getCategoriesTreeByCategoryId = '<?php echo $this->getUrl('*/*/getCategoriesTreeByCategoryId'); ?>';
    M2ePro.url.getCategoryInformation = '<?php echo $this->getUrl('*/*/getCategoryInformation'); ?>';

    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    M2ePro.formData.marketplace_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['marketplace_id']); ?>';
    M2ePro.formData.categories_main_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['categories_main_attribute']); ?>';
    M2ePro.formData.categories_secondary_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['categories_secondary_attribute']); ?>';

    M2ePro.formData.tax_category = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['tax_category']); ?>';
    M2ePro.formData.tax_category_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['tax_category_attribute']); ?>';

    M2ePro.formData.store_categories_main_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_categories_main_id']); ?>';
    M2ePro.formData.store_categories_main_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_categories_main_attribute']); ?>';

    M2ePro.formData.store_categories_secondary_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_categories_secondary_id']); ?>';
    M2ePro.formData.store_categories_secondary_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_categories_secondary_attribute']); ?>';

    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other template. Template title must be unique.')); ?>';
    M2ePro.text.fill_category_id_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Please enter the Category ID.')); ?>';

    M2ePro.url.getEbayStoreByAccount = '<?php echo $this->getUrl('*/*/getEbayStoreByAccount'); ?>';
    M2ePro.url.updateEbayStoreByAccount = '<?php echo $this->getUrl('*/*/updateEbayStoreByAccount'); ?>';

    M2ePro.customData.attributesReceiving = [];
    M2ePro.customData.categoriesAlreadyRendered = false;

    M2ePro.customData.attributesReceiving.push(
        {
            id : 'store_categories_main_attribute',
            container : 'store_categories_main_attribute_td'
        }, {
            id : 'store_categories_secondary_attribute',
            container : 'store_categories_secondary_attribute_td'
        }
    );

    Event.observe(window, 'load', function() {

        EbayTemplateGeneralCategoryHandlerObj = new EbayTemplateGeneralCategoryHandler();
        EbayTemplateGeneralCategoryHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_General'); ?>');
        EbayTemplateGeneralCategoryHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_General'); ?>');

        $$('.requirie-attribute-set').invoke('hide');

        setTimeout(function(){
            $('attribute_sets').observe('change', AttributeSetHandlerObj.changeAttributeSets);
            $('attribute_sets').value && EbayTemplateGeneralHandlerObj.attribute_sets_confirm();

            $('marketplace_id').observe('change', EbayTemplateGeneralHandlerObj.marketplace_id_change);
            $F('marketplace_id') && $('marketplace_id').simulate('change');

            $('categories_mode').observe('change', EbayTemplateGeneralCategoryHandlerObj.categories_mode_change);
            $F('categories_mode') && $('categories_mode').simulate('change');

            $$('.ebay-cat').each(function(item) {
                item.observe('change', EbayTemplateGeneralCategoryHandlerObj.categories_change);
            });

            $('account_id').observe('change', EbayTemplateGeneralHandlerObj.account_id_change)
            $F('account_id') && $('account_id').simulate('change');

            $('store_categories_main_mode')
                .observe('change', EbayTemplateGeneralCategoryHandlerObj.store_categories_main_mode_change)
                .simulate('change');

            $('store_categories_secondary_mode')
                .observe('change', EbayTemplateGeneralCategoryHandlerObj.store_categories_secondary_mode_change)
                .simulate('change');

            $('variation_ignore')
                .observe('change', EbayTemplateGeneralCategoryHandlerObj.variation_ignore_change);
        }, 1000);
    });
    //-----------------------------

</script>

<style type="text/css">
    .main-ebay-category-hidden, .secondary-ebay-category-hidden {
        display: none;
    }
</style>

<div class="entry-edit" id="magento_block_ebay_template_general_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-listing-tpl-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short meaningful template title for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Sets'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">

                        <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                            <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                            <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="attribute_sets<?php echo $attributeSetPostfix; ?>[]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                    <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <?php if ($this->attribute_set_locked): ?>
                            <div id="attribute_sets_breadcrumb" style="width: 280px;">
                                <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                                    <?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                                <?php endforeach; ?>
                                <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                            </div>
                            <input id="attribute_sets" name="attribute_sets" value="<?php echo $this->escapeHtml(implode(',', $formData['attribute_sets'])); ?>" type="hidden" />
                        <?php endif; ?>

                        <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                            <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                            <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                        </div>

                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Attribute Sets of products which will be listed on eBay<br />using this template.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="marketplace_id"><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="marketplace_id" name="marketplace_id" class="required-entry select">
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('marketplaces') as $marketplace): ?>
                                <option value="<?php echo $marketplace['id']; ?>" <?php if ($formData['marketplace_id'] == $marketplace['id']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__($marketplace['title']); ?></option>
                            <?php endforeach; ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Only the marketplaces chosen in Configuration > Marketplaces are shown for selection.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr <?php if (count($this->getData('accounts')) == 1) { ?>style="display: none;" <?php } ?>>
                    <td class="label">
                        <label for="account_id"><?php echo Mage::helper('M2ePro')->__('eBay Account'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="account_id" name="account_id" class="required-entry">
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('accounts') as $account): ?>
                                <option value="<?php echo $account['id']; ?>" <?php if ($formData['account_id'] == $account['id']): echo ' selected="selected"'; endif; ?>><?php echo $account['title'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('eBay accounts you have already added in Configuration > eBay Accounts.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_general_categories">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Categories'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="categories_mode"><?php echo Mage::helper('M2ePro')->__('Category Source'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="categories_mode" name="categories_mode" class="select required-entry">
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <option value="0" <?php if ($formData['categories_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('eBay Categories'); ?></option>
                            <option value="1" <?php if ($formData['categories_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Where the categories data should be taken from.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="main_category_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Primary Category Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="main_category_attribute_td" class="value" style="width: auto;"></td>
                    <td id="main_category_attribute_td_note" style="display: none;">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose the attribute contains Primary eBay Category ID.'); ?></span>
                        </p>
                    </td>
                </tr>

                <?php
                    $categoryData = $this->getData('main_category');

                    $default = array(
                        'breadcrumbs' => '',
                        'select-1' => '',
                        'select-2' => '',
                        'select-3' => '',
                        'select-4' => '',
                        'select-5' => '',
                        'select-6' => '',
                        'select-7' => '',
                    );
                    $categoryData = array_merge($default, (array)$categoryData);
                ?>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="main_ebay_category_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Primary Category'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="categories_main_id" name="categories_main_id" value="<?php echo $this->escapeHtml($formData['categories_main_id']); ?>" type="hidden" />
                        <div id="main_ebay_category_div">

                            <?php for ($i = 1; $i <=7; $i++) : ?>
                                <?php if ($categoryData["select-$i"]):
                                    echo $categoryData["select-$i"];
                                    echo '<div style="clear: both;"></div>';
                                else: ?>
                                    <select id="main_ebay_category-<?php echo $i; ?>" name="main_ebay_category-<?php echo $i; ?>" class="ebay-cat M2ePro-required-when-visible" style="display: none;" ></select>
                                    <div style="clear: both;"></div>
                                <?php endif ?>
                            <?php endfor; ?>

                            <div id="main_ebay_category_confirm_div" style="display: none;">
                                <?php echo $this->getChildHtml('confirm_main_category_button'); ?>
                            </div>

                            <span id="main_ebay_category_breadcrumbs_div" style="display: none; font-weight: bold;" class="nobr"><?php echo $categoryData['breadcrumbs'] ?></span>

                            <div>
                                <?php echo $this->getChildHtml('change_main_category_button'); ?>
                                <?php echo $this->getChildHtml('cancel_main_category_button'); ?>
                            </div>

                        </div>
                    </td>
                    <td id="main_ebay_category_by_id_td" style="padding-top: 5px;">
                        <?php echo Mage::helper('M2ePro')->__('or Category ID'); ?>: <input id="main_ebay_category_by_id" name="main_ebay_category_by_id" type="text" style="width: 50px;" class="input-text" /> <?php echo $this->getChildHtml('select_main_category_by_id_button'); ?>
                    </td>
                </tr>

                <tr id="secondary_category_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Secondary Category Attribute'); ?>: </label>
                    </td>
                    <td id="secondary_category_attribute_td" class="value" style="width: auto;"></td>
                    <td id="secondary_category_attribute_td_note" style="display: none;">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose the attribute contains Secondary eBay Category ID.'); ?></span>
                        </p>
                    </td>
                </tr>

                <?php
                $categoryData = $this->getData('secondary_category');
                $default = array(
                    'breadcrumbs' => '',
                    'select-1' => '',
                    'select-2' => '',
                    'select-3' => '',
                    'select-4' => '',
                    'select-5' => '',
                    'select-6' => '',
                    'select-7' => '',
                );
                $categoryData = array_merge($default, (array)$categoryData);
                ?>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="secondary_ebay_category_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Secondary Category'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="categories_secondary_id" name="categories_secondary_id" value="<?php echo $this->escapeHtml($formData['categories_secondary_id']); ?>" type="hidden" />
                        <div id="secondary_ebay_category_div">

                            <?php for ($i = 1; $i <=7; $i++) : ?>
                                <?php if ($categoryData["select-$i"]):
                                    echo $categoryData["select-$i"];
                                    echo '<div style="clear: both;"></div>';
                                else: ?>
                                    <select id="secondary_ebay_category-<?php echo $i; ?>" name="secondary_ebay_category-<?php echo $i; ?>" style="display: none;" class="ebay-cat"></select>
                                    <div style="clear: both;"></div>
                                <?php endif ?>
                            <?php endfor; ?>

                            <div id="secondary_ebay_category_confirm_div" style="display: none;">
                                <?php echo $this->getChildHtml('confirm_secondary_category_button'); ?>
                            </div>

                            <span id="secondary_ebay_category_breadcrumbs_div" style="display: none; font-weight: bold;" class="nobr"><?php echo $categoryData['breadcrumbs'] ?></span>

                            <div>
                                <?php echo $this->getChildHtml('change_secondary_category_button'); ?>
                                <?php echo $this->getChildHtml('reset_secondary_category_button'); ?>
                                <?php echo $this->getChildHtml('cancel_secondary_category_button'); ?>
                            </div>

                        </div>
                    </td>
                    <td id="secondary_ebay_category_by_id_td" style="padding-top: 5px;">
                        <?php echo Mage::helper('M2ePro')->__('or Category ID'); ?>: <input id="secondary_ebay_category_by_id" name="secondary_ebay_category_by_id" type="text" style="width: 50px;" class="input-text" /> <?php echo $this->getChildHtml('select_secondary_category_by_id_button'); ?>
                    </td>
                </tr>

            </table>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="tax_category_tr" style="display: none;">
                    <td class="label">
                        <label for="tax_category"><?php echo Mage::helper('M2ePro')->__('Tax Category'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="tax_category" name="tax_category">
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('This is to be used only by sellers who have opted into sales tax<br /> being calculated by a sales tax calculation vendor.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="tax_category_attribute_tr" style="display: none;">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Tax Category Attribute'); ?>: </label>
                    </td>
                    <td id="tax_category_attribute_td" class="value" style="width: auto;"></td>
                    <td id="tax_category_attribute_td_note" style="display: none;">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('This is to be used only by sellers who have opted into sales tax<br /> being calculated by a sales tax calculation vendor.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_general_account_store" style="display: none;">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Store Categories'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr class="ebay-store">
                    <td class="label" >
                        <label><?php echo Mage::helper('M2ePro')->__('eBay Store Name'); ?>:</label>
                    </td>
                    <td class="value">
                        <span id="store_name" style="font-weight: bold; padding-left: 3px;"></span>
                    </td>
                    <td class="buttons">
                        <?php echo $this->getChildHtml('update_ebay_store_button'); ?>
                    </td>
                </tr>

                <tr class="ebay-store">
                    <td class="label">
                        <label for="store_categories_main_mode"><?php echo Mage::helper('M2ePro')->__('Primary Category Source'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="store_categories_main_mode" name="store_categories_main_mode" class="select M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_NONE; ?>" <?php if ($formData['store_categories_main_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_NONE): echo ' selected="selected"'; endif; ?>>---</option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_EBAY_VALUE; ?>" <?php if ($formData['store_categories_main_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_EBAY_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('eBay Store Categories'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['store_categories_main_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Where the Primary eBay Store category data should be taken from.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="store_categories_main_id_tr" class="ebay-store">
                    <td class="label">
                        <label for="store_categories_main_id"><?php echo Mage::helper('M2ePro')->__('Primary Category'); ?>:</label>
                    </td>
                    <td id="store_categories_main_id_td" class="value" style="width: auto;">
                        <select id="store_categories_main_id" name="store_categories_main_id"></select>
                    </td>
                </tr>

                <tr id="store_categories_main_attribute_tr" class="ebay-store">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Primary Category Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="store_categories_main_attribute_td" class="value" style="width: auto;"></td>
                    <td id="store_categories_main_attribute_td_note" style="display: none;">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose the attribute contains Primary eBay Store Category ID.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr class="ebay-store">
                    <td class="label">
                        <label for="store_categories_secondary_mode"><?php echo Mage::helper('M2ePro')->__('Secondary Category Source'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="store_categories_secondary_mode" name="store_categories_secondary_mode" class="select M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_NONE; ?>" <?php if ($formData['store_categories_secondary_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_NONE): echo ' selected="selected"'; endif; ?>>---</option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_EBAY_VALUE; ?>" <?php if ($formData['store_categories_secondary_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_EBAY_VALUE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('eBay Store Categories'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_CUSTOM_ATTRIBUTE; ?>" <?php if ($formData['store_categories_secondary_mode'] == Ess_M2ePro_Model_Ebay_Template_General::STORE_CATEGORY_CUSTOM_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Where the Secondary eBay Store category data should be taken from.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="store_categories_secondary_id_tr" class="ebay-store">
                    <td class="label">
                        <label for="store_categories_secondary_id"><?php echo Mage::helper('M2ePro')->__('Secondary Category'); ?>:</label>
                    </td>
                    <td id="store_categories_secondary_id_td" class="value" style="width: auto;">
                        <select id="store_categories_secondary_id" name="store_categories_secondary_id"></select>
                    </td>
                </tr>

                <tr id="store_categories_secondary_attribute_tr" class="ebay-store">
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Secondary Category Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td id="store_categories_secondary_attribute_td" class="value" style="width: auto;"></td>
                    <td id="store_categories_secondary_attribute_td_note" style="display: none;">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Choose the attribute contains Secondary eBay Store Category ID.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_general_multivariation" style="display: none;">

    <input type="hidden" id="variation_enabled" name="variation_enabled" value="<?php $formData['variation_enabled']; ?>">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Multi Variation'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_ebay_template_general_multivariation_marketplace_disabled" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Multi Variation Disabled'); ?>" collapseable="no" always_show="yes" hideblock="no" style="display: none;">
                <?php echo Mage::helper('M2ePro')->__('Selected eBay marketplace does not allow creating multi variation eBay listings.
                <br/>Configurable, Bundle, Grouped and Simple Products with Custom Options will be listed as regular eBay items. All variations will be ignored.'); ?>
            </div>

            <div id="block_notice_ebay_template_general_multivariation_category_enabled" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Multi Variation Enabled'); ?>" collapseable="no" always_show="yes" hideblock="no" style="display: none;">
                <?php echo Mage::helper('M2ePro')->__('Selected Primary eBay category allows creating multi variation listings.
                <br/>Configurable, Bundle, Grouped and Simple Products with Custom Options can be listed as multi variation eBay items.<br/><br/>
                <b>Note:</b> eBay allows listing items with variations only in Fixed Price listing (in Auction listing type all variation
                will be ignored) and the Best Offer option is not used in this case (it will be ignored if it was set in your Selling Format
                Template).'); ?>
            </div>

            <div id="block_notice_ebay_template_general_multivariation_category_disabled" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Multi Variation Disabled'); ?>" collapseable="no" always_show="yes" hideblock="no" style="display: none;">
                <?php echo Mage::helper('M2ePro')->__('Selected Primary eBay category does not allow creating multi variation eBay listings.
                <br/>Configurable, Bundle, Grouped and Simple Products with Custom Options will be listed as regular eBay items. All variations will be ignored.'); ?>
            </div>

            <table id="multivariation_settings" class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="variation_ignore"><?php echo Mage::helper('M2ePro')->__('Ignore Variations'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="variation_ignore" name="variation_ignore" class="select M2ePro-required-when-visible">
                            <option value="0" <?php if ($formData['variation_ignore'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['variation_ignore'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i>, the variations of products will be ignored.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_ebay_template_general_general_inventory">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Inventory Information'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="sku_mode"><?php echo Mage::helper('M2ePro')->__('Custom Label (SKU)'); ?>: </label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="sku_mode" name="sku_mode">
                            <option value="0" <?php if ($formData['sku_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="1" <?php if ($formData['sku_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                        </select>
                        <input type="hidden" id="fake_sku_mode" name="fake_sku_mode" value="1">
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i>, the Product SKU will be used as a Custom Label.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>