<div id="block_notice_ebay_template_general_upgrades" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Upgrades'); ?>">
    <?php echo Mage::helper('M2ePro')->__('To stand out your Listing from others use eBay standard tools.<br/><br/>
    <b>Note:</b> These features come with additional eBay fees.');?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();
    $defaults = array(
        'enhancement' => '',
        'gallery_type' => Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_EMPTY
    );
    $formData = array_merge($defaults, $formData);

    $formData['enhancement'] = explode(',', $formData['enhancement']);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    Event.observe(window, 'load', function() {

    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_ebay_template_general_upgrades_upgrade_tools">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Upgrade Tools'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Value Pack'); ?>:</label>
                    </td>
                    <td class="value">
                        <label>
                            <input name="enhancement[]" value="ValuePackBundle" type="checkbox" <?php if (in_array('ValuePackBundle', $formData['enhancement'])): echo ' checked="checked"'; endif; ?> /> <?php echo Mage::helper('M2ePro')->__('Value Pack Bundle'); ?>
                        </label>
                        <p class="note nobr">
                            <span><?php echo Mage::helper('M2ePro')->__('Combine Gallery, Subtitle, and Listing Designer and you will get a discount.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('M2ePro')->__('Listing Upgrades'); ?>:</label>
                    </td>
                    <td class="value">
                        <label>
                            <input name="enhancement[]" value="BoldTitle" type="checkbox" <?php if (in_array('BoldTitle', $formData['enhancement'])): echo ' checked="checked"'; endif; ?> /> <?php echo Mage::helper('M2ePro')->__('Bold Title'); ?><br />
                        </label>
                        <p class="note nobr">
                            <span><?php echo Mage::helper('M2ePro')->__('Bolding your listing title.'); ?></span>
                        </p>
                        <label>
                            <input name="enhancement[]" value="Highlight" type="checkbox" <?php if (in_array('Highlight', $formData['enhancement'])): echo ' checked="checked"'; endif; ?> /> <?php echo Mage::helper('M2ePro')->__('Highlight'); ?><br />
                        </label>
                        <p class="note nobr">
                            <span><?php echo Mage::helper('M2ePro')->__('Adding an eye-catching background to your listing in search results.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="gallery_type"><?php echo Mage::helper('M2ePro')->__('Gallery Type'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="gallery_type" name="gallery_type">
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_EMPTY; ?>" <?php if ($formData['gallery_type'] == Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_EMPTY): echo ' selected="selected"'; endif; ?>></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_NO; ?>" <?php if ($formData['gallery_type'] == Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_PICTURE; ?>" <?php if ($formData['gallery_type'] == Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_PICTURE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Gallery Picture'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_PLUS; ?>" <?php if ($formData['gallery_type'] == Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_PLUS): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Gallery Plus'); ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_FEATURED; ?>" <?php if ($formData['gallery_type'] == Ess_M2ePro_Model_Ebay_Template_General::GALLERY_TYPE_FEATURED): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Gallery Featured'); ?></option>
                        </select>
                        <p class="note nobr">
                            <span><?php echo Mage::helper('M2ePro')->__('Adding listing\'s pictures using different modes in search results.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>