<?php /* @var Ess_M2ePro_Block_Adminhtml_Wizard_InstallationCommon_Installation_License_Form $this*/?>

<script type="text/javascript">

    M2ePro.url.add(<?php echo json_encode(array('formSubmit' => $this->getUrl('*/*/createLicense'))); ?>);

    M2ePro.translator.add(<?php echo json_encode(array(
        'Error create license.' => Mage::helper('M2ePro')->__('License creation is failed. Please contact M2E Pro support for resolution.')
    )); ?>);

    var init = function() {
        var licenseForm = new varienForm('edit_form');

        $('form_confirm_button').observe('click',function() {

            if (!licenseForm.validate()) {
                return;
            }

            new Ajax.Request(M2ePro.url.get('formSubmit'),
                {
                    method: 'post',
                    asynchronous: true,
                    parameters: $('edit_form').serialize(true),
                    onSuccess: function(transport)
                    {
                        checkResult = transport.responseText.evalJSON()['result'];
                        if (checkResult) {
                            window.opener.completeStep = 1;
                            window.close();
                        } else {
                            MagentoMessageObj.addError(M2ePro.translator.translate('Error create license.'));
                        }
                    }
                });
        });

        $('installation_common_license_complete_this_step').observe('click', function(){
            $('form_confirm_button').simulate('click');
        });

    }

    Event.observe(window, 'load', init);

</script>
<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action');?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div>
        <div>
            <div class="block_notices_module"  style="width: 600px" title="<?php echo Mage::helper('M2ePro')->__('Please confirm the information provided below is valid before the registration in M2E Pro system is done.'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes"></div>
                <div class="fieldset">
                    <div class="hor-scroll">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tbody>
                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('Email') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <input type="text" name="email" class="input-text required-entry validate-email" value="<?php echo Mage::helper('M2ePro')->__($this->getData('email')); ?>">
                                </td>
                            </tr>

                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('First Name') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <input type="text" name="firstname" class="input-text required-entry" value="<?php echo Mage::helper('M2ePro')->__($this->getData('firstname')); ?>" />
                                </td>
                            </tr>

                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('Last Name') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <input type="text" name="lastname" class="input-text required-entry" value="<?php echo Mage::helper('M2ePro')->__($this->getData('lastname')); ?>" />
                                </td>
                            </tr>

                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('Country') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <select name="country" class="required-entry">
                                        <?php $selectCountry = Mage::helper('M2ePro')->__($this->getCountryLabelByCode($this->getData('country'))); ?>
                                        <?php foreach($this->getData('countries') as $country) {?>
                                            <option value="<?php echo $country['label']; ?>" <?php echo $selectCountry == $country['label'] ? ' selected="selected"' : ''; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($country['label']); ?></option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>

                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('City') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <input type="text" name="city" class="input-text required-entry" value="<?php echo Mage::helper('M2ePro')->__($this->getData('city')); ?>" />
                                </td>
                            </tr>

                            <tr>
                                <td class="label">
                                    <?php echo Mage::helper('M2ePro')->__('Postal Code') ?>: <span class="required">*</span>
                                </td>
                                <td class="value">
                                    <input type="text" name="postal_code" class="input-text required-entry" value="<?php echo Mage::helper('M2ePro')->__($this->getData('postal_code')); ?>" />
                                </td>
                            </tr>

                            </tbody>

                        </table>

                    </div>
                </div>
        </div>

        <div id="button_block">
            <?php echo $this->getChildHtml('form_confirm_button'); ?>
        </div>

    </div>
</form>