<div id="block_notice_ebay_template" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Policies'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows the policies you\'re currently using in your M2E Pro listings.<br/><br/>
        Click the line of the policy in the table below to <b>Edit</b> the policy. You can <b>Delete</b> policy only if it\'s not already being used for an M2E Pro Listing.<br/><br/>
        To add a new policy, click the <b>Add Policy</b> button.'
    ); ?>
</div>