<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.logViewUrl = '<?php echo $this->getUrl('*/adminhtml_log/synchronization',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_synchronization/index'))); ?>';

    M2ePro.url.runSynchNow = '<?php echo $this->getUrl('*/adminhtml_marketplace/runSynchNow'); ?>';

    M2ePro.url.runAllEnabledNow = '<?php echo $this->getUrl('*/adminhtml_synchronization/runAllEnabledNow'); ?>';
    M2ePro.url.runNowTemplates = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowTemplates'); ?>';
    M2ePro.url.runNowOrders = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowOrders'); ?>';
    M2ePro.url.runNowFeedbacks = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowFeedbacks'); ?>';
    M2ePro.url.runNowEbayListings = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowEbayListings'); ?>';
    M2ePro.url.runNowMessages = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowMessages'); ?>';

    M2ePro.url.synchCheckState = '<?php echo $this->getUrl('*/adminhtml_general/synchCheckState'); ?>';
    M2ePro.url.synchGetLastResult = '<?php echo $this->getUrl('*/adminhtml_general/synchGetLastResult'); ?>';
    M2ePro.url.synchGetExecutingInfo = '<?php echo $this->getUrl('*/adminhtml_general/synchGetExecutingInfo'); ?>';

    M2ePro.text.marketplaces_settings_save_success_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Marketplaces settings have been saved.')); ?>';
    M2ePro.text.marketplaces_settings_save_error_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You must select at least one marketplace you will work with.')); ?>';

    M2ePro.text.synch_already_running_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Another Synchronization Is Already Running')); ?>';
    M2ePro.text.synch_getting_information_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Getting information. Please wait ...')); ?>';
    M2ePro.text.synch_prepare_to_start_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Preparing to start. Please wait ...')); ?>';

    M2ePro.text.synch_end_success_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization has successfully ended.')); ?>';
    M2ePro.text.synch_end_warning_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with warnings. <a href="%url%">View log</a> for details.')); ?>';
    M2ePro.text.synch_end_error_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with errors. <a href="%url%">View log</a> for details.')); ?>';

    Event.observe(window, 'load', function() {
        editForm = new varienForm('<?php echo $this->getForm()->getId(); ?>', '<?php echo $this->getValidationUrl(); ?>');

        MarketplaceProgressBarObj = new ProgressBar('marketplaces_progress_bar');
        MarketplaceWrapperObj = new AreaWrapper('marketplaces_content_container');

        MarketplaceProgressHandlerObj = new SynchProgressHandler(MarketplaceProgressBarObj, MarketplaceWrapperObj );
        MarketplaceHandlerObj = new MarketplaceHandler(MarketplaceProgressHandlerObj);
        MarketplaceProgressHandlerObj.initPageCheckState();

        <?php if (!is_null($this->getChildBlockId())) { ?>
            <?php
                $childBlockId = Mage::helper('M2ePro')->escapeJs($this->getChildBlockId());
                $destinationBlockId = Mage::helper('M2ePro')->escapeJs($this->getForm()->getId());
            ?>
            MarketplaceHandlerObj.moveChildBlockContent('<?php echo $childBlockId; ?>', '<?php echo $destinationBlockId; ?>');
        <?php } ?>

        varienGlobalEvents && varienGlobalEvents.fireEvent('initReady');
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

</form>