<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.components = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.enabledComponents = <?php echo json_encode(Mage::helper('M2ePro/Component')->getActiveComponents()); ?>;

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.logViewUrl = '<?php echo $this->getUrl('*/adminhtml_log/synchronization',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_synchronization/index'))); ?>';

    M2ePro.url.runSynchNow = '<?php echo $this->getUrl('*/adminhtml_marketplace/runSynchNow'); ?>';

    M2ePro.url.runAllEnabledNow = '<?php echo $this->getUrl('*/adminhtml_synchronization/runAllEnabledNow'); ?>';
    M2ePro.url.runNowTemplates = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowTemplates'); ?>';
    M2ePro.url.runNowOrders = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowOrders'); ?>';
    M2ePro.url.runNowOtherListings = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowOtherListings'); ?>';

    M2ePro.url.runNowFeedbacks = '<?php echo $this->getUrl('*/adminhtml_ebay_synchronization/runNowFeedbacks'); ?>';
    M2ePro.url.runNowMessages = '<?php echo $this->getUrl('*/adminhtml_ebay_synchronization/runNowMessages'); ?>';

    M2ePro.url.synchCheckProcessingNow = '<?php echo $this->getUrl('*/adminhtml_synchronization/synchCheckProcessingNow'); ?>';

    M2ePro.url.synchCheckState = '<?php echo $this->getUrl('*/adminhtml_general/synchCheckState'); ?>';
    M2ePro.url.synchGetLastResult = '<?php echo $this->getUrl('*/adminhtml_general/synchGetLastResult'); ?>';
    M2ePro.url.synchGetExecutingInfo = '<?php echo $this->getUrl('*/adminhtml_general/synchGetExecutingInfo'); ?>';

    M2ePro.text.synch_settings_saved_successfully = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization settings have been saved.')); ?>';
    M2ePro.text.synch_running_all_enabled_tasks = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Running All Enabled Tasks')); ?>';
    M2ePro.text.synch_running_templates = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Templates Synchronization')); ?>';
    M2ePro.text.synch_running_orders = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Orders Synchronization')); ?>';
    M2ePro.text.synch_running_feedbacks = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Feedbacks Synchronization')); ?>';
    M2ePro.text.synch_running_3rd_party = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('3rd Party Listings Synchronization')); ?>';
    M2ePro.text.synch_running_messages = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Messages Synchronization')); ?>';

    M2ePro.text.synch_already_running_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Another Synchronization Is Already Running')); ?>';
    M2ePro.text.synch_getting_information_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Getting information. Please wait ...')); ?>';
    M2ePro.text.synch_prepare_to_start_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Preparing to start. Please wait ...')); ?>';

    M2ePro.text.synch_end_success_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization has successfully ended.')); ?>';
    M2ePro.text.synch_end_warning_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with warnings. <a href="%url%">View log</a> for details.')); ?>';
    M2ePro.text.synch_end_error_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with errors. <a href="%url%">View log</a> for details.')); ?>';

    Event.observe(window, 'load', function() {
        setTimeout(function() {
            SynchronizationProgressHandlerObj = new SynchProgressHandler(SynchProgressBarObj, SynchWrapperObj );
            SynchronizationHandlerObj = new SynchronizationHandler(SynchronizationProgressHandlerObj);
            SynchronizationProgressHandlerObj.initPageCheckState();

            editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');

            <?php if (!is_null($this->getChildBlockId())) { ?>
                <?php
                    $childBlockId = Mage::helper('M2ePro')->escapeJs($this->getChildBlockId());
                    $destinationBlockId = Mage::helper('M2ePro')->escapeJs($this->getForm()->getId());
                ?>
                SynchronizationHandlerObj.moveChildBlockContent('<?php echo $childBlockId; ?>', '<?php echo $destinationBlockId; ?>');
            <?php } ?>

        }, 350);
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

</form>