<div id="block_notice_buy_template_description" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Description Template'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Description Template is used to design your items\' description on Rakuten.com.<br/><br/>
It is possible to choose a Product Description or Product Short Description, which will be taken from Magento. Or you can create a Custom Description by adding necessary information.
'); ?>
</div>

<?php
$formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();
!empty($formData['bullet_points']) && $formData['bullet_points'] = json_decode($formData['bullet_points'], true);

$paramsAttributeSetId = $this->getRequest()->getParam('attribute_sets');
!is_null($paramsAttributeSetId) && $formData['attribute_sets'] = explode(',', $paramsAttributeSetId);

$default = array(
    'title' => '',
    'attribute_sets' => array(),
);

$formData = array_merge($default, $formData);

$isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.formSubmitNew = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_template_description/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.magentoGetAttributesByAttributeSets = '<?php echo $this->getUrl('*/adminhtml_general/magentoGetAttributesByAttributeSets'); ?>';

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';

    M2ePro.text.chapter_when_duplicate = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Add Description Template.')); ?>';
    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other template. Template title must be unique.')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Sets first and press Confirm button.')); ?>';

    Event.observe(window, 'load', function() {
        AttributeSetHandlerObj = new AttributeSetHandler();
        BuyTemplateDescriptionHandlerObj = new BuyTemplateDescriptionHandler();
        BuyTemplateDescriptionHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_Description'); ?>');
        BuyTemplateDescriptionHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Buy_Template_Description'); ?>');

        $('attribute_sets').observe('change', AttributeSetHandlerObj.changeAttributeSets);
        $('attribute_sets').value && BuyTemplateDescriptionHandlerObj.attribute_sets_confirm();

        $('title_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.title_mode_change)
            .simulate('change');

        $('brand_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.brand_mode_change)
            .simulate('change');

        $('manufacturer_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.manufacturer_mode_change)
            .simulate('change');

        $('bullet_points_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.bullet_points_mode_change)
            .simulate('change');

        $('description_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.description_mode_change)
            .simulate('change');

        $('image_main_mode')
            .observe('change', BuyTemplateDescriptionHandlerObj.image_main_mode_change)
            .simulate('change');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style type="text/css">
    .input-text-title {
        width: 350px !important;
    }
    .input-text-small {
        width: 120px !important;
    }
    .textarea {
        width: 98% !important;
        height: 500px !important;
    }
    select.select-main {
        width: 356px !important;
    }
    .select-wrapper {
        margin-left: 15px;
    }
    a.action-disabled {
        color: gray !important;
        text-decoration: none !important;
    }
    a.action-disabled:hover {
        color: gray !important;
        text-decoration: none !important;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

<input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

<input id="editor_type" name="editor_type" type="hidden" />

<div class="entry-edit" id="magento_block_buy_template_description_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input id="title" name="title" value="<?php echo $formData['title']; ?>" type="text" class="input-text required-entry M2ePro-description-tpl-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short meaningful template title for your internal use.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Sets'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                            <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                            <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="attribute_sets<?php echo $attributeSetPostfix; ?>[]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <?php if ($this->attribute_set_locked): ?>
                        <div id="attribute_sets_breadcrumb" style="width: 280px;">
                            <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                            <?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                            <?php endforeach; ?>
                            <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                        </div>
                        <input id="attribute_sets" name="attribute_sets" value="<?php echo $this->escapeHtml(implode(',', $formData['attribute_sets'])); ?>" type="hidden" />
                        <?php endif; ?>

                        <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                            <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                            <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                        </div>

                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Attribute Sets of products which will be listed on Rakuten.com<br />using this template.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

</form>