<div id="block_notice_buy_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Section contains information about Product Items of chosen Listing and their Statuses on Play.com. <br/><br/>
    You can manage Items by choosing appropriate Actions from the <strong>Actions</strong> Dropdown of the Grid and manage Listing and its Settings by using Buttons in the top right corner.'); ?>
</div>