<div id="block_notice_buy_listings_view_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listing Items'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains information about Product Items of chosen Listing and their statuses on Play.com. <br/><br/>
    You can manage Items by choosing appropriate actions from the <strong>Actions</strong> dropdown of the grid and manage Listing and its settings by using buttons in the top right corner.'); ?>
</div>