<div id="block_notice_ebay_template_selling_format_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Selling Format Template'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Selling Format Template contains information about Listings types, quantity, duration and price-related data for the items,
    which will be listed on eBay.
    <br/>
    <br/>Next to each price options dropdown there is a box for Price Change. Price Change is a value you want the Magento Price to be modified while listing on eBay. <br/><br/>
    <i><b>Examples:</b></i><br/>
    If you want the price on eBay to be greater by 15% than the price in Magento, you should set +15% in the Price Change field.<br/>
    <i>eBay Price = Magento Price + Magento Price * 0.15</i><br/>
    If you want the price on eBay to be less by 10 currency units than the price in Magento, you should set -10 in the Price Change field.<br/>
    <i>eBay Price = Magento Price - 10</i><br/>
    If you want the price on eBay to be multiplied by coefficient 1.2, you should set 1.2 in the Price Change field.<br/>
    <i>eBay Price = Magento Price * 1.2.</i><br/><br/>

    <b>Note:</b>     If the Special Price is chosen, but it is not set in Magento Product settings or it is set but it has already expired, the Product Price is used instead.
    <br/>
    <br/>
    You can also enable the Best Offer feature for Fixed Price type listings and fill two additional options of automatic responding: Accept Best Offer and Decline Best Offer.<br/>
    These options can be set by entering percentages of Buy It Now price or choosing appropriate custom attributes, which contain necessary price values.
    <br/><br/><b>Note:</b> Attributes must contain only numeric values.'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();

    $paramsAttributeSetId = $this->getRequest()->getParam('attribute_set_id');
    !is_null($paramsAttributeSetId) && $formData['attribute_sets'] = array($paramsAttributeSetId);

    $default = array(
        'title' => '',
        'attribute_sets' => array(),

        'listing_type' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_FIXED,
        'listing_type_attribute' => '',

        'listing_is_private' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_IS_PRIVATE_NO,

        'duration_mode' => 3,
        'duration_attribute' => '',

        'qty_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_PRODUCT,
        'qty_custom_value' => 1,
        'qty_custom_attribute' => '',
        'qty_max_posted_value' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MAX_POSTED_DEFAULT_VALUE,

        'currency' => Mage::helper('M2ePro/Magento')->getBaseCurrency(),

        'price_variation_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT,

        'start_price_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT,
        'start_price_coefficient' => '',
        'start_price_custom_attribute' => '',

        'reserve_price_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_NONE,
        'reserve_price_coefficient' => '',
        'reserve_price_custom_attribute' => '',

        'buyitnow_price_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT,
        'buyitnow_price_coefficient' => '',
        'buyitnow_price_custom_attribute' => '',

        'best_offer_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_MODE_NO,
        'best_offer_based_on_attribute' => '#price#',

        'best_offer_accept_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_NO,
        'best_offer_accept_value' => '',
        'best_offer_accept_attribute' => '',

        'best_offer_reject_mode' => Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_NO,
        'best_offer_reject_value' => '',
        'best_offer_reject_attribute' => '',

        'customer_group_id' => ''
    );
    $formData = array_merge($default, $formData);
    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.formSubmitNew = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/adminhtml_template_sellingFormat/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.magentoGetAttributesByAttributeSets = '<?php echo $this->getUrl('*/adminhtml_general/magentoGetAttributesByAttributeSets'); ?>';

    M2ePro.text.buyitnow_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The fixed price for immediate purchase.')); ?>';
    M2ePro.text.buyitnow_final_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The fixed price for immediate purchase.<br/><b>Note:</b> The Final Price is only used for Simple Products.')); ?>';

    M2ePro.text.start_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The starting price at which bidding begins.')); ?>';
    M2ePro.text.start_final_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The starting price at which bidding begins.<br/><b>Note:</b> The Final Price is only used for Simple Products.')); ?>';

    M2ePro.text.reserve_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The lowest price at which you are selling an item.<br/><b>Note:</b> eBay charges some additional fee for using this option.')); ?>';
    M2ePro.text.reserve_final_price_note = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The lowest price at which you are selling an item.<br/><b>Note:</b> The Final Price is only used for Simple Products.')); ?>';

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';

    M2ePro.formData.qty_mode = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_mode']); ?>';
    M2ePro.formData.qty_max_posted_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_max_posted_value']); ?>';

    M2ePro.formData.listing_type_selected = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['listing_type']); ?>';
    M2ePro.formData.listing_type_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['listing_type_attribute']); ?>';
    M2ePro.formData.duration_mode = <?php echo Mage::helper('M2ePro')->escapeJs($formData['duration_mode']); ?>;
    M2ePro.formData.duration_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['duration_attribute']); ?>';
    M2ePro.formData.qty_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['qty_custom_attribute']); ?>';

    M2ePro.formData.start_price_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['start_price_custom_attribute']); ?>';
    M2ePro.formData.reserve_price_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['reserve_price_custom_attribute']); ?>';
    M2ePro.formData.buyitnow_price_custom_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['buyitnow_price_custom_attribute']); ?>';
    M2ePro.formData.best_offer_based_on_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['best_offer_based_on_attribute']); ?>';
    M2ePro.formData.best_offer_accept_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['best_offer_accept_attribute']); ?>';
    M2ePro.formData.best_offer_reject_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['best_offer_reject_attribute']); ?>';

    <?php
        if (count(Mage::helper('M2ePro/Component')->getActiveComponents()) > 1) {
            $componentName = ' eBay';
        } else {
            $componentName = '';
        }
    ?>

    M2ePro.text.chapter_when_duplicate = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__("Add%s Selling Format Template", $componentName)); ?>';
    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other template. Template title must be unique.')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Sets first and press Confirm button.')); ?>';
    M2ePro.text.price_coef_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Coefficient is not valid.')); ?>';

    Event.observe(window, 'load', function() {

        AttributeSetHandlerObj = new AttributeSetHandler();

        EbayTemplateSellingFormatHandlerObj = new EbayTemplateSellingFormatHandler();
        EbayTemplateSellingFormatHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Template_SellingFormat'); ?>');
        EbayTemplateSellingFormatHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Ebay_Template_SellingFormat'); ?>');

        $('attribute_sets').observe('change', AttributeSetHandlerObj.changeAttributeSets);
        $('attribute_sets').value && EbayTemplateSellingFormatHandlerObj.attribute_sets_confirm();

        $('listing_type').observe('change', EbayTemplateSellingFormatHandlerObj.listing_type_change);
        $('listing_type').simulate('change');

        $('qty_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.qty_mode_change)
                .simulate('change');

        $('qty_max_posted_value_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.qtyMaxPostedMode_change)
                .simulate('change');

        $('start_price_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.start_price_mode_change)
                .simulate('change');

        $('reserve_price_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.reserve_price_mode_change)
                .simulate('change');

        $('buyitnow_price_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.buyitnow_price_mode_change)
                .simulate('change');

        $('best_offer_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.best_offer_mode_change)
                .simulate('change');

        $('best_offer_accept_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.best_offer_accept_mode_change)
                .simulate('change');

        $('best_offer_reject_mode')
                .observe('change', EbayTemplateSellingFormatHandlerObj.best_offer_reject_mode_change)
                .simulate('change');

        $('customer_group_id')
                .observe('change', function() { CommonHandlerObj.hideEmptyOption(this); });

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style type="text/css">
    .coef {
        padding-left: 5px !important;
        padding-top: 5px !important;
    }
    .coef input {
        text-align: right;
        width: 36px;
    }
    .form-list td.label {
        width: 275px;
    }
</style>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_ebay_template_selling_format_general">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-price-tpl-title"/>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Short meaningful template title for your internal use.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="attribute_sets"><?php echo Mage::helper('M2ePro')->__('Product Attribute Sets'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <div id="attribute_sets_container" <?php if ($this->attribute_set_locked): ?>style="display: none;"<?php endif; ?>>
                                <?php $this->attribute_set_locked ? $attributeSetPostfix = '_fake' : $attributeSetPostfix = ''; ?>
                                <select id="attribute_sets<?php echo $attributeSetPostfix; ?>" name="attribute_sets<?php echo $attributeSetPostfix; ?>[]" multiple="multiple" class="<?php if (!$this->attribute_set_locked): ?>M2ePro-validate-attribute-sets<?php endif; ?>">
                                    <?php foreach ($this->getData('attributes_sets') as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <?php if ($this->attribute_set_locked): ?>
                                <div id="attribute_sets_breadcrumb" style="width: 280px;">
                                    <?php $breadcrumb = array(); foreach ($this->getData('attributes_sets') as $set): ?>
                                        <?php if (in_array($set['attribute_set_id'], $formData['attribute_sets'])): $breadcrumb[] = $set['attribute_set_name']; endif; ?>
                                    <?php endforeach; ?>
                                    <strong><?php echo implode(', ', $breadcrumb); ?></strong>
                                </div>
                                <input id="attribute_sets" name="attribute_sets" value="<?php echo $this->escapeHtml(implode(',', $formData['attribute_sets'])); ?>" type="hidden" />
                            <?php endif; ?>

                            <div id="attribute_sets_buttons_container" style="padding-top: 5px; <?php if ($this->attribute_set_locked): ?>display: none;<?php endif; ?>">
                                <?php echo $this->getChildHtml('attribute_sets_select_all_button'); ?>
                                <?php echo $this->getChildHtml('attribute_sets_confirm_button'); ?>
                            </div>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Attribute Sets of products which will be listed on eBay<br />using this template.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="listing_type"><?php echo Mage::helper('M2ePro')->__('Listing Type'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">

                            <div id="listing_type_container" <?php if ($this->listing_type_locked): ?>style="display: none;"<?php endif; ?>>
                                <?php $this->listing_type_locked ? $listingTypePostfix = '_fake' : $listingTypePostfix = ''; ?>
                                <select id="listing_type<?php echo $listingTypePostfix; ?>" name="listing_type<?php echo $listingTypePostfix; ?>" class="select-main <?php if (!$this->listing_type_locked): ?>required-entry<?php endif; ?>">
                                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_AUCTION; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_AUCTION == $formData['listing_type']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Auction'); ?></option>
                                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_FIXED; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_FIXED == $formData['listing_type']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Fixed Price'); ?></option>
                                    <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_ATTRIBUTE == $formData['listing_type']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                                </select>
                            </div>

                            <?php if ($this->listing_type_locked): ?>
                                <div id="listing_type_breadcrumb" style="width: 280px;">
                                    <strong>
                                        <?php
                                            switch($formData['listing_type']) {
                                                case Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_AUCTION:
                                                    echo Mage::helper('M2ePro')->__('Auction');
                                                    break;
                                                case Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_FIXED:
                                                    echo Mage::helper('M2ePro')->__('Fixed Price');
                                                    break;
                                                case Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_TYPE_ATTRIBUTE:
                                                    Mage::helper('M2ePro')->__('Custom Attribute');
                                                    break;
                                            }
                                        ?>
                                    </strong>
                                </div>
                                <input id="listing_type" name="listing_type" value="<?php echo $formData['listing_type']; ?>" type="hidden" />
                            <?php endif; ?>

                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('How you want to sell your item.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="listing_type_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Listing Type Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="listing_type_custom_attribute_td" class="value"></td>
                        <td id="listing_type_custom_attribute_td_note" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Attribute must contain ID. ID for Fixed price is FixedPriceItem, for Auction is Chinese.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="listing_is_private"><?php echo Mage::helper('M2ePro')->__('Private Listing'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="listing_is_private" name="listing_is_private" class="select">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_IS_PRIVATE_NO; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_IS_PRIVATE_NO == $formData['listing_is_private']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_IS_PRIVATE_YES; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::LISTING_IS_PRIVATE_YES == $formData['listing_is_private']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i> selected the buyers remain anonymous to other eBay users.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_template_selling_format_qty_and_duration">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Quantity And Duration'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="duration_mode"><?php echo Mage::helper('M2ePro')->__('Listing Duration'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="duration_mode" name="duration_mode" class="required-entry select">
                                <option id="durationId1" value="1"><?php echo '1 '.Mage::helper('M2ePro')->__('day'); ?></option>
                                <option id="durationId3" value="3"><?php echo '3 '.Mage::helper('M2ePro')->__('days'); ?></option>
                                <option id="durationId5" value="5"><?php echo '5 '.Mage::helper('M2ePro')->__('days'); ?></option>
                                <option id="durationId7" value="7"><?php echo '7 '.Mage::helper('M2ePro')->__('days'); ?></option>
                                <option id="durationId10" value="10"><?php echo '10 '.Mage::helper('M2ePro')->__('days'); ?></option>
                                <option id="durationId30" value="30"><?php echo '30 '.Mage::helper('M2ePro')->__('days'); ?></option>
                                <option id="durationId100" value="100"><?php echo Mage::helper('M2ePro')->__('GTC'); ?></option>
                            </select>
                            <span id="duration_attribute_span"></span>
                            <p class="note">
                                <span id="duration_mode_note"><?php echo Mage::helper('M2ePro')->__('How long your eBay listings will be active.'); ?></span>
                                <span id="duration_attribute_note" style="display: none;"><?php echo Mage::helper('M2ePro')->__('Attribute must contain a whole number. If you choose GTC the attribute must contain 100.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr class="requirie-attribute-set">
                        <td class="label">
                            <label for="qty_mode"><?php echo Mage::helper('M2ePro')->__('Item Quantity'); ?>: </label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="qty_mode" name="qty_mode">
                                <option id="qty_mode_product" value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_PRODUCT == $formData['qty_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product QTY'); ?></option>
                                <option id="qty_mode_single" value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_SINGLE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_SINGLE == $formData['qty_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Single Item'); ?></option>
                                <option id="qty_mode_cv" value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_NUMBER; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_NUMBER == $formData['qty_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom QTY Number'); ?></option>
                                <option id="qty_mode_ca" value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MODE_ATTRIBUTE == $formData['qty_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom QTY Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Products quantity in eBay listing.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="qty_mode_cv_tr" style="display: none;">
                        <td class="label">
                            <label for="qty_custom_value"><?php echo Mage::helper('M2ePro')->__('Custom QTY Number'); ?>: </label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input id="qty_custom_value" name="qty_custom_value" value="<?php echo $this->escapeHtml($formData['qty_custom_value']); ?>" type="text" class="input-text M2ePro-required-when-visible validate-digits" />
                        </td>
                    </tr>

                    <tr id="qty_mode_ca_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom QTY Attribute'); ?>: </label>
                        </td>
                        <td id="qty_custom_attribute_td" class="value" style="width: auto;"></td>
                    </tr>

                    <!-- Max Posted QTY-->
                    <tr id="qty_max_posted_value_mode_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Conditional Quantity'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="qty_max_posted_value_mode" name="qty_max_posted_value_mode" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MAX_POSTED_MODE_OFF; ?>" <?php if ($formData['qty_max_posted_value'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::QTY_MAX_POSTED_MODE_ON; ?>" <?php if ($formData['qty_max_posted_value'] > 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                            </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('<i>Enables</i> to set the quantity that will be sent on eBay.'); ?></span>
                                </p>
                        </td>
                    </tr>

                    <tr id="qty_max_posted_value_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Max Quantity to Be Listed'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="qty_max_posted_value_td" class="value" style="width: auto;">
                            <input id="qty_max_posted_value" name="qty_max_posted_value" value="<?php echo $this->escapeHtml($formData['qty_max_posted_value']); ?>" type="text" class="input-text validate-qty M2ePro-required-when-visible" />
                        <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('If you have 5 pieces in stock but set a max qty of 2 to be listed, a qty of 2 will be listed on eBay.
                                                                                <br/>If you have 1 piece in stock but max qty is set to 3, only 1 will be listed on eBay. '); ?></span>
                                </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_template_selling_format_prices">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Price'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table id="currency_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="currency"><?php echo Mage::helper('M2ePro')->__('Currency'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="currency" name="currency" class="select-main">
                                <?php foreach ($this->getData('currencies') as $code => $title): ?>
                                    <option value="<?php echo $code; ?>"<?php if ($formData['currency'] == $code): echo ' selected="selected"'; endif;?>><?php echo $title ?></option>
                                <?php endforeach; ?>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The currency for items price(s). Must correspond to eBay Marketpace.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

                <table id="start_price_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="start_price_mode"><?php echo Mage::helper('M2ePro')->__('Start Price'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="start_price_mode" name="start_price_mode" class="select-main required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT == $formData['start_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL == $formData['start_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL == $formData['start_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Final Price'); ?></option> -->
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE == $formData['start_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span id="start_price_note"></span>
                            </p>
                        </td>
                        <td id="note_start_price_custom_attribute" class="coef">
                            <div id="note_start_price_custom_attribute2" style="font-size: 11px; float: right; padding-left: 10px;">
                                <img src="<?php echo $this->getSkinUrl('images/note_cell_bg.gif'); ?>" />
                                <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or currency rate (1.44)'); ?>.</span>
                            </div>
                            <input id="start_price_coefficient" name="start_price_coefficient" value="<?php echo $this->escapeHtml($formData['start_price_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                        </td>
                    </tr>

                    <tr id="start_price_custom_attribute_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Start Price Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="start_price_custom_attribute_td" class="value"></td>
                    </tr>

                </table>

                <table cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="buyitnow_price_mode"><?php echo Mage::helper('M2ePro')->__('"Buy It Now" Price'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="buyitnow_price_mode" name="buyitnow_price_mode" class="select-main">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_NONE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_NONE == $formData['buyitnow_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT == $formData['buyitnow_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL == $formData['buyitnow_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL == $formData['buyitnow_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Final Price'); ?></option> -->
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE == $formData['buyitnow_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span id="buyitnow_price_note"></span>
                            </p>
                        </td>
                        <td id="note_use_buy_from" style="display: none;" class="coef">
                            <div id="note_use_buy_from2" style="display: none; font-size: 11px; float: right; padding-left: 10px;">
                                <img src="<?php echo $this->getSkinUrl('images/note_cell_bg.gif'); ?>" />
                                <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or currency rate (1.44)'); ?>.</span>
                            </div>
                            <input id="buyitnow_price_coefficient" name="buyitnow_price_coefficient" value="<?php echo $this->escapeHtml($formData['buyitnow_price_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                        </td>
                    </tr>

                    <tr id="buyitnow_price_custom_attribute_tr" style="display: none;">
                        <td class="label nobr">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom "Buy It Now" Price Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="buyitnow_price_custom_attribute_td" class="value"></td>
                    </tr>

                </table>

                <table id="reserve_price_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="reserve_price_mode"><?php echo Mage::helper('M2ePro')->__('Reserve Price'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="reserve_price_mode" name="reserve_price_mode" class="select-main">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_NONE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_NONE == $formData['reserve_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_PRODUCT == $formData['reserve_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Product Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_SPECIAL == $formData['reserve_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Special Price'); ?></option>
                                <!-- <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_FINAL == $formData['reserve_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Final Price'); ?></option> -->
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_ATTRIBUTE == $formData['reserve_price_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                            <p class="note">
                                <span id="reserve_price_note"></span>
                            </p>
                        </td>
                        <td id="note_reserve_price_custom_attribute" style="display: none;" class="coef">
                            <div id="note_reserve_price_custom_attribute2" style="display: none; font-size: 11px; float: right; padding-left: 10px;">
                                <img src="<?php echo $this->getSkinUrl('images/note_cell_bg.gif'); ?>" />
                                <span style="padding-left: 5px;"><?php echo Mage::helper('M2ePro')->__('Absolute figure (+8,-3), percentage (+15%, -20%) or currency rate (1.44)'); ?>.</span>
                            </div>
                            <input id="reserve_price_coefficient" name="reserve_price_coefficient" value="<?php echo $this->escapeHtml($formData['reserve_price_coefficient']); ?>" type="text" class="M2ePro-validate-price-coefficient input-text" />
                        </td>
                    </tr>

                    <tr id="reserve_price_custom_attribute_tr" style="display: none;">
                        <td class="label nobr"><?php echo Mage::helper('M2ePro')->__('Custom Reserve Price Attribute'); ?>: <span class="required">*</span></td>
                        <td id="reserve_price_custom_attribute_td" class="value"></td>
                    </tr>

                </table>

                <table id="price_variation_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="price_variation_mode"><?php echo Mage::helper('M2ePro')->__('Variation Price Source'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="price_variation_mode" name="price_variation_mode" class="select-main">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_VARIATION_MODE_PARENT == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Main Product'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::PRICE_VARIATION_MODE_CHILDREN == $formData['price_variation_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Associated Products'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Determines where the price for Configurable and Bundle products options should be taken from.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_template_selling_format_customer_group_id">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Customer Group For Final Price'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <div id="block_notice_ebay_template_selling_format_customer_group_id" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Final Price'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This block appears when the <b>Final Price</b> is chosen in the Price option(s).
                <br/>
                The Final Price means that the price, that will be sent to eBay, is calculated according to Catalog Price Rules. So eBay buyers can buy your products at Magento Store Price.
                <br/><br/>
                <b>Note:</b> If there is a Special Price on a product and conditions are met for Catalog Price Rule to be applied, the <u>smaller</u> price from the Special and price calculated according to Catalog Price Rules will be set.
                <br/>
                If the Final Price is set, but any of Catalog Price Rules is not applied, the Special Price will be chosen, if there is no Special Price on the product, the Products Price will be set.
                <br/><br/>
                For correct definition Price Rule, which must be applied, you have to specify the <b>Customer Group</b> your eBay buyers will be associated to.
                '); ?>
                </div>

                <table cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label for="customer_group_id"><?php echo Mage::helper('M2ePro')->__('Customer Group'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="customer_group_id" name="customer_group_id" class="select-main">
                                <?php if ($formData['customer_group_id'] === ''): ?>
                                    <option class="empty" selected="selected"></option>
                                <?php endif; ?>
                                <?php foreach ($this->customerGroups as $group): ?>
                                    <option value="<?php echo (int)$group['value'] ?>" <?php if ($formData['customer_group_id'] !== '' && $formData['customer_group_id'] == (int)$group['value']): ?>selected="selected"<?php endif; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($group['label']); ?></option>
                                <?php endforeach; ?>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Which customer group eBay buyers have to be associated to.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_ebay_template_selling_format_best_offer">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Best Offer'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table id="best_offer_mode_table" cellspacing="0" class="form-list">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Allow Best Offer'); ?>:</label>
                        </td>
                        <td class="value">
                            <select id="best_offer_mode" name="best_offer_mode" class="select-main">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_MODE_YES; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_MODE_YES == $formData['best_offer_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_MODE_NO; ?>" <?php if (Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_MODE_NO == $formData['best_offer_mode']): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Allows buyers to send their Best Offers for your consideration.<br/><b>Note:</b> Listing Duration is not revised on eBay Listings with allowed Best Offer.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

                <table id="best_offer_respond_table" class="form-list" cellspacing="0" cellpadding="0">

                    <tr class="best-offer">
                        <td class="label nobr"><?php echo Mage::helper('M2ePro')->__('Automatically Accept Offers of at Least'); ?>:</td>
                        <td class="value">
                            <select id="best_offer_accept_mode" name="best_offer_accept_mode">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_NO; ?>" <?php if ($formData['best_offer_accept_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_PERCENTAGE; ?>" <?php if ($formData['best_offer_accept_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_PERCENTAGE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('% of "Buy It Now" Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_ATTRIBUTE; ?>" <?php if ($formData['best_offer_accept_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Price from Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="best_acc_input_text_tr" class="best-offer">
                        <td class="label"><?php echo Mage::helper('M2ePro')->__('Percentage (%)'); ?>: <span class="required">*</span></td>
                        <td class="value">
                            <input id="best_offer_accept_value" name="best_offer_accept_value" value="<?php echo $this->escapeHtml($formData['best_offer_accept_value']); ?>" type="text" class="input-text validate-digits M2ePro-required-when-visible" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Percentage of "Buy It Now" Price. Do not use %-sign in this field.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="best_acc_input_select_tr" class="best-offer">
                        <td class="label"><?php echo Mage::helper('M2ePro')->__('Price Custom Attribute'); ?>: <span class="required">*</span></td>
                        <td id="best_offer_accept_attribute_td" class="value"></td>
                        <td id="best_offer_accept_attribute_td_note" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose an Attribute that contains an appropriate price value.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr class="best-offer ">
                        <td class="label nobr"><?php echo Mage::helper('M2ePro')->__('Automatically Decline Offers Less than'); ?>:</td>
                        <td class="value">
                            <select id="best_offer_reject_mode" name="best_offer_reject_mode">
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_ACCEPT_MODE_NO; ?>" <?php if ($formData['best_offer_reject_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_NO): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_PERCENTAGE; ?>" <?php if ($formData['best_offer_reject_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_PERCENTAGE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('% of "Buy It Now" Price'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_ATTRIBUTE; ?>" <?php if ($formData['best_offer_reject_mode'] == Ess_M2ePro_Model_Ebay_Template_SellingFormat::BEST_OFFER_REJECT_MODE_ATTRIBUTE): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Price from Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="best_offer_reject_value_text_tr" class="best-offer">
                        <td class="label"><?php echo Mage::helper('M2ePro')->__('Percentage (%)'); ?>: <span class="required">*</span></td>
                        <td class="value">
                            <input id="best_offer_reject_value" name="best_offer_reject_value" value="<?php echo $this->escapeHtml($formData['best_offer_reject_value']); ?>" type="text" class="input-text validate-digits M2ePro-required-when-visible"/>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Percentage of "Buy It Now" Price. Do not use %-sign in this field.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="best_offer_reject_value_select_tr" class="best-offer">
                        <td class="label"><?php echo Mage::helper('M2ePro')->__('Price Custom Attribute'); ?>: <span class="required">*</span></td>
                        <td id="best_offer_reject_attribute_td" class="value"></td>
                        <td id="best_offer_reject_attribute_td_note" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose an Attribute that contains an appropriate price value.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</form>