<p class="switcher">
    <label for="group_filter">Group:</label>
    <select id="group_filter" name="group_filter" style="min-width: 100px;" onchange="TranslationHandlerObj.filter_change(this)">
        <option value="-1"></option>
        <?php foreach($this->groups as $group) { ?>
        <option value="<?php echo $group; ?>" <?php if ($this->groupFilter == $group) echo 'selected="selected"'; ?>><?php echo $group; ?></option>
        <?php } ?>
    </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <label for="status_filter">Status:</label>
    <select id="status_filter" name="status_filter" style="min-width: 100px;" onchange="TranslationHandlerObj.filter_change(this)">
        <option value="-1"></option>
        <option value="translated" <?php if ($this->statusFilter == "translated") echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Translated'); ?></option>
        <option value="untranslated" <?php if ($this->statusFilter == "untranslated") echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Translated'); ?></option>
    </select>
</p>