<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php
        $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();
        echo Mage::helper('M2ePro')->__('
This page contains all orders imported from Amazon.
Use Amazon Accounts dropdown to filter Amazon orders by accounts.<br/>
If Magento Order, Invoice or / and Shipment was not created automatically,
you can create them manually by using appropriate options in the Action dropdown.<br/><br/>
<b>Note:</b> Automatic creation of Magento Orders, Invoices, and Shipments executes according to Amazon Accounts settings in %s > Configuration > Amazon Accounts > Orders.', $menuLabel);
    ?>
</div>