<div id="block_notice_logs_synchronizations_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization Log'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains information on processes, which were done in Synchronization tasks.<br/><br/>
    <b>Note:</b> Logs of Default, Templates, Orders, Feedbacks and 3rd Party Listings Synchronizations are only recorded when Error(s) or Warning(s) appears.'); ?>
</div>