<div class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('New M2E Pro Amazon Generation'); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <div>
        <?php echo Mage::helper('M2ePro')->__('It is strongly recommended to go through Migration Wizard for new M2E Pro Amazon Generation. '); ?>
    </div>

    <div class="step_container_buttons">
        <?php echo $this->getChildHtml('continue_button'); ?>
    </div>
</div>
