<div id="block_notice_ebay_marketplace" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Sites'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page lists the eBay international sites that allow you to sell on Marketplaces around the world.<br/><br/>
        <b>Enable</b> the sites you want to sell on and click <b>Save</b>.
        Please be patient when enabling sites as this can take some time, depending on how many sites you are enabling and the speed of your own server.<br/>
        Click <b>Update Now</b> to update sites with the most up-to-date information, such as Category structure.<br/><br/>
        If a site has been <b>Used in Listing(s)</b> you cannot disable it.'
    ); ?>
</div>