<div id="block_notice_ebay_marketplace" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Sites'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Enable certain marketplaces you will work with and press the Save And Update button. All necessary marketplace data will be downloaded and synchronized with M2E Pro.
<br>
It is recommended to update marketplaces when any marketplace changes are announced.
<br><br>
<b>Note:</b> Installation and update processes might be time-consuming, depending on the number of enabled marketplaces and your server environment. '); ?>
</div>