<div id="block_notice_wizard_congratulation" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php

    $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
    $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
    $descriptionTemplatesUrl = $this->getUrl('*/adminhtml_template_description/index');
    $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

    $listingsUrl = $this->getUrl('*/adminhtml_listing/index',array('tab'=>'ebay'));
    $docsLink = Mage::helper('M2ePro/Module')->getConfig()->getGroupValue('/documentation/', 'baseurl');

    $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

    $tempString = Mage::helper('M2ePro')->__(
        '<strong>eBay settings were successfully set up.</strong> <br/><br/>
        Now you can continue working with extension. You can see below the short instructions, you may follow to start
        listing on eBay quickly.<br/> The more detailed information can be found in the <a href="%s" target="_blank">Documentation</a>.<br/><br/>

        <strong>The next steps you need to perform are:</strong><br/><br/>

        <span style="text-decoration: underline;"><strong>1)</strong> Selling Format Template creation:</span><br/>
        Navigate to %s > Templates > <a href="%s" target="_blank">Selling Format Templates</a>,
        Press on the Add Selling Format Template button;
        Fill in all necessary data;
        Save the template.<br/><br/>

        <span style="text-decoration: underline;"><strong>2)</strong> Description Template creation:</span><br/>
        Navigate to %s > Templates > <a href="%s" target="_blank">Description Templates</a>;
        Press on the Add Description Template button;
        Fill in all necessary data;
        Save the template.<br/><br/>

        <span style="text-decoration: underline;"><strong>3)</strong> General Template creation:</span><br/>
        Navigate to %s > Templates > <a href="%s" target="_blank">General Templates</a>;
        Press on the Add General Template button;
        Fill in all necessary data;
        Save the template.<br/><br/>

        <span style="text-decoration: underline;"><strong>4)</strong> Synchronization Template creation:</span><br/>
        Navigate to %s > Templates > <a href="%s" target="_blank">Synchronization Templates</a>;
        Press on the Add Synchronization Template button;
        Fill in all necessary data;
        Save the template.<br/><br/>

        After completing these four necessary steps, you can start to create Listings (%s > Manage

        Listings > <a href="%s" target="_blank">Listings</a>), add Magento products to them and list on eBay.<br/>',
        $docsLink, $menuLabel, $sellingFormatTemplatesUrl, $menuLabel, $descriptionTemplatesUrl, $menuLabel, $listingTemplatesUrl,
        $menuLabel, $synchronizationTemplatesUrl, $menuLabel, $listingsUrl
    );
    echo $tempString;

    ?>
</div>