<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php
        $menuLabel = Mage::helper('M2ePro/View_Common')->getMenuRootNodeLabel();
        echo Mage::helper('M2ePro')->__('
This section contains Amazon Listings, which belong to registered Amazon Accounts (%menu_label% > Configuration > Amazon Accounts) and were listed not by M2E Pro extension.<br/>
Use Amazon Accounts and Marketplaces dropdowns to filter them.
You can map these Listings to existing products in Magento and move them to another M2E Listings for further management. For that use single actions on appropriate Listing record or use mass Actions in the top right corner.<br/><br/>
<b>Note:</b> To import Amazon 3rd Party Listings the 3rd Party Listings Import must be enabled in account\'s settings
(%menu_label% > Configuration > Amazon Accounts > General tab) and the 3rd Party Listings Synchronization must be enabled in %menu_label% > Configuration > Synchronization.', $menuLabel);
    ?>
</div>