<?php
$formData = Mage::helper('M2ePro/Data_Global')->getValue('temp_data') ? Mage::helper('M2ePro/Data_Global')->getValue('temp_data') : array();

$defaults = array(
    'account_id' => 0,
    'sku_mode' => Ess_M2ePro_Model_Buy_Listing::SKU_MODE_NOT_SET,
    'sku_custom_attribute' => '',
    'generate_sku_mode' => Ess_M2ePro_Model_Buy_Listing::GENERATE_SKU_MODE_NO,

    'general_id_mode' => Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET,
    'general_id_custom_attribute' => '',

    'search_by_magento_title_mode' => Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES,

    'shipping_standard_mode' => Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET,
    'shipping_standard_value' => 0,
    'shipping_standard_custom_attribute' => '',

    'shipping_expedited_mode' => Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET,
    'shipping_expedited_value' => 0,
    'shipping_expedited_custom_attribute' => '',

    'shipping_two_day_mode' => Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET,
    'shipping_two_day_value' => 0,
    'shipping_two_day_custom_attribute' => '',

    'shipping_one_day_mode' => Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET,
    'shipping_one_day_value' => 0,
    'shipping_one_day_custom_attribute' => '',

    'condition_mode' => Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_NOT_SET,
    'condition_value' => '',
    'condition_custom_attribute' => '',
    'condition_note_mode' => Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_NOT_SET,
    'condition_note_value' => '',
    'condition_note_custom_attribute' => '',
);
$formData = array_merge($defaults, $formData);

if (count($this->getData('accounts')) == 1) {
    $formData['account_id'] = $this->getData('accounts');
    $formData['account_id'] = reset($formData['account_id']);
    $formData['account_id'] = (int)$formData['account_id']['id'];
}

$isEdit = (bool)$this->getRequest()->getParam('id');

$docsLink = Mage::helper('M2ePro/View_Common')->getDocumentationUrl();
$docsLink .= 'Rakuten.com+Listing+Creation#Rakuten.comListingCreation-ConditionIDs';
?>

<?php if (!$isEdit) { ?>
<div id="block_notice_buy_listing_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Channel Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains Rakuten.com Channel, Product Search, Shipping and Condition settings.<br/>
        <ul class="list">
        <li>In the General section you have to specify Rakuten.com Account, which listed items will be related to, and the Reference ID for its products.</li>
        <li>In the Search Settings you have to specify the identifiers, at which products will be searched on Rakuten.com.</li>
        <li>In the Shipping section you have to specify Shipping information.</li>
        <li>The Condition section allows specifying item(s) condition and making notes to better describe the condition.</li>
        </ul>
        <b>Note:</b> <i>Not Set</i> and <i>Not Set / Not Changeable</i> options are used for the 3rd Party Listings mainly. If these options are chosen, Rakuten.com will be used as a master record.'); ?>
</div>
<?php } ?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }
    //-----------------------------

    M2ePro.text.general_id_label_upc = '<?php echo Mage::helper('M2ePro')->__('UPC Attribute') ?>';
    M2ePro.text.general_id_label_bsku = '<?php echo Mage::helper('M2ePro')->__('Rakuten.com SKU Attribute') ?>';
    M2ePro.text.general_id_label_ssku = '<?php echo Mage::helper('M2ePro')->__('Seller SKU Attribute') ?>';
    M2ePro.text.general_id_label_isbn = '<?php echo Mage::helper('M2ePro')->__('ISBN Attribute') ?>';

</script>

<script type="text/javascript">

    // ie bug fix
    // ---------
    if (Prototype && Prototype.Browser.IE && varienLoaderHandler) {
        var loaderOnCompleteFunction = varienLoaderHandler.handler.onComplete;
        varienLoaderHandler.handler.onComplete = function() {

            loaderOnCompleteFunction();
            $$('select').each(function (el) {
                $(el).style.visibility = 'visible';
            });
        }
    }
    // ---------

    // Data for current tab
    //-----------------------------
    M2ePro.formData.account_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['account_id']); ?>';

    M2ePro.text.condition_note_length_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be not more than 250 characters long.')); ?>';
    M2ePro.text.shipping_rate_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Must be positive number.')); ?>';

    Event.observe(window, 'load', function() {

        BuyListingChannelSettingsHandlerObj = new BuyListingChannelSettingsHandler();
        BuyListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Ess_M2ePro_Model_Buy_Listing'); ?>');

        $('sku_mode').observe('change', BuyListingChannelSettingsHandlerObj.sku_mode_change);

        $('sku_custom_attribute').observe('change', BuyListingChannelSettingsHandlerObj.sku_custom_attribute_change);
        $F('sku_custom_attribute') && $('sku_custom_attribute').simulate('change');

        $('general_id_mode').observe('change', BuyListingChannelSettingsHandlerObj.general_id_mode_change);
        $F('general_id_mode') && $('general_id_mode').simulate('change');

        $('general_id_custom_attribute').observe('change', BuyListingChannelSettingsHandlerObj.general_id_custom_attribute_change);
        $F('general_id_custom_attribute') && $('general_id_custom_attribute').simulate('change');

        $('shipping_standard_mode').observe('change', BuyListingChannelSettingsHandlerObj.shipping_standard_mode_change);
        $('shipping_standard_mode').simulate('change');

        $('shipping_expedited_mode').observe('change', BuyListingChannelSettingsHandlerObj.shipping_expedited_mode_change);
        $('shipping_expedited_mode').simulate('change');

        $('shipping_two_day_mode').observe('change', BuyListingChannelSettingsHandlerObj.shipping_two_day_mode_change);
        $('shipping_two_day_mode').simulate('change');

        $('shipping_one_day_mode').observe('change', BuyListingChannelSettingsHandlerObj.shipping_one_day_mode_change);
        $('shipping_one_day_mode').simulate('change');

        $('condition_mode').observe('change', BuyListingChannelSettingsHandlerObj.condition_mode_change);
        $('condition_mode').simulate('change');

        $('condition_value').observe('change', BuyListingChannelSettingsHandlerObj.condition_value_change);
        $F('condition_value') && $('condition_value').simulate('change');

        $('condition_custom_attribute').observe('change', BuyListingChannelSettingsHandlerObj.condition_custom_attribute_change);
        $F('condition_custom_attribute') && $('condition_custom_attribute').simulate('change');

        $('condition_note_mode').observe('change', BuyListingChannelSettingsHandlerObj.condition_note_mode_change);

        $('condition_note_custom_attribute').observe('change', BuyListingChannelSettingsHandlerObj.condition_note_custom_attribute_change);
        $F('condition_note_custom_attribute') && $('condition_note_custom_attribute').simulate('change');
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_buy_listing_channel_settings_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr <?php if (count($this->getData('accounts')) == 1) { ?>style="display: none;" <?php } ?>>
                    <td class="label">
                        <label for="account_id"><?php echo Mage::helper('M2ePro')->__('Rakuten.com Account'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="account_id" name="account_id" class="required-entry" <?php if ($isEdit): ?>disabled="disabled"<?php endif; ?>>
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('accounts') as $account): ?>
                                <?php if ($isEdit && $formData['account_id'] != $account['id']){ continue; } ?>
                                <option value="<?php echo $account['id']; ?>" <?php if ($formData['account_id'] == $account['id']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($account['title']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Rakuten.com accounts previously added in Configuration > Accounts.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="sku_mode"><?php echo Mage::helper('M2ePro')->__('Reference ID') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="sku_mode" id="sku_mode" class="M2ePro-required-when-visible">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SKU_MODE_NOT_SET ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Buy_Listing::SKU_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SKU_MODE_PRODUCT_ID ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Buy_Listing::SKU_MODE_PRODUCT_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product ID') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SKU_MODE_DEFAULT ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Buy_Listing::SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SKU_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Buy_Listing::SKU_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('A unique ID, which identify a product in your Rakuten.com seller inventory.<br/>
                            <b>Note:</b> If you list a product and M2E Pro find a product with the same Reference ID in Rakuten.com inventory, they will be mapped.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="sku_custom_attribute_container" <?php if ($formData['sku_mode'] != Ess_M2ePro_Model_Buy_Listing::SKU_MODE_CUSTOM_ATTRIBUTE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="sku_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Reference ID Attribute'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="sku_custom_attribute" name="sku_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['sku_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['sku_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="generate_sku_mode"><?php echo Mage::helper('M2ePro')->__('Generate Reference ID') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="generate_sku_mode" id="generate_sku_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERATE_SKU_MODE_NO; ?>" <?php if ($formData['generate_sku_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERATE_SKU_MODE_NO) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('No') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERATE_SKU_MODE_YES ?>" <?php if ($formData['generate_sku_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERATE_SKU_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Yes') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If <i>Yes</i>, then if the Reference ID of the product you list is found in the 3rd Party or M2E Listings, another one will be automatically created and the product will be listed.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_listing_channel_settings_source">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Search Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_buy_listing_general_search" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Search Products on Rakuten.com'); ?>">
                <?php echo Mage::helper('M2ePro')->__('Before the list action, each product in listing must have existing Rakuten.com SKU.
This section contains parameters for action "Assign Rakuten.com SKU Automatically",
which is used to search and assign Rakuten.com SKU for a single product or in a bulk.
<br/><br/>The parameters are used according to the following logic:

                <ul class="list">
                <li>the product is searched by Rakuten.com identifier you have specified. (if specified)</li>
                <li>if no result by identifier parameter, then additional
                search by Magento product name is performed. (if enabled)</li>
                </ul>
<b>Note:</b> These settings are also used in auto list action.
                '); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="general_id_mode_container">
                    <td class="label">
                        <label for="general_id_mode"><?php echo Mage::helper('M2ePro')->__('Identifiers'); ?>:</label>
                    </td>
                    <td class="value">
                        <select id="general_id_mode" name="general_id_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_WORLDWIDE ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_WORLDWIDE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('UPC') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_GENERAL_ID ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_GENERAL_ID) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Rakuten.com SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_SELLER_SKU ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_SELLER_SKU) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Seller SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_ISBN ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_ISBN) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('ISBN') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Parameter the product search will be performed by.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="general_id_custom_attribute_container" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Buy_Listing::GENERAL_ID_MODE_NOT_SET): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="general_id_custom_attribute" id="general_id_attribute_label"></label>
                    </td>
                    <td class="value">
                        <select id="general_id_custom_attribute" name="general_id_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['general_id_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['general_id_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Specify the attribute, which contains necessary information.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="search_by_magento_title_mode"><?php echo Mage::helper('M2ePro')->__('Additional Search by Product Name'); ?>:
                    </td>
                    <td class="value">
                        <select id="search_by_magento_title_mode" name="search_by_magento_title_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE ?>" <?php if ($formData['search_by_magento_title_mode'] == Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Disable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES ?>" <?php if ($formData['search_by_magento_title_mode'] == Ess_M2ePro_Model_Buy_Listing::SEARCH_BY_MAGENTO_TITLE_MODE_YES) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Enable') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('If no results are found by the search criteria above, the additional search will be performed by Magento Product Name.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>
</div>

<div class="entry-edit" id="magento_block_buy_listing_channel_settings_additional">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Shipping Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <div id="block_notice_buy_listing_general_shipping" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Shipping'); ?>">
                <?php echo Mage::helper('M2ePro')->__('This section determines information about how your products will be shipped.
                <br/><br/>
                In each method you can choose:
                <ul class="list">
                <li><b>Not Set / Not Changeable</b> - is used for the 3rd Party Listings mainly. If this option is chosen, Rakuten.com will be used as a master record.</li>
                <li><b>Disable</b> - disables Shipping method.</li>
                <li><b>Free</b> - automatically sets zero value for Shipping Cost.</li>
                <li><b>Rakuten.com Settings</b> - uses settings, which you have set in your seller account settings on Rakuten.com.</li>
                <li><b>Custom Value</b> - allows setting Shipping Cost manually.</li>
                <li><b>Custom Attribute</b> - allows setting Shipping Cost from the chosen attribute.</li>
                </ul>
                '); ?>
            </div>

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr id="shipping_methods_tr" style="margin-top: 10px;">
                    <td class="grid" colspan="2">

                        <table class="border" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr class="headings">
                                <th style="width: 150px;"><?php echo Mage::helper('M2ePro')->__('Shipping Method'); ?></th>
                                <th style="width: 100px;"><?php echo Mage::helper('M2ePro')->__('Mode'); ?></th>
                                <th style="width: 300px;"><?php echo Mage::helper('M2ePro')->__('Cost'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Standard Shipping</td>
                                    <td>
                                        <select name="shipping_standard_mode" id="shipping_standard_mode" style="width: 164px;">
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET ?>"<?php if ($formData['shipping_standard_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE ?>"<?php if ($formData['shipping_standard_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Free'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT ?>"<?php if ($formData['shipping_standard_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Rakuten.com Settings'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE ?>"<?php if ($formData['shipping_standard_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE ?>"<?php if ($formData['shipping_standard_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="shipping_standard_custom_attribute" id="shipping_standard_custom_attribute" style="width: 300px;" class="M2ePro-required-when-visible">
                                            <?php if ($formData['shipping_standard_custom_attribute'] == ''): ?>
                                                <option class="empty"></option>
                                            <?php endif; ?>
                                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                                <option value="<?php echo $attribute['code']; ?>"<?php if ($formData['shipping_standard_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="text" name="shipping_standard_value" id="shipping_standard_value" style="width: 295px;" class="input-text M2ePro-validation-float M2ePro-required-when-visible-and-enabled" value="<?php echo (float)$formData['shipping_standard_value']; ?>">
                                    </td>
                                </tr>
                                <tr>
                                    <td>Expedited Shipping</td>
                                    <td>
                                        <select name="shipping_expedited_mode" id="shipping_expedited_mode" style="width: 164px;">
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Free'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Rakuten.com Settings'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE ?>"<?php if ($formData['shipping_expedited_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="shipping_expedited_custom_attribute" id="shipping_expedited_custom_attribute" style="width: 300px;" class="M2ePro-required-when-visible">
                                            <?php if ($formData['shipping_expedited_custom_attribute'] == ''): ?>
                                            <option class="empty"></option>
                                            <?php endif; ?>
                                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                            <option value="<?php echo $attribute['code']; ?>"<?php if ($formData['shipping_expedited_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="text" name="shipping_expedited_value" id="shipping_expedited_value" style="width: 295px;" class="input-text M2ePro-validation-float M2ePro-required-when-visible-and-enabled" value="<?php echo (float)$formData['shipping_expedited_value']; ?>">
                                    </td>
                                </tr>
                                <tr>
                                    <td>Two Day Shipping</td>
                                    <td>
                                        <select name="shipping_two_day_mode" id="shipping_two_day_mode" style="width: 164px;">
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Free'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Rakuten.com Settings'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE ?>"<?php if ($formData['shipping_two_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="shipping_two_day_custom_attribute" id="shipping_two_day_custom_attribute" style="width: 300px;" class="M2ePro-required-when-visible">
                                            <?php if ($formData['shipping_two_day_custom_attribute'] == ''): ?>
                                            <option class="empty"></option>
                                            <?php endif; ?>
                                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                            <option value="<?php echo $attribute['code']; ?>"<?php if ($formData['shipping_two_day_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="text" name="shipping_two_day_value" id="shipping_two_day_value" style="width: 295px;" class="input-text M2ePro-validation-float M2ePro-required-when-visible-and-enabled" value="<?php echo (float)$formData['shipping_two_day_value']; ?>">
                                    </td>
                                </tr>
                                <tr>
                                    <td>One Day Shipping</td>
                                    <td>
                                        <select name="shipping_one_day_mode" id="shipping_one_day_mode" style="width: 164px;">
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_NOT_SET) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DISABLED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disable'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_FREE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Free'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_DEFAULT) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Rakuten.com Settings'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_VALUE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE ?>"<?php if ($formData['shipping_one_day_mode'] == Ess_M2ePro_Model_Buy_Listing::SHIPPING_MODE_CUSTOM_ATTRIBUTE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="shipping_one_day_custom_attribute" id="shipping_one_day_custom_attribute" style="width: 300px;" class="M2ePro-required-when-visible">
                                            <?php if ($formData['shipping_one_day_custom_attribute'] == ''): ?>
                                            <option class="empty"></option>
                                            <?php endif; ?>
                                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                            <option value="<?php echo $attribute['code']; ?>"<?php if ($formData['shipping_one_day_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="text" name="shipping_one_day_value" id="shipping_one_day_value" style="width: 295px;" class="input-text M2ePro-validation-float M2ePro-required-when-visible-and-enabled" value="<?php echo (float)$formData['shipping_one_day_value']; ?>">
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_buy_listing_channel_settings_condition">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Condition Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="condition_mode"><?php echo Mage::helper('M2ePro')->__('Condition') ?>: </label>
                    </td>
                    <td class="value">
                        <select name="condition_mode" id="condition_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_NOT_SET ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_DEFAULT ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Recommended Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['condition_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <?php if (!$isEdit) { ?>
                                <span><?php echo Mage::helper('M2ePro')->__('Condition of the product(s) you want to list on Rakuten.com.<br/>
                                <b>Note:</b> <i>Not Set</i>&rlm;&rlm; is used for the 3rd Party Listings mainly. If this option is chosen, Rakuten.com will be used as a master record.'); ?></span>
                            <?php } else { ?>
                                <span><?php echo Mage::helper('M2ePro')->__('Condition of the product(s) you want to list on Rakuten.com.<br/>
                                <b>Note:</b> Condition of Active Items cannot be changed.'); ?></span>
                            <?php } ?>
                        </p>
                    </td>
                </tr>

                <tr id="condition_value_tr" <?php if ($formData['condition_mode'] != Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_DEFAULT): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_value"><?php echo Mage::helper('M2ePro')->__('Condition Value') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="condition_value" id="condition_value" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_value'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_NEW ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('New') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_LIKE_NEW ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_LIKE_NEW) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Like New') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_VERY_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_VERY_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Very Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_GOOD ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_GOOD) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Good') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_ACCEPTABLE ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_USED_ACCEPTABLE) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Used - Acceptable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_REFURBISHED ?>" <?php if ($formData['condition_value'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_REFURBISHED) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Refurbished') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="condition_custom_attribute_tr" <?php if ($formData['condition_mode'] != Ess_M2ePro_Model_Buy_Listing::CONDITION_MODE_CUSTOM_ATTRIBUTE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Condition Attribute') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select id="condition_custom_attribute" name="condition_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['condition_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span>
                            <?php echo Mage::helper('M2ePro')->__('Choose the attribute that contains Condition <a href="%url%" target="_blank">identifier</a>.', $docsLink); ?>
                            </span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_mode_tr">
                    <td class="label">
                        <label for="condition_note_mode"><?php echo Mage::helper('M2ePro')->__('Comment') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="condition_note_mode" id="condition_note_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_NOT_SET ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_NOT_SET) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Not Set / Not Changeable') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_NONE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Value') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['condition_note_mode'] == Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Short description of item(s) condition.<br/>
                            <b>Note:</b> <i>Not Set / Not Changeable</i>&rlm;&rlm; is used for the 3rd Party Listings mainly. If this option is chosen, Rakuten.com will be used as a master record.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_value_tr" <?php if ($formData['condition_note_mode'] != Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_VALUE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_note_value"><?php echo Mage::helper('M2ePro')->__('Comment Text') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <textarea name="condition_note_value" id="condition_note_value" class="M2ePro-required-when-visible M2ePro-validate-condition-note-length"><?php echo Mage::helper('M2ePro')->escapeHtml($formData['condition_note_value']) ?></textarea>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Description of the condition of the item(s).'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="condition_note_custom_attribute_tr" <?php if ($formData['condition_note_mode'] != Ess_M2ePro_Model_Buy_Listing::CONDITION_NOTE_MODE_CUSTOM_ATTRIBUTE): ?>style="display: none;"<?php endif; ?>>
                    <td class="label">
                        <label for="condition_note_custom_attribute"><?php echo Mage::helper('M2ePro')->__('Comment Attribute') ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <select name="condition_note_custom_attribute" id="condition_note_custom_attribute" class="M2ePro-required-when-visible">
                            <?php if ($formData['condition_note_custom_attribute'] == ''): ?>
                            <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                            <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['condition_note_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>
