<div id="block_notice_ebay_account" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Account Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('To change account settings click on its record in the grid or choose Edit in the Action dropdown.
    <br>To review accounts feedback, click the appropriate link. An account can be also deleted, but only if it is not used in M2E listing settings.'); ?>
</div>