<div id="block_notice_ebay_account" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Account Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__(
        'This page shows information for the eBay Accounts you\'ve added.<br/><br/>
        Click the line of the eBay Account in the table below to <b>Edit</b> the account details, such as the rules on how eBay sales should be imported,
        whether eBay feedback should be imported and eBay Store settings. To see the eBay feedback for an eBay Account, click <b>Feedback</b>.
        You can <b>Delete</b> an eBay Account only if it\'s not being used for an M2E Pro Listing.<br/><br/>
        To add a new eBay Account, click the <b>Add Account</b> button.'
    ); ?>
</div>